### ISSUE TITLE
Add a CODE_OF_CONDUCT.md 

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#1]
# AIM
-  Create a Code of Conduct which all Project Administrators, Mentors and Participants must abide by.

# Details
- Mention the Standards which everyone should abide by on welcoming and inclusive language including constructive criticism.
- Add the required responsibilities for Project Maintainers.
- Mention the Scope of this Code of Conduct.

**Comment by jeffugo** [comment]
I'd love to help out with this.

**Comment by avinashkranjan** [comment]
@jeffugo Go ahead..assigned to you..

**Comment by jeffugo** [comment]
Hi @avinashkranjan, I'm a bit confused about which branch name to use where it says git remote <branch-name> on the Contributing Guidelines. Could you point me in the right direction? Thank you.

**Comment by avinashkranjan** [comment]
You can create any branch on your side...
`git checkout -b branch_name` 
change branch_name to whatever you want..then you can start working on it

**Comment by avinashkranjan** [comment]
@jeffugo When can I expect the PR for the issue

**Comment by jeffugo** [comment]
I already sent a pull request this morning. Maybe I didn't do it right. I was having trouble using the process described in How to Contribute, so I was directed by a friend to upload the Code of Conduct through the browser, open a branch and send a pull request. I'm sorry, this is all still new to me.

**Comment by avinashkranjan** [comment]
@jeffugo It's okay...I haven't received any PR..Check once..

**Comment by jeffugo** [comment]
@avinashkranjan Alright. I'll check again.
