### ISSUE TITLE
Script to Find Your Wifi Password

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#10]
# Aim

- Script to find all the saved WiFi password in your system

# Details

- Functionality to Search for the Saved Passwords in the system and Print it out/Save it in text file.
- Will Help in looking for the Password, if you have forgotten

**Comment by geekymeeky** [comment]
I would like to work on this issue

**Comment by avinashkranjan** [comment]
@geekymeeky Sure, Go ahead

**Comment by geekymeeky** [comment]
Closed via #76
