### ISSUE TITLE
Corona Chatbot

### ISSUE THREAD

**Issue by Himanshi2997** [avinashkranjan/Amazing-Python-Scripts#1001]
# Aim

-To make a tkinter based gui for answering user queries related to coronavirus

# Details

- Make normal conversation 
- Use machine learning to enhance chat experience
- Use tensorflow and keras libraries for building neural network model

I would like to work on this issue under GSSoC'21,please assign it to me.

**Comment by kaustubhgupta** [comment]
`Use tensorflow and keras libraries for building neural network model`

How you will use this model in the script? We are not looking for notebook-based files but actual ones .py files which can be run by user in the terminal or a suitable GUI.

**Comment by Himanshi2997** [comment]
I will use tkinter for the interface and the libraries will be used to create a sequential model. This project will take more one files to execute to completion.
-A .py file where the training of chatbot will be done
-A .py file for cleaning sentences and creating chat interface
-A .txt file for keeping intents 
-Two .pkl files to store lemmatized sentences(will be created on executing the training file)
-Finally  the model will be created and saved(after execution of training file)

Once the chatbot is trained the user will just have to run the interface file and start chatting.

**Comment by Himanshi2997** [comment]
Sir I will need two more days to complete this. I am working on adding more intents in my training data.

**Comment by kaustubhgupta** [comment]
updates?

**Comment by kaustubhgupta** [comment]
@Himanshi2997?

**Comment by kaustubhgupta** [comment]
Issue closed due to no response from the participant
