### ISSUE TITLE
Real Estate Property Data

### ISSUE THREAD

**Issue by Himanshi2997** [avinashkranjan/Amazing-Python-Scripts#1003]
# Aim

- To make a program to extract required information from web pages and put the data in well structured format using beautiful soup library in python.

# Details
-Take data from real estate websites and chart them in tabular form.

I would like to work on this issue under GSSoC'21, please assign it to me.

**Comment by kaustubhgupta** [comment]
@Himanshi2997 you need to clearly specify which type of data, websites to be scrapped, and how you will store the data

**Comment by Himanshi2997** [comment]
I will take real estate property data from websites like http://pyclass.com/real-estate/rock-springs-wy/LCWYROCKSPRINGS/
Then the data will be stored in form of csv file, then it can be opened in Microsoft Excel.

**Comment by kaustubhgupta** [comment]
Name your script as "Real Estate Property Data" scrapper

**Comment by kaustubhgupta** [comment]
@Himanshi2997 updates on this?

**Comment by Himanshi2997** [comment]
Just completed the code, currently working on the README.md file.
