### ISSUE TITLE
MAD LIBS GAME IN PYTHON

### ISSUE THREAD

**Issue by Mrinal81** [avinashkranjan/Amazing-Python-Scripts#1005]
I am a GSSOC'21 participant. I would like to make Mad Libs game in python....

@kaustubhgupta  @santushtisharma10  Please assign me this issue........

**Comment by santushtisharma10** [comment]
@Mrinal81 go ahead, assigned to you

**Comment by Mrinal81** [comment]
@kaustubhgupta yaa working

**Comment by Mrinal81** [comment]
@kaustubhgupta i will made PR tommorow for sure.....
