### ISSUE TITLE
Gesture Volume Control 

### ISSUE THREAD

**Issue by soumik2012** [avinashkranjan/Amazing-Python-Scripts#1006]
**Is your feature request related to a problem? Please describe.**
Control the volume up and down using the hand gesture with the OpenCV

**Describe the solution you'd like**
Using our hand control the volume in pc Using the OpenCV and Mediapipe library I would like to make this program. 

**Additional context**
![ ](https://i.imgur.com/8fl6zqU.gif)

**Comment by soumik2012** [comment]
@kaustubhgupta please  assign me issue

**Comment by kaustubhgupta** [comment]
@soumik2012 I would suggest this is a full-fledged good project and you should not undermine this by contributing here.

**Comment by soumik2012** [comment]
> @soumik2012 I would suggest this is a full-fledged good project and you should not undermine this by contributing here.

so can I continued work on this project or should close this issue

**Comment by soumik2012** [comment]
> @soumik2012 I would suggest this is a full-fledged good project and you should not undermine this by contributing here.

@kaustubhgupta so can I continued work on this project or should close this issue

**Comment by kaustubhgupta** [comment]
> > @soumik2012 I would suggest this is a full-fledged good project and you should not undermine this by contributing here.
> 
> @kaustubhgupta so can I continued work on this project or should close this issue

you can close this issue
