### ISSUE TITLE
Fidget spinner Game 

### ISSUE THREAD

**Issue by soumik2012** [avinashkranjan/Amazing-Python-Scripts#1007]
# Aim

- Make an advanced level fidget spinner game 

# Details 
- Controls: Left and Right arrows to rotate the Spinner in direction, spacebar to change the color of Spinner
- the Longer you press arrow key the more speed it reaches!
- should look like this
![Screenshot 2021-05-04 085335](https://user-images.githubusercontent.com/66599363/116965175-d01f1000-acca-11eb-96e3-8ffee2ecc1d8.png)

**Comment by soumik2012** [comment]
@kaustubhgupta please assign me this issue under GSSOC'21

**Comment by kaustubhgupta** [comment]
@soumik2012 are you planning to submit this code?

https://github.com/jatinmandav/Animation-and-Simulations/blob/master/Fidget_Spinner/Fidget%20Spinner.py

**Comment by soumik2012** [comment]
@kaustubhgupta Yes but if change the code i can change it

**Comment by kaustubhgupta** [comment]
I don't think there can be a change of code in this particular case and you will end up getting a plag strike from one of the mentors. So it's better we drop this idea.

**Comment by soumik2012** [comment]
@kaustubhgupta let me try me if i can't make the program  i will close the issue
