### ISSUE TITLE
Toonify a Given Image 

### ISSUE THREAD

**Issue by soumik2012** [avinashkranjan/Amazing-Python-Scripts#1009]
# Aim

- This is a python application which takes a image as input and toonify it (make a cartoonist image of it)

# Details

- using https://deepai.org/machine-learning-model/toonify api.

**Comment by soumik2012** [comment]
@kaustubhgupta  please check this issue

**Comment by kaustubhgupta** [comment]
We already have this script
https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Cartooning%20Image

**Comment by kaustubhgupta** [comment]
Secondly, I agree that your approach is different from the implemented one but a simple API call is not what we want
