### ISSUE TITLE
Information Finder

### ISSUE THREAD

**Issue by Arnab11917676** [avinashkranjan/Amazing-Python-Scripts#1010]
# Aim
I will build a GUI Information Finder desktop application.
# Details
In this application, the window will open and in the search option you can search for the query and a short summary will be provided to you by the application. In, that case if you want to read more about the query you can download from the download button and read more information about it.

**Comment by kaustubhgupta** [comment]
@Arnab11917676 what kind of information this application provides? What modules will you use for this script?

**Comment by Arnab11917676** [comment]
Basic information basically a one-liner...I will be using Wikipedia for the information

**Comment by kaustubhgupta** [comment]
https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Wikipedia-Summary-GUI we already have this script
