### ISSUE TITLE
Updating Scripts contributors in Website, implementation of search bar and releasing the first draft!

### ISSUE THREAD

**Issue by kaustubhgupta** [avinashkranjan/Amazing-Python-Scripts#1013]
## Problem
The website is almost ready to be showcased. One thing we still need to implement is script updation in the website. The current implementation is hard-coded HTML. The file [scripts.html](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/gh-pages/website/scripts.html) contains the scripts information but all has been done manually. Also, we need to implement a search bar where one can search for a script name. 

## Solution
The main branch contains a folder called master script and there you will find a file called datastore.json. Your task is to create the scripts to fetch that data onto the scripts.html and also implement the search functionality. For now, you can simply copy the JSON file to this branch, and later on, the GitHub action will automatically update this file. 

P.S: I have little knowledge about JS so anyone who takes this issue, kindly explain if this thing is possible or not

## More context:
- The contributors display on the home.html needs JS
- The website file needs to be shifted from the website folder to the root folder and the current index.html needs to be replaced with home.html

**Comment by Ayushjain2205** [comment]
@kaustubhgupta I would like to work on this

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 I want to know that the JSON file is sufficient for this searching?

**Comment by Ayushjain2205** [comment]
@kaustubhgupta we want to search based on name of script right? searching can be implemented based on anything contained in the JSON file. So yes this JSON file is sufficient for searching

**Comment by kaustubhgupta** [comment]
Okay cool, assigned to you!
