### ISSUE TITLE
Voice Calculator

### ISSUE THREAD

**Issue by Arnab11917676** [avinashkranjan/Amazing-Python-Scripts#1014]
# Aim
Build a calculator using voice command

# Details
I am building a calculator in which you can use voice commands for doing the calculation. The calculator is able to perform both Arithmetic as well as Scientific calculations. I might add a GUI but that's not promised.

**Comment by Arnab11917676** [comment]
I will be building this calculator using an API that will do the calculation for me...

**Comment by kaustubhgupta** [comment]
@Arnab11917676 GUI is not needed for this, you can make it command line

**Comment by Arnab11917676** [comment]
@kaustubhgupta will this voice calculator be merged with the mainchain
