### ISSUE TITLE
Blood alcohol content 

### ISSUE THREAD

**Issue by soumik2012** [avinashkranjan/Amazing-Python-Scripts#1018]
# Aim

-  this script to know how much drunk you are!! 

# Details

-  it tell you how amount of alcohol you drink and what is percentage of alcohol content in the blood

**Comment by soumik2012** [comment]
@kaustubhgupta please check this issue

**Comment by kaustubhgupta** [comment]
@soumik2012 how will you implement this? Is it an ML model? if yes then which dataset?

**Comment by soumik2012** [comment]
@kaustubhgupta  No ML modules I am capitulating  using BMC formula
