### ISSUE TITLE
Predicting next K words

### ISSUE THREAD

**Issue by Aparna-Sakshi** [avinashkranjan/Amazing-Python-Scripts#1020]
**Description**
Given a sequence of words, next k words will be predicted using

- character-based LSTM models
- word-based LSTM models
- Transformer-based language model (i.e)BERT

I am a GSSOC-21 participant, kindly assign this issue to me @kaustubhgupta.

**Comment by kaustubhgupta** [comment]
@Aparna-Sakshi how will you make the script for this? these models are themselves way too large in size

**Comment by Aparna-Sakshi** [comment]
@kaustubhgupta I do agree that these models are very compute-intensive. LSTM models can be trained in google collab with GPU on.  It took me around an hour to completely run these models. Since Bert is a pre-trained model, hence this part was not very time-consuming.

**Comment by kaustubhgupta** [comment]
@Aparna-Sakshi got it. But we cannot continue with this idea
