### ISSUE TITLE
Amazon Alexa Reviews Analysis

### ISSUE THREAD

**Issue by Manasi2001** [avinashkranjan/Amazing-Python-Scripts#1028]
**Is your feature request related to a problem? Please describe.**
It's difficult and tedious for a company to analyze the huge amount of feedback that they get from their customer in terms of words (as reviews).

**Describe the solution you'd like**
In order to solve this issue for Amazon Alexa, I would like to add my project. Using NLP, the program can classify any feedback given to Alexa as a positive or a negative one and in turn can help the developers to automate the feedback process and improve on the service accordingly.

**Additional context**
My folder will be complete with the dataset, the notebook, model's pkl file and also a proper README.
The analysis looks something like this:
![image](https://user-images.githubusercontent.com/68627617/117625404-9e5aed00-b193-11eb-933c-7a7282a2b3d4.png)

**Comment by kaustubhgupta** [comment]
We are not looking for notebooks but script-based files. Can you configure your project in this manner: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Salary%20Predictor?
