### ISSUE TITLE
Laptop Price Predictor

### ISSUE THREAD

**Issue by Manasi2001** [avinashkranjan/Amazing-Python-Scripts#1029]
**Is your feature request related to a problem? Please describe.**
The task of buying a new laptop can be very hectic. Comparing the companies, prices, model features, etc. is very time taking.

**Describe the solution you'd like**
My project can ease this process by using ML. A nice catchy GUI will make the process even more fun!

**Additional context**
My project folder will be complete with the dataset, the notebook, model's pkl file, the GUI's notebook and a descriptive README.

The final GUI will look something like this:

![image](https://user-images.githubusercontent.com/68627617/117627052-6654a980-b195-11eb-9ed0-59f8e885a6ce.png)

**Comment by kaustubhgupta** [comment]
The GUI script is fine. For other files, can you structure your files in this format? https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Salary%20Predictor
