### ISSUE TITLE
Fake News detector

### ISSUE THREAD

**Issue by noobkid2411** [avinashkranjan/Amazing-Python-Scripts#1033]
# Aim
The aim of the project would be to predict if the news is real or fake.

# Details

- I'd be using passive aggressive classifier for the model and the dataset that I will be using for training is: https://drive.google.com/file/d/1er9NJTLUA3qnRuyhfzuN0XUsoIC4a-_q/view

**Comment by kaustubhgupta** [comment]
Can you structure your project in this manner? https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Salary%20Predictor

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta The folder structure will be like this:
> 
> Dataset folder->csv file
> fakenewsdetection.py
> README
> 
> I'll start with the structure this way,if there are any edits or changes,I'll update ,is that okay?

Okay cool!

**Comment by noobkid2411** [comment]
Hey,unfortunately I have a health emergency in my family to deal with.I would still like to contribute but I might not be able to make a pr before the 20th.If this is an urgent work,you can unassign me,sorry for the inconvenience from my side.

**Comment by kaustubhgupta** [comment]
> Hey,unfortunately I have a health emergency in my family to deal with.I would still like to contribute but I m

Hey, It's not urgent work, you should look after your family first. If you feel like contributing, try to contribute max by 27-28 May so that your PR is well-reviewed and merged before the program ends. Hope your family member recovers soon!

**Comment by kaustubhgupta** [comment]
Sorry but as the program is about to end, I have to close this issue.
