### ISSUE TITLE
Collage Maker using Python

### ISSUE THREAD

**Issue by undetectablevirus** [avinashkranjan/Amazing-Python-Scripts#1034]
# Aim

- We can make collage of two images using Python

# Details

- The script will take two images as input and will give a collage of both images.

**Comment by undetectablevirus** [comment]
I can increase the number of images and about random templates query, user will input the path of images that they want to be a part of the collage. So random placing of images won't be an issue. I hope I got it right about template thing.

**Comment by kaustubhgupta** [comment]
> I can increase the number of images and about random templates query, user will input the path of images that they want to be a part of the collage. So random placing of images won't be an issue. I hope I got it right about template thing.

Yes, I am thinking about this only. Let's give it a try!

**Comment by kaustubhgupta** [comment]
@undetectablevirus updates on this?
