### ISSUE TITLE
Video to PDF (GUI)

### ISSUE THREAD

**Issue by kaustubhgupta** [avinashkranjan/Amazing-Python-Scripts#1035]
# Aim

Convert video to PDf format

# Details

The user will select the video file via the GUI, then extract the audio, convert it into text format and dump it as pdf. There should be a progress bar to show the progress of the process.

**Comment by kaustubhgupta** [comment]
@noobkid2411 No issues, you can work on 2-3  issues at the same time.I have assigned this issue to you!

**Comment by noobkid2411** [comment]
Hey one doubt, the structure needs to be like this  link(https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Salary%20Predictor)mentioned previously right or some other structure?

**Comment by tanvi355** [comment]
I have never worked on something like this before but I want to try. Can I take this up?

**Comment by kaustubhgupta** [comment]
> ke

sure!

**Comment by amonikag** [comment]
If this issue has not been resolved. Can I give it a try? I'm a GSSoC participant. Can u assign it to me?

**Comment by kaustubhgupta** [comment]
@tanvi355 updates on this?

**Comment by tanvi355** [comment]
Working on it ....will make a PR soon.

**Comment by kaustubhgupta** [comment]
@tanvi355 did you found the workaround for this? You need to make the PR before 2 pm.

**Comment by tanvi355** [comment]
> @tanvi355 did you found the workaround for this? You need to make the PR before 2 pm.

I've made a PR,  please check.
