### ISSUE TITLE
PDF to Video (CLI)

### ISSUE THREAD

**Issue by kaustubhgupta** [avinashkranjan/Amazing-Python-Scripts#1036]
# Aim

Convert a PDF to Video

# Details

Take a PDF file, extract the text from it, convert it to audio format and attach that audio to the video provided by the user. Make sure to remove the existing audio of the video.

**Comment by Sukriti-sood** [comment]
I would like to work on this.

**Comment by santushtisharma10** [comment]
@Sukriti-sood go ahead, assigned to you

**Comment by sandipswain** [comment]
I would love to work on this issue

**Comment by kaustubhgupta** [comment]
@sandipswain Issue is already assigned. Look for `up-for-grab` label where someone else has not commented to claim the issue
