### ISSUE TITLE
Facebook video downloader (GUI)

### ISSUE THREAD

**Issue by kaustubhgupta** [avinashkranjan/Amazing-Python-Scripts#1037]
# Aim

Download videos from Facebook

# Details

The user will pass the link of the video in the text field and you need to implement the logic to download the video. If possible, implement the progress bar to show the progress of the download. 

If progress bar, the level will be increased to 3 else 2.

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta can I work??

Sure!

**Comment by Sukriti-sood** [comment]
Can I work on this.....?

**Comment by kaustubhgupta** [comment]
> Can I work on this.....?

sure

**Comment by kaustubhgupta** [comment]
@Sukriti-sood updates on this?

**Comment by Sukriti-sood** [comment]
@kaustubhgupta Will make pr by today.
