### ISSUE TITLE
LinkedIn video downloader (GUI)

### ISSUE THREAD

**Issue by kaustubhgupta** [avinashkranjan/Amazing-Python-Scripts#1038]
# Aim
Download videos from LinkedIn

# Details
The user will pass the link of the video in the text field and you need to implement the logic to download the video. If possible, implement the progress bar to show the progress of the download.

If progress bar, the level will be increased to 3 else 2.

**Comment by Amit366** [comment]
@kaustubhgupta can I work?

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta can I work?

sure!

**Comment by kaustubhgupta** [comment]
@Amit366 updates on this?

**Comment by Amit366** [comment]
I will complete in 2 days

**Comment by Sukriti-sood** [comment]
I wanted to work on this.

**Comment by kaustubhgupta** [comment]
@Sukriti-sood updates on this?

**Comment by Sukriti-sood** [comment]
@kaustubhgupta Will make pr by today.
