### ISSUE TITLE
Twitter video downloader (GUI)

### ISSUE THREAD

**Issue by kaustubhgupta** [avinashkranjan/Amazing-Python-Scripts#1039]
# Aim
Download videos from Twitter

# Details
The user will pass the link of the video in the text field and you need to implement the logic to download the video. If possible, implement the progress bar to show the progress of the download.

If progress bar, the level will be increased to 3 else 2.

**Comment by kaustubhgupta** [comment]
> can I take this up?

Sure!

**Comment by XZANATOL** [comment]
Good, will update you if I managed to add the progressbar
