### ISSUE TITLE
Medium Articles Scrapper

### ISSUE THREAD

**Issue by kaustubhgupta** [avinashkranjan/Amazing-Python-Scripts#1040]
# Aim

Scrap articles from Medium

# Details

Come up with a script that scraps `n` number of articles from `any category` such as Python, JS, Android provided by the user and stores all the `n` articles separately in PDFs. The PDF file should contain the title, article content, and author-name

User Input: `n` and `category`
Expected Output: n PDF files

**Comment by Ayushjain2205** [comment]
@kaustubhgupta I would like to work on this

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta I would like to work on this

sure!

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 updates on this?

**Comment by Ayushjain2205** [comment]
almost done PR by today EOD
