### ISSUE TITLE
Pomodoro clock GUI

### ISSUE THREAD

**Issue by RohiniRG** [avinashkranjan/Amazing-Python-Scripts#1044]
**Is your feature request related to a problem? Please describe.**
We often find it difficult for us to stay productive and manage time to complete our tasks without getting distracted.

**Describe the solution you'd like**
The Pomodoro technique uses a timer to break down work into intervals, traditionally 25 minutes in length, separated by 5 -15 min breaks. I will be implementing this in a GUI based form along with an extra functionality of website blocking to prevent distractions.

**Comment by kaustubhgupta** [comment]
@rmoyano updates on this?

**Comment by kaustubhgupta** [comment]
@RohiniRG updates on this?

**Comment by RohiniRG** [comment]
> @RohiniRG updates on this?

Yes, I am working on it, I'll put up the PR within a day.
