### ISSUE TITLE
GUI Vector Calculator

### ISSUE THREAD

**Issue by XZANATOL** [avinashkranjan/Amazing-Python-Scripts#1045]
# Aim

A GUI that accepts a 2 3D vector inputs and shows relations between each of them, along with the properties of each.

# Details

By properties I mean:
* Unit Direction of each vector.
* Cosine Direction of each vector.
* Cosine Angles of each vector.
* Absolute Value of each vector. |A|

By relations I mean:
* Dot product.
* Cross product.
* Angle between both vectors.
* Component of each vector on the other.
* Projection of each vector on the other

The GUI will contain 3 windows, the main one will have the input fields of the vectors. Other two will be accessible from the toolbar, where each one will have the properties of each individual vector.

# Contribution Event
- GSSOC

**Comment by kaustubhgupta** [comment]
@XZANATOL updates on this?

**Comment by XZANATOL** [comment]
Already fimished the first windows.. 2 left. Sorry for the delay, I'm under some pressure considering exams timings because of the COVID.

**Comment by kaustubhgupta** [comment]
> Already finished the first windows.. 2 left. Sorry for the delay, I'm under some pressure considering exams timings because of the COVID.

no issues
