### ISSUE TITLE
Encrypting Text using SHA256

### ISSUE THREAD

**Issue by Arnab11917676** [avinashkranjan/Amazing-Python-Scripts#1047]
# Aim

Encrypting Text using SHA256

# Details

In this code module, I will be building a GUI based application that will be encoding the text using an SHA-256 algorithm, and also be generating the hash which will be used for the decryption of the text.

**Comment by kaustubhgupta** [comment]
We already have this script: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Cryptography
