### ISSUE TITLE
Color Detection on images using python

### ISSUE THREAD

**Issue by Ayush7614** [avinashkranjan/Amazing-Python-Scripts#1051]
# Aim

- Color Detection on images using python

# Details

- We have use opencv and pandas for color detection and dataset csv in the script

**Comment by Ayush7614** [comment]
Plss assign me this issue under gssoc21

**Comment by kaustubhgupta** [comment]
@Ayush7614 we already have this script: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Color_detection
