### ISSUE TITLE
Automation Script to Send Bday Emails

### ISSUE THREAD

**Issue by dhanrajdc7** [avinashkranjan/Amazing-Python-Scripts#1052]
`GSSOC21`

# Aim

- Python script to send automated emails on BDays

# Details

- The script will send Bday Emails on Specific Date

**Comment by kaustubhgupta** [comment]
@dhanrajdc7 we already have two iterations of the same: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Custom-Bulk-Email-Sender and https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/HTML-Email-Sender

**Comment by dhanrajdc7** [comment]
This script will run automatically every day. This is not the same as you given links

**Comment by kaustubhgupta** [comment]
Any type of script can be made to run every day, every hour but that doesn't make it unique
