### ISSUE TITLE
Python Script to download large files from the internet.

### ISSUE THREAD

**Issue by noviicee** [avinashkranjan/Amazing-Python-Scripts#1056]
# Aim

This python script will help users to download any kind of files, irrespective of their size from the internet.

# Details

This script can be used to download any kind of files (files of any format), irrespective of their size from the internet.
You just need to have the url and you are good to go!

**Comment by kaustubhgupta** [comment]
@noviicee you already have two active issues, kindly make PR for them and then I will assign this issue to you

**Comment by noviicee** [comment]
> @noviicee you already have two active issues, kindly make PR for them and then I will assign this issue to you

Okay 👍
