### ISSUE TITLE
Python script  to track the typing speed and improve it with regular practice.

### ISSUE THREAD

**Issue by sameeksharl** [avinashkranjan/Amazing-Python-Scripts#1061]
# Aim
-The main aim is to track the typing speed and improve it with regular practice.

# Details
- The user will be given a single line of sentence . After completion of the sentence , it would show time ,Accuracy , Wpm(words per minute) with good looking UI
- I would try giving options for the user , how many words that they want to practice and list of paragraphs , which they could select any to practice 
@kaustubhgupta could you please assign me this issue

**Comment by kaustubhgupta** [comment]
Already implemented: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Typing-Speed-Test
