### ISSUE TITLE
Handwritten Digit Recognition

### ISSUE THREAD

**Issue by sameeksharl** [avinashkranjan/Amazing-Python-Scripts#1062]
# Aim

This project will be able to recognize the digits written instantly with its  accuracy .

# Details
- I will be using  deep learning with Keras library and the Tkinter library for building GUI.
- Apart from recognizing the digits , will be including accuracy as well.
- @kaustubhgupta please assign this to me

**Comment by kaustubhgupta** [comment]
@sameeksharl This is a very popular project and the dataset is fairly old. Also, the description you have provided is indicating that it should be made as a standalone project and not a script to be contributed here.
