### ISSUE TITLE
Script to Convert PDF book into Audiobook.

### ISSUE THREAD

**Issue by geekymeeky** [avinashkranjan/Amazing-Python-Scripts#107]
# Aim

- Convert PDF book into Audiobooks to disseminate knowledge among learners who find difficulty reading.

# Details

- Write a python script where user can enter the path of the pdf file they would like to read. The Script will convert the text of the file specified to speech and render it in real time. You can also add a feature to save it as a mp3 file.

**Comment by quentin-vigne** [comment]
Hi ! I would like to work on this 😄

**Comment by avinashkranjan** [comment]
Sure @quentin-vigne go ahead..

**Comment by argha-dot** [comment]
Hi, can you also assign me?

**Comment by avinashkranjan** [comment]
@argha-dot It is already assigned. you can work on other issues or create one of your own
