### ISSUE TITLE
Addition of clear the clutter

### ISSUE THREAD

**Issue by robin025** [avinashkranjan/Amazing-Python-Scripts#1074]
# Aim

- Clear the clutter

# Details

- This app can be used to separate files based on their extensions.
- Example
   - Suppose a folder has many file like word,pdf,ppt,md,rst,exe,jpg,png,gif,mp3,mp4 etc many more
   - so this application will separate all the files

**Comment by kaustubhgupta** [comment]
@robin025 Already implemented: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/File-Mover
