### ISSUE TITLE
Mardown editor and previewer 

### ISSUE THREAD

**Issue by Ayushjain2205** [avinashkranjan/Amazing-Python-Scripts#1080]
# Aim

To enable a user to see live preview of markdown while making the markdown file

# Details

The user can play around with markdown in the editor and once they are satisfied with the preview the file can be exported as a .md file

**Comment by Ayushjain2205** [comment]
@kaustubhgupta can i work on this?

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 updates on this?
