### ISSUE TITLE
Automatically Send Custom Named Certificates via Mail

### ISSUE THREAD

**Issue by dhanrajdc7** [avinashkranjan/Amazing-Python-Scripts#1085]
`GSSOC21`

# Aim

- Send custom-named certificates via Mail

# Details
- Adding names of participants to the certificate programmatically from CSV file
- Using SMTP to send mails
- Optimized process for creating & sending certificate

**Comment by kaustubhgupta** [comment]
@dhanrajdc7 updates on this?

**Comment by dhanrajdc7** [comment]
Working on it.... Almost done...
