### ISSUE TITLE
Turtle Module

### ISSUE THREAD

**Issue by anumshka** [avinashkranjan/Amazing-Python-Scripts#1086]
**Is your feature request related to a problem? Please describe.**
A bunch of small projects that helps to understand the implementation of turtle module.

**Describe the solution you'd like**
Making designs and beautiful patterns using turtle module, and at last making a final painting.

**Comment by kaustubhgupta** [comment]
@anumshka let me know what else can be added to this folder: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Codes%20on%20Turtle%20Graphics

**Comment by anumshka** [comment]
I would like to add the following:
1. A random walk generator
2. A beautiful pattern using regular polygons
3. A model of Hirst spot painting (https://www.damienhirst.com/texts1/series/spots)
4. Basic designs for beginners
