### ISSUE TITLE
Adding Sentiment Analysis 

### ISSUE THREAD

**Issue by eeshasrivastava** [avinashkranjan/Amazing-Python-Scripts#1097]
# Aim

- Train a neural network for sentiment analysis

# Details

- Sentiment Analysis is a field of Natural Language Processing (NLP) that builds models that try to identify and classify attributes of the expression.
@avinashkranjan I am a GSSoC'21 participant. Kindly allow me to work on this issue and contribute to this project!

**Comment by kaustubhgupta** [comment]
@eeshasrivastava already implemented: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Script%20to%20check%20Sentiment
