### ISSUE TITLE
Turtle Racing Game

### ISSUE THREAD

**Issue by anumshka** [avinashkranjan/Amazing-Python-Scripts#1098]
# Aim

Hosting a race

# Details

The user will bet on a turtle to win and a race would be hosted to see who wins.

**Comment by kaustubhgupta** [comment]
GUI ?

**Comment by anumshka** [comment]
Yes

**Comment by kaustubhgupta** [comment]
@anumshka are you trying to push this code? https://github.com/techwithtim/Turtle-Racing-V2

**Comment by anumshka** [comment]
A little bit same, but , would also let the user to predict the winner and at the end show the result whether he lost or won.

**Comment by kaustubhgupta** [comment]
@anumshka will you be able to do it because you already have a lot of pending issues?

**Comment by anumshka** [comment]
Yes, I will push it today
