### ISSUE TITLE
Guess a Number 

### ISSUE THREAD

**Issue by SharmaTanish** [avinashkranjan/Amazing-Python-Scripts#1099]
# Aim

- In this game a random number is generated in range 1 to 1000 (so to make game tough) and player has only 10 number of attempts to guess correct number. This algorithm automatically tells the player that if he/she is going in right direction or not.

# Details

- A random number is generated is generated by the random module using randint() function in range 1 to 1000.
- Player can input his guessed number at most 10 times.
- This algorithm tells the user if his entered number is greater or less than the destination number and each time alarm the player that this many attempts are left for his to reach the destination number otherwise he will lose the game.
- If player wins it shows that in how in many attempts he/she able to reach the correct number.

**Comment by SharmaTanish** [comment]
@kaustubhgupta sir please assign this issue to me and add relevant labels.
Thank you 
Regards

**Comment by kaustubhgupta** [comment]
@SharmaTanish already implemented: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Guessing_Game_GUI

**Comment by SharmaTanish** [comment]
But @kaustubhgupta the program you are talking about is in GUI form , mine is directly in terminal.
As you can see that Stone-paper-scissor game also is in both forms in our repository , one via terminal and other via GUI.
So by looking to this,  have made this game.
I request you to please have a look on this and merge this.
Looking forward for your response
Thank you 
Regards

**Comment by kaustubhgupta** [comment]
@SharmaTanish we not looking for CLI version of this game

**Comment by SharmaTanish** [comment]
Okay , sorry for raising this issue 🙁
Thank you
