### ISSUE TITLE
Image Contrast Adjusting Filter

### ISSUE THREAD

**Issue by A-kriti** [avinashkranjan/Amazing-Python-Scripts#1101]
**Is your feature request related to a problem? Please describe.**
Images captured in dim light mostly not have a much better contrast so an (Image Contrast Adjusting filter) filter helps accordingly to adjusts and increase its contrast and hence we are having a better version of the image.

**Describe the solution you'd like**
Using some of the python libraries to implement this "Image Contrast Adjusting Filter". 
- matplotlib,
- IPython.display
- NumPy
- PIL 

**Comparison**

![Screenshot (390)](https://user-images.githubusercontent.com/73133055/119268399-5ff01400-bc10-11eb-9d36-03c03ed8c2b2.png)

**Comment by kaustubhgupta** [comment]
@A-kriti assigned to you
