### ISSUE TITLE
Reddit Scraper without API

### ISSUE THREAD

**Issue by RohiniRG** [avinashkranjan/Amazing-Python-Scripts#1104]
<h1>DESCRIPTION:</h1>
With the help of beautiful soup any desired subreddit can be scraped and the result can be stored in a database.

@kaustubhgupta I would like to work on this issue

**Comment by kaustubhgupta** [comment]
What kind of data you will scrap?

**Comment by RohiniRG** [comment]
Number of upvotes, comments, author, date of posting, post content titles based on the tags like hot, controversial, etc. for user-desired subreddit.
