### ISSUE TITLE
Get Wifi Passwords

### ISSUE THREAD

**Issue by get-satyam** [avinashkranjan/Amazing-Python-Scripts#1114]
# Aim

- The aim of this script is to get Wifi passwords registered on the system via email.  Once the script is run it sends all the wifi passwords with their ssid to users email.

# Details

- Get Wifi passwords
- Email that password to the users email id.
- Language used : PYTHON

**Comment by get-satyam** [comment]
@kaustubhgupta I would like to work on this issue. Kindly assign me this issue. :)

**Comment by kaustubhgupta** [comment]
@get-satyam we already have this script: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Get-Wifi-Password
