### ISSUE TITLE
Neon Effect Filter

### ISSUE THREAD

**Issue by A-kriti** [avinashkranjan/Amazing-Python-Scripts#1117]
**Is your feature request related to a problem? Please describe.**
Want to apply a "Neon Effect Filter" on an image.

**Describe the solution you'd like**
Implementing a neon effect filter using OpenCV, Matplotlib, Os and NumPy.

**Final Output**
![Screenshot (396)](https://user-images.githubusercontent.com/73133055/119543719-99f71c80-bdae-11eb-848f-819523d8257d.png)

**Comment by kaustubhgupta** [comment]
@A-kriti assigned. Make sure to save the new image as suggested in the latest PR too!
