### ISSUE TITLE
Label Application

### ISSUE THREAD

**Issue by anumshka** [avinashkranjan/Amazing-Python-Scripts#1118]
# Aim

To label all the continents and oceans.

# Details

An empty blank world map would be displayed ,the user will enter the names of continents and oceans , and the names will point to a desired point(where they are supposed to be).The user may quit to know the answers and get the final labelled map.

**Comment by kaustubhgupta** [comment]
This idea is very similar to this: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Guess%20the%20Countries

**Comment by anumshka** [comment]
Should I change the world map idea? or everything?

**Comment by kaustubhgupta** [comment]
Let's drop this idea. The program will be very similar to already implemented solution and it doesn't make sense to have same game again.
