### ISSUE TITLE
Scraping google play store

### ISSUE THREAD

**Issue by RohiniRG** [avinashkranjan/Amazing-Python-Scripts#1119]
**Is your feature request related to a problem? Please describe.**
The python script scrapes through a list of app results of a search query and obtaining data like number of installs, number of reviews, stars, email, etc.

**Describe the solution you'd like**
The script will be implemented using selenium library in python.

**Comment by kaustubhgupta** [comment]
@RohiniRG The search query should be the category of apps (ex: Games, utilities, books etc)

**Comment by kaustubhgupta** [comment]
@RohiniRG updates on this? Make the PR before 2 pm so that we can review the code properly and merge it on time.
