### ISSUE TITLE
Manipulating google calendar with python

### ISSUE THREAD

**Issue by iamakkkhil** [avinashkranjan/Amazing-Python-Scripts#1120]
**Is your feature request related to a problem? Please describe.**
To schedule, view, update, etc. calendar events in google calendar.

**Describe the solution you'd like**
The python script will make use of google calendar API to perform mentioned tasks.

**Additional context**
I am a GSSoC'21 participant and would like to work on this issue

**Comment by kaustubhgupta** [comment]
@iamakkkhil Interesting idea, can you make it GUI ?

**Comment by iamakkkhil** [comment]
I want to work on command line based script

**Comment by kaustubhgupta** [comment]
Level may increase based on script contributed

**Comment by kaustubhgupta** [comment]
@iamakkkhil updates on this? Make the PR before 2 pm so that we can review the code properly and merge it on time.

**Comment by kaustubhgupta** [comment]
GSSOC ends
