### ISSUE TITLE
Cryptocurrency price checker GUI (web scraping)

### ISSUE THREAD

**Issue by Ayushjain2205** [avinashkranjan/Amazing-Python-Scripts#1124]
# Aim

To display live top cryptocurrency in a GUI

# Details

Web scrape this data from coinmarketcap.com or other such websites

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 the word dashboard has different meaning. Kindly change it to Crypto Price Checker GUI

**Comment by Ayushjain2205** [comment]
@kaustubhgupta sure I have made the changes in the PR as well
