### ISSUE TITLE
Python voice assistant to fetch and read news from NewsAPI

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#113]
# Aim

- A python script which will fetch news from newsapi.com and will speak that news with headlines and description.

# Details

- A python script which will fetch news from newsapi.com and will speak that news with headlines and description. Reading news and articles sometimes may too time consuming and boring .With the help of this python news reader you listen to top news while working on your other work.

**Comment by Yagueteiro** [comment]
Hi, it looks interesting, can I work on this?

**Comment by avinashkranjan** [comment]
Sure @Yagueteiro ..Go Ahead,..
