### ISSUE TITLE
Script to get a Football Player's Club History from Wikipedia

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#114]
# Aim

- A Script to get the Club History (with noteworthy years, if any are specified in Wikipedia) of a Football Player by scraping that footballer's Wikipedia Page.

**Comment by shahidshakil** [comment]
This sounds interesting to me, Can you please assign it to me?

**Comment by avinashkranjan** [comment]
Sure Go ahead... @shahidshakil

**Comment by avinashkranjan** [comment]
@shahidshakil any updates?

**Comment by shahidshakil** [comment]
@avinashkranjan I should be done in the next couple of days.

**Comment by avinashkranjan** [comment]
@shahidshakil Okay..

**Comment by shahidshakil** [comment]
Raising a Pull Request

**Comment by shahidshakil** [comment]
@@avinashkranjan  can you please validate of the logic is fine,So that I can start with refactoring the code further.
