### ISSUE TITLE
Download Page as a Pdf

### ISSUE THREAD

**Issue by viraldevpb** [avinashkranjan/Amazing-Python-Scripts#1143]
# Aim

- This script's objective is to download the page as a pdf and store it on the Computer.

# Details

- This script converts the page that we are viewing as a pdf for further Understanding.
- Please assign me this issue under GSSOC.

**Comment by kaustubhgupta** [comment]
@viraldevpb asssigned. Make the PR before 2 pm so that we can review the code properly and merge it on time.

**Comment by viraldevpb** [comment]
@kaustubhgupta I have Send a Pull Request Please Check Now!!
