### ISSUE TITLE
Scrap E-Mail Links from a LinkedIn Post

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#115]
# Aim

- Scrap E-Mail Links from a LinkedIn Post.

# Details

- The basic features I am looking at from this Script include:

> - Enter the Link of the Post
> - Scrap the E-Mail of specified subdomains (G-Mail, Yahoo, Outlook, ProtonMail).
> - Store them on a CSV File and output the same.

**Comment by KGene1901** [comment]
Hi, this look interesting - may I have a go at it?

**Comment by ealvarez968** [comment]
Hi, look interesting can I help?

**Comment by avinashkranjan** [comment]
Sure @ealvarez968 , @KGene1901 Go ahead..!
