### ISSUE TITLE
 Whatsapp bot to get COVID statistics

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#116]
# Aim

- Build a WhatsApp bot, that will display the current statistics of COVID-19 given a county or any Indian state or district

**Comment by Muskan33** [comment]
Hey can you please assign this issue to me? It looks interesting.

**Comment by avinashkranjan** [comment]
Sure @Muskan33 ...Assigned to you..

**Comment by avinashkranjan** [comment]
@Muskan33 Any Updates?

**Comment by gpriya32** [comment]
@avinashkranjan can u assign this to me...?

**Comment by gpriya32** [comment]
as a swoc participant?

**Comment by avinashkranjan** [comment]
Ya Sure go ahead @gpriya32

**Comment by avinashkranjan** [comment]
Any Updates @gpriya32

**Comment by gpriya32** [comment]
I was working on it but now as I have exams it will take time...so if you want to assign it to someone.... go ahead.

**Comment by avinashkranjan** [comment]
Sure @gpriya32

**Comment by vybhav72954** [comment]
@avinashkranjan Is this open?
Can you assign this?

**Comment by avinashkranjan** [comment]
Yes @vybhav72954 It's Open, Go Ahead..

**Comment by vybhav72954** [comment]
@avinashkranjan 
I will open a PR within an hour or so, can you assign me #18  as well meanwhile so that I can open a PR for the same.

**Comment by avinashkranjan** [comment]
Done @vybhav72954
