### ISSUE TITLE
Indian State Guessing game

### ISSUE THREAD

**Issue by Souhardya-Ganguly** [avinashkranjan/Amazing-Python-Scripts#1162]
Middle school geography students usually have a tough time trying to learn the name of Indian states by heart.

This game helps students to test their knowledge of the same in a fun manner by entering the name of the states and seeing it entered on the blank map if it is correct. The states that they do not remember will be stored additionally so that they can refer to it and revise.

I have attached herewith, snapshots of the blank map, input dropdown and the partially filled map while the game is in progress.
![Blank_map](https://user-images.githubusercontent.com/60609964/131453688-20ef435d-92c8-4955-97d0-ca0bd0b0529c.PNG)
![Input terminal](https://user-images.githubusercontent.com/60609964/131453692-5a451577-36f3-4d2d-a42f-0580824df0fb.PNG)
![Partial_map](https://user-images.githubusercontent.com/60609964/131453693-783a7d1d-33ce-4cfa-ad6e-ce748ec3cbd4.PNG)

**Comment by Souhardya-Ganguly** [comment]
Could you please assign this issue to me?

**Comment by avinashkranjan** [comment]
Sure @Souhardya-Ganguly Go Ahead.. Sounds Like a great addition to the repo.
