### ISSUE TITLE
Cofffee Machine py game

### ISSUE THREAD

**Issue by syamala27** [avinashkranjan/Amazing-Python-Scripts#1168]
**Is your feature request related to a problem? Please describe.**
I have seen many games but how about a coffe machine game? Oh yes !!
I love to drink coffee. But, I wonder how coffee is being made by the cafe's. My project is similar to that. For more picture clear, i have added the ss below.

**Describe the solution you'd like**
Sir, this is a BasicPythonScripts to implement coffee machine game

**Additional context**
It will be a BasicPythonScripts in which the user plays a coffee machine game.

![image](https://user-images.githubusercontent.com/58478495/135570327-5afd8c33-0b24-4733-962b-b1f247ac4d60.png)

pls, assign me this issue @avinashkranjan sir I would like to contribute my work.

**Comment by kaustubhgupta** [comment]
@syamala27 Sounds good, go ahead with the implementation. Let me know if have any doubts

**Comment by preetimahto17** [comment]
Hello! I'm really excited about this project. I would love to contribute and work on it. Could you kindly assign the project to me? I'm confident that I can make a valuable contribution.

**Comment by ayush-09** [comment]
Hello @syamala27 
I love to work on this issue "Coffee Machine Game".I am experienced python developer and wants to make this game with full of excitement under GSSOC'23.
I would appreciate it if you could assign me this issue. I am excited about the opportunity to contribute to the project and collaborate with the team.
Thanks.

**Comment by avinashkranjan** [comment]
GO Ahead @preetimahto17
