### ISSUE TITLE
Documentation: Optimize/Modify the SCRIPTS.md for the Project

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#12]
# Aim

- Optimize/Modify the `Scripts.md` for the Project. 

# Details [The end results I am looking for]

- An Attractive Header with good Markdown Badges
- Name and Functions of the Scripts Available 
- Adding Name and Linking it to the profile of the Contributor.

**Comment by AnandD007** [comment]
I am SWOC Participant.I want to work on this issue

**Comment by avinashkranjan** [comment]
Sure @AnandD007 ..Go ahead Assigned to you..
