### ISSUE TITLE
scripts about 3 data structures: Linked List, Queue and Scripts

### ISSUE THREAD

**Issue by CarlosViniMSouza** [avinashkranjan/Amazing-Python-Scripts#1242]
# Aim

I would like to add a project with three python scripts about linked list, queue and stack (these are the structures that I have been trying to study)

# What is the objective of the Script

Show how simple it is to implement and use data structures

# Details

1 - well i would like to add something very simple (that a beginner would be able to look at and understand how the framework operates as a whole)

2 - if this 'issue' gets rejected for whatever reasons, no problem, I'd think of something that's more interesting. (I just want to be a contributor to this beautiful project 🖖🤓)

# What the features will your script have

The basic functionalities: add, remove and search element. Some scripts will have their own functions (functions that fulfill specific tasks, in particular, operations that recruiters ask for in technical interviews). Image for example:

![image](https://user-images.githubusercontent.com/60679101/177631766-801dedc8-c73d-4997-9e41-fe62ffa627b9.png)

**Comment by Vidhish-Trivedi** [comment]
I would like to work on this issue, if it is still open. Kindly respond.

**Comment by Vidhish-Trivedi** [comment]
@avinashkranjan

**Comment by CarlosViniMSouza** [comment]
Hi @Vidhish-Trivedi, this issue is still open. What are your doubts?

**Comment by Vidhish-Trivedi** [comment]
Hello @CarlosViniMSouza, I would like to work on this issue as part of GSSOC'23. Could you please describe what the expectations are?

**Comment by CarlosViniMSouza** [comment]
This is new to me. Well, if my issue is accepted or not, I'm fine. ✌️

**Comment by avinashkranjan** [comment]
Go Ahead @CarlosViniMSouza

**Comment by vk20july** [comment]
@avinashkranjan sir can i do this task under gssoc'23
