### ISSUE TITLE
Script to find size of Github Repository + List of Contributors

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#126]
# Aim

- Create a Script to find the size of Github Repository + List of Contributors

**Comment by HyperTHD** [comment]
I'd like to take this one if no one is assigned to this one yet

**Comment by HyperTHD** [comment]
I finished the issue as per specifications. I'm awaiting to be assigned so that I can make the PR as per your contribution guide.
Let me know when you're ready for my PR

**Comment by avinashkranjan** [comment]
Sure..Go ahead..
