### ISSUE TITLE
Perform a Google news search and email results using Python

### ISSUE THREAD

**Issue by funbeedev** [avinashkranjan/Amazing-Python-Scripts#128]
# Aim
- Perform a google news search of a topic
- Extract the news heading and link and send an email with results

# Details
- Reading user configuration from file
- Web scraping of Google using Selenium 
- Sending Emails with Python
- Scheduling when script will run using Linux Crontab

**Comment by funbeedev** [comment]
@avinashkranjan Please assign to me.

**Comment by avinashkranjan** [comment]
Sure @funbeedev go ahead
