### ISSUE TITLE
Convert Folder ( with all subfolder ) into .html file

### ISSUE THREAD

**Issue by techdobz** [avinashkranjan/Amazing-Python-Scripts#1287]
# Aim

- will convert any given folder into an HTML file, For better management and search for your files.

# Details

- search functionality based on title,
- subfolder will become a tag, so you can search it using the tag also.
- check this,
![search](https://user-images.githubusercontent.com/40512595/193437757-f72b2a4c-0881-4d9a-a1e5-e645dbdbdc8b.png)
![tags](https://user-images.githubusercontent.com/40512595/193437752-0547ee17-901e-4ccf-8142-ea02a4d423d5.png)

**Comment by avinashkranjan** [comment]
Go Ahead @techdobz Assigned it you.

**Comment by techdobz** [comment]
Added pull request
