### ISSUE TITLE
Script to develop a Keylogger

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#13]
# Aim

- Create a Script to implement a Keylogger.

# Details

- A Script that can log all your KeyPress.
- Should save all the keys logs in a file.
- If Send a emails that'd be great too.

**Comment by madihamallick** [comment]
I would like to work on this issue.

**Comment by avinashkranjan** [comment]
Go Ahead...Assigned to you..
