### ISSUE TITLE
Make a Banner Image for the Repository

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#131]
# Aim

- Make a Banner Image for the Repository. The Banner Image can be simply the title of this Project with an awe-striking background. This Issue can be assigned to any number of participants but only one would be accepted as the Main Banner.

# Details

- You need to submit:

> - The Raw File of the Banner
> - A JPEG/PNG File of the Output

# Tools which can be Used

-  Adobe XD
- Figma
- Photoshop
- Illustrator

**Comment by SHITIZ-AGGARWAL** [comment]
I would like to work on this if available

**Comment by avinashkranjan** [comment]
Sure Go ahead @SHITIZ-AGGARWAL

**Comment by SHITIZ-AGGARWAL** [comment]
Can you tell more about what texts or tags you need on the banner or anything else you need specifically

**Comment by avinashkranjan** [comment]
@SHITIZ-AGGARWAL Sure, Create a Logo and Then Amazing Python Scripts Add a Little description `Curated collection of Amazing Python scripts from Basics to Advance with automation task scripts.`.. and a GitHub Link `avinashkranjan/Amazing-Python-Scripts`.. Rest I leave to you and your Creative Imagination.

**Comment by SHITIZ-AGGARWAL** [comment]
![banner](https://user-images.githubusercontent.com/53532851/104196174-7bb90180-5449-11eb-9433-3486adff44f5.gif)
![banner](https://user-images.githubusercontent.com/53532851/104196620-013cb180-544a-11eb-9a86-336946cf0a46.png)

@avinashkranjan

**Comment by SHITIZ-AGGARWAL** [comment]
Do you want any changes or shall i make a pr

**Comment by avinashkranjan** [comment]
@SHITIZ-AGGARWAL I don't find it appealing. Do you more iterations to show??

**Comment by SHITIZ-AGGARWAL** [comment]
Sure I will make some more designs

**Comment by avinashkranjan** [comment]
@SHITIZ-AGGARWAL Any Updates??

**Comment by subhangi2731** [comment]
can you assign this to me please?

**Comment by manastole03** [comment]
Assign this work to me !

**Comment by kaustubhgupta** [comment]
@subhangi2731 Updates on this?

**Comment by kaustubhgupta** [comment]
@manastole03 you want to work on this?

**Comment by manastole03** [comment]
Yes @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@manastole03 assigned to you! as it's an urgent issue, can you make the PR by tomorrow?

**Comment by manastole03** [comment]
Yeah sure @kaustubhgupta

**Comment by manastole03** [comment]
@kaustubhgupta  work is done. 
In which folder I have upload that file or I have to change the readme.md file.
Please guide me.

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta work is done.
> In which folder I have upload that file or I have to change the readme.md file.
> Please guide me.

@avinashkranjan

**Comment by manastole03** [comment]
I am not getting any response. @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@manastole03 check out the gh-pages branches. I think you need to upload the banner there. I will confirm this with the mentor. https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/gh-pages

**Comment by manastole03** [comment]
sure @kaustubhgupta

**Comment by avinashkranjan** [comment]
> @kaustubhgupta work is done.
> In which folder I have upload that file or I have to change the readme.md file.
> Please guide me.

Hello @manastole03 Kindly, Post the Banner Image here, Once Approved your can push it to `gh-pages`

**Comment by manastole03** [comment]
![Banner Image](https://user-images.githubusercontent.com/55608869/111196946-e02c4480-85e3-11eb-95b9-1609d4ec96c8.png)

This is the banner image for python-scripts.
If the design is good and if any changes required then I am able to do that.

@kaustubhgupta @subhangi2731 @avinashkranjan

**Comment by kaustubhgupta** [comment]
> ![Banner Image](https://user-images.githubusercontent.com/55608869/111196946-e02c4480-85e3-11eb-95b9-1609d4ec96c8.png)
> 
> This is the banner image for python-scripts.
> If the design is good and if any changes required then I am able to do that.
> 
> @kaustubhgupta @subhangi2731 @avinashkranjan

I would suggest some more appealing font, stylish font. What say @avinashkranjan, @antrikshmisri & @santushtisharma10?

**Comment by manastole03** [comment]
Yeah sure I will do that but what about the total design ? 
Is it appealing @kaustubhgupta

**Comment by kaustubhgupta** [comment]
> Yeah sure I will do that but what about the total design ?
> Is it appealing @kaustubhgupta

Yes. the word clouds are pretty good

**Comment by antrikshmisri** [comment]
> > ![Banner Image](https://user-images.githubusercontent.com/55608869/111196946-e02c4480-85e3-11eb-95b9-1609d4ec96c8.png)
> > This is the banner image for python-scripts.
> > If the design is good and if any changes required then I am able to do that.
> > @kaustubhgupta @subhangi2731 @avinashkranjan
> 
> I would suggest some more appealing font, stylish font. What say @avinashkranjan, @antrikshmisri & @santushtisharma10?

@kaustubhgupta For sure , the font style needs some improvement. @manastole03 maybe refer the [site](https://avinashkranjan.github.io/Amazing-Python-Scripts/) for inspiration. Good job on the word cloud 🔥

**Comment by manastole03** [comment]
Thanks a lot for your comments 🙂 @antrikshmisri @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@manastole03 have you implemented the new font?

**Comment by manastole03** [comment]
Yes I will update you before 6 pm @kaustubhgupta

**Comment by manastole03** [comment]
Do you want that 'Amazing' word there ? @kaustubhgupta

**Comment by manastole03** [comment]
![Turquoise Orbs General Twitch Banner (2)](https://user-images.githubusercontent.com/55608869/111686632-48329300-884f-11eb-9f47-f6d97523a875.png)

Please review it.
@kaustubhgupta @subhangi2731 @avinashkranjan

**Comment by kaustubhgupta** [comment]
> ![Turquoise Orbs General Twitch Banner (2)](https://user-images.githubusercontent.com/55608869/111686632-48329300-884f-11eb-9f47-f6d97523a875.png)
> 
> Please review it.
> @kaustubhgupta @subhangi2731 @avinashkranjan

noice! I have put a message on the discord server about final confirmation from PA

**Comment by kaustubhgupta** [comment]
@manastole03 Make the PR for the above banner. Make sure to put the banner in the gh-pages branch of the repo
