### ISSUE TITLE
Website for this Project

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#132]
----------------------
Updates: All task done
----------------------

# AIM

The minimum features I am looking for is:

- 1. Static Landing Page which mentions the Core Objective of the Project
- 2. A-List of Scripts in mentioned along with their description
- 3.  Contributors List

 Issue is simply too large to be assigned to one person. It would be further broken up into multiple issues. People who will be contributing will be given separate issue to work for.

Check out the **Discussion Channel** for More  #155

**Comment by vaibhav1865** [comment]
Hello there ,
Please assign this to me

**Comment by avinashkranjan** [comment]
Sure @vaibhav1865 .. Before going in could you giv a gist of things you'll working on..and Make a PR to the `gh-pages` branch instead of master.

**Comment by avinashkranjan** [comment]
@vaibhav1865 Are you working on this?

**Comment by fatmab2809** [comment]
Hi, I would like to work on this. I know HTML, CSS and JS. Will it be enough to work on this issue?

**Comment by vaishnavirshah** [comment]
Hi, I have basic knowledge of HTML, CSS and JS, so I think I will be able to work on the frontend of the webpage. So how will this issue be further divided? What part should I work on?
And I would like to contribute to this issue - as part of SWOC-21

**Comment by dhwanishingala** [comment]
Hello, I would like to work on this!

**Comment by avinashkranjan** [comment]
Hello @fatmab2809 @vaishnavirshah @dhwanishingala Can we discuss about the website and what you'll be doing?
You guys can decide among yourselves and divide the work or if not then I can assign you different parts of website to work on? which one would you guys be more comfortable in?

**Comment by fatmab2809** [comment]
Yes, we can discuss about the website on Slack to get a clear picture. And I am comfortable with both ways.

**Comment by vaishnavirshah** [comment]
Could we discuss about what is expected before we divide the work?

**Comment by Priyanshu-official** [comment]
@avinashkranjan I also want to Work on this Project 
SWOC-21- Participant

**Comment by Priyanshu-official** [comment]
If we are going to divide this so we can use React and Make component for the website...

**Comment by SHITIZ-AGGARWAL** [comment]
@avinashkranjan  I can work on the ui designing part ,this will ease the work since you will have a basic layout about how the site will look

**Comment by avinashkranjan** [comment]
I was looking for a UI/UX Designer.. To Get Started with the Designing Part Sure go ahead.. @SHITIZ-AGGARWAL

**Comment by avinashkranjan** [comment]
Kindly, Share your Ideas and what are you looking forward to work in the website in this discussion thread [here.](https://github.com/avinashkranjan/Amazing-Python-Scripts/discussions/155) 
@fatmab2809 @vaishnavirshah @Priyanshu-official @dhwanishingala

**Comment by Ayush7614** [comment]
@avinashkranjan i also want to work on this issue

**Comment by jainstuti** [comment]
I want to contribute to it.Please assign this to me as a part of gssoc21.

**Comment by Ayushbajpai19** [comment]
I would really like to work on this project, once approved I can start working on it under GSSOC'21.

**Comment by kaustubhgupta** [comment]
Final Update:

The website will be launched soon! All necessary tasks done
