### ISSUE TITLE
PDF tables to CSV files

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#136]
# Aim

-  Script to convert the tables in the PDF file into CSV files.

# Details

- Each CSV file has one table from the PDF and the number of CSV should be equal to the number of tables in the PDF.

**Comment by Siddhant-K-code** [comment]
Can we use this [API](https://pdftables.com/pdf-to-excel-api) to complete this task?

**Comment by avinashkranjan** [comment]
Sure.. @Siddhant-K-code

**Comment by avinashkranjan** [comment]
@Siddhant-K-code Should I assign this to you?

**Comment by Siddhant-K-code** [comment]
yes, please.

**Comment by avinashkranjan** [comment]
[sample1.pdf](https://github.com/avinashkranjan/Amazing-Python-Scripts/files/5501176/sample1.pdf)
Here You go... Assigned to you.. @Siddhant-K-code
