### ISSUE TITLE
Discord News Bot With AI functionalities

### ISSUE THREAD

**Issue by cop6567** [avinashkranjan/Amazing-Python-Scripts#1402]
## A Discord bot which sends news articles every 10 minutes with AI functionalities

**This is the first time I've contributed to open source. This project consists of sending news articles to a discord server. It then responds to the article sarcastically** 

## Instructions

- Get a token from the Discord developer portal: https://discord.com/developers/applications
- Get a token from the NewsAPI: https://newsapi.org
- Install the necessary Python packages: pip install -r requirements.txt
- Enter the token from the discord developer portal ``TOKEN`` variable
- Enter the token from the NewsAPI in the ``params`` tuple
- Enter the channel ID in the ``CHANNEL_ID`` for the bot to send articles to your desired channel
- Run the bot: ``python discord_news.py`` or ``python3 discord_news.py`` on Linux and MacOS
- The bot will automatically send news articles every 10 minutes.

### Programming Language

- [x] Python

I'd Like to upload this project.

**Comment by cop6567** [comment]
I'd like to upload this project. Could you please assign this issue to me?

**Comment by avinashkranjan** [comment]
Sure @cop6567 Go Ahead Assiging it to you.
