### ISSUE TITLE
Python code to open a website multiple times in a single click

### ISSUE THREAD

**Issue by Shivansh-Jain-github** [avinashkranjan/Amazing-Python-Scripts#1408]
Hi @avinashkranjan 
I am Shivansh Jain. I want to contribute by adding " Python code to open a website multiple times in a single click ".
Kindly assign me this task for GSSoc'23.

**Description of issue.**
The Python code snippet provided allows users to open a website multiple times with a single click. By utilizing the power of automation, this code saves the user from the repetitive task of manually opening a website multiple times. With a simple execution, the code launches a web browser and navigates to the specified website repeatedly, according to the desired number of iterations specified by the user. This efficient solution provides a convenient way to streamline website access and increase productivity.

**Comment by RaghavLimbani** [comment]
The input of how many times the site should open should be manual or what, help me with this single thing. I think I would like to do it

**Comment by rahulkothuri** [comment]
I'll solve this issue.

**Comment by RaghavLimbani** [comment]
I have already solved it bro, I just need to clear what does it mean to open a site multiple times, like to open it in multiple tabs or refresh same tab

**Comment by kgaurav35** [comment]
I was wondering why do you want to open a website multiple times? what purpose does it serve exactly?

**Comment by avinashkranjan** [comment]
Go Ahead @Shivansh-Jain-github
