### ISSUE TITLE
Sentiment analysis of texts

### ISSUE THREAD

**Issue by okaditya84** [avinashkranjan/Amazing-Python-Scripts#1410]
# Aim

- Quantifying emotions of text buy sentiment analyzer.

# Details

- Using RNN model to detect the emotion used to write the text trained on word2vec dataset with 15 epochs.
- Detecting emotions and rating them on a scale of 0 to 1 where 0 being the lowest and 1 being the highest.
- Classifying into very positive, positive, neutral, negative and very negative.
- Using python libraries like Pandas, numpy, keras, LSTM, tokenizer.

**Comment by aman-kumar29** [comment]
Hello, I have worked on models like this and sentiment analysis using many approaches. It would be great if you could assign it to me. @avinashkranjan

**Comment by avinashkranjan** [comment]
Go Ahead @okaditya84
