### ISSUE TITLE
Automate adding songs in a Spotify Playlist

### ISSUE THREAD

**Issue by hima-v** [avinashkranjan/Amazing-Python-Scripts#1412]
# Aim:
To add new songs from Discover Weekly which are recommended by Spotify in one playlist

# Details
The Discover Weekly playlist refreshes every week. To automatically save the songs in one playlist we can use Spotify Web API to access user data and build a Flask application. This will create the playlist in which songs get added automatically.

I want to work on this issue as a GSSoC'23 Contributor

**Comment by swetha3456** [comment]
Hi, I'd like to work on this. It would be great if you could add me as a contributor. Thanks!

**Comment by avinashkranjan** [comment]
GO Ahead @hima-v
