### ISSUE TITLE
Python Script to scrap the data searched by user

### ISSUE THREAD

**Issue by mahesh-11102** [avinashkranjan/Amazing-Python-Scripts#1413]
## Aim
To make a User Friendly search bot which summarizes the result.

## What the features will your script have
- The search bot locates the relevant webpage and extracts the text content from it using the Beautiful Soup library.
- Using Gensim Library I've summarized the result.
- With an interface created using the Tkinter GUI toolkit that enables the user to easily enter their search query in the text box and initiate the search by clicking the submit button.
-  The search bot also allows users to create a word cloud visualization of the summary using the WordCloud library. This feature is particularly useful in visualizing the most prominent words in the summary and providing a quick overview of the main themes and ideas presented in the content.

<hr>

## Flow chart of the process
- Text summarization
![image](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/77436328/cf0f220d-af9a-4b0c-9421-28533a9bfdb9)
- Whole process
![image](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/77436328/bac31a70-d940-4b39-8a5b-01fe48d81384)
<hr>

## Snapshot of the project

<p>
    <img src="https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/77436328/e9f4c359-2546-40be-9897-98d779b5484e" width="350" height="450">
   <img src="https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/77436328/2a169568-9cf2-4dfd-ad2c-19b5c8d02533" width="350" height="450">
</p>

**Comment by avinashkranjan** [comment]
Go Ahead @mahesh-11102
