### ISSUE TITLE
AI Calculator

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [avinashkranjan/Amazing-Python-Scripts#1415]
# Aim

The calculator with the power of artificial intelligence

**Comment by MahraibFatima** [comment]
Tasks have to do:
1.It takes in inputs as text.
2.Translates them into mathematical notation.
3.Returns the answers in the numerical form.

It use some general command for plus, minus, multiplication and division with associated function.
I'd done it before I think I can do it very. Assign this to me if you got me capable for it..

**Comment by Soumya-Kushwaha** [comment]
@avinashkranjan I created this issue. Please have a look. I'd like to work on this.

**Comment by Vethan123** [comment]
Hi @Soumya-Kushwaha I have the code ready for virtual calculator using 
Cv2 and open cv libraries . I think that code with slight modification helps
In this issue. For that please assign this to me.

**Comment by avinashkranjan** [comment]
Go Ahead @Soumya-Kushwaha
