### ISSUE TITLE
Suggesting impovement/expansion of the CPU temperature script

### ISSUE THREAD

**Issue by infernalsaber** [avinashkranjan/Amazing-Python-Scripts#1416]
**Is your feature request related to a problem? Please describe.**
I think the in the CPU temperature script [here](https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/CPU%20temperature), we could also add an option for displaying the RAM/CPU utilization

**Describe the solution you'd like**
Adding another script which tells the cpu/ram usage or integrating it into the same script

**Additional context**
This will tell the user more about their system utilization, and can be really helpful for applications esp those over the cloud where whipping up the task manager is not an option

**Comment by infernalsaber** [comment]
@avinashkranjan could you please look at this

**Comment by avinashkranjan** [comment]
Go Ahead @infernalsaber

**Comment by vk20july** [comment]
@avinashkranjan sir can i do this task under gssoc'23
