### ISSUE TITLE
Add Number details tracking project

### ISSUE THREAD

**Issue by Uma-95** [avinashkranjan/Amazing-Python-Scripts#1417]
**Is your feature request related to a problem? Please describe.**
This is a beginner-level Python project which gives details about the phone number provided. Details like the area of registration of sim card, the company name of that SIM card, etc.(as a part of GSSOC'23)

**Comment by Uma-95** [comment]
@avinashkranjan could you please assign this issue to me.

**Comment by avinashkranjan** [comment]
Go Ahead @Uma-95
