### ISSUE TITLE
Updating the README.md file of face_detection project.

### ISSUE THREAD

**Issue by sakshid2706** [avinashkranjan/Amazing-Python-Scripts#1418]
[GSSOC 23] The README.md of face_detection project has some grammatical errors and is also not very clear, it is needed to be updated.

**Comment by PrathmeshN99** [comment]
Hello @sakshid2706 , I'm a contributor in GSSoC, this is my first contribution to the programme, can you please assign this to me?

**Comment by sakshid2706** [comment]
Hello @PrathmeshN99 , Actually I am also a contributor in GSSoC, I have created this issue for my own contribution.

**Comment by avinashkranjan** [comment]
Go Ahead @sakshid2706

**Comment by sakshid2706** [comment]
Thank You @avinashkranjan for assigning this issue to me.
