### ISSUE TITLE
Add a "Scroll to Top" floating button

### ISSUE THREAD

**Issue by harshita-kaushik2** [avinashkranjan/Amazing-Python-Scripts#1419]
### Description :
Missing "Scroll to Top" button in the website

### Expected Outcome :
Adding this floating button would enhance the user experience of the website. One click on it will lead the user to the home page.

I'd love to contribute this feature as I have past experience of creating in my personal projects and would request you to assign this issue to me as GSSoC 2023 Contributor.
Thank You :)

**Comment by VyjayantiN** [comment]
Dear @harshita-kaushik2,
In my recent personal project, I have worked on similar issues. I could really make it out in no time. I am interested to do this. Will you please assign me this issue as well!!

**Comment by avinashkranjan** [comment]
Go Ahead @harshita-kaushik2
