### ISSUE TITLE
Add styling to the scroll bar

### ISSUE THREAD

**Issue by harshita-kaushik2** [avinashkranjan/Amazing-Python-Scripts#1420]
### Description :
The scroll bar is plain vanilla and does not match the theme of the website.

### Expected Outcome :
Styling the scrollbar as per the theme of the website would add to enhance the overall UI of the page.

I would love to add this feature and request you to assign this issue to me as a GSSoC 2023 contributor.
Thank You :)

**Comment by VyjayantiN** [comment]
Dear @harshita-kaushik2,
I would love to do this!! We you please assign me this task.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by avinashkranjan** [comment]
Go Ahead @harshita-kaushik2
