### ISSUE TITLE
[SCRIPTS] Adding Basic Data Structure Scripts

### ISSUE THREAD

**Issue by himanshu-03** [avinashkranjan/Amazing-Python-Scripts#1421]
# Aim

- The objective for the script is pretty simplem It will help users in seeing the working of basic data structures with menu driven and neatly formatted codes.

# Details

- [x] Menu Driven Stack Scripts
- [x] Menu Driven Queue Scripts
- [x] Menu Driven Linked List Scripts
- [x] Sorting Techniques (Bubble Sort, Merge Sort, Insertion Sort)
- [x] Searching Techniques (Binary Search, Sequential Search)

Hello!
I am [Himanshu Agarwal](https://github.com/himanshu-03), a proud contribtuor at GSSoC '23. I would like to the contribute to this project.

@avinashkranjan if you think it is useful then do assign me the issue under GSSoC '23 with the level of the PR as well

**Comment by avinashkranjan** [comment]
Go Ahead @himanshu-03

**Comment by himanshu-03** [comment]
Hi @avinashkranjan! 👋🏻

💯 I have successfully completed the things I mentioned in my issue.

✌🏻 Do review my PR here: #1656
