### ISSUE TITLE
Refactor code for improved readability in Stone-Paper-Scissors-Game

### ISSUE THREAD

**Issue by mukeshmade** [avinashkranjan/Amazing-Python-Scripts#1422]
## Issue:
The current code for the Stone Paper Scissors game could benefit from refactoring to enhance readability and maintainability. The code would benefit from the following changes:

Improve Error Handling: Currently, when the user enters an invalid number, the program continues to the next iteration without providing proper feedback. We should modify the code to display an error message and prompt the user to enter a valid number.

Code Refactoring: The code can be refactored to improve modularity and clarity. It would be helpful to break down the code into smaller functions that handle specific tasks, such as getting user input, determining the winner, and displaying the results. This will make the code more maintainable and easier to understand.

Documentation and Comments: It would be beneficial to add comments throughout the code to explain the purpose of the code blocks, functions, and important variables. Additionally, including a docstring at the beginning of the code or each function would provide a brief description of what the program does and how to use it.

## Details:

- [ ] Modify error handling logic
- [ ] Refactor code into smaller functions
- [ ] Add comments to explain code blocks
- [ ] Include docstrings for functions
- [ ] Update overall code documentation

Hello!
I am a proud contributor at GSSoC '23. I would like to the contribute to this project.

@avinashkranjan if you think it is useful then do assign me the issue under GSSoC '23 with the level of the PR as well

**Comment by avinashkranjan** [comment]
Go Ahead @mukeshmade
