### ISSUE TITLE
Language Translator

### ISSUE THREAD

**Issue by tayyab-ilyas** [avinashkranjan/Amazing-Python-Scripts#1428]
# Aim

- Translate a string to multiple languages

# Details

- Take an input from the user and translate it to multiple languages.

**Comment by tayyab-ilyas** [comment]
hey @avinashkranjan ! can you assign me this issue under GSSoc'23, thanks!

**Comment by avinashkranjan** [comment]
Go Ahead @tayyab-ilyas

**Comment by tayyab-ilyas** [comment]
Hi @avinashkranjan thanks for assigning this to me! I've created a PR :)
