### ISSUE TITLE
[GSSoC'23] Add GUI to Weather-App

### ISSUE THREAD

**Issue by subhradip-bo** [avinashkranjan/Amazing-Python-Scripts#1429]
**Is your feature request related to a problem? Please describe.**
So to access the Weather app, we have to use terminal, I want to add GUI to it.

**Describe the solution you'd like**
I will be using Tkinter to do it.

@avinashkranjan I hope you assign this to me, under GSSoC'23, thank you!

**Comment by RaghavLimbani** [comment]
I would love to do contribute to this can you assign me this

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by avinashkranjan** [comment]
Go Ahead @subhradip-bo
