### ISSUE TITLE
Create a Script to summarize Text

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#143]
# Aim

- Create a Script to summarize Text. You can take a look at some SOTA Techniques to achieve this along with wrappers that make it really easy to summarize the Text. You can also try out your own algorithm for Text Summarization and to make it lightweight and-efficient at the same time.

**Comment by kazuyoshi-tech** [comment]
Hey, I would like to contribute towards this issue. Please assign me.

Thanks

**Comment by avinashkranjan** [comment]
Sure @kazuyoshi-tech Go ahead
