### ISSUE TITLE
[GSSoC '23] Email Automation with File Attachments

### ISSUE THREAD

**Issue by swetha3456** [avinashkranjan/Amazing-Python-Scripts#1431]
# Aim

- To send personalized emails (with similar content) to different clients with email attachments.

# Details

- It will allow the user to modify the receiver's name and email address for a fixed email body.
- The user can also attach files to the email.
- The email will be sent automatically when the script is executed.

**Comment by swetha3456** [comment]
Hi @avinashkranjan, I'd like to work on this issue as a GSSoC '23 contributor. Please assign this issue to me.

**Comment by shubham725809** [comment]
I am good at machine learning and had developed lots of machine learning projects, so adding this feature is not a big task for me. so please assign me this and I am also a GSSOC 2023 contributor.

**Comment by avinashkranjan** [comment]
Go Ahead @swetha3456
