### ISSUE TITLE
AI Tic Tac Toe Game [GSSOC'23]

### ISSUE THREAD

**Issue by ayush-09** [avinashkranjan/Amazing-Python-Scripts#1437]
# Aim

The objective of the script is to enhance the Tic Tac Toe game by adding an AI player that provides a challenging gameplay experience for single-player mode.

# Details

The script will include the following features:

- AI Player: Implement an intelligent AI player that can make strategic moves in the Tic Tac Toe game.
- Difficulty Levels: Include different difficulty levels for the AI player, allowing users to choose the level of challenge they desire.
- Minimax Algorithm: Utilize the minimax algorithm to optimize the AI player's decision-making process and ensure optimal moves.
- User Interface: Improve the user interface by displaying game status, current player's turn, and the AI player's moves.
- Error Handling: Implement error handling to handle invalid inputs and provide appropriate error messages to the user.
- Replay and Exit: Provide options for the user to replay the game or exit after completing a game.

By adding these features to the script, it will offer an enhanced and engaging gameplay experience for users, allowing them to enjoy playing Tic Tac Toe against an intelligent AI player.

**Comment by Harshajny** [comment]
Hi 
I wish to work on this issue. Can you assign it to me.

**Comment by ayush-09** [comment]
@Harshajny Avinash is the person who assign the issue.
@avinashkranjan may you review and check the issue.

**Comment by shubham725809** [comment]
I am good at web development and have developed many web development projects, so adding this feature is not a big task for me. so please assign me this and I am also a GSSOC 2023 contributor.

**Comment by avinashkranjan** [comment]
Go Ahed @ayush-09

**Comment by ayush-09** [comment]
@avinashkranjan Please check my PR and merge it if everything allright

**Comment by avinashkranjan** [comment]
> @avinashkranjan Please check my PR and merge it if everything allright

Requested Changes
