### ISSUE TITLE
Multi-Language Translation [GSSoC'23]

### ISSUE THREAD

**Issue by Archit-Kohli** [avinashkranjan/Amazing-Python-Scripts#1438]
# Aim

- Convert any phrase in any language to a list of languages input by the user.

# Details

- User inputs the text (in any language).
- User inputs a list of languages into which he wants to translate.
- The text is translated into all languages in the list using google translate API.
- **Output** is a list of phrases in the translated languages.

**Comment by Archit-Kohli** [comment]
Please assign this issue to me, I can create a wonderful python script to do this. 
Thanks 😋

**Comment by avinashkranjan** [comment]
Go Ahead @Archit-Kohli
