### ISSUE TITLE
[GSSOC'23] Updating readme of  BMI Calculator GUI

### ISSUE THREAD

**Issue by mkswagger** [avinashkranjan/Amazing-Python-Scripts#1442]
# Title: 
Add README with Screenshots and Output for BMI Calculator
https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/BMI-Calculator-GUI
# Description: 
The current repository lacks a detailed README explaining the usage and features of the salary predictor. Create a comprehensive README.md file that includes clear installation instructions, usage examples, and screenshots showcasing the application's output. This will help users understand and utilize the salary predictor effectively.

# Additional Information:   
to include relevant screenshots of the application's output and provide clear instructions on how to reproduce the results. 
![Screenshot (1762)](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/34826479/e0587b52-ca9a-43f9-b60c-6f25c8fe0d1f)

https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/BMI-Calculator-GUI

**Comment by mkswagger** [comment]
Hi @avinashkranjan ,
I am a contributor in GSSOC'23 and would love to work on this issue. Please assign the issue to me

**Comment by anandanmukh** [comment]
Hello @mkswagger I would love to contribute... Please check out my readme files, so you know who to pick :)

**Comment by avinashkranjan** [comment]
Go Ahead @mkswagger
