### ISSUE TITLE
[GSSOC'23]Invalid input NAME in age calculator

### ISSUE THREAD

**Issue by Shiv-Expert2503** [avinashkranjan/Amazing-Python-Scripts#1444]
## **Describe the bug**
In Age-Calculator-GUI the name section takes Numerical string also as an Input which is INVALID! The name section must take only Characters.

## **To Reproduce**
1. Go to the code.
2. Run the code.
3. In the name section pass a numerical value.
4. See the error.

## **Expected behavior**
The name section must only take characters as input, not numerical values. 

## **Screenshots**
![Screenshot (73)](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/122978299/1747cd29-6613-4fdf-9388-03f7c4e822c5)

## **Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

# **Additional context**
I can fix this issue! Please give me the opportunity to solve it.

**Comment by Ujjawalsidana** [comment]
I want to work on this issue

**Comment by Shiv-Expert2503** [comment]
@avinashkranjan please check and review it. I'm almost done with it!

**Comment by shubham725809** [comment]
I am good at web development and have developed many web development projects, so adding this feature is not a big task for me. so please assign me this and I am also a GSSOC 2023 contributor.

**Comment by avinashkranjan** [comment]
Go Ahead @Shiv-Expert2503
