### ISSUE TITLE
[GSSOC 2023] Incomplete README Content and Updated Script of CPU TEMPERATURE

### ISSUE THREAD

**Issue by slayerrr12** [avinashkranjan/Amazing-Python-Scripts#1447]
The README file for the project currently contains incomplete information, which makes it difficult for other users to understand and use the CPU temperature retrieval script. The previous version of the README lacked important sections such as Prerequisites, Explanation of the Script, Setup Instructions, Output, Compatibility, Contributing, and License.

In addition to the incomplete **README**, the assistant provided an updated **script** in the previous interaction, which is missing from the repository. The updated script includes improvements such as better code organization and enhanced error handling.

This issue is raised to request the completion of the README file by adding the missing sections with the relevant information and to include the updated script in the repository. By doing so, it will provide clear instructions, improve the usability of the script, and ensure consistency between the README and the code.
@avinashkranjan  pls assign this issue to me

**Comment by slayerrr12** [comment]
@avinashkranjan  may you review and check this issue pls

**Comment by avinashkranjan** [comment]
Go Ahead @slayerrr12 , Assigned it to you.
