### ISSUE TITLE
Updating website name and  favicon 

### ISSUE THREAD

**Issue by anuza08** [avinashkranjan/Amazing-Python-Scripts#1449]
**Describe the bug**
The website's favicon is missing, also the title is wrong 

**Expected behavior**
Adding the title 'Amazing Python Script'  which is the name of the website

**Screenshots**
![Screenshot (16)](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/98256478/226f9162-cacb-4a08-8381-f819df884608)

**Comment by avinashkranjan** [comment]
Issue Aleady Open and Assigned to Someone else.
