### ISSUE TITLE
[GSSOC'23] Half output statement in Age-Calculator

### ISSUE THREAD

**Issue by Shiv-Expert2503** [avinashkranjan/Amazing-Python-Scripts#1450]
## **Is your feature request related to a problem? Please describe.**
I'm always frustrated when this type of half-message is shown.
![Screenshot (76)](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/122978299/1b73db57-5384-42c8-815f-9db45717e94f)

## **Describe the solution you'd like**
I'll make it look like the following: which is more liked and easily readable.
![Screenshot (77)](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/122978299/3fddcb4d-acc0-405b-bf0f-4b84e188cb38)

# **Additional context**
I can do this for all the texts. Please assign me this issue. I want it to make user-friendly.

**Comment by shubham725809** [comment]
I am good at machine learning and had developed lots of machine learning projects, so adding this feature is not a big task for me. so please assign me this and I am also a GSSOC 2023 contributor.

**Comment by avinashkranjan** [comment]
Go Ahead @Shiv-Expert2503
