### ISSUE TITLE
[GSSOC'23] : Login & Sign-up page Script GUI

### ISSUE THREAD

**Issue by bishalde** [avinashkranjan/Amazing-Python-Scripts#1452]
# Aim
I want to add an login and signup page tkinter GUI Script.

# Details
This is basically a login and signup page with authentication that will be implemented using database of text file.

**Comment by Aditya-madwal** [comment]
Hi, this is Aditya Madwal, a contributor in GSSOC'23.
I would like to work on this issue.
I would like to create this with a good and genuine UI and all the necessary requisites.
With all due respect, you are requested to assign it to me.

**Comment by shubham725809** [comment]
I am good at machine learning and had developed lots of machine learning projects, so adding this feature is not a big task for me. so please assign me this and I am also a GSSOC 2023 contributor.

**Comment by avinashkranjan** [comment]
Go Ahead @bishalde
