### ISSUE TITLE
[GSSoC 23'] GUI-based Sign-Up Portal with Custom Tkinter

### ISSUE THREAD

**Issue by HartzFrequency** [avinashkranjan/Amazing-Python-Scripts#1453]
# Aim

 GUI[Custom Tkinter] based Sign-Up portal 

# Details

The script provides a graphical user interface (GUI) for a sign-up portal that validates user credentials by checking them against a database. The portal ensures that the entered username and password are correct before allowing the user to proceed further. This enhanced and professional script is designed to deliver a secure and user-friendly sign-up experience.

Key Features:
1. User Authentication: The script verifies the authenticity of user credentials by querying a database. It compares the entered username and password with the stored records to ensure their correctness.

2. Database Integration: The script employs a database, such as SQLite, to store and retrieve user information securely. It connects to the database and executes SQL queries to perform necessary operations.

3. Password Security: To ensure the security of a password, the hides the password and shows '*' in place of words

**Comment by avinashkranjan** [comment]
Go Ahead @HartzFrequency
