### ISSUE TITLE
[GSSoC 2023] Image-to-PDF Conversion Program Contribution

### ISSUE THREAD

**Issue by VishalS-HK** [avinashkranjan/Amazing-Python-Scripts#1455]
I am a contributor at GSSoC'23. I want to contribute a Python program to convert a collection of image files into a single PDF file. 
The allowed file types for image files are .jpg, .jpeg, .png, and .gif.

**Comment by AvishkarArjan** [comment]
Hi I'm a contributor at GSSoC '23, I would like to contribute on this issue ! Could I be assigned ?

**Comment by shubham725809** [comment]
I am good at machine learning and had developed lots of machine learning projects, so adding this feature is not a big task for me. so please assign me this and I am also a GSSOC 2023 contributor.

**Comment by avinashkranjan** [comment]
Go Ahead @VishalS-HK
