### ISSUE TITLE
[GSSOC'23] Resume Parser using Python

### ISSUE THREAD

**Issue by mkswagger** [avinashkranjan/Amazing-Python-Scripts#1461]
# Title: Proposal: Add Resume Parser Using PDFMiner and Python

# Description: 
This proposal suggests adding a resume parser script to the repository that utilizes the PDFMiner library in Python. The script will extract essential information from PDF resumes, including personal details, education, skills, and work experience. This will streamline the recruitment process and assist in automated resume screening.

# Additional Information:
 As a contributor, I will be working on implementing the resume parser using PDFMiner and Python.

**Comment by mkswagger** [comment]
Hi @avinashkranjan , I am a contributor in GSSOC'23 and would love to work on this issue, Please assign this issue to me

**Comment by hindvee** [comment]
**Objective**: Add Resume parser using python
**Methodology and approach**: As our basic aim is to extract relevant information from the resume, my suggestion would be to use PDFMiner as our primary library. 

I have already worked on data scraping projects and look forward to contributing to this exciting project. I ask that you consider me for this, and I look forward to putting my all into the effort.

**Comment by mkswagger** [comment]
> I am a contributor in GSSOC2023 **Objective**: Add Resume parser using python **Methodology and approach**: As our basic aim is to extract relevant information from the resume, my suggestion would be to use PDFMiner as our primary library.
> 
> I have already worked on data scraping projects and look forward to contributing to this exciting project. I ask that you consider me for this, and I look forward to putting my all into the effort.

Sorry , I created this issue for me to work on
Thankyou

**Comment by avinashkranjan** [comment]
Go Ahead @mkswagger

**Comment by mkswagger** [comment]
> Go Ahead @mkswagger

Thankyou @avinashkranjan

**Comment by Avdhesh-Varshney** [comment]
@avinashkranjan @1e9abhi1e10 @Yashbhadiyadra Sirs, i would like to work this project. can you assign it to me ?

**Comment by mkswagger** [comment]
> @avinashkranjan @1e9abhi1e10 @Yashbhadiyadra Sirs, i would like to work this project. can you assign it to me ?

I am currently working on this issue and will make a pr in a day or two. Thankyou
