### ISSUE TITLE
[GSSoC'23 ]PDFs merger Program Contribution

### ISSUE THREAD

**Issue by VishalS-HK** [avinashkranjan/Amazing-Python-Scripts#1470]
I am a contributor at GSSoC'23. I want to contribute the following : 

# Aim
- Contribute a Python program to merge all pdf files in a directory into a single PDF file.

Can I be assigned this issue.

**Comment by avinashkranjan** [comment]
Go Ahead @VishalS-HK

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by avinashkranjan** [comment]
Go Ahead @sagnik-p
