### ISSUE TITLE
[GSSOC] Discord bot Feature Addition Request and Readme Updation

### ISSUE THREAD

**Issue by slayerrr12** [avinashkranjan/Amazing-Python-Scripts#1473]
Hi @avinashkranjan 

_Is your feature request related to a problem? Please describe._
### **I would like to request the addition of new features and improvements to the bot.**

_Describe the solution you'd like_
I have added a roll command that can generate random numbers within a specified range, and a server member count command that displays the current member count of the server. I have also made updates to the **README file** and added comments to the script for better **readability and maintainability**.

_Describe alternatives you've considered_
I have considered other ways to implement the **roll command** and **server member count feature**, but integrating them as built-in commands in the bot provides a more seamless and cohesive user experience.

_Additional context_
The updates to the **README** provide clear instructions on how to use the newly added commands and provide information about the bot's functionality. The **comments** added to the script improve code understanding and make it easier for others to contribute to the project.

pls assign this issue to me

**Comment by slayerrr12** [comment]
@avinashkranjan  pls review this issue so that i can start working on it and make a PR asap

**Comment by shubham725809** [comment]
I am good at machine learning and had developed lots of machine learning projects, so adding this feature is not a big task for me. so please assign me this and I am also a GSSOC 2023 contributor.

**Comment by avinashkranjan** [comment]
Go Ahead @slayerrr12
