### ISSUE TITLE
[GSSoC'23] Improve functionalities of YouTube-Video-Downloader

### ISSUE THREAD

**Issue by anandanmukh** [avinashkranjan/Amazing-Python-Scripts#1475]
**Is your feature request related to a problem? Please describe.**
- The current solution doesn't allow the feature of downloading playlists, only single videos
- So, I propose a solution where users can download entire playlists

**Describe the solution you'd like**
- Use the inbuilt functions from pytube to be able to download entire playlists

**Additional context**
- I have previously worked with pytube and would like to implement a better solution with this repository. Kindly assign me this issue under the GSSoC'23.

**Comment by avinashkranjan** [comment]
Go Ahead @anandanmukh
