### ISSUE TITLE
Hand Written digit prediction

### ISSUE THREAD

**Issue by Raghucharan16** [avinashkranjan/Amazing-Python-Scripts#1477]
- **What is the objective of the Script?**

*It is a simple web app integrated with small convolutional model which takes the input drawing on canvas and predicts the output and displays the confidence of that predicted number*

- **What the features will your script have**
*It is functional on all devices by adjusting itself to the screen and provides the suitable space for canvas ( for user to draw ) and gives the accurate outputs in realtime.*

**Screenshot**

![Screenshot (1)](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/104614903/78993fda-183d-465d-a5df-832273f11016)

## kindly assign this issue to me under GSSoC label.

**Comment by avinashkranjan** [comment]
Go Ahead @Raghucharan16
