### ISSUE TITLE
[GSSoC 23'] Flipkart Scraper 

### ISSUE THREAD

**Issue by paritoshtripathi935** [avinashkranjan/Amazing-Python-Scripts#1479]
# Aim

- I wrote this script to help in my project product-matching to scrape products from flipkart, it may be helpful to others for various use cases.

# Details

- added support for easy product input.
- SQLite db for data storage.
- selenium backup support in case rate-limiting or blocking happens while scraping.
- Multi threading support for faster scraping.
- scrape multi parameters of a product.

**Comment by paritoshtripathi935** [comment]
hey @shubham725809 i am already working on this issue as it was opened by me i am waiting for @avinashkranjan to assign it to me.

**Comment by hindvee** [comment]
I've completed a project on collecting weather data, thus I am familiar with the various libraries used in it. I hope that you consider me for this position, and I look forward to contributing my all to the endeavor. Kindly assign me this project.

**Comment by avinashkranjan** [comment]
Go Ahead @paritoshtripathi935

**Comment by paritoshtripathi935** [comment]
@avinashkranjan please can you have a look on pr?

**Comment by avinashkranjan** [comment]
> @avinashkranjan please can you have a look on pr?

Kindly Mention the Issue No In PR.
