### ISSUE TITLE
[GSSOC'23] Request to add code for Measuring Internet Speed

### ISSUE THREAD

**Issue by Abhishek-Rajput-81** [avinashkranjan/Amazing-Python-Scripts#1481]
# Aim

-  To measure the internet speed of a network connection using "Speedtest" library.

# Details
- The script will have the following features:
 1. Download Speed Measurement: The script will perform a download speed test to measure the rate at which data can be downloaded from the internet.

 2. Upload Speed Measurement: The script will also conduct an upload speed test to measure the rate at which data can be uploaded to the internet.

 3. Latency Measurement: The script will measure the latency or ping time, which represents the time it takes for a data packet to travel from the user's device to a server and back. This metric helps determine the responsiveness of the network connection.

**Comment by Abhishek-Rajput-81** [comment]
@avinashkranjan  may you review and check this issue pls

**Comment by shubham725809** [comment]
I am good at machine learning and web development and had developed lots of machine learning projects, so adding this feature is not a big task for me. so please assign me this and I am also a GSSOC 2023 contributor.

**Comment by avinashkranjan** [comment]
Go Ahead @Abhishek-Rajput-81
