### ISSUE TITLE
Flask Boiler Plate code

### ISSUE THREAD

**Issue by devkakeri06** [avinashkranjan/Amazing-Python-Scripts#1487]
# Aim

- To create a boilerplate code that works for most Flask applications with a brief description of what it can do.

# Details

- All the methods such as GET, POST, PUT etc will be included along with instructions on how to set up the app in readme.md file.
- All the methods will be briefly described in the comments.
- Users can use this as a starter code to accelerate their development.

**Comment by avinashkranjan** [comment]
Not a kind of a script, as in Not Applicable for this Repo, Do Let me know if you are planning it make is as some kind of script. Till then keeping the issue on hold

**Comment by owenwu811** [comment]
Something like this?

from flask import Flask, render_template, request
app = Flask(__name__)
@app.route('/', methods=['GET'])
def get_method():
    return 'This is a GET method.'
@app.route('/', methods=['POST'])
def post_method():
    data = request.get_json()
    return 'Received data: {}'.format(data)
@app.route('/', methods=['PUT'])
def put_method():
    data = request.get_json()
    return 'Updated data: {}'.format(data)
@app.route('/', methods=['DELETE'])
def delete_method():
    return 'Deleted the requested resource.'
if __name__ == '__main__':
    app.run(debug=True)

**Comment by avinashkranjan** [comment]
Not Applicable for this Repo..Create Issues for adding some kind of Script.
