### ISSUE TITLE
[ GSSOC '23 ] Adding README.md file for Webcam Image Capture Script

### ISSUE THREAD

**Issue by Abhishek-Rajput-81** [avinashkranjan/Amazing-Python-Scripts#1504]
# Aim

- To add a comprehensive README.md file that provides clear instructions and documentation for the webcam image capture script.

Thank you for your attention to this matter.
@avinashkranjan

**Comment by avinashkranjan** [comment]
Go Ahead @Abhishek-Rajput-81
