### ISSUE TITLE
[GSSOC'23] Request to add code for Number Plate Detection System

### ISSUE THREAD

**Issue by parag477** [avinashkranjan/Amazing-Python-Scripts#1506]
# Aim

- I wrote this script using opencv library for detection of number plates of vehicles. 

# Details

- Can scan number plates using pc's camera.
- Take images of number plates as input and give output
- Used computer vision for making it.

Please assign me this issue under GSSoC-2023

**Comment by shubham725809** [comment]
I am good at machine learning and had developed lots of machine learning projects, so adding this feature is not a big task for me. so please assign me this and I am also a GSSOC 2023 contributor.

**Comment by Vethan123** [comment]
Hii @parag477 . I had done my previous project In this domain. I believe that
I can do It.please assign it to me.

**Comment by avinashkranjan** [comment]
Go Ahead @parag477
