### ISSUE TITLE
{Gssoc'23}  Displaying social media handles on hover the image of contributors.

### ISSUE THREAD

**Issue by SrishtiSonam** [avinashkranjan/Amazing-Python-Scripts#1507]
**Is your feature request related to a problem? Please describe.**
Displaying social media handles on hover the image of contributors, rather than giving it extra space on screen before that.

**Describe the solution you'd like**
Basically an example of my idea.
Before hover, on screen. =>        
<img width="228" alt="image" src="https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/113123593/a07f22f0-8a9f-4a23-9974-28b28d98f04c">
After Hover over the image. =>
<img width="247" alt="image" src="https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/113123593/3230da1e-9ae0-41f2-9c56-3d60ef1855e3">

**Additional context**
Assign this issue to me under gssoc23.

**Comment by avinashkranjan** [comment]
Go Ahead @SrishtiSonam
