### ISSUE TITLE
Script to scrap Social Media Pages of Websites

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#151]
# Objective

- Create a Script that can analyze the Social Media Links on a Website and generate results. You can check for popular Social Media Links and generate them as a result. Integrate an option to also pick a CSV file of Websites to scrap their data together and store in a CSV.

**Comment by twilight-warlock** [comment]
I would like to take up this issue. Can you assign it to me?

**Comment by avinashkranjan** [comment]
Sure @twilight-warlock Go ahead..

**Comment by twilight-warlock** [comment]
Hey, I am a participant in SWOC and this is my first time contributing to open source. I am done with the code so do I create a PR today or after 5th for it to be considered under SWOC

**Comment by avinashkranjan** [comment]
You can create a PR now or else wait till 5th as I'll be accepting the PRs after 5th.
