### ISSUE TITLE
Snake game additin

### ISSUE THREAD

**Issue by Akanksha-202** [avinashkranjan/Amazing-Python-Scripts#1514]
# Aim
- It is a game where the snake(player) has to get max no. of food items 

# Details

- There is a score function to keep track of how many food items are obtained.
- Restart option available so the user doesn't have to run the code again and again.
- Easy-to-understand code, for the user to manipulate according to their use. In order to alter the speed of the snake or to alter the size of the snake.

![image](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/100708686/bded5f90-d207-4f2e-bbb8-ec3fe77ddc14)

Please assign this under GSSoC'23 label :)

**Comment by avinashkranjan** [comment]
Go Ahead @Akanksha-202
