### ISSUE TITLE
[ GSSOC '23 ] Adding README.md file for Football-Player-Club-Info script.

### ISSUE THREAD

**Issue by Abhishek-Rajput-81** [avinashkranjan/Amazing-Python-Scripts#1516]
# Aim

- To add a comprehensive README.md file which is essential for providing clear instructions and information about the script.

@avinashkranjan 
Thank you for considering this suggestion!

**Comment by Mbaoma** [comment]
Hi, kindly assign this issue to me

**Comment by avinashkranjan** [comment]
Go Ahead @Abhishek-Rajput-81
