### ISSUE TITLE
Script to generate Pagespeed Results for the Website

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#152]
# Aim

- Create a Script that can generate the Pagespeed Results for the Website using the Pagespeed API.

**Comment by keshavbansal015** [comment]
Hi @avinashkranjan, I would like to work on this issue; could you assign it to me?

**Comment by avinashkranjan** [comment]
Sure @keshavbansal015 go ahead
