### ISSUE TITLE
Port Scanning

### ISSUE THREAD

**Issue by tanujbordikar** [avinashkranjan/Amazing-Python-Scripts#1522]
**Issue:**
While running the python file for the port scanner I noticed that the code was taking time so I request you to let me work on that issue. 

**Solution:**
So to tackle that issue I would use asynchronous I/O operations with non-blocking sockets to achieve faster scanning by using the in-build python library "asyncio".

**Comment by avinashkranjan** [comment]
Go Ahead @tanujbordikar
