### ISSUE TITLE
 [GSSOC'23] Number to Words convertor program

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [avinashkranjan/Amazing-Python-Scripts#1523]
# Aim

- What is the objective of the Script
Convert Number to International system in words.
# Details

- What the features will your script have
Conversion of the number -> 

Input :-
123456 

Output :-
One Hundred Twenty Three Thousand Four Hundred Fifty Six.

Please Assign This program to me to contribute in GSSoC'23

**Comment by Avdhesh-Varshney** [comment]
Please assign this task to me, Please !

**Comment by avinashkranjan** [comment]
Go Ahead @Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
Thanking you so much sir, @avinashkranjan for assigning this issue to me.

**Comment by Anjali2312-Thombare** [comment]
Hey @avinashkranjan  Can you please assign me this issue?

**Comment by Avdhesh-Varshney** [comment]
Sirs @avinashkranjan @Yashbhadiyadra , please review my pull request and merge it into the main branch for successful contribution in the program GSSoC'23.
