### ISSUE TITLE
[gssoc'23] show List files in a directory

### ISSUE THREAD

**Issue by gulshanjakhon** [avinashkranjan/Amazing-Python-Scripts#1527]
Hi @avinashkranjan 
# Aim

- What is the objective of the Script
- to display list of file content available in current directory

# Details

- What the features will your script have
script shows how to get the list of a specific directory in python using the os module.

Please assign it under gssoc'23 label
Thank you

**Comment by avinashkranjan** [comment]
Go Ahead @gulshanjakhon
