### ISSUE TITLE
A script to list out all the songs by an Artist.

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#153]
# Aim

- A Python Script to list out all the songs of an artist. Sorted according to their popularity.

# Details

- Use Google Search API for this purpose, not the most time-efficient method.
- Everyone has a favorite band/artist. But sometimes, we miss out on an old gem by that artist just because we had no clue about it.

**Comment by gargnityansh** [comment]
hello @avinashkranjan I would like to work for this issue. Can you please assign it to me?

**Comment by avinashkranjan** [comment]
Sure @gargnityansh Go ahead..

**Comment by gargnityansh** [comment]
Is this issue will be included for the swoc? As I am a participant of swoc and when do I need to complete this issue?

**Comment by avinashkranjan** [comment]
Yes, It's included..All PRs after 4th Jan would be considered as Valid PR for SWoC..So for now..you have plenty of time..

**Comment by gargnityansh** [comment]
Okay. Thanks for the help.

**Comment by gargnityansh** [comment]
Can I use spotify api for searching the songs?

**Comment by avinashkranjan** [comment]
Yes You can use it Spotify Api @gargnityansh
