### ISSUE TITLE
Want to create Age Calculator [GSSOC '23]

### ISSUE THREAD

**Issue by Kalivarapubindusree** [avinashkranjan/Amazing-Python-Scripts#1530]
# Aim

- Simple Age calculator

# Details

- Just It will ask your date of birth then it will print your age in numbers so simple so easy to use!

**Comment by Kalivarapubindusree** [comment]
Yes

**Comment by avinashkranjan** [comment]
Go Ahead @Kalivarapubindusree

**Comment by Kalivarapubindusree** [comment]
completed my task @avinashkranjan

**Comment by Kalivarapubindusree** [comment]
Please review and Let me know any correction's!  [PR](https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/1509)

**Comment by Anjali2312-Thombare** [comment]
hey @avinashkranjan i will  develop Age Calculator as per your requirements .Can you please assign me this issue?

**Comment by Kalivarapubindusree** [comment]
Taks was completed Please check and Review at once! [NEW_PR](https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/1646)  @avinashkranjan
