### ISSUE TITLE
Heart rate Detection using webcam

### ISSUE THREAD

**Issue by raj3000k** [avinashkranjan/Amazing-Python-Scripts#1531]
# Aim

To detect Heart Rate using OpenCV and other various libraries.

# Details

A Python Script which can read input using a webcam and using some AI/ML algorithm and pre-fetched dataset it can detect the heart rate using the eye-blinking of the user.

- What the features will your script have

Heart Rate detection, and chances of heart attack, And generate tips for high and low bpm.

#gssoc

**Comment by raj3000k** [comment]
So I have been assigned this under gssoc23 or ?

**Comment by avinashkranjan** [comment]
Go Ahead @raj3000k

**Comment by raj3000k** [comment]
Hey any update? @avinashkranjan

**Comment by avinashkranjan** [comment]
Merged in commit [285cd41](https://github.com/avinashkranjan/Amazing-Python-Scripts/commit/285cd41217a08e99a0ae063504c2a8973fa22fe2)
