### ISSUE TITLE
[GSSOC '23]  To add Palindrome Checker Bot with GUI

### ISSUE THREAD

**Issue by Abhishek-Rajput-81** [avinashkranjan/Amazing-Python-Scripts#1534]
# Aim

- The objective of the Palindrome Checker Bot is to allow users to easily determine whether a given word or phrase is a palindrome or not using "tkinter" and "custom tkinter" libraries of Python. 

# Details

- The Palindrome Checker Bot with GUI will include the following features:
 1. Graphical User Interface
 2. Input Field
 3. Check Button
 4. Real-time Feedback 

Thank you for your time and consideration. I look forward to your positive response.
@avinashkranjan

**Comment by avinashkranjan** [comment]
Go Ahead @Abhishek-Rajput-81
