### ISSUE TITLE
Flappy Bird Game Agent

### ISSUE THREAD

**Issue by ayush-09** [avinashkranjan/Amazing-Python-Scripts#1535]
# Aim

This is the AI agaent which addapt the environment of the Flappy Bird Game using Reinforcement Learning with Open AI Gym environment.

# Details

### Performance of  Agent
https://user-images.githubusercontent.com/51924622/121337387-1dca1080-c93a-11eb-9b9f-61bf00bc327f.mp4 
- What the features will your script have

**Comment by ayush-09** [comment]
@avinashkranjan Please Assign me this issue under GSSoc23

**Comment by avinashkranjan** [comment]
Go Ahead @ayush-09
