### ISSUE TITLE
Enhance : UI of the scripts page.

### ISSUE THREAD

**Issue by Pragati-3003** [avinashkranjan/Amazing-Python-Scripts#1536]
I would like to change the ui of the script page by adding background color and by adding cool effects.
![sa1](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/132778037/dbbd4d7a-2b88-4ed0-a85c-4acd4f12b20b)
So,please assign this issue to me under gssoc'23.

**Comment by Pragati-3003** [comment]
> Hi thanks for creating your first issue at Amazing-Python-Scripts, hope you followed the guidelines.

Please assign this issue to me under gssoc'23

**Comment by avinashkranjan** [comment]
Go Ahead @Pragati-3003

**Comment by avinashkranjan** [comment]
Merged in commit [757cd87](https://github.com/avinashkranjan/Amazing-Python-Scripts/commit/757cd8754c6ab72b364d910c068b2ff29b0a1eb6)
