### ISSUE TITLE
[GSSOC 23] Cookie Clicker Bot 

### ISSUE THREAD

**Issue by whiteknight16** [avinashkranjan/Amazing-Python-Scripts#1540]
# Aim

- What is the objective of the Script
- A python script based on selenium that will play the cookie clicker game automatically

# Details

- What the features will your script have
- The bot will play the cookie clicker game and will also purchase the add ons as per the requirements

**Comment by whiteknight16** [comment]
Kindly assign me this issue

**Comment by meashishpatel** [comment]
Kindly assign me this issue

**Comment by avinashkranjan** [comment]
Go Ahead @whiteknight16
