### ISSUE TITLE
[GSSOC'23] Face Detection using OpenCV

### ISSUE THREAD

**Issue by Tanya-1109** [avinashkranjan/Amazing-Python-Scripts#1547]
# Aim

- It calculates the amount of time any person was away from the webcam.

# Details

- It uses openCV library to detect for how many seconds any person was away from the webcam. This will allow us to detect if any person was away for a long time

**Comment by avinashkranjan** [comment]
Go Ahed @Tanya-1109

**Comment by Anjali2312-Thombare** [comment]
@avinashkranjan  I will develop Face Detection using OpenCV . Can you please assign me this issue?
