### ISSUE TITLE
[Gssoc'23] flipkart web scraping 

### ISSUE THREAD

**Issue by Sushilverma002** [avinashkranjan/Amazing-Python-Scripts#1551]
# Aim- web scraping of mobile phone under 50000.

- What is the objective of the Script
Main objective is i will provide the scrapped data from flipkart that contain :
-product name
-price
-description 
-review
this data can be used for various purposes.
# Details
i will provide the TEXT file which shows the all the steps of scraping. 
i will provide the CSV file which contain scrapped data .
- What the features will your script have

**Comment by avinashkranjan** [comment]
Go Ahead @Sushilverma002

**Comment by Sushilverma002** [comment]
PLEASE CHECK PR #1631
