### ISSUE TITLE
[GSSoC'23] Flappy bird using PyGame

### ISSUE THREAD

**Issue by codewithavantika** [avinashkranjan/Amazing-Python-Scripts#1566]
# Aim

- I want to develop  a simple flappy bird game using PyGame library

# Details

- Library used will be PyGame, this will also contain sprites and sounds!
- It will consist of a loading screen, the main game page and then a game over page!

![Screenshot (259)](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/89691113/867b2127-7e05-4bcf-8484-15f3bff6d24a)

**Comment by codewithavantika** [comment]
@avinashkranjan I checked the issue and it involved using Reinforcement learning so i thought i could add a simple version so that it is more accessible to anyone who is new to pygame library and can learn from it, 
Can you please let me know if that would be helpful and guide me ahead with it!

**Comment by avinashkranjan** [comment]
Ok Then, Go ahead @codewithavantika

**Comment by codewithavantika** [comment]
@avinashkranjan So can you please assign this to me under GSSoC label ,It would help me out, Thanks a lot!
