### ISSUE TITLE
[GSSoC'23] Todo list using Flask

### ISSUE THREAD

**Issue by codewithavantika** [avinashkranjan/Amazing-Python-Scripts#1568]
# Aim

- This is a project that uses flask as a backend to create a todo list

# Details

- This is a simple todo-list application which allows user to create a new todo
- The user can make changes, delete and add a new todo
- Backend: Flask (CRUD Operations)
- Frontend: Bootstrap

**Comment by avinashkranjan** [comment]
Not a Script, If you're planning to create an script for the same, Do let me know, till then keeping the issue at pause.

**Comment by codewithavantika** [comment]
@avinashkranjan as I'm a little new to this, can you please elaborate this a little more? So like do i just add the flask main.py file or any other thing?

**Comment by codewithavantika** [comment]
@avinashkranjan so instead of an application do I have to just create the python script?

**Comment by codewithavantika** [comment]
@avinashkranjan i have a different idea for this can i add it here or create a new issue?

**Comment by Adhivp** [comment]
I am not sure , but I guess he asked to add only python script (which works on it's own) not any other frontend

**Comment by avinashkranjan** [comment]
@codewithavantika, Since this repo only contains, Scripts, you need to add some kind of script, as adding a To-Do list with flask is small project which is not a script.

**Comment by codewithavantika** [comment]
@avinashkranjan Okayy thanks a lot! as i was new to the repo i didn't understood it back then, thanks for letting me know, i do have another idea similar to it do i make changes in this issue itself, or close this issue and make a new issue?
