### ISSUE TITLE
[GSSoc'23] Chrome Dinosaur Game

### ISSUE THREAD

**Issue by Atharvashirsh** [avinashkranjan/Amazing-Python-Scripts#1570]
# Aim

- This project creates a Dinosaur game (similar to the [Chrome Dinosaur game](https://chromedino.com/) )

# Details

- It uses the Python Pygame Library.
- It will have functionalities similar to the Chrome dinosaur game.

![trex-chrome-game](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/121449422/bac64004-3cd4-4548-92ec-c0d90faa1839)

**Comment by Atharvashirsh** [comment]
@avinashkranjan Can you assign this issue to me under GSSoC'23 label?

**Comment by Atharvashirsh** [comment]
@avinashkranjan Can I work on this issue?

**Comment by avinashkranjan** [comment]
Go Ahead @Atharvashirsh

**Comment by Atharvashirsh** [comment]
Hey @avinashkranjan, I've added the PR which contains the game files.
