### ISSUE TITLE
[GSSoc'23] Persistent Feedback System: A User-Friendly GUI Program for Secure and Continuous Feedback Collection in Python

### ISSUE THREAD

**Issue by HartzFrequency** [avinashkranjan/Amazing-Python-Scripts#1573]
# Aim

The aim of this project is to develop and implement a user-friendly graphical interface program for a feedback system in Python. The primary goal is to ensure that the feedback provided by users is stored securely and without any risk of overwriting previous entries. By incorporating a mechanism for indefinite feedback storage until manual reset by the developer, the aim is to enhance the user experience and gather valuable feedback from users of Python scripts in an organized and systematic manner.

# Details

I would like to incorporate a graphical user interface program for a feedback system that avoids overwriting previous feedback. Instead, it includes a mechanism to indefinitely store feedback until it is manually reset by the developer. This valuable feature can be seamlessly integrated into various Python programs, allowing users of the Python script to provide feedback conveniently and efficiently.

**Comment by avinashkranjan** [comment]
Go Ahead @HartzFrequency
