### ISSUE TITLE
Welcome to Script Winter of Code '2021

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#158]
## Hello, Everyone <img src="https://raw.githubusercontent.com/ABSphreak/ABSphreak/master/gifs/Hi.gif" width="25px"> 
Thanks for showing your interest in being a part of the [Script Winter of Code '2021](https://swoc.tech/) 🎆

We are super delighted to have you on board for your Contributions on [Amazing Python Scripts](https://github.com/avinashkranjan/Amazing-Python-Scripts) 🙌

Please join our [Slack](https://join.slack.com/t/swoc-workspace/shared_invite/zt-jzl70ku9-xW3k1AKj9Jij47IXaoEm7w) Channel here. We would like you to introduce yourself and what are the fields that you work on. We would also love to have your Social Media Profiles so that we can connect over there and do mention that you are a participant at Script Winter of Code '2021.

During this Winter of Code, we will be focusing on these specific topics:

- Documentation
- Automation and Scripting
- Development of a Web Interface
- Refactoring existing Code

If you have any ideas around the same, we would love to have your opinion on it on the Slack Channel. On further discussion, the apt issues would be created and assigned to you.

Here are some 12 Rules, you should be following while doing Open-Source to make your Contributions shine during the whole process:

- Be Nice, Be Respectful (BNBR)
- Check if the Issue you created, exists or not.
- Make proper commit messages and document your PR well.
- Always add Comments in your Code and explain it at points.
- Dynamic Input is always preferred over static Driver Code.
- Squash your commits before you push them.
- Always create a Pull Request from a Branch; Never from the Master.
- Follow proper Code conventions. Using i, j in Loops show a poor understanding of Code Quality. Use proper Variable, Function Names.
- Issues would be served on "First Come, First Serve" basis.
- Issues would be tagged as Easy, Medium, Hard. Scores would be assigned on the difficulty of Issue you solve.
- Code would be reviewed by Mentors before they are merged. Every PR requires 3 Reviews.
- No person can take up more than 2 Issues at a single point of time.

Regards,
_Avinash Ranjan_ (@avinashkranjan ), Project Administrator 🤗

**Comment by ami-harry** [comment]
I want to work with you
Want to contribute to this project
