### ISSUE TITLE
Facebook-AutoLogin

### ISSUE THREAD

**Issue by antrikshmisri** [avinashkranjan/Amazing-Python-Scripts#159]
# Aim

- This script allows user to automate facebook login process.

# Details

- This script will automatically open a new browser window , open facebook.com , add the user credentials and finally login.

**Comment by antrikshmisri** [comment]
@avinashkranjan I would like to work on this feature

**Comment by avinashkranjan** [comment]
Sure @antrikshmisri Go ahead

**Comment by antrikshmisri** [comment]
@avinashkranjan created the [PR](https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/160) , can you review it ?
