### ISSUE TITLE
[GSSoC'23] Student Placement Prediction

### ISSUE THREAD

**Issue by anandpiyush1521** [avinashkranjan/Amazing-Python-Scripts#1592]
# Aim

- To predict the outcome of placement of student based on CGPA, IQ, Profile Score.

# Details

- Library use will be numpy & scikit-learn.
- Flask is used for predicting the outcome.

# Screenshots -
![Screenshot (1633)](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/75721333/5ddbe2b9-6a2e-4d22-b4d6-05a304c9b463)

**Comment by anandpiyush1521** [comment]
please assign this issue to me

**Comment by avinashkranjan** [comment]
Go Ahead @anandpiyush1521
