### ISSUE TITLE
[GSSOC'23]Showing month parse issue for day section in AGE_CALCULATOR_GUI

### ISSUE THREAD

**Issue by Shiv-Expert2503** [avinashkranjan/Amazing-Python-Scripts#1598]
**Describe the bug**
The Python script written in the age calculator shows the month parse error statement for the day section also.

**To Reproduce**
1. Go to the code.
2. Run the code.
3. In the day section pass any non-numerical value.
4. See the error.

**Screenshots**
The error looks like:-
![Screenshot (85)](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/122978299/b2c1e4d0-99c8-4654-b29a-1bf0b9b1d9d2)

**Expected behavior**
The output statement must show cannot parse day to int. Like:-
![Screenshot (86)](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/122978299/0e863828-16fd-4f92-a908-e8879c4ca911)

**Additional context**
I can fix this issue! Also, I'm almost done with it. So, Please give me the opportunity to solve it.

**Comment by vinay-ghate** [comment]
I m very interested to contribute to this project Pls assign me this work under the label Gssoc'23.
