### ISSUE TITLE
Dark Mode Theme

### ISSUE THREAD

**Issue by parasss19** [avinashkranjan/Amazing-Python-Scripts#1599]
## Current
Right now the website have no dark mode button theme which is nowadays very demanding and present in most of the website

## Change
I would apply the attractive sliding effect dark mode button using pure HTML, CSS and JAVASCRIPT
I will apply the toggle class to changing the theme of the website with google icons of moon and sun.

## ScreenShot (Its just the sample i will make it more better)

https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/101205226/c82fef65-8925-493a-b01c-5ba1ec73b721

Hi @avinashkranjan  I would like to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @parasss19

**Comment by Akanksha-202** [comment]
@avinashkranjan can you please assign this to me, it's already been more than a month since you assigned it.
