### ISSUE TITLE
Script to track Data Usage

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#16]
# Aim

- Create a Script to track Data Usage.

# Details

- Create a Python Script to keep a track of network usage and notify you if it exceeds a specified limit.

**Comment by adarshkushwah** [comment]
Hi, i would like to contribute on this, please assign this issue to me.

**Comment by avinashkranjan** [comment]
@adarshkushwah Sure.... Go ahead..
