### ISSUE TITLE
Adding a simple bird game

### ISSUE THREAD

**Issue by Shr-reny** [avinashkranjan/Amazing-Python-Scripts#1617]
# Aim

- I want to add a simple bird game made using html and css only.

# Details

- It's a simple game which will earn points according to the birds aimed and shot.

![Bird_game](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/125943681/cab1ff02-95c7-46b9-9c4e-bb6dcf3b31ae)

**Comment by avinashkranjan** [comment]
This repo is collection of Python Scripts not HTML, CSS and JavaScript Websites.
