### ISSUE TITLE
Generate QR Code for Website or any other link

### ISSUE THREAD

**Issue by gulshanjakhon** [avinashkranjan/Amazing-Python-Scripts#1619]
Hi @avinashkranjan 
# Aim

- What is the objective of the Script
To generate a QR code that redirects to specific links
assign me under gssoc23 label
Thank You
# Details

- What the features will your script have

**Comment by sagnik-p** [comment]
I would Like to work on this issue for GSSOC 2023. Please assign , if possible

**Comment by sagnik-p** [comment]
I have submitted a pull request that adds this feature.
Please review and merge

**Comment by sagnik-p** [comment]
Thanks!
