### ISSUE TITLE
PDF-Tools

### ISSUE THREAD

**Issue by LakshitF** [avinashkranjan/Amazing-Python-Scripts#162]
# Aim

-  Create a script with a menu interface providing the user with multiple functionalities related to PDF's.

# Details

-  Merge/Split multiple PDFs
-  Encrypt PDF
-  Watermarking PDF
-  Rotate PDF's ( For eg: from landscape to portrait mode )

**Comment by LakshitF** [comment]
@avinashkranjan Please assign this feature to me.

**Comment by avinashkranjan** [comment]
Sure @LakshitF Go Ahead..
