### ISSUE TITLE
python script for display calendar

### ISSUE THREAD

**Issue by gulshanjakhon** [avinashkranjan/Amazing-Python-Scripts#1621]
Hi @avinashkranjan 
# Aim

- What is the objective of the Script
display calendar by providing mnth and year 
# Details

- What the features will your script have
Using Pyhton file

Kindly Assign under gssoc23 label. 
Thank You

**Comment by avinashkranjan** [comment]
This script has not real world use-case. If I'm wrong, kindly let me know what are you planning to do in this issue.

**Comment by PiyushBL45t** [comment]
Hey, @avinashkranjan I am a contributor for GSSOC 2023, I would like to work upon this issue. I can make it a real world use case by integrating a clock along with the calendar GUI. It will fetch the current time as well as date for the user.
