### ISSUE TITLE
Enhancing the responsiveness of the page.

### ISSUE THREAD

**Issue by abhi03ruchi** [avinashkranjan/Amazing-Python-Scripts#1623]
**Is your feature request related to a problem? Please describe.**
The website responsiveness needs to be improved for mobile view. Its not looking good in mobile view.

Thus I would like to add enhance the responsiveness of the site to improve user experience and engagement.

https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/105661636/60d7bfe2-5a3e-49de-b95d-3c3dcf52f3d4

**Additional context**
Please assign this task to me under gssoc'23.

**Comment by avinashkranjan** [comment]
Someone already create an issue for the same and it already assigned.
