### ISSUE TITLE
Found error in contributing.md [Documentation]

### ISSUE THREAD

**Issue by sam-arth07** [avinashkranjan/Amazing-Python-Scripts#1635]
Hi @avinashkranjan, I am a part of Gssoc'23 as a contributor.

## Reference Screenshot
![image](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/82860337/ed834ec1-3efe-4217-b1fc-a5c333c5366f)

### AIM
- I would like to contribute to this project by updating the contributing.md file.
- To remove the above highlighted writing error.

Any suggestion or guidance is welcomed.

**Comment by avinashkranjan** [comment]
Go Ahead @sam-arth07
