### ISSUE TITLE
Python script to fetch IOC from a website

### ISSUE THREAD

**Issue by steffigeorge** [avinashkranjan/Amazing-Python-Scripts#1639]
**What is IOC?**
Indicators of Compromise can be malicious activities or phishing links that indicate probable damage to a device if the user clicks it or handles it in any way.

**Describe the solution you'd like**
I have a Python script that fetches the URL from the browser and traces the contents of the website for any IOCs. It can be incorporated with the Chrome browser extension as well.

Please do assign me the issue..I would love to be part of the project!

**Comment by avinashkranjan** [comment]
GO Ahead @steffigeorge

**Comment by steffigeorge** [comment]
PR done!
