### ISSUE TITLE
Birthday Wisher Bot

### ISSUE THREAD

**Issue by whiteknight16** [avinashkranjan/Amazing-Python-Scripts#1641]
# Aim

- Will wish on birthdays of friends and family members

# Details

- Will go through a predefined database of birthdays
- If there is a birthday of anyone today will send a mail wishing them

**Comment by mubasharaKhan** [comment]
Assign me this issue under GSSoC'23 label

**Comment by avinashkranjan** [comment]
Go Ahead @whiteknight16
