### ISSUE TITLE
The scrollbar is very not very attractive

### ISSUE THREAD

**Issue by Shreyans2004** [avinashkranjan/Amazing-Python-Scripts#1647]
**Is your feature request related to a problem? Please describe.**

The website is beautiful but the scrollbar is very simple.

**Describe the solution you'd like**

I can add styling to the scrollbar so that it looks more attractive and the website also looks better.

**Describe alternatives you've considered**

**Additional context**

I can change the styling of scrollbar .Can you assign this issue to me?

**Comment by avinashkranjan** [comment]
Go Ahead @Shreyans2004

**Comment by Shreyans2004** [comment]
Hi @avinashkranjan ,Thanks for assigning this issue to me. In the code I am not able to find the html and css files for the front-page .Can you please guide me about this.
