### ISSUE TITLE
Anime tracker 

### ISSUE THREAD

**Issue by hackedak** [avinashkranjan/Amazing-Python-Scripts#165]
# Aim

- A script which checks for new episode release of a particular anime automatically

# Details

- It will accept a link to the anime from any anime website.
- Give alert if a new episode is released

**Comment by hackedak** [comment]
Please assign this to me

**Comment by avinashkranjan** [comment]
Sure @hackedak Go ahead..

**Comment by pritamp17** [comment]
@avinashkranjan please could you assign this to me?

**Comment by avinashkranjan** [comment]
Sure Go ahead @pritamp17 Assigned it to you

**Comment by pritamp17** [comment]
@avinashkranjan script will give anime information and the number of anime episodes released will this be okay??

**Comment by avinashkranjan** [comment]
Ya It'll be more than enough @pritamp17

**Comment by pritamp17** [comment]
![anime_tracker](https://user-images.githubusercontent.com/65030567/103664788-a95d0100-4f98-11eb-9231-b0d52bf55b16.png)

**Comment by pritamp17** [comment]
@avinashkranjan this is the final result of my script..will this be okay?

**Comment by avinashkranjan** [comment]
@pritamp17 Ya it's okay You can push you PR..

**Comment by pritamp17** [comment]
@avinashkranjan I have sent PR, please review when you can.
