### ISSUE TITLE
MAKING A GET REQUEST

### ISSUE THREAD

**Issue by kharshita590** [avinashkranjan/Amazing-Python-Scripts#1654]
# Aim
MAKING A GET REQUEST ON AN API AND RETRIEVE JSON DATA
- What is the objective of the Script
MAKING A GET REQUEST ON AN API AND RETRIEVE JSON DATA
# Details
MAKING A GET REQUEST ON AN API AND RETRIEVE JSON DATA
- What the features will your script have
MAKING A GET REQUEST ON AN API AND RETRIEVE JSON DATA

**Comment by mubasharaKhan** [comment]
Assign me this issue under GSSoC'23 label

**Comment by avinashkranjan** [comment]
Too Basic, Not Applicable for this Repo..
