### ISSUE TITLE
Contact form input boxes can be submitted as empty

### ISSUE THREAD

**Issue by ATiwari2000** [avinashkranjan/Amazing-Python-Scripts#1657]
**Describe the bug**
The input boxes of Name,Email,Message can be submitted as empty, which can cause problems such as: incomplete data,user confusion and inaccurate results. So, it's better to make them required so there are no blank values.

**To Reproduce**
1. Go to 'https://amazing-python-scripts.pages.dev/page_contactUs'
2. Click on 'Submit Button, without filling the form'
3. See the error in searchbar,empty form got submitted

**Expected behavior**
The form shouldn't submit unless there is some appropriate value in each text box of the form.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser microsoft edge
 - Version 113.0.1774.57

Please assign this issue to me, it's a quick fix and I'm part of GSSoC '23.

**Comment by avinashkranjan** [comment]
Go Ahead @ATiwari2000

**Comment by avinashkranjan** [comment]
Closed in Commit [802fbfe](https://github.com/avinashkranjan/Amazing-Python-Scripts/commit/802fbfedc4bf06e76968890de83b2635a0f7022b)
