### ISSUE TITLE
CSV to JSON script [GSSoC'23]

### ISSUE THREAD

**Issue by prernamittal** [avinashkranjan/Amazing-Python-Scripts#1659]
# Aim

The aim of the script is to convert CSV files to JSON format. It provides a convenient way to transform data stored in CSV files into the JSON data structure.

# Details

The script has the following features:

CSV to JSON Conversion: The main functionality of the script is to convert a CSV file into JSON format. It reads the data from the CSV file, converts it into a JSON object, and writes it to a JSON file.

Input and Output Files: The script allows you to specify the input CSV file path and the output JSON file path. You can customize these file paths according to your needs.

CSV Parsing: The script uses the csv.DictReader class from the csv module to parse the CSV data. It treats the first row of the CSV file as column headers and maps each subsequent row to a dictionary where the keys are the column headers and the values are the corresponding row values.

JSON Formatting: The converted JSON data is formatted with an indentation of 4 spaces for improved readability. The json.dumps() function is used to convert the CSV data dictionary into a JSON string.

Error Handling: The script handles potential errors such as file not found or invalid file formats. It uses the with statement to automatically close the file handles, ensuring proper resource management.

**Comment by prernamittal** [comment]
Request @avinashkranjan @Yashbhadiyadra , to kindly assign this task to me, to contribute under GSSoC'23. Thanks!

**Comment by avinashkranjan** [comment]
Go Ahead @prernamittal
