### ISSUE TITLE
A Python Script to Unzip folders 

### ISSUE THREAD

**Issue by saiharsha-22** [avinashkranjan/Amazing-Python-Scripts#166]
# Aim

- To Unzip files

# Details

- The system wil first fetch the path of the .zip files and it will directly unzip the file in to different folders.

This script will be an useful to so many people who don't .zip file extractor in thier system they can run this script and unzip the file easily.

**Comment by saiharsha-22** [comment]
@avinashkranjan I am parciacpant of Swoc 2021. I have seen your scripts this would be helpful for others also if  you add this script, so that people can easily run the PYTHON script and download the files rather than using file extractors. Can you assign this issue to me

**Comment by avinashkranjan** [comment]
Sure @saiharsha-22 go ahead

**Comment by saiharsha-22** [comment]
@avinashkranjan thank you, for assigning the issue. I will make PR on Jan 5

**Comment by avinashkranjan** [comment]
@saiharsha-22 Why did you close this issue ??

**Comment by saiharsha-22** [comment]
@avinashkranjan I am working on the issue of #82 and 
. This is issue already there in another project. So it is not acceptable according to the rules. I have seen that very late. So I have closed this issue.

**Comment by avinashkranjan** [comment]
Okay No Issues Go ahead with #82
