### ISSUE TITLE
Multiple spaces fails the search for anime in Anime-Tracker

### ISSUE THREAD

**Issue by akshaykhoje** [avinashkranjan/Amazing-Python-Scripts#1666]
# Description of the bug:

When the user input is something like ```classroom of the elite```, it will fetch the desired result.
However, when the user inputs multiple spaces like ```classroom         of    the      elite```, it fails in fetching the desired results.

## Steps to reproduce the behavior:
1. Go to './Anime-Tracker'
2. Run anime-tracker.py
3. Enter anime name with multiple spaces between two words like --> "attack   on               titan"

### Expected behavior
Directly the result must be fetched irrespective of the number of spaces entered by the user. 

### Screenshots

![anime-tracker-bug](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/98017423/70660f40-e5fb-457e-9ec7-c2e0d52410d5)
|:--:|
| <b>anime-tracker-bug</b>|

### Desktop
 - OS : Debian GNU/Linux 11 (bullseye) x86_64
 - Browser : Mozilla Firefox
 - Version : 102.10.0esr

**Comment by akshaykhoje** [comment]
I want to work on this bug. Please assign me this issue.

Thank you! :)

**Comment by avinashkranjan** [comment]
Go Ahead @akshaykhoje
