### ISSUE TITLE
Python Script to download Audio of YouTube Video

### ISSUE THREAD

**Issue by sejalsksagar** [avinashkranjan/Amazing-Python-Scripts#167]
# Aim

- To download audio of a YouTube video 

# Details

- It will download audio of the YouTube video whose url is specified. 
- It will also display video title, rating, view count, author and video length.

**Comment by sejalsksagar** [comment]
I am SWOC '21 participant. I found this Script interesting and would like to work on it.

**Comment by avinashkranjan** [comment]
Sure @sejalsksagar Go ahead,...

**Comment by sejalsksagar** [comment]
Thank you for assigning! I will make PR on 5th Jan.
