### ISSUE TITLE
Script for  Convert JSON to CSV file

### ISSUE THREAD

**Issue by gulshanjakhon** [avinashkranjan/Amazing-Python-Scripts#1672]
Hi @avinashkranjan , Please assign this issue to me under gssoc23 label
# Aim

- What is the objective of the Script
to convert  JSON to CSV file 
# Details

- What the features will your script have

**Comment by vinay-ghate** [comment]
I m very interested to contribute to this issue Pls assign me this work under the label Gssoc'23.

**Comment by sagnik-p** [comment]
I have submitted a pull request #1693
Please check
Thanks
