### ISSUE TITLE
Python Script to fetch all links from webpage [gssoc23]

### ISSUE THREAD

**Issue by gulshanjakhon** [avinashkranjan/Amazing-Python-Scripts#1673]
hi @avinashkranjan 
 # Aim

- What is the objective of the Script
Extract all the links from  a given webpage
# Details

- What the features will your script have

**Comment by kaashikaagrawal** [comment]
assign me this one

**Comment by avinashkranjan** [comment]
Go Ahead @gulshanjakhon

**Comment by gulshanjakhon** [comment]
also please check https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/1609#pullrequestreview-1471441253
in this PR I also add a script for fetching links in the webpage.

Please review @avinashkranjan 
Thank you

**Comment by avinashkranjan** [comment]
Closed in commit #[9400018](https://github.com/avinashkranjan/Amazing-Python-Scripts/commit/940001863295e73aead52c9ffdfb9a9f04a94c0a)
