### ISSUE TITLE
Python Script for Low battery Notification under [gssoc23]

### ISSUE THREAD

**Issue by gulshanjakhon** [avinashkranjan/Amazing-Python-Scripts#1674]
# Aim
Low battery Notification python program
- What is the objective of the Script
this script will display a message over the system that says that **Battery low**
# Details

- What the features will your script have

**please assign under gssoc23**

**Comment by avinashkranjan** [comment]
Go Ahead @gulshanjakhon

**Comment by gulshanjakhon** [comment]
Hi @avinashkranjan i have open a PR please review: Low battery script #1719
Thank You
