### ISSUE TITLE
Additional Functionalities in Text Extraction from Images

### ISSUE THREAD

**Issue by vybhav72954** [avinashkranjan/Amazing-Python-Scripts#168]
# Aim

- Python script for text extraction from images, using Tessaract.

# Details

- Using important OCR tools, we can extract Text from Images, which would be a great script here. I know there is a script present here already, but it is as minimalistic as possible, it can't deal with multiple images, neither have the option to save the text file, also can be made more interactive, like 
- User Inputs, 
- extension types, 
- Destination, 
- Multiple Images in 1 text file etc.

**Comment by vybhav72954** [comment]
Can this be assigned to me?

P.S. Is `SWoC 21` label regarding Script WInter Of Code? If yes kindly add the label, I am a participant

**Comment by avinashkranjan** [comment]
@vybhav72954 we already hav a script for the same.. [Here](https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/OCR-Image-To-Text).. If you want to add more features to it, you can go ahead I'll assign it to you..else you can work on some other issues.

**Comment by vybhav72954** [comment]
@avinashkranjan As explained, I know the script exists, but it is minimalistic, I was thinking about adding a few functionalities, like aforementioned.

For example

- Bulk Extraction
- Bulk Extraction to Single file and so on

**Comment by avinashkranjan** [comment]
@vybhav72954 Sure Go ahead then.. Assigning it to you
