### ISSUE TITLE
Missing .gitignore?

### ISSUE THREAD

**Issue by vybhav72954** [avinashkranjan/Amazing-Python-Scripts#169]
**Is your feature request related to a problem? Please describe.**
So apparently we are missing a `.gitignore`.
That  is not a major problem obviously, but I do believe that if say I was a newcomer, I would have a hard time pushing my code without including the say `.idea` or `.vs` or `jupyter-checkpoints` 

**Describe the solution you'd like**
A `.gitignore` 

**Describe alternatives you've considered**
The simplest solution is just making sure that IDE generated files are not committed, it is effective, Yes. But Not optimized.

**Additional context**
In case there is a particular reason why we are missing `.gtignore` I am sorry as I want aware of that

**Comment by vybhav72954** [comment]
It is a small `.gitignore`, the owner can push one. Or I can in case it is fine.

**Comment by avinashkranjan** [comment]
Sure @vybhav72954 Go ahead.. I was thinking of adding it.. But was caught up with other things

**Comment by vybhav72954** [comment]
I shall issue the PR after 5th right?

**Comment by avinashkranjan** [comment]
Yup.. Since Contribution Period starts from 5th.
