### ISSUE TITLE
Handwritten Character Recognition

### ISSUE THREAD

**Issue by Mukesh751** [avinashkranjan/Amazing-Python-Scripts#1697]
# Aim

- This script will recognize the alphabetical character written in human handwriting.

# Details

- This project has been tested over various datasets and resulted in accuracy rate of over 90%.

**Comment by avinashkranjan** [comment]
Already Present in the Repo..

**Comment by Mukesh751** [comment]
The script that is present in the repo is for digit recognition not character recognition.
I have gone through all the projects in repo thoroughly to remove redundancy.

**Comment by avinashkranjan** [comment]
Ok Then Go Ahead @Mukesh751
