### ISSUE TITLE
Script for adding water mark to PDF's

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#17]
# Aim

- This script is for adding water mark to any PDF's which has single page to multiple pages.

**Comment by madiha123-design** [comment]
I would like to work on this issue.

**Comment by avinashkranjan** [comment]
Assigned to you..

> Also, @madiha123-design  as you are a participant of [Synthax](https://synthax.live/) please introduce yourselves in the [Welcome to Synthax](https://github.com/avinashkranjan/Amazing-Python-Scripts/issues/20) thread. 👋. It will help us keep track of your progress and contributions during the period. 😄
