### ISSUE TITLE
Subtraction not working in Calculator[GUI]

### ISSUE THREAD

**Issue by adviksinghania** [avinashkranjan/Amazing-Python-Scripts#170]
**The bug**
In Calculator[GUI] script, the subtraction operations are not working with any value and always returns 0.0

**To Reproduce**
1. Go to Amazing-Python-Scripts/Calculator[GUI]
2. Run the script.py
3. Click on any number e.g.: 5
4. Click on ' - ' operator
5. Click again on a number (e.g.: 3)
6. Click on ' = '
7. See error (Output: 0.0)

**Expected behavior**
Using the above example, the output should've been 2.0

**Desktop:**
 - OS: Windows 10, 20H2
 - Browser Google Chrome
 - Version 87.0.4280.88

**Additional context**
I propose to work on this issue and improve the script, adding comments wherever needed.

Advik Singhania,
Participant at SWoC'21

**Comment by avinashkranjan** [comment]
Sure @adviksinghania go ahead and fix the bug.. looking forward to your script.. Assigning it to you
