### ISSUE TITLE
Password Generator APP GUI

### ISSUE THREAD

**Issue by sagnik-p** [avinashkranjan/Amazing-Python-Scripts#1701]
# Aim

A Python script that generates a random password

These parameters have to be set by the user
1. the number of characters
2. strength of the password : low/medium/strong

# Details
Generate a random password
Copy to clipboard button
GUI

**Comment by sagnik-p** [comment]
May I work on this Issue?
Thanks

**Comment by avinashkranjan** [comment]
Go Ahead @sagnik-p

**Comment by sagnik-p** [comment]
Done
Please check
Thanks
