### ISSUE TITLE
Nth Fibonacci Generator

### ISSUE THREAD

**Issue by Mukesh751** [avinashkranjan/Amazing-Python-Scripts#1704]
# Aim

- This script will generate Nth Fibonacci Number in log(N) time complexity.

# Details

- I have gone through the repo, there is a script which generate all the Fibonacci numbers from 1 to N in O(N) complexity. But what if we want only Nth Fibonacci Number and let's say N will be in the range of 1e18, in that case we will use this log(N) algorithm.

**Comment by avinashkranjan** [comment]
Go Ahead @Mukesh751
