### ISSUE TITLE
OCR Feature for Table Format

### ISSUE THREAD

**Issue by GmGniap** [avinashkranjan/Amazing-Python-Scripts#171]
# Aim
- I would like to upgrade the current OCR simple code into the updated version that works in Table format text. 
- First implementation - English language-focused. 

# Details
- I want to use image processing(OpenCV) to detect lines and tables, then extract words from the table, pass them through pyTesseract. 
- Later, I hope to work on my local language(Burmese - especially for tesseract training with Python tools) to get more accuracy and also for the Indian language (if any others from India also interest to help.) But as far as I know, there're several supporters in Indian languages and also had strong training ground in Tesseract accuracy. 

# Tools 
1. Python
2. PyTesseract
3. OpenCV

# Further plan
- Add UI for user input (maybe with python Kivy or Flask) 
- Easy tool for Tesseract training for local (Asian) languages

**Comment by avinashkranjan** [comment]
Sounds Great.. Assigned to you @GmGniap

**Comment by GmGniap** [comment]
Thanks, @avinashkranjan  , I start working on it. May I know if I got any trouble while implementing, I just need to ask in the related slack channel or is there any mentors assigned to specific tasks?

**Comment by avinashkranjan** [comment]
You can ask me or ask in slack channel mentors or I'll help you..

**Comment by avinashkranjan** [comment]
Hey @GmGniap Any Updates? Are you having any issues?

**Comment by subhangi2731** [comment]
can you assign this to me?

**Comment by avinashkranjan** [comment]
Assigned to you @subhangi2731

**Comment by kaustubhgupta** [comment]
@subhangi2731 Updates on this?

**Comment by anandhu-eng** [comment]
@kaustubhgupta @avinashkranjan can you please explain what is this about... im gssoc 21 participant and looking forward to contribute to this issue:)

**Comment by kaustubhgupta** [comment]
The current OCR script is not very effective for tabular formats. Suppose an image has a table, then the script needs to extract the table contents and save it to CSV. You can use any approach for this

**Comment by anandhu-eng** [comment]
okay... can i work on this project.... i wish to learn more about it:)

**Comment by kaustubhgupta** [comment]
@anandhu-eng sure, I am assigning this to you. If you are stuck anywhere just ping me here or in the discord channel

**Comment by anandhu-eng** [comment]
okay thanks:)

**Comment by anandhu-eng** [comment]
@kaustubhgupta i have installed tesseract using pip command in ubuntu but unable to find the path. I have surfed the web for the same, they say its in usr/bin/tesseract, but couldn't find it. Can you please assist me.

**Comment by kaustubhgupta** [comment]
updates @anandhu-eng?

**Comment by anandhu-eng** [comment]
Im working on it....just figured how to execute it... we are having sem exam next week that's y im going little bit slow @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@anandhu-eng updates?

**Comment by kaustubhgupta** [comment]
@anandhu-eng you need to make the PR today only else this issue will be assigned to someone else

**Comment by subhangi2731** [comment]
@kaustubhgupta can you please assign me this issue and tell me the deadline when I have to make a pr so that I will work accordingly

**Comment by kaustubhgupta** [comment]
@subhangi2731 You have 7 days from the day of assignment and I will ask for the updates on 5th day from now.
