### ISSUE TITLE
Want to add GIF creator 

### ISSUE THREAD

**Issue by Kalivarapubindusree** [avinashkranjan/Amazing-Python-Scripts#1715]
# Aim

I want to add GIF creator using python.

# Details

-It created GIFs.
can you please assign me this task @avinashkranjan

**Comment by 1e9abhi1e10** [comment]
> # Aim
> I want to add GIF creator using python.
> 
> # Details
> -It created GIFs. can you please assign me this task @avinashkranjan

GO AHEAD @Kalivarapubindusree
