### ISSUE TITLE
A back to top button.

### ISSUE THREAD

**Issue by medhacodes** [avinashkranjan/Amazing-Python-Scripts#1718]
**Is your feature request related to a problem? Please describe.**
Add a beautiful and smooth back-to-top button.

**Describe the solution you'd like**
This back-to-top button will help to smoothly scroll back to the top.
**Describe alternatives you've considered**

**Additional context**
@avinashkranjan please assign this issue to me..

**Comment by avinashkranjan** [comment]
Not Needed
