### ISSUE TITLE
HTTP server using Python3 Socket Programming

### ISSUE THREAD

**Issue by PrajjwalDatir** [avinashkranjan/Amazing-Python-Scripts#172]
# Aim
Implemented RFC of HTTP using SOCKET programming in python3

- Functions as a HTTP server.

# Details

- GET, 
- POST, 
- PUT, 
- HEAD, 
- DELETE, 
- Cookies, 
- Headers, 
- non-persistent connections, 
- Multiple clients at the same time, 
- logging with levels of logging, 
- handling file permissions;  
- Server configuration 
- config file with DocumentRoot, 
- log file name, max simulateneous connections ; 
- way to stop and restart the server;

**Comment by PrajjwalDatir** [comment]
Please Assign it to me :)

**Comment by avinashkranjan** [comment]
Assigned to you.. Go ahead @PrajjwalDatir
