### ISSUE TITLE
Resize Images

### ISSUE THREAD

**Issue by singhchanmeet** [avinashkranjan/Amazing-Python-Scripts#1725]
# Aim

- This script will automatically resize any image(s) to the desired Pixel size at the desired DPI input by the user

# Details

- The script will use OpenCV library to resize images into desired Pixels and Pillow library to set them to desired DPI
- The script can work on any number of images at once

**Comment by singhchanmeet** [comment]
Please assign this issue to me @avinashkranjan

**Comment by 1e9abhi1e10** [comment]
GO AHEAD @singhchanmeet
