### ISSUE TITLE
File Encryption/Decryption

### ISSUE THREAD

**Issue by Abhinavcode13** [avinashkranjan/Amazing-Python-Scripts#1733]
# Aim

Build a script that allows users to encrypt and decrypt their files using various encryption algorithms. It can provide password-based encryption, support different file formats, and ensure secure file handling.

# Details

In this script:

The generate_key function generates a cryptographic key using the Fernet class from the cryptography library and saves it to a file.
The load_key function reads the encryption key from the file.
The encrypt_file function takes a filename and the encryption key as inputs. It reads the contents of the file, encrypts them using the Fernet class, and saves the encrypted content to a new file.
The decrypt_file function takes a filename and the encryption key as inputs. It reads the encrypted file, decrypts the contents using the Fernet class, and saves the decrypted content to a new file.
The main function provides a menu to the user, allowing them to generate a key, encrypt a file, or decrypt a file based on their choice.

**Comment by Abhinavcode13** [comment]
Please assign me this issue @avinashkranjan

**Comment by 1e9abhi1e10** [comment]
GO AHEAD @Abhinavcode13
