### ISSUE TITLE
Disk Space Analyzer [GSSoC'23]

### ISSUE THREAD

**Issue by prernamittal** [avinashkranjan/Amazing-Python-Scripts#1739]
# Aim

The aim of the script is to analyze disk space usage in a specified directory and provide a summary of the sizes of files and folders within that directory. The script will help users gain insights into the distribution of disk space and identify the largest files and folders.

# Details

The script will have the following features:

1. Directory Selection: The script will prompt the user to specify the directory path they want to analyze or accept it as a command-line argument.

2. File and Folder Analysis: The script will recursively scan the specified directory and calculate the size of each file and folder within it.

3. Sorting by Size: The script will sort the files and folders based on their sizes in descending order, with the largest ones displayed first.

4. Display: The script will output the names and sizes of the files and folders in a readable format.

5. Error Handling: The script will handle cases where the specified directory does not exist or is not accessible. It will provide appropriate error messages to the user.

With these features, the script will enable users to efficiently analyze disk space usage and identify space-consuming files and folders within a directory.

Request @avinashkranjan @Yashbhadiyadra , to kindly assign this task to me, to contribute under GSSoC'23. Thanks!

**Comment by 1e9abhi1e10** [comment]
GO AHEAD @prernamittal
