### ISSUE TITLE
[SCRIPTS] Adding random Quote Generator Script

### ISSUE THREAD

**Issue by Mahitej28** [avinashkranjan/Amazing-Python-Scripts#1740]
# Aim

- The objective of the script is to generate random quotes and display them to users.

# Details

- The Quote Generator would display random quotes to the user
- It would consist of an additional feature like filtering the quotes as per user needs

Hello!
I am  Mahima Churi, a proud contributor at GSSoC '23. I would like to contribute to this project.

@avinashkranjan if you think it is useful then do assign me the issue under GSSoC '23 with the level of the PR as well

**Comment by TechTrendset** [comment]
I would like to contribute to this project, kindly assign it to me.

**Comment by Mahitej28** [comment]
> I would like to contribute to this project, kindly assign it to me.

I have found this feature and raised the issue kindly see some another issue and work upon it

**Comment by 1e9abhi1e10** [comment]
> > I would like to contribute to this project, kindly assign it to me.
> 
> I have found this feature and raised the issue kindly see some another issue and work upon it

GO AHEAD @Mahitej28

**Comment by Mahitej28** [comment]
Sure @1e9abhi1e10
