### ISSUE TITLE
The Resizeable button is not working

### ISSUE THREAD

**Issue by mahi0601** [avinashkranjan/Amazing-Python-Scripts#175]
**Describe the bug**
The maximizing button is not working if we want a big screen of calculator.
**To Reproduce**
1. Go to 'the calculator[GUI] and run the file  we can see it.'
2. Click on 'maximize button it is not responding'
3. Scroll down to 'the GUI screen is also not proper'

**Expected behavior**
it should maximize properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/50989202/103615076-f2d52e00-4f4f-11eb-9d79-0046873ceddc.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mahi0601** [comment]
I want to contribute in this issue

**Comment by avinashkranjan** [comment]
Sure Go ahead @mahi0601

**Comment by mahi0601** [comment]
I have done a few changes in the sizes and colors of the button also.
