### ISSUE TITLE
Adding Pattern match with regular expressions

### ISSUE THREAD

**Issue by Kalivarapubindusree** [avinashkranjan/Amazing-Python-Scripts#1758]
# Aim

- I want to python script related to pattern that matches with the regular expressions.

# Details

- Python allows for more detailed pattern matching using regular expressions. This is useful for categorizing textual information as part of a data-processing workflow or searching for specific keywords in user-submitted content. The built-in regular expression library is called re, and once you get the hang of the regular expression syntax, you can automate almost any pattern-matching script.

can you please assign me this task under gssoc'23 @avinashkranjan

**Comment by 1e9abhi1e10** [comment]
GO AHEAD @Kalivarapubindusree
