### ISSUE TITLE
Text 2 Sheets

### ISSUE THREAD

**Issue by Tisha6661** [avinashkranjan/Amazing-Python-Scripts#1763]
# Aim
I would like to add a feature of adding text data automatically to google sheets in this projects, for tabular data.

# Details
It can make it easy to handle the tabular data store din text files, or copied for scraping from sites.

It would work using Goggle API keys and it would be a good extension to the project, could u please assign me this task.

**Comment by Tisha6661** [comment]
Yes, I understood the project, and would like to get assigned for this task, under GSSOC 2023.

**Comment by Tisha6661** [comment]
It's been 5 days, could you please assign me this task, it would be a great addition to the project, as it a necessity today to convert data from one form to another, and python script to convert raw data in tabular one like excel sheets or goggle sheets, would be a great addition.

**Comment by Tisha6661** [comment]
When will I be assigned the task?

**Comment by avinashkranjan** [comment]
Go Ahead @Tisha6661

**Comment by Tisha6661** [comment]
@avinashkranjan I am unable to clone your repositoty, 
![image](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/98682478/d0a7f8c8-06c8-4e72-8ad0-00739d51e404)

Also I tried by downloading it, and making the changes, then it is automatically deleting these lines, and same files are causing problem in cloning-
![image](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/98682478/586555e1-0ed6-4e25-a3cc-646dc678b073)


Should I commit my changes, with these changes, or what should I do?

**Comment by Tisha6661** [comment]
@avinashkranjan I have created a pull request for this task, please verify and merge it.
