### ISSUE TITLE
Adding Language Detection

### ISSUE THREAD

**Issue by yashhibare7** [avinashkranjan/Amazing-Python-Scripts#1768]
**Is your feature request related to a problem? Please describe.**
The language detection project aims to address the need for accurate language identification in various applications and systems.

**Describe the solution you'd like**
I would like a language detection solution that utilizes machine learning algorithms to accurately identify the language of text inputs, providing reliable results for multilingual applications and services.

**Additional context**
(https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/96299060/beb51055-5a1b-453b-bad0-538c3e774eb5)

**Comment by yashhibare7** [comment]
Requesting @avinashkranjan , to kindly assign this task to me, to contribute under GSSoC'23.
Thanks!

**Comment by 1e9abhi1e10** [comment]
GO AHEAD @yashhibare7
