### ISSUE TITLE
Python script to monitor file changes in a directory

### ISSUE THREAD

**Issue by antrikshmisri** [avinashkranjan/Amazing-Python-Scripts#177]
# Aim

- A python script to monitor changes made in a directory

# Details

- This is a script that monitors changes made in a working directory. This includes newly created files , changes made in an existing files. Changes are logged to the terminal.

**Comment by antrikshmisri** [comment]
@avinashkranjan I would like to work on this issue.

**Comment by avinashkranjan** [comment]
Go ahead with Script @antrikshmisri Assigned to you..

**Comment by antrikshmisri** [comment]
@avinashkranjan Created the [PR](https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/207) , please review when you can.
