### ISSUE TITLE
adding number guessing game

### ISSUE THREAD

**Issue by yashhibare7** [avinashkranjan/Amazing-Python-Scripts#1771]
**Is your feature request related to a problem? Please describe.**
Alternatives considered for the number guessing game include implementing a word-based guessing game, creating a visual puzzle, or designing a riddle-based game with clues to deduce the number.

**Describe the solution you'd like**
I would like a number guessing game where the player tries to guess a randomly generated number within a specified range, with hints provided after each guess.

**Comment by yashhibare7** [comment]
Requesting @avinashkranjan  , to kindly assign this task to me, to contribute under GSSoC'23.
Thanks!

**Comment by avinashkranjan** [comment]
Too Basic
