### ISSUE TITLE
[GSSoC'23] Voice Recorder App

### ISSUE THREAD

**Issue by Atharvashirsh** [avinashkranjan/Amazing-Python-Scripts#1776]
# Aim

- This is a simple voice recording app.

# Details

- This will have the following features : 
  - Record audio.
  - Save recorded audio file in `.mp3` format.
  - Play back the recorded audio.

#### Can you assign me @Atharvashirsh this issue under `gssoc23` label ?

**Comment by 1e9abhi1e10** [comment]
GO AHEAD @Atharvashirsh

**Comment by Nishitbaria** [comment]
@avinashkranjan ,I have impelemnted this python script,please assign me this issue,I will create pull request asap
