### ISSUE TITLE
Streamlit Youtube Analytics Web App

### ISSUE THREAD

**Issue by abhisek-1221** [avinashkranjan/Amazing-Python-Scripts#1791]
# Aim

> To build a python based streamlit app that gives entire analysis of playlist videos including total duration of playlist using the Youtube Data API. It also includes data vizualization for more analytical observations

# Details

- User will have to provide the URL of playlist
- Data will be fetched from the `Youtube API` by means of requests and response
- Total Duration of entire playlist will be displayed along with `total duration at different playback speed`.
- Other informations of playlist like `total likes,comments,views, like to comment ratio etc will also be displayed`
- Good streamlit based web app with **animations**
- Interactive `data vizuallization metrics`
- `Deployment` using Heroku or other alternatives

Label this issue under `gssoc23` and `assign`

**Comment by avinashkranjan** [comment]
Go Ahead @abhisek-1221
