### ISSUE TITLE
Facebook messenger bot to get COVID statistics

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#18]
# Aim

- Build a Facebook messenger bot, that will display the current statistics of COVID-19 given a county or any Indian state or district

**Comment by garinm90** [comment]
Hey, I'm interested in working on this. Could you please assign it to me?

**Comment by avinashkranjan** [comment]
@garinm90 Sure..Go ahead..

**Comment by avinashkranjan** [comment]
@garinm90 When I expect the PR?

**Comment by garinm90** [comment]
@avinashkranjan Unfortunately a public API for WhatsApp doesn't seem to exist. You can use a third party for sending and receiving messages via WhatsApp though. 

I originally used Twilio for this service and it was working. However, it required you to create an account setup a sandbox get API keys etc, then only you could send your bot messages. Twilio just updated their WhatsApp service and now the bot will expire every 3 days.

I looked at using signal or another third party messenger but the API wasn't well documented. Would you be opposed to making it a Facebook messenger bot? This would probably be the easiest method for accessibility and programming as the API is well documented, and it's much easier to setup.

**Comment by avinashkranjan** [comment]
@garinm90 Sure go ahead for the Facebook messenger bot...

**Comment by avinashkranjan** [comment]
@garinm90 Any updates?

**Comment by avinashkranjan** [comment]
@garinm90 Are you still working on this..Or should I assign it to someone else

**Comment by ami-harry** [comment]
I will try to do that
please assign me

**Comment by avinashkranjan** [comment]
Sure @ami-harry Go ahead

**Comment by vybhav72954** [comment]
@avinashkranjan Lol I can do this too along with the WhatsApp bot, but it would be better than I first deal with WhatsApp bot only.

If in the meantime it's not solved, I will take this

That won't be a problem, right?

**Comment by avinashkranjan** [comment]
It won't be a problem @vybhav72954

**Comment by vybhav72954** [comment]
@avinashkranjan Can you assign this to me, I will close this by tonight

**Comment by kshittijagrawal** [comment]
Hey there!
I'd like to contribute to the project. I want to address and fix this issue. My implementation will be in python with a clean code and documentation. Kindly provide me with this issue.
I'm also a GSSOC'21 participant.

**Comment by avinashkranjan** [comment]
Assigned to you @kshittijagrawal

**Comment by kaustubhgupta** [comment]
@kshittijagrawal Updates on this?

**Comment by amrzaki2000** [comment]
Hello,
Can I work on this with issue: [#528](https://github.com/avinashkranjan/Amazing-Python-Scripts/issues/528) ?

**Comment by dsg1320** [comment]
Can I work on this issue ? Do assign it to me

**Comment by kaustubhgupta** [comment]
@amrzaki2000 if you had made the PR for the same before @dsg1320 commented, then I would have assigned you. Since you already have an issue assigned, this issue is now assigned to @dsg1320

**Comment by kaustubhgupta** [comment]
@dsg1320 updates?

**Comment by dsg1320** [comment]
I have created the page and app . Still working on it.

**Comment by kaustubhgupta** [comment]
@dsg1320  Umm, created the page and app? This was supposed to be a python script right?

**Comment by dsg1320** [comment]
According to the article you sent we have to 1st have an app ID and a
facebook page for it . I'm getting to the python script. Need some time.

**Comment by kaustubhgupta** [comment]
@dsg1320 Oh, okay, take your time, you have max of 2 days to complete this task

**Comment by dsg1320** [comment]
Ok

**Comment by kaustubhgupta** [comment]
@dsg1320 did you found any workaround? or you need any additional help?

**Comment by dsg1320** [comment]
https://github.com/dsg1320/Amazing-Python-Scripts/tree/feature/covidStats

This is the link to my repository where I've shown the progress.
I'm creating a generic script that can be leveraged by anyone to their app.
Will include the steps in REadme.md. Will this be fine?
