### ISSUE TITLE
Driver Drowsiness Detection

### ISSUE THREAD

**Issue by transponster27** [avinashkranjan/Amazing-Python-Scripts#1808]
**Is your feature request related to a problem? Please describe.**
Since countless people drive on the highway day and night. Taxi drivers, bus drivers, truck drivers, and people traveling long-distance who suffer from lack of sleep. Due to this, it becomes very dangerous to drive resulting in the majority of accidents happening due to the drowsiness of the driver.

**Describe the solution you'd like**
So, to prevent these accidents I will build a system that will alert the driver whenever they feel sleepy.
This project aims to build a safety technology that will detect if the driver’s eyes are closed for a few seconds and will alert the driver when drowsiness is detected.

**Describe alternatives you've considered**
Track traffic police officers at intervals with flashlights to keep the drivers in check. Track systems for any signs of improperly driven vehicles.  

**Additional context**
In this project, I'll be making a Driver Drowsiness Detection System built using Python, Open CV, AND Dlib which will help reduce accidents and their impacts by warning the drivers depending upon their physical state.

**Comment by transponster27** [comment]
Please assign this project to me and allow me to contribute my hard work to GSSoC'23.

**Comment by 1e9abhi1e10** [comment]
@transponster27 GO AHEAD

**Comment by avinashkranjan** [comment]
Already Present in the Script
