### ISSUE TITLE
Movie Recommendation system in Python.

### ISSUE THREAD

**Issue by amandp13** [avinashkranjan/Amazing-Python-Scripts#181]
# Aim

- A content-based recommender system works on the data generated from a user.

# Details

- Recommender System is a system that seeks to predict or filter preferences according to the user’s choices.
-  A statistical algorithm that seeks to predict users' ratings for a particular entity, based on the similarity between the entities or similarity between the users that previously rated those entities.

**Comment by avinashkranjan** [comment]
@amandp13 Check out [Here](https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Movie%20Recommendation) This Script.. You can improve this one or Go ahead and tell me how's your script different than this..

**Comment by amandp13** [comment]
@avinashkranjan Oh, I didn't notice this script, but this script classify based on the user emotion as an input but I am saying to take the movie ratings from the user and then predicting the recommendation to the user.
Should I close this as this is already present in this repo?

**Comment by avinashkranjan** [comment]
@amandp13 No, If yours one is different from this one. Go ahead with the _Script.. Assigning_ it to you
