### ISSUE TITLE
[GSSoC'23] Fleury's Algorithm for directed graph

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [avinashkranjan/Amazing-Python-Scripts#1812]
# Aim

- What is the objective of the Script
   - A highly efficient algorithm specifically designed for discovering Eulerian circuits or paths in directed or undirected graphs.

# Details

- What the features will your script have
   - Manual exploration of the directed graph to identify an Eulerian circuit or path. However, this approach can be time-consuming and prone to errors.
   - Applying the brute force technique will also time consuming and takes a lot of memory
   - But this algorithm becomes increasingly inefficient as the size of the graph grows.

**Comment by Avdhesh-Varshney** [comment]
@avinashkranjan @Yashbhadiyadra Sirs, please assign this task to me for a contribution under GSSoC'23
I can solve it in Java, Python and C++ languages
/assign

**Comment by Avdhesh-Varshney** [comment]
@avinashkranjan @Yashbhadiyadra @1e9abhi1e10 Sirs, please assign this task to me to contribute in this repository under GSSoC'23 program
I can solve this algorithm in Python, C++ and Java languages
/assign

**Comment by Avdhesh-Varshney** [comment]
@avinashkranjan @Yashbhadiyadra @1e9abhi1e10 Sirs, please assign this task to me to contribute in this repository under GSSoC'23 program
I can solve this algorithm in Python, C++ and Java languages
/assign

**Comment by Avdhesh-Varshney** [comment]
@avinashkranjan @Yashbhadiyadra @1e9abhi1e10 Sirs, I have done with task and want to create a pull request to contribute in this repository under GSSoC'23.
So please /assign this task to me

**Comment by Yashbhadiyadra** [comment]
Go ahead @Avdhesh-Varshney
