### ISSUE TITLE
Adding Favicon 

### ISSUE THREAD

**Issue by parthpathakpp1** [avinashkranjan/Amazing-Python-Scripts#1813]
**Is your feature request related to a problem? Please describe.**
There is no Favicon . 

**Describe the solution you'd like**
I will add a Favicon.

**Describe alternatives you've considered**

**Additional context**
![nofaviconamazingpythonscripts](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/85991449/5228108d-0786-4d00-bce9-b23f306952f5)

**Comment by parthpathakpp1** [comment]
Can you assign this issue to me under GSSOC'23.

**Comment by avinashkranjan** [comment]
Duplicate Issue
