### ISSUE TITLE
[GSSOC '23] : Python Script for Word Embedding Using PyTorch

### ISSUE THREAD

**Issue by sujanrupu** [avinashkranjan/Amazing-Python-Scripts#1817]
# Aim

Using word embedding method, any word can be vectorized in vector plane. This vector representation will be done using tensor.

# Details
- Any word or text segment will be vectorized
- Both N gram(Skip Gram) and CBOW language model will be implemented
- All the (training) text segment will be represented in vectorized dimension.

**Comment by avinashkranjan** [comment]
Go Ahead @sujanrupu
