### ISSUE TITLE
Creating-Emoji-Using-Python

### ISSUE THREAD

**Issue by Ayush7614** [avinashkranjan/Amazing-Python-Scripts#182]
# Aim

- Creating different-different emojis using python module

# Details

Fortunately ,python have multiple way using which we can print emojis :
Unicode
CLDR names
emoji module
Unicodes:
To use Unicodes , we need to replace “+” with “000” from the list of unicodes .
For example :
“U+1F600” will become “U0001F600” and prefix the unicode with “\” and print it.
CLDR names:
Emojis have CLDR short names which can also be used.

![image](https://user-images.githubusercontent.com/67006255/103727358-199f6d00-5001-11eb-9549-fe03aaa6f7e7.png)
In above code , first line used CLDR names and second line used Unicode.

- emoji module:
Emojis can also be implemented by using the emoji module provided in Python. To install it run the following in the terminal.
pip install emoji
emojize() function requires the CLDR short name to be passed in it as the parameter. It then returns the corresponding emoji. Replace the spaces with underscore in the CLDR short name.
![image](https://user-images.githubusercontent.com/67006255/103727426-3d62b300-5001-11eb-9270-1991b533ce7c.png)

**Comment by Ayush7614** [comment]
@avinashkranjan plss review it

**Comment by vaishnavijha** [comment]
Can you assign me this issue ?

**Comment by avinashkranjan** [comment]
@vaishnavijha Issue is already assigned to @Ayush7614

**Comment by Ayush7614** [comment]
#179 @avinashkranjan  sir this is pull request

**Comment by avinashkranjan** [comment]
@all-contributors please add @Ayush7614  for code
