### ISSUE TITLE
Python script for Tableau-style UI in Jupyter Notebook for visual analysis. [GSSOC'23]

### ISSUE THREAD

**Issue by sachi-shah** [avinashkranjan/Amazing-Python-Scripts#1824]
**Aim:**
The objective of the script is to create a user-friendly Tableau-style interface within a Python environment, such as Jupyter Notebook, to facilitate visual analysis.

**Details:**
The script will provide a Tableau-style user interface in Jupyter Notebook, offering, a variety of visualization options (charts, graphs, maps), interactive controls (filtering, sorting), and much more using a GUI based simple dashboard style within a Jupyter Notebook cell.

**Please do assign me the issue under GSSOC'23. I would love to be part of the project!**

**Comment by avinashkranjan** [comment]
Go Ahead @sachi-shah
