### ISSUE TITLE
[GSSoC'23] Scientific Calculator using PYTHON

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [avinashkranjan/Amazing-Python-Scripts#1829]
# Aim

- What is the objective of the Script
   - To create a scientific calculator using python language
   - Adding all the features of a scientific calculator in this script

# Details

- What the features will your script have
   - Best GUI based program
   - Best look and user interface for easy to handle it
   - All basic function like +, -, *, and /
   - All trigonometric functions
   - All exponential functions
   - Logarithmic functions, and etc.

**Comment by Avdhesh-Varshney** [comment]
@avinashkranjan @Yashbhadiyadra Sirs, please assign this task to me to contribute in this repository under GSSoC'23 program
/assign

**Comment by Avdhesh-Varshney** [comment]
@avinashkranjan @Yashbhadiyadra @1e9abhi1e10 Sirs, please assign this project to me for a valuable contribution in this repository under GSSoC'23 program
/assign

**Comment by Avdhesh-Varshney** [comment]
@avinashkranjan @Yashbhadiyadra @1e9abhi1e10 Sirs, I have done with task and want to create a pull request to contribute in this repository under GSSoC'23.

So please /assign this task to me

**Comment by Yashbhadiyadra** [comment]
Go ahead @Avdhesh-Varshney
