### ISSUE TITLE
[GSSoC'23] Chess Game using PYTHON

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [avinashkranjan/Amazing-Python-Scripts#1831]
# Aim

- What is the objective of the Script
   - This game is a two player game
   - Using python modules, creating a attractive interface for users to play chess just using 1 file of python

# Details

- What the features will your script have
   - Giving a attractive look and move actions, etc. to the GUI
   - Adding algorithm of all conditions
   - Using AI integration makes this game also for a single player also

**Comment by Avdhesh-Varshney** [comment]
@avinashkranjan @Yashbhadiyadra @1e9abhi1e10 Sirs, i requested to assign me this task to contribute in this repository under GSSoC'23 program
/assign

**Comment by Avdhesh-Varshney** [comment]
@avinashkranjan @Yashbhadiyadra @1e9abhi1e10 Sirs, Please assign this task to me to work on it and contribute in this repository under GSSoC'23 program

please /assign

**Comment by Yashbhadiyadra** [comment]
Go ahead @Avdhesh-Varshney
