### ISSUE TITLE
Text to Image

### ISSUE THREAD

**Issue by MihirRajeshPanchal** [avinashkranjan/Amazing-Python-Scripts#1839]
# Aim

- To create a script that converts text input to images

# Details

- Input text converted to downloaded image file

**Comment by Yashbhadiyadra** [comment]
@MihirRajeshPanchal Image To Text or Text To Image?

**Comment by MihirRajeshPanchal** [comment]
Text to image

**Comment by MihirRajeshPanchal** [comment]
@Yashbhadiyadra Check the pull request 
https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/1840
