### ISSUE TITLE
Adding Wikipedia Scrapper

### ISSUE THREAD

**Issue by Shreya111111** [avinashkranjan/Amazing-Python-Scripts#1849]
# Aim

- What is the objective of the Script
- It is basically a technique or a process in which large amounts of data from a huge number of websites is passed through a web scraping software coded in a programming language and as a result, structured data is extracted

# Details

- What the features will your script have??
 -  Web scraping is an automatic process of extracting information from the web. 
 - It allows scrapping based on Javascript and Python Framework.
 - Almost compatible with all the websites and retrieve necessary informations

**Comment by Shreya111111** [comment]
@avinashkranjan  and @1e9abhi1e10 plz assign this issue to me

**Comment by Yashbhadiyadra** [comment]
Go ahead @Shreya111111

**Comment by Shreya111111** [comment]
@1e9abhi1e10 @Yashbhadiyadra Plz review the PR https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/1867 fixes https://github.com/avinashkranjan/Amazing-Python-Scripts/issues/1849 ..
