### ISSUE TITLE
Arbitary Quotes Generator

### ISSUE THREAD

**Issue by pavansai5448** [avinashkranjan/Amazing-Python-Scripts#1850]
# Aim
- to generate random quotes on user given category
- to generate n number of quotes where n is the user input

# Details

- this script allows user to get random quotes based on the category they have opt to and also the n number of quotes they needed under that category.

@1e9abhi1e10 abd @avinashkranjan please assign this issue to me .!!

**Comment by Yashbhadiyadra** [comment]
@pavansai5448 How's it different from this? 
https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Random-Quote-generator

**Comment by pavansai5448** [comment]
@Yashbhadiyadra 
my script gives random n number of quotes based on the user selected category , whereas the other script doesn't

**Comment by Yashbhadiyadra** [comment]
Go ahead @pavansai5448
