### ISSUE TITLE
Feature : Issues Template Modify

### ISSUE THREAD

**Issue by parasss19** [avinashkranjan/Amazing-Python-Scripts#1855]
### 1  Issue template is not looking good it doesn't have separate columns for addition content and ss
<img width="721" alt="temp img" src="https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/101205226/b01dcdc0-17f7-496c-9d4d-e1ce4017601f">

### 2 Also right now in issue template there are no checkboxes for GSSOC'23.   Checkboxes make labeling task easy for project admins
<img width="640" alt="Screenshot 2023-06-20 233055" src="https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/101205226/0415df35-9c73-411a-914d-40302b84f4f6">

**Comment by Bhanuteja01** [comment]
assign me this issue
I'm gssoc contributor

**Comment by Yashbhadiyadra** [comment]
Go ahead @parasss19 
Must follow all the guidelines
