### ISSUE TITLE
Add the CodeQL workflow 

### ISSUE THREAD

**Issue by metabiswadeep** [avinashkranjan/Amazing-Python-Scripts#1856]
**Is your feature request related to a problem? Please describe.**
As a project with multiple users contributing to it, it is essential to ensure that no security vulnerabilities arise due to improper coding styles followed by contributors.

**Describe the solution you'd like**
Add the codeql analysis workflow to be run on every push and pull request to prevent any security vulnerabilities in the codebase.

I would like to work on this as a part of GSSoC 23.

**Comment by Yashbhadiyadra** [comment]
Go ahead @metabiswadeep 
Must follow all the guidelines
