### ISSUE TITLE
[ADD]: Stock Price Prediction

### ISSUE THREAD

**Issue by Killer2OP** [avinashkranjan/Amazing-Python-Scripts#1863]
# Aim

To Create a project in which we will predict the stock price.

# Details

Machine learning has significant applications in the stock price prediction. In this machine learning project, we will be talking about predicting the returns on stocks. This is a very complex task and has uncertainties.
We will develop this project into two parts:

-> First, we will learn how to predict stock price using the LSTM neural network.
-> Then we will build a dashboard using Plotly dash for stock analysis.

**Comment by Yashbhadiyadra** [comment]
Go ahead @Killer2OP 
Must follow all the guidelines

**Comment by Killer2OP** [comment]
@Yashbhadiyadra Can you review the PR and merge it.
