### ISSUE TITLE
 Traffic-Signal-Violation-Detection-System

### ISSUE THREAD

**Issue by Killer2OP** [avinashkranjan/Amazing-Python-Scripts#1864]
# Aim

The goal of the project is to automate the traffic signal violation detection system and make it easy for the traffic police department to monitor the traffic and take action against the violated vehicle owner in a fast and efficient way. Detecting and tracking the vehicle and their activities accurately is the main priority of the system.

# Details

The increasing number of cars in cities can cause high volume of traffic, and implies that traffic violations become more critical nowadays in Bangladesh and also around the world. This causes severe destruction of property and more accidents that may endanger the lives of the people. To solve the alarming problem and prevent such unfathomable consequences, traffic violation detection systems are needed. For which the system enforces proper traffic regulations at all times, and apprehend those who does not comply. A traffic violation detection system must be realized in real-time as the authorities track the roads all the time. Hence, traffic enforcers will not only be at ease in implementing safe roads accurately, but also efficiently; as the traffic detection system detects violations faster than humans. This system can detect traffic light violation in real-time. A user friendly graphical interface is associated with the system to make it simple for the user to operate the system, monitor traffic and take action against the violations of traffic rules.

**Assign me this under GSSoC'23**

**Comment by Yashbhadiyadra** [comment]
Go ahead @Killer2OP 
Must follow all the guidelines

**Comment by Killer2OP** [comment]
@Yashbhadiyadra Can you review the PR and merge it.
