### ISSUE TITLE
Python Script for story generator

### ISSUE THREAD

**Issue by shraddha761** [avinashkranjan/Amazing-Python-Scripts#1865]
# Aim

This script randomly selects a character, setting, action, and conclusion from predefined lists and generates a story using these elements. 

# Details

When you run the script, it will generate and print a random story. We can run the script multiple times to generate different stories each time.

Assign this issue to me under GSSOC'23

**Comment by Yashbhadiyadra** [comment]
Go ahead @shraddha761
