### ISSUE TITLE
[GSSoC'23] Color Guessing Game using Python GUI(Tkinter)

### ISSUE THREAD

**Issue by varshanim** [avinashkranjan/Amazing-Python-Scripts#1866]
# Aim

- I want to develop a simple Color guessing game using Tkinter.

# Details

- A color name will be displayed on the screen in a different color and you have to guess the color the word is displayed in.
- In this game, you will be given 45 seconds to guess the color of the word displayed on the screen.
- The more number of colors you guess right, your score increases.

Ex: In this case, the answer would be pink.

![Screenshot 2023-06-21 at 11 38 45 AM](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/105119278/5acbc80d-678c-416e-b816-d957af02fbe9)

**Comment by varshanim** [comment]
@Yashbhadiyadra Please assign me this issue! Thank you.

**Comment by avinashkranjan** [comment]
Go Ahead @varshanim
