### ISSUE TITLE
Sentiment analysis tweets of twitter

### ISSUE THREAD

**Issue by Sushilverma002** [avinashkranjan/Amazing-Python-Scripts#1870]
**Is your feature request related to a problem? Please describe.**
i would like to do sentiment analysis on tweet of twitter like which tweets contain sensitive language.

**Describe the solution you'd like**
i will take data set of around 30k of tweets from Kaggle and use ML(MACHINE LEARNING) MODEL NAMED [LOGISTIC REGRESSION] to test the data set.
along with i will provide you the data set on which i am going to work.
i will use jupyter notebook for coding.
**Describe alternatives you've considered**

**Additional context**

**Comment by Yashbhadiyadra** [comment]
@Sushilverma002 How is it different from this? https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/TwitterTweetSentimentalAnalysis

**Comment by Sushilverma002** [comment]
@Yashbhadiyadra 
1st i will gonna work on data set of around 30k-35k 
2nd i will gonna be use matplot to plot graph and showing the data more effectively.
3rd the major thing is the accuracy level bhi around 90-95 %
4th i will be provide you the data which i will use doing this SENTIMENT ANLAYSIS

**Comment by Sushilverma002** [comment]
@Yashbhadiyadra did you check out?
