### ISSUE TITLE
Add QuickSort Algorithm

### ISSUE THREAD

**Issue by mukeshmade** [avinashkranjan/Amazing-Python-Scripts#1871]
# Aim

To Add the QuickSort Algorithm in Python

Hello!
I am a proud contributor at GSSoC '23. I would like to the contribute to this project.

@avinashkranjan if you think it is useful then do assign me the issue under GSSoC '23 with the level of the PR as well.

**Comment by avinashkranjan** [comment]
Too Basic, Read the Description of the Project, We don't need algorithms we need scripts.
