### ISSUE TITLE
Adding pagination to the scripts page

### ISSUE THREAD

**Issue by Akanksha-202** [avinashkranjan/Amazing-Python-Scripts#1875]
**Is your feature request related to a problem? Please describe.**
I have to scroll a lot for checking all the scripts available.

**Describe the solution you'd like**
Pagination will reduce the no. of cards (scripts) on a page.

Please assign this issue to me under GSSoc'23 label:)

**Comment by avinashkranjan** [comment]
Go Ahead @Akanksha-202

**Comment by Akanksha-202** [comment]
@avinashkranjan Please review the PR
