### ISSUE TITLE
Whatsapp Automation with Python

### ISSUE THREAD

**Issue by vaishnavirshah** [avinashkranjan/Amazing-Python-Scripts#188]
# Aim

Send whatsapp messages to a user.

# Details

In this script the user will be asked to :
- Mention the name of the user they want to send the message to
- Write the message they want to send
- And scan for whatsapp web.
And then the message will be automatically sent to that user.

**Comment by avinashkranjan** [comment]
Go ahead with the script @vaishnavirshah Assigned to you..
