### ISSUE TITLE
Add  Image Processing and Computer Vision python script

### ISSUE THREAD

**Issue by AnushkaS1** [avinashkranjan/Amazing-Python-Scripts#1883]
# Aim

- What is the objective of the Script
- Image Enhancement: Develop a script that enhances the quality of images by applying filters, adjusting brightness and contrast, and reducing noise. This could be useful for improving the visual appearance of images for various applications like photography or medical imaging.

# Details

- What the features will your script have
- Image Loading, Image Filtering, Edge Detection etc.

**Comment by AnushkaS1** [comment]
@avinashkranjan I want to work on this issue 
please assign it to me under gssoc'23

**Comment by avinashkranjan** [comment]
Go Ahead @AnushkaS1

**Comment by AnushkaS1** [comment]
Thankyou !

**Comment by AnushkaS1** [comment]
#2080 @avinashkranjan could you please review this changes.
