### ISSUE TITLE
Natural Language Processing

### ISSUE THREAD

**Issue by shraddha761** [avinashkranjan/Amazing-Python-Scripts#1884]
# Aim

 A script that utilizes NLP techniques to perform tasks like sentiment analysis, text classification, or named entity recognition. 
Assign this issue to me under GSSOC'23

**Comment by shraddha761** [comment]
> @shraddha761 Please provide some more details.

In this script, I am using the Natural Language Toolkit (NLTK) library, specifically the SentimentIntensityAnalyzer class, to perform sentiment analysis. The SentimentIntensityAnalyzer calculates sentiment scores for a given text and provides polarity scores for positive, negative, neutral, and compound sentiments.

The perform_sentiment_analysis function takes a text as input, initializes the sentiment analyzer, analyzes the sentiment of the text, and prints the sentiment scores. It then determines the overall sentiment based on the compound score.

**Comment by avinashkranjan** [comment]
Already Present in the Repo
