### ISSUE TITLE
Network Scanner

### ISSUE THREAD

**Issue by tayyab-ilyas** [avinashkranjan/Amazing-Python-Scripts#1885]
# Aim

- A script that will scan the network.

# Details

- It will output the list of devices connected to that particular network.

**Comment by tayyab-ilyas** [comment]
hey @avinashkranjan ! can  you assign this to me under Gssoc'23 ? thanks!

**Comment by tayyab-ilyas** [comment]
hey @Yashbhadiyadra  ! can  you assign this to me under Gssoc'23 ? thanks!

**Comment by avinashkranjan** [comment]
Go Ahead @tayyab-ilyas
