### ISSUE TITLE
Fake News Detector

### ISSUE THREAD

**Issue by shraddha761** [avinashkranjan/Amazing-Python-Scripts#1886]
# Aim

A script that analyzes news articles or headlines and determines their credibility using machine learning algorithms. In this script we can train a model on a labeled dataset of real and fake news articles and use it to classify new articles as potentially fake or genuine.

Assign this issue to me under GSSOC'23

**Comment by Yashbhadiyadra** [comment]
@shraddha761 Please provide some more details like what's the size of the dataset, source of the dataset, what's new in your approach?

**Comment by shraddha761** [comment]
> @shraddha761 Please provide some more details like what's the size of the dataset, source of the dataset, what's new in your approach?

In this script, we're using the TfidfVectorizer to convert text data into numerical feature vectors based on term frequency-inverse document frequency (TF-IDF) weighting. We then use a PassiveAggressiveClassifier to train a binary classification model for distinguishing between real and fake news articles.

**Comment by avinashkranjan** [comment]
Alreadt Present in the Repo.
