### ISSUE TITLE
Project : Internet SpeedTest 

### ISSUE THREAD

**Issue by dev-32** [avinashkranjan/Amazing-Python-Scripts#1887]
**Is your feature request related to a problem? Please describe.**
If anyone who wanted to test its internet speed can use this project **using Python**

**Describe the solution you'd like**
This project can give the following things:
**_1)Upload Speed
2)Download Speed
3)Ping_**

Assign me @dev-32 to contribute this project for the same.
Thus, contributing to GSSOC'23

**Comment by avinashkranjan** [comment]
Already Present in Repo
