### ISSUE TITLE
[Script]: Add Sorting visualiser in python

### ISSUE THREAD

**Issue by MisterMickey** [avinashkranjan/Amazing-Python-Scripts#1896]
### Aim

Visualise different sorting algorithms

### Details

The py script will visualise the sorting algorithms

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @MisterMickey
