### ISSUE TITLE
Making Graphical Calculator using Tkinter (GUI)

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#19]
# Aim

- Script in python to build User Interactive Calculator using Tkinter which is a GUI toolkit.

# Details

- The user have a choice to do any operation.
- Define all the functions and the user interactive buttons and more..

**Comment by abirbhattacharya82** [comment]
i want to work on this issue:
Making Graphical Calculator using Tkinter (GUI) #19
Assign it to me

**Comment by avinashkranjan** [comment]
Assigned to you..

> Also, @abirbhattacharya82   as you are a participant of [Synthax](https://synthax.live/) please introduce yourselves in the [Welcome to Synthax](https://github.com/avinashkranjan/Amazing-Python-Scripts/issues/20) thread. 👋. It will help us keep track of your progress and contributions during the period. 😄
