### ISSUE TITLE
[Script]: Reverse a Number

### ISSUE THREAD

**Issue by sabhisharma-ise** [avinashkranjan/Amazing-Python-Scripts#1901]
### Aim

The script seeks to reverse the value of a number.

### Details

In this case, the solution entails:

1. Take the integer’s value and store it in a variable.
2. Get each digit of the number and store the reversed number in another variable using a while loop.
3. Write the number backward.
4. Get out of there.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Too Basic
