### ISSUE TITLE
[Script]: To check External IP Address

### ISSUE THREAD

**Issue by sabhisharma-ise** [avinashkranjan/Amazing-Python-Scripts#1902]
### Aim

This is a basic Python script for determining your external IP address.

### Details

Needing to know your external IP address isn’t something that happens all the time…until it does.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @sabhisharma-ise
