### ISSUE TITLE
[Script]: Searching your PC for specific files

### ISSUE THREAD

**Issue by sabhisharma-ise** [avinashkranjan/Amazing-Python-Scripts#1903]
### Aim

Using the os.walk() module function and match filenames with the fnmatch module.
It walks the tree top-down or bottom-up to create file names in a directory tree. It returns a 3-tuple for each directory in the tree rooted at directory top, including top itself, i.e., dirpath, dirnames, filenames.

### Details

fnmatch() compares a single file name to a pattern and returns a boolean that indicates whether they match or not. If the operating system uses a case-sensitive file system, the comparison is case-sensitive.
If you choose to use a different pattern type, such as regular expressions, simply fit your filenames with regex operations. This script searches the hard drive for all image files using the commands’ os.walk’ and ‘fnmatch’ with filters.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @sabhisharma-ise
