### ISSUE TITLE
[Script]: View all GitHub Repositories

### ISSUE THREAD

**Issue by sabhisharma-ise** [avinashkranjan/Amazing-Python-Scripts#1904]
### Aim

This script aims at providing access to the public repositories, given the username.

### Details

Details of the repository such as name, date of creation, and so on are displayed.
The library PyGithub, which is built on Python is used. 
The requests library is also used, in order to interact and obtain data from Github.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @sabhisharma-ise
