### ISSUE TITLE
[Script]: Hexadecimal Calculator

### ISSUE THREAD

**Issue by pavitrachavda97** [avinashkranjan/Amazing-Python-Scripts#1908]
### Aim

The aim of a decimal to hexadecimal (hex) calculator is to provide a tool that allows users to convert decimal numbers into their equivalent hexadecimal representation.

### Details

Decimal to hexadecimal calculator takes a decimal number as input and converts it into a hexadecimal number. 
The following steps are involved in the conversion process:
- User input
- Validation 
- Conversion algorithm
- Hexadecimal Output

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @pavitrachavda97

**Comment by iditocommerce** [comment]
i will work on this project. please assign it to me. once done i will open pull request on this issue.
