### ISSUE TITLE
[Bug]: Inconsistent Card Design

### ISSUE THREAD

**Issue by Sriparno08** [avinashkranjan/Amazing-Python-Scripts#1912]
### Describe the bug

The content of one card does not align with the content of the other cards. As you can see in the below screenshot, the **Take Me** buttons in the cards are positioned inconsistently and they are not in a straight line, which affects the UI impression.

### Steps to reproduce the behavior

1. Go to https://amazing-python-scripts.pages.dev/scripts
2. See the bug

### Expected behavior

The content in the cards should be aligned properly and they need to be in a straight line. This way, the UI will look much nicer.

### Screenshots

![Screenshot 2023-06-23 213300](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/89148144/e77c752f-04a5-4ea0-ae7e-10cbaea746f2)

### Device?

Desktop

### Which OS are affected?

Windows

### Enter the version of your web browser

114

### Which browsers are affected?

Chrome

### Additional context

It will look like this or even better:

![Screenshot 2023-06-23 214641](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/89148144/3071885f-09e4-4fa1-be08-ba1fd4d49ace)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @Sriparno08

**Comment by avinashkranjan** [comment]
Closed in commit [9eb5956](https://github.com/avinashkranjan/Amazing-Python-Scripts/commit/9eb59567058d8b47a4d810f15ca55a947d650f89)
