### ISSUE TITLE
[Script]: Morse Code

### ISSUE THREAD

**Issue by whiteknight16** [avinashkranjan/Amazing-Python-Scripts#1919]
### Aim

The code for the Morse code generator already exists in the repo so I will modify it so it can copy the generated code for a better user experience

### Details

Will use certain python libraries to achieve this task

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @whiteknight16
