### ISSUE TITLE
[Script]: Reddit Sentiment Analysis using Pytorch

### ISSUE THREAD

**Issue by karthikbhandary2** [avinashkranjan/Amazing-Python-Scripts#1922]
### Aim

To perform sentiment analysis on reddit data.

### Details

This uses the dataset from Kaggle to perform sentiment analysis on the text data. At the end of the file, I even predict the tone of a comment. I will be using pytorch to do this.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @karthikbhandary2
