### ISSUE TITLE
[Script]: want to add checksum script

### ISSUE THREAD

**Issue by Kalivarapubindusree** [avinashkranjan/Amazing-Python-Scripts#1929]
### Aim

I want to add checksum script.
can you please assign me this task under gssoc'23 @av

### Details

checksum script

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @Kalivarapubindusree
