### ISSUE TITLE
[Script]: Current-city-weather.

### ISSUE THREAD

**Issue by Kalivarapubindusree** [avinashkranjan/Amazing-Python-Scripts#1931]
### Aim

I want to add current city weather script.
can you please assign this task under gssoc'23 @avinashkranjan 

### Details

current city weather script

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @Kalivarapubindusree
