### ISSUE TITLE
[Script]: Want to add html table to list script

### ISSUE THREAD

**Issue by Kalivarapubindusree** [avinashkranjan/Amazing-Python-Scripts#1932]
### Aim

I want to add html table to list script.
can you please assign this task under gssoc'23 @av

### Details

Want to add html table to list script

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Not Needed, Create another Issue
