### ISSUE TITLE
[Script]: Handwriting Recognizer script

### ISSUE THREAD

**Issue by Kalivarapubindusree** [avinashkranjan/Amazing-Python-Scripts#1933]
### Aim

I want to add handing recognizer script.
can you please assign this task under gssoc'23 @av

### Details

Handwriting Recognizer script

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Already Present in the Repo
