### ISSUE TITLE
[Feat]:Copy encryption or decryption

### ISSUE THREAD

**Issue by whiteknight16** [avinashkranjan/Amazing-Python-Scripts#1941]
### Is your feature request related to a problem? Please describe.

The Caesar cipher encryptor or decryptor already exists. Will add copy to the clipboard feature so encrypted or decrypted text gets copied to the clipboard itself.

### Describe the solution you'd like.

will use pyperclip module

### Describe alternatives you've considered.

will use cliboard module

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @whiteknight16
