### ISSUE TITLE
[Script]: BMI calculator gui

### ISSUE THREAD

**Issue by Swapnil-2503** [avinashkranjan/Amazing-Python-Scripts#1949]
### Aim

This is a simple BMI (Body Mass Index) calculator implemented in Python using a Graphical User Interface (GUI) with Tkinter.

### Details

Tkinter: This is the standard Python GUI library used to create the graphical interface for the BMI calculator.

It will calculate bmi of person.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @Swapnil-2503

**Comment by bhavya1857** [comment]
please assign me this issue as i have already created the PR #2171
