### ISSUE TITLE
[Feat]: Improvement needs for Design of Submit Button UI in Contact Us Section 

### ISSUE THREAD

**Issue by NarendraKoya999** [avinashkranjan/Amazing-Python-Scripts#1953]
### Issue Description:
- **Improvement Needs for Design of` Submit Button UI` in `Contact Us Section` as Per `Latest Trending Designs`.**

### Describe the solution you'd like.

- **`Look at below Screenshot, Where I Can suggest to Replacing to add this Submit Button in Contact Us Section.`**

### Describe alternatives you've considered.

-**` No Alternatives, Just Follow Above Describing the Solution Steps. `**

### Show us the magic with screenshots

![pythonscripts-1](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/84512164/d00d03c7-84f6-4b0e-93dd-87c0a90d6fc2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @NarendraKoya999

**Comment by NarendraKoya999** [comment]
Thank you for assigned this Issue to me @avinashkranjan
