### ISSUE TITLE
[Script]: Memory Game

### ISSUE THREAD

**Issue by Vyshnavi21504** [avinashkranjan/Amazing-Python-Scripts#1955]
### Aim

Design a memory-testing game where players are presented with a grid of hidden cards and have to match pairs by flipping them over.

### Details

Design a memory-testing game where players are presented with a grid of hidden cards and have to match pairs by flipping them over.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Vyshnavi21504** [comment]
@avinashkranjan please assign me this issue under GSSOC'23

**Comment by avinashkranjan** [comment]
Go Ahead @Vyshnavi21504
