### ISSUE TITLE
Network scanner in python.

### ISSUE THREAD

**Issue by pritamp17** [avinashkranjan/Amazing-Python-Scripts#196]
# Aim

Building a network scanner

# Details

- It will give IP and MAC-ADDRESS of devices connected to the same network as yours.

**Comment by pritamp17** [comment]
please assign me this issue under SWOC

**Comment by avinashkranjan** [comment]
Go ahead @pritamp17

**Comment by pritamp17** [comment]
@avinashkranjan sir I have sent PR please review it when you can.
