### ISSUE TITLE
[Script]: Internet Speed Checker (GUI)

### ISSUE THREAD

**Issue by smty2018** [avinashkranjan/Amazing-Python-Scripts#1964]
### Aim

The internet speed checker program aims to measure the download and upload speeds of an internet connection using Python. 

### Details

Measurement of Download Speed and Upload Speed. After performing the speed tests, the program displays the measured download and upload speeds in a user-friendly format. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by smty2018** [comment]
@avinashkranjan @Yashbhadiyadra please assign me this issue under gssoc'23

**Comment by avinashkranjan** [comment]
Go Ahead @smty2018
