### ISSUE TITLE
[Script]: URL Shortener

### ISSUE THREAD

**Issue by Vyshnavi21504** [avinashkranjan/Amazing-Python-Scripts#1965]
### Aim

Build a URL shortening service where long URLs can be shortened into shorter, more manageable links.

### Details

Build a URL shortening service where long URLs can be shortened into shorter, more manageable links.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @Vyshnavi21504
