### ISSUE TITLE
[Script]:  Automatic jokes generator

### ISSUE THREAD

**Issue by Ks103** [avinashkranjan/Amazing-Python-Scripts#1968]
### Aim

This python script will generate the jokes 

### Details

Particular this code will fetch jokes from an API and generate code in the terminal.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @Ks103
