### ISSUE TITLE
scripts using ZIP in python

### ISSUE THREAD

**Issue by vaishnavijha** [avinashkranjan/Amazing-Python-Scripts#197]
# Aim

ZIP function in python makes a lot of process easy and reduces several lines of code into one liner

# Details

- The zip function makes our python code very elegant. However, uses of the zip function are not very intuitive for beginners and sometimes they are error-prone.So i want to demonstrate how zip function can efficiently used to our purpose.

**Comment by vaishnavijha** [comment]
Can i be assigned this issue to work on.Please review this issue.

**Comment by avinashkranjan** [comment]
Sure Go ahead @vaishnavijha

**Comment by vaishnavijha** [comment]
Created pull request
