### ISSUE TITLE
[Script]: Improvement in Password Generator | Password Generator 2.0

### ISSUE THREAD

**Issue by duragpal** [avinashkranjan/Amazing-Python-Scripts#1970]
### Aim

Password Generator will generate secure password of 16 characters. (character length can be changed). The previous password generator uses long code which can be shortened to 8-10 lines of code.

### Details

This password generator script will consist of 10 lines of code and will use "secrets" module to generate random passwords. These passwords can be used for better security.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by duragpal** [comment]
I want to work on this issues. Please assign me this issue.

**Comment by avinashkranjan** [comment]
Script Not Needed
