### ISSUE TITLE
Cryptography Algorithms

### ISSUE THREAD

**Issue by hima-v** [avinashkranjan/Amazing-Python-Scripts#1971]
### Aim

To add the scripts for key exchange algorithms like: RSA, Diffie Hellman, Encryption by Substitution Cipher and Transposition Cipher.

### Details

These algorithms are taught in the curriculum of Computer Science Engineering course of 6th semester. These scripts will be helpful for students to understand the implementation.
Features will be:
- Easy to implement
- Efficient code

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by hima-v** [comment]
Since there is an already existing folder of Cryptography, I can simply add these algorithms.

**Comment by avinashkranjan** [comment]
Go Ahead @hima-v
