### ISSUE TITLE
[Script]: ISBN Number Validator using PYTHON

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [avinashkranjan/Amazing-Python-Scripts#1972]
### Aim

- Full form of - International Standard Book Numbers.
- ISBNs are unique identifiers assigned to books. 
- They can have either 10 or 13 digits, depending on the edition and publication date.

To ensure that they are entered accurately for book identification and inventory management purposes.

### Details

- The last digit of an ISBN is called the check digit, which is used to verify the accuracy of the number. 
- It is calculated based on the preceding digits using a specific algorithm.
- To validate an ISBN, the algorithm is applied to the provided digits, excluding the check digit. 
- The resulting value is compared with the check digit. If they match, the ISBN is considered valid; otherwise, it is likely to be incorrect or mistyped.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Avdhesh-Varshney** [comment]
@avinashkranjan @1e9abhi1e10 @Yashbhadiyadra Sirs, please assign this task to work on it and give a valuable contribution under GSSoC'23 program

**Comment by avinashkranjan** [comment]
Go Ahead @Avdhesh-Varshney
