### ISSUE TITLE
[Feat]: Adding traversals in Tree(DSA in Python)

### ISSUE THREAD

**Issue by Juhibhojani** [avinashkranjan/Amazing-Python-Scripts#1973]
### Is your feature request related to a problem? Please describe.

I would like to add inorder, preorder as well as postorder traversal of the given tree in DSA in the Python folder inside Data Structures.

### Describe the solution you'd like.

It will be a recursive solution to print given traversal. 3 functions will be added.

### Describe alternatives you've considered.

Adding new file containing given traversals in single python file

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
No need of DSA Algorithms in this Repo
