### ISSUE TITLE
[Feat]: Adding group message automation in Whatsapp

### ISSUE THREAD

**Issue by Juhibhojani** [avinashkranjan/Amazing-Python-Scripts#1974]
### Is your feature request related to a problem? Please describe.

Sending message to WhatsApp group

### Describe the solution you'd like.

I would like to add a script in [WhatsApp-Auto-Messenger](https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/WhatsApp-Auto-Messenger) for sending the text to a group at a scheduled time.

### Describe alternatives you've considered.

Using pywhatkit module for same

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @Juhibhojani
