### ISSUE TITLE
[Script]: Blurring an image

### ISSUE THREAD

**Issue by invigorzz313** [avinashkranjan/Amazing-Python-Scripts#1977]
### Aim

to blur an image eg, guassian blur depending on input amount of pixels

### Details

using cv2 and required libraries, there will be a slider to choose pixel value so that image will be blurred by that amount

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @invigorzz313
