### ISSUE TITLE
[Script]: number in words

### ISSUE THREAD

**Issue by invigorzz313** [avinashkranjan/Amazing-Python-Scripts#1978]
### Aim

a python script to output the number name for an input number, eg. 345: three hundred fourty five

### Details

using tkinter and other required libraries, there will be dropdowns for selecting each digit while output simultaneously gives the number name eg. 345: three hundred fourty five

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Too Basic
