### ISSUE TITLE
[Script]: AUTOMATED Software testing using python.

### ISSUE THREAD

**Issue by Kalivarapubindusree** [avinashkranjan/Amazing-Python-Scripts#1986]
### Aim

I want to add automated software testing script using python.
Can you please assign me this task under GSSOC'23 contribution @avi

### Details

Adding automatic software testing python script 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @Kalivarapubindusree
