### ISSUE TITLE
[Script]: Chinese Number Plate Scanner

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [avinashkranjan/Amazing-Python-Scripts#1987]
### Aim

Hello @avinashkranjan ,
Adding a Chinese number plate scanner which helps the China for the traffic ratio evolution also I when I was visited the Shanghai for a project on E-Traffic Catcher me and  my friend who is from IIT Delhi developed this for the China Traffic and we are the winner of that project.
So, I think I should add this in your Project {Amazing-Python-Scripts}
### Details

It is an end-to-end Chinese license plate recognition software based on U-Net, OpenCV, and CNN, where U-Net and OpenCV are used for license plate localization and correction, and CNN is used for license plate recognition. Both U-Net and CNN are implemented using TensorFlow's Keras.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @SyedImtiyaz-1
