### ISSUE TITLE
[Script]: URL Shortner Script 

### ISSUE THREAD

**Issue by Tisha6661** [avinashkranjan/Amazing-Python-Scripts#1991]
### Aim

To shorten the url given for any image, account, etc using python.

### Details

One of the most important benefits of a URL shortener is the ability to track clicks on each link you share. It makes it easy to use the shorten url.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Script Already Present.
