### ISSUE TITLE
[Script]: Image resizing Script

### ISSUE THREAD

**Issue by Tisha6661** [avinashkranjan/Amazing-Python-Scripts#1992]
### Aim

To resize the image as per the requirement using pyhton.

### Details

Today it's a requirement to use a particular size of the image. This python script is used to resize the image width and height.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @Tisha6661

**Comment by Tisha6661** [comment]
@avinashkranjan I have created a pull request regarding this task, please verify and merge it.
