### ISSUE TITLE
[Script]: Web page screenshot script using Selenium.

### ISSUE THREAD

**Issue by Tisha6661** [avinashkranjan/Amazing-Python-Scripts#1993]
### Aim

To take screenshot of the webpage using selenium library of python. 

### Details

Today we take a lot of screenshots, of required webpages to save them, and use them or learn from them. This script would help to do that.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Script Already Present.
