### ISSUE TITLE
[Feat]: Design logo of the website

### ISSUE THREAD

**Issue by Tisha6661** [avinashkranjan/Amazing-Python-Scripts#1994]
### Is your feature request related to a problem? Please describe.

There is no logo on the website. It enhances the look of the website.

### Describe the solution you'd like.

A name logo of the website describes it well, I would like to design a logo for the website.

### Describe alternatives you've considered.

Alternatively I can design initials logo also.

### Show us the magic with screenshots

Here are some designs I have made-

![Screenshot 2023-06-27 011300](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/98682478/b0c4558f-ca72-419e-9980-16953cbafc05)
![Screenshot 2023-06-29 000158](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/98682478/8c7b436f-1ae8-4e50-a68e-db07a201ff13)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @Tisha6661

**Comment by Tisha6661** [comment]
@avinashkranjan  I have created a pull request regarding this task, please verify and merge it.
