### ISSUE TITLE
[Feat]: Better Ui of the Cards

### ISSUE THREAD

**Issue by Tisha6661** [avinashkranjan/Amazing-Python-Scripts#1995]
### Is your feature request related to a problem? Please describe.

The card style for scripts is very simple right now. I would like to enhance that.

### Describe the solution you'd like.

The card style can be made better by adding hovering feature, using better design and apply changes to font.

### Describe alternatives you've considered.

By changing the layout of the cards on the page. And aligning them rightly. Like look at this- 
![image](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/98682478/aec09022-deb0-4b34-8929-91c90589dae3)

It's all uneven.

### Show us the magic with screenshots

![image](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/98682478/d5b474fb-892d-42ee-b49a-5dff65ff186b)

I would suggest something like this-
![Screenshot 2023-06-29 231630](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/98682478/9665beb1-3be1-4696-a7b2-0696669b0eb2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @Tisha6661
