### ISSUE TITLE
Welcome to Synthax

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#20]
### Thanks for showing your interest in [Synthax](https://synthax.live/).
Super glad to know that you're interested in contributing to [Amazing-Python-Scripts](https://github.com/avinashkranjan/Amazing-Python-Scripts).

### Introducing mentor below:

| Name 🎖️       | Social Media 👋 | GitHub :octocat: |
|----------------|-----------------|------------------|
| Avinash Ranjan | 🐦 [Twitter ](https://twitter.com/iavinashranjan)  🎓 [Linkedin](https://www.linkedin.com/in/avinashkranjan)    | @avinashkranjan  |

This thread is dedicated for open discussions. Feel free to **ask your doubts here.**

Before you start contributing, I highly recommend all of you to go through the 
- 📑 [Contributing Guidelines](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)

Kindly note that the coding period starts from 12th September. The least you should know to contribute is [basic understanding of git.](https://medium.com/@onejohi/git-understanding-the-basics-ba004a20dacc) 

Keep watching this repo. 👁️

🤗

**_Regards,_**
`Avinash Ranjan [Project Admin]`

[![Open Source Love svg2](https://badges.frapsoft.com/os/v2/open-source.svg?v=103)](https://github.com/ellerbrock/open-source-badges/)

**Comment by madihamallick** [comment]
I am Madiha Mallick, a second year student of CIEM belonging to the CSE stream.

**Comment by abirbhattacharya82** [comment]
Hi I am Abir Bhattacharya. I am from Calcutta Institute of Engineering and Management, IT department

**Comment by geekymeeky** [comment]
Hi I'm Srijan Kumar Gupta, sophomore at Calcutta Institute Of Engineering and Management pursuing BTech in CSE

**Comment by avinashkranjan** [comment]
Event Completed.... Great Work guys @madihamallick @geekymeeky @abirbhattacharya82
