### ISSUE TITLE
[Script] ML Regression algorithms in Python [GSSoc’23]

### ISSUE THREAD

**Issue by varshanim** [avinashkranjan/Amazing-Python-Scripts#2011]
### Aim

Under this issue i would like to add the scripts for Simple Linear Regression and Multiple Linear Regression such that the output would display a graph and the estimated coefficients.

### Details

Linear Regression is an ML algorithm that is used to estimate data given specific amounts of data.
This script can be added by using the  Matplotlib library in python and the numpy module also from python.

![IMG_5929](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/105119278/229821d6-64f2-4b79-922f-afaa7d43a337)

![IMG_5928](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/105119278/fbdb26b7-087e-46f6-99ab-d407772659de)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by varshanim** [comment]
@avinashkranjan @Yashbhadiyadra 
Can you please assign this issue to me under GSSoC'23? Thank you!

**Comment by avinashkranjan** [comment]
Not Needed.
