### ISSUE TITLE
[Script]: NATO Alphabet Project

### ISSUE THREAD

**Issue by whiteknight16** [avinashkranjan/Amazing-Python-Scripts#2012]
### Aim

Converts word to nato phonetic alphabets

### Details

You enter the word will return a list of letters in the word in the form of the NATO Phonetic Alphabet

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @whiteknight16
