### ISSUE TITLE
[Feat]:  Twitter bot

### ISSUE THREAD

**Issue by Abhinavcode13** [avinashkranjan/Amazing-Python-Scripts#2016]
### Is your feature request related to a problem? Please describe.

This script interacts with the Twitter API to automate actions on Twitter. It can be programmed to post tweets, like or retweet specific tweets, follow or unfollow users based on certain criteria, or even analyze sentiments of tweets.

### Describe the solution you'd like.

adding the scripts required for making twitter bot

### Describe alternatives you've considered.

no

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @Abhinavcode13
