### ISSUE TITLE
[Script]: DOH-dig

### ISSUE THREAD

**Issue by shraddha761** [avinashkranjan/Amazing-Python-Scripts#2023]
### Aim

A python dig script that returns json dns record lookup using cloud flares DNS servers.

### Details

A "DoH dig" script combines the functionality of performing DNS queries with the security and privacy benefits of DNS over HTTPS (DoH). It allows you to query DNS records using Cloudflare's DoH service, which encrypts the DNS traffic and provides an additional layer of privacy.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @shraddha761
