### ISSUE TITLE
[Script]: Crypt_Socket

### ISSUE THREAD

**Issue by shraddha761** [avinashkranjan/Amazing-Python-Scripts#2024]
### Aim

The  script establishes a secure encrypted socket connection to a server using SSL/TLS. It allows you to communicate securely with the server over a network.

### Details

this script allows  to establish a secure encrypted connection to a server using SSL/TLS, send data to the server, receive a response, and then close the connection. It is commonly used for secure communication with servers over protocols like HTTPS.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @shraddha761
