### ISSUE TITLE
Script to Send Professional HTML Bulk Emails using Python

### ISSUE THREAD

**Issue by dhanrajdc7** [avinashkranjan/Amazing-Python-Scripts#204]
# Aim
- Send Bulk HTML Emails using Python Automation

# Details
- Send Bulk HTML Emails
- Responsive Email Design
- SMTP Server Cooldown 
- Option to attach files to Template

# Demo
![Screenshot 2021-01-08 at 15 19 05](https://user-images.githubusercontent.com/39642060/104002162-ad6e6600-51c6-11eb-9662-7adccff6a292.png)

**Comment by avinashkranjan** [comment]
Sure go ahead @dhanrajdc7 Assigned to you
