### ISSUE TITLE
[Script]: Automatic Spelling Checker + Corrector

### ISSUE THREAD

**Issue by sabhisharma-ise** [avinashkranjan/Amazing-Python-Scripts#2041]
### Aim

This Script is used to detect spelling errors in a text and correct them if the user wishes to do so.

### Details

- Create a Virtual Environment.
- Install the requirements by using pip3 install -r requiremnts.txt
- Hurray.! You're ready to use the Script.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
GO Ahead @sabhisharma-ise
