### ISSUE TITLE
[Script]: Domain Name Availabilty Checker

### ISSUE THREAD

**Issue by sabhisharma-ise** [avinashkranjan/Amazing-Python-Scripts#2042]
### Aim

The python script uses GoDaddy's API to get all the domain names which are available according to the keyword given by user.

### Details

All the results are stored in a .txt file, named after the keyword.
# Setup
- A virtual environment.
- pip install -r requirements.txt
- Generate your GoDaddy API KEY and Secret KEY from [here](https://developer.godaddy.com/keys)
- Paste the token in a .env file

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
GO Ahead @sabhisharma-ise
