### ISSUE TITLE
[Script]: Fetch contributions

### ISSUE THREAD

**Issue by sabhisharma-ise** [avinashkranjan/Amazing-Python-Scripts#2043]
### Aim

It's a Python script to fetch the pull requests made by a github user in an Organization. It helps organization members to keep record of a particular github user requests and also helps the github user to record the pull requests made to the organization.

### Details

- Script can be executed as a CLI.
- Takes arguments username and organization.
- Returns the pull requests made by user to the organization into a Markdown file.
- Markdown file consists a table having - "Title of PR" , "Link of PR" , "Status(Merged/Closed/Open)"

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @sabhisharma-ise
