### ISSUE TITLE
[Script]: FindByLyrics

### ISSUE THREAD

**Issue by sabhisharma-ise** [avinashkranjan/Amazing-Python-Scripts#2044]
### Aim

Python script to get song lyrics or find a song from a snippet of it's lyrics, and more.

### Details

- User can write the lyrics and get the song
- User can enter the song name and get the lyrics

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
GO Ahead @sabhisharma-ise
