### ISSUE TITLE
[Script]: Save any article you like from GeeksForGeeks as a pdf

### ISSUE THREAD

**Issue by sabhisharma-ise** [avinashkranjan/Amazing-Python-Scripts#2045]
### Aim

This python script will download articles from GeeksForGeeks and save them as a pdf file. 

### Details

The script uses Selenium Webdriver and fpdf library. 
Selenium is used with Chrome Webdriver, so having Chrome browser is a requirement.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @sabhisharma-ise
