### ISSUE TITLE
[Bug]: Auto-LinkedIn Files Deleted

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [avinashkranjan/Amazing-Python-Scripts#2048]
### Describe the bug

- Auto-LinkedIn Files are deleted before commiting any files.
- They are automatcally deleted on fetching the upstream and pulling data

### Expected behavior

This will stop before commiting anything

### Screenshots

![image](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/114330097/09beacce-9344-437b-97c8-e00a80277501)

### Device?

Desktop

### Which OS are affected?

Windows

### Enter the version of your web browser

Latest version of Brave

### Which browsers are affected?

Brave

### Additional context

I will fix it
- First restore the code in a separate file
- Commit the changes both deletion and addition in one commit
- Send the code by creating a pr

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Avdhesh-Varshney** [comment]
@avinashkranjan @1e9abhi1e10 @Yashbhadiyadra Sirs, please review this bug so that i can contribute in this repository

**Comment by avinashkranjan** [comment]
Go Ahead @Avdhesh-Varshney
