### ISSUE TITLE
Spelling Checker in python

### ISSUE THREAD

**Issue by Ayush7614** [avinashkranjan/Amazing-Python-Scripts#205]
# Aim

- Build a spell-checker using python packages

# Details

- This  is going to talk about three different packages for coding a spell checker in Python – `pyspellchecker`, `TextBlob`, and `autocorrect`.

**Comment by Ayush7614** [comment]
Plss assign me this issue @avinashkranjan sir

**Comment by avinashkranjan** [comment]
Assigned it you @Ayush7614

**Comment by Ayush7614** [comment]
#206 sir this is pull request

**Comment by Ayush7614** [comment]
plss review it @avinashkranjan sir

**Comment by Ayush7614** [comment]
@avinashkranjan  Sir plss review it

**Comment by Ayush7614** [comment]
@avinashkranjan sir plss review it
