### ISSUE TITLE
[Script]: Space Invader Game Using pygame

### ISSUE THREAD

**Issue by whiteknight16** [avinashkranjan/Amazing-Python-Scripts#2051]
### Aim

Use pygame to make space invaders game

### Details

Simple and classic space invader game made using pygame

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by ayush-09** [comment]
@whiteknight16  It same as issue no. #1861. If it is different from this give appropiate approach.
@avinashkranjan Please check it once carefully before assign.
Thanks
