### ISSUE TITLE
[Feat]: IP drone Python Script

### ISSUE THREAD

**Issue by alwenpy** [avinashkranjan/Amazing-Python-Scripts#2060]
### Is your feature request related to a problem? Please describe.

Ipdrone is a simply python script, which can be used to Ip lookup and to get information of particular target Ip. This tool works on both rooted Android device and Non-rooted Android device.

### Describe the solution you'd like.

-  Real live location
- Updated maintainence 
-  Ip lookup
- Easy For Beginners

### Describe alternatives you've considered.

No alternatives

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Already Contributed to `Pentesting Repo`
