### ISSUE TITLE
[Script]: Eazydiner restaurant scraper

### ISSUE THREAD

**Issue by Mihan786Chistie** [avinashkranjan/Amazing-Python-Scripts#2067]
### Aim

To scrape the [eazydiner](https://www.eazydiner.com/) website and obtain valuable information such as restaurant names, addresses, contact details, ratings, and reviews, etc.

### Details

It will provide a JSON response which will have the restaurant names, addresses, contact details, ratings, and reviews, etc. for a given city provided by the user.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @Mihan786Chistie
