### ISSUE TITLE
[Script]: Tech Crunch website scrapper

### ISSUE THREAD

**Issue by Mihan786Chistie** [avinashkranjan/Amazing-Python-Scripts#2068]
### Aim

To scrape the [TechCrunch](https://techcrunch.com/) website and retrieve the latest news from the website

### Details

It will return the news for a particular category in JSON.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @Mihan786Chistie
