### ISSUE TITLE
[Script]: Image rotation 

### ISSUE THREAD

**Issue by invigorzz313** [avinashkranjan/Amazing-Python-Scripts#2072]
### Aim

This script, using cv2 library, aims to rotate an image (input) by the amount of degrees specified by the user

### Details

Using cv2 library, we shall use required functions to perform rotation on an image. User can give input degrees using trackbar.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Already Present in the Repo
