### ISSUE TITLE
[Feat]: Back to Top button

### ISSUE THREAD

**Issue by BhartiNagpure** [avinashkranjan/Amazing-Python-Scripts#2073]
### Is your feature request related to a problem? Please describe.

In Script page after clicking load more button there is lots of script card and after going to bottom of page it is very difficult to scroll to Top, So that I would like to work on this to make more easy use for user.

### Describe the solution you'd like.

I would like to add bottom to top button in script page so that user can easily move to top after clicking that button.

### Describe alternatives you've considered.

We  can also toggle load less button with load  more button  so that user can easily move to top by scrolling less data.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Not Needed
