### ISSUE TITLE
[Script]: Blob detection

### ISSUE THREAD

**Issue by invigorzz313** [avinashkranjan/Amazing-Python-Scripts#2074]
### Aim

To determine the number of blobs in an image using dfs algorithm and cv2 library.

### Details

This script reads an image and returns/prints the number of blobs in the image mainly using DFS algorithm and cv2 library.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @invigorzz313
