### ISSUE TITLE
[Script]: EDA on Global Cost of Living

### ISSUE THREAD

**Issue by smty2018** [avinashkranjan/Amazing-Python-Scripts#2079]
### Aim

Want to add an exploratory data analysis (EDA) project on the global cost of living with machine learning (ML) models, I investigate various factors impacting living expenses worldwide.I want to  analyze data on factors such as housing, transportation, food, and healthcare costs using statistical techniques and visualizations. 

### Details

ML models are utilized to uncover patterns and relationships within the data, enabling us to predict and compare the cost of living in different regions, facilitating informed decision-making for individuals or businesses.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @smty2018
