### ISSUE TITLE
[Script Addition] I will be adding a AI chat bot 

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [avinashkranjan/Amazing-Python-Scripts#2092]
### Aim

To make an AI command line chat bot 

### Details

AI chat bot which will use ChatGPT's Unofficial Free API to obtain results, and chat with the person using command line.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @Swapnil-Singh-99

**Comment by Swapnil-Singh-99** [comment]
@avinashkranjan Please review and merge
