### ISSUE TITLE
[Script]: Desktop Water drinking notifier

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [avinashkranjan/Amazing-Python-Scripts#2093]
### Aim

A desktop notifier that notifies user to drink water and particular intervals to stay hydrated.

### Details

This is a python desktop notifier code to stay hydrated at all times while working on your PC or Laptop 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @Swapnil-Singh-99

**Comment by Swapnil-Singh-99** [comment]
@avinashkranjan Please Review and Merge
