### ISSUE TITLE
[Script]: File Searching python script

### ISSUE THREAD

**Issue by srujana-16** [avinashkranjan/Amazing-Python-Scripts#2094]
### Aim

This Python script allows you to search for files with a specific extension in a directory. It recursively searches through all subdirectories of the specified directory and returns a list of files that match the provided file extension.

### Details

- Recursive file search within a specified directory
- File extension filter to search for specific types of files
- Clear and user-friendly command-line interface

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @srujana-16
