### ISSUE TITLE
Making Graphical URL Shortener using Tkinter (GUI) 

### ISSUE THREAD

**Issue by geekymeeky** [avinashkranjan/Amazing-Python-Scripts#21]
### Aim:

- Script in python to build User Interactive URL shortener using Tkinter which is a GUI toolkit.

**Comment by avinashkranjan** [comment]
Assigned to you..

> Also, @geekymeeky  as you are a participant of [Synthax](https://synthax.live/) please introduce yourselves in the [Welcome to Synthax](https://github.com/avinashkranjan/Amazing-Python-Scripts/issues/20) thread. 👋. It will help us keep track of your progress and contributions during the period. 😄
