### ISSUE TITLE
A script to organise files in a folder as per their extensions

### ISSUE THREAD

**Issue by Rahul555-droid** [avinashkranjan/Amazing-Python-Scripts#210]
# Aim

On running this script the files in an input folder(command line) will be put into a folder as per their extension

# Details
Say I have a folder or a directory named "my_files"
In my_files I have files of all sorts of extensions like .txt , .pdf , .epub, etc.
Their numbers are in 100s
Going through each file and moving it to a directory will be cumbersome so will let python do it.

This script will take a path of my_files as input from command line and will organise the folders automatically as per their extensions,

Like all the files with .pdf extension will be moved to a sub directory inside "my_files" named as "pdf" and all the files with .txt extension will be moved to a sub directory named "txt" and so on.

**Comment by Rahul555-droid** [comment]
Hi please assign me this issue for SWOC.
Thanks :)

**Comment by avinashkranjan** [comment]
Assigned to you @Rahul555-droid

**Comment by Rahul555-droid** [comment]
Thanks will do it.

**Comment by yonMaor** [comment]
@Rahul555-droid @avinashkranjan 
Please let me know if I can help :)

**Comment by Rahul555-droid** [comment]
Hi abhinav I have opened the PR please review it.

Also I have used the stdin input instead of commandline arguments that I mentioned here.

**Comment by Rahul555-droid** [comment]
Hi @yonMaor .
I am almost done here.

Maybe you can make a shell script similar to this if allowed here.
