### ISSUE TITLE
A script that will check sentiment for an input text without any external lib [GUI]

### ISSUE THREAD

**Issue by Rahul555-droid** [avinashkranjan/Amazing-Python-Scripts#211]
# Aim

- A script that will check sentiment for an input text using tkinter.
This can be helpful for people who use Social media a lot and would want to get how positive or negative their tweet,post,etc. is.
Usually positive text has more reach so it can be a "sentiment checker"

# Details

- I will implement a script that will take a text as an input via GUI and give the user how positive or negative their tweet/text is.
I will implement this using only python so no need for any other external library or dependency.
The only things the script will use are two text files "positive.txt" containing a list of positive words and a "negative.txt" containing a list of negative words.

On running the script a GUI in tkinter would open up and the user can paste their text and c.ick on a "get  score" nutton to find out of how positive or negative the input text is.

**Comment by Rahul555-droid** [comment]
Please assign this to me for SWOC.

**Comment by avinashkranjan** [comment]
Sure Go ahead @Rahul555-droid

**Comment by Rahul555-droid** [comment]
Ok thanks will do it.

**Comment by avinashkranjan** [comment]
Any Updates @Rahul555-droid

**Comment by Rahul555-droid** [comment]
Hi @avinashkranjan will get this done by sunday along with others I have pending here.
I had exams that's why forgot about these

**Comment by amritakesh** [comment]
hello
i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

**Comment by osamamagdy** [comment]
hey @avinashkranjan  
I am a participant in GSSoC 2021. Can you assign this issue to me?

**Comment by Lakhankumawat** [comment]
I m ready to take it up 🙂

**Comment by santushtisharma10** [comment]
@amritakesh assigned to you

**Comment by Lakhankumawat** [comment]
Guys what if i make a PR corresponding to this issue before @amritakesh , will it get merged ? `Just for asking purposes i ain't doing it `

**Comment by santushtisharma10** [comment]
@Lakhankumawat only the assigned person can send the PR. If the assignee fails to submit within given time, only then you can be assigned.

**Comment by kaustubhgupta** [comment]
@amritakesh Updates?

**Comment by kaustubhgupta** [comment]
@amritakesh are you working on this issue?

**Comment by Lakhankumawat** [comment]
## I m ready to grab it up 
> Conditions 
- I will be using [`Pandas library`](https://pandas.pydata.org/about/)
- I will be using [`NLTK`](https://www.nltk.org/)

If mentors are good to go with that than  please let me know asap

**Comment by kaustubhgupta** [comment]
@Lakhankumawat Nope, this issue already states that you cannot use any external library

**Comment by Amit366** [comment]
@kaustubhgupta can I work??

**Comment by Amit366** [comment]
@kaustubhgupta I would like to work

**Comment by shantamsultania** [comment]
hey @kaustubhgupta can I can take this ?

**Comment by kaustubhgupta** [comment]
> hey @kaustubhgupta can I can take this?
> 
> things I will be using
> 
> 1. no external lib like nltk just simple Data Structures
> 2. thinking of using flask / create a web app in place of GUI but if Gui is required I can also do the same

You already have one pending issue. After completing that I will assign this issue to you, then you can start working on this. We don't need flask app, you can create GUI using Tkinter, Pygame or Kivymd, any library of your choice in case of GUI

**Comment by shantamsultania** [comment]
> > hey @kaustubhgupta can I can take this?
> > things I will be using
> > 
> > 1. no external lib like nltk just simple Data Structures
> > 2. thinking of using flask / create a web app in place of GUI but if Gui is required I can also do the same
> 
> You already have one pending issue. After completing that I will assign this issue to you, then you can start working on this. We don't need flask app, you can create GUI using Tkinter, Pygame or Kivymd, any library of your choice in case of GUI

cool man thanks for the update I am done with my other PR mostly will share the code for review and then start working on this one then
