### ISSUE TITLE
[Script]: Quiz Game Script

### ISSUE THREAD

**Issue by ishita-43** [avinashkranjan/Amazing-Python-Scripts#2151]
### Aim

To ask user certain set of questions and maintaining the score record.

### Details

Script will provide following features:-

- Asking user quiz questions

- Taking user input 

- Maintaining the score of each user

- Viewing the score 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by ishita-43** [comment]
Assign this issue to me.

**Comment by avinashkranjan** [comment]
Go AHead @ishita-43
