### ISSUE TITLE
[Script]: Multiplication Table Generator

### ISSUE THREAD

**Issue by nashira26** [avinashkranjan/Amazing-Python-Scripts#2173]
### Aim

Create a script that generates a multiplication table up to a specified number.

### Details

With this script, when the user runs it and enters a valid positive integer, it will generate a multiplication table up to that number.
Please assign to me under GSSoC'23.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
@nashira26 As, @Killer2-O already mentioned and you still went and created a PR. So, I'm marking this as Invalid

**Comment by nashira26** [comment]
I didn't know before so I've closed the other one. And this is the only genuine one.
