### ISSUE TITLE
Creating a spiral star using Python

### ISSUE THREAD

**Issue by Ayush7614** [avinashkranjan/Amazing-Python-Scripts#220]
# Aim

- Creating a spiral star using Python

# Details

- Spiral star made of python using python turtle module

**Comment by Ayush7614** [comment]
@avinashkranjan sir plss assign me this issue

**Comment by avinashkranjan** [comment]
Sure Go ahead But Try creating Multiple Shapes @Ayush7614

**Comment by Ayush7614** [comment]
@avinashkranjan sir plss review it #225 this is PR for the issue

**Comment by Ayush7614** [comment]
@avinashkranjan plss sir review it

**Comment by Ayush7614** [comment]
@avinashkranjan plss review it sir
