### ISSUE TITLE
Github Automation

### ISSUE THREAD

**Issue by antrikshmisri** [avinashkranjan/Amazing-Python-Scripts#223]
# Aim

- A script that allows user to automate github workflow

# Details

- This script allows user to completely automate github workflow. This script keeps track of changed files and generates a diff, then auto adds and commits(asks for a commit message) the changed files.

**Comment by antrikshmisri** [comment]
@avinashkranjan  Please assign me this issue

**Comment by avinashkranjan** [comment]
Sure Go ahead @antrikshmisri
