### ISSUE TITLE
[Feat]: Scroll to Top

### ISSUE THREAD

**Issue by Rancho2002** [avinashkranjan/Amazing-Python-Scripts#2242]
### Is your feature request related to a problem? Please describe.

In the website there is no ```back to top``` button which is not a user friendly idea. It has huge number of scripts, so if user want to scroll up, he/she have to scroll manually which is annoying. Please assign me this issue, so that I can add the functionality.

### Describe the solution you'd like.

I want to add a ```back to top``` button in the website that help user to get back to page up, automatically.

### Describe alternatives you've considered.

I have to scroll manually as a alternative which is very annoying.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @Rancho2002
