### ISSUE TITLE
Add text on image using python script

### ISSUE THREAD

**Issue by vaishnavijha** [avinashkranjan/Amazing-Python-Scripts#226]
# Aim

Usually, when we work in frontend web development we have a requirement sometimes of having text on the image and it is done by CSS. But we can easily do the same in python with few lines of code.So the aim is to have an image with text of the desired font on it

# Details

- Script will make use of a python library called pillow which is Python Imaging Library (Fork). The Python Imaging Library adds image processing capabilities to  Python interpreter.
This library provides extensive file format support, an efficient internal representation, and fairly powerful image processing capabilities. This addition of script will basically show one of the good application of pillow.

**Comment by vaishnavijha** [comment]
Can i be assigned this issue if it seems a good addition to the repository?

**Comment by avinashkranjan** [comment]
Sure @vaishnavijha .. Go ahead

**Comment by vaishnavijha** [comment]
Pull request to resolve this issue is added
