### ISSUE TITLE
[Feat]: ADD NEW PROJECT

### ISSUE THREAD

**Issue by khushimarothi** [avinashkranjan/Amazing-Python-Scripts#2271]
### Is your feature request related to a problem? Please describe.

I want to add a new python project. The project is basically a betting game so i have named it slot-machine game.

### Describe the solution you'd like.

The betting game allows the player to bet and know about the maximum bet they can place. It will predict a winner at the end.

### Describe alternatives you've considered.

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @khushimarothi
