### ISSUE TITLE
A script to delete selected pages from PDF

### ISSUE THREAD

**Issue by Rahul555-droid** [avinashkranjan/Amazing-Python-Scripts#230]
# Aim

-  A script that will delete input pages from a PDF file

# Details

- It will be a simple script using pdfrw or some other small python library and will remove the pages that the user enters as arguments from stdin.

**Comment by Rahul555-droid** [comment]
I would want to work on this issue for SWOC.
Please assign this to me :)

**Comment by avinashkranjan** [comment]
Sure Go ahead @Rahul555-droid
