### ISSUE TITLE
Script to organise out-of-order pages in a  PDF File.

### ISSUE THREAD

**Issue by Rahul555-droid** [avinashkranjan/Amazing-Python-Scripts#231]
# Aim
- At times we get a pdf that is not ordered properly but we know the pages which have are out of order and it is tough to reorder it with an Android PDF app or windows app.
This script will make it easy to reorder your pages in a PDF with just one click.

# Details

- A python script that will take an input of pages which are unordered and where these unordered pages should go Example input:-

1,2
3,1
2,3

here the 1st page in the pdf should be on the 2nd page instead and so on

and parse it into dictionary.

- Using this dictionary and a python library called 'pdfrw' I will reorder the PDF.

**Comment by Rahul555-droid** [comment]
I would want to work on this issue for SWOC in python please assign it to me!

**Comment by avinashkranjan** [comment]
Sure Go ahead @Rahul555-droid
