### ISSUE TITLE
[Script]: Convert an image to png

### ISSUE THREAD

**Issue by Tisha6661** [avinashkranjan/Amazing-Python-Scripts#2347]
### Aim

There are several images where we want to remove the background, and make it into png format, i would like to make a python script for it.

### Details

It works especially on stickers, when we want to remove the background, also so in some important documents like online signature.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by anmoltan** [comment]
Hi, I am ready to work on this, kindly assign this issue to me.

**Comment by Tisha6661** [comment]
@avinashkranjan I raised this issue, and i said i want to work on it, but you didn't assign me this, is there any issue.

**Comment by anmoltan** [comment]
hi @avinashkranjan kindly review my PR.
