### ISSUE TITLE
Dice Roll Simulator

### ISSUE THREAD

**Issue by Ayush7614** [avinashkranjan/Amazing-Python-Scripts#237]
# Aim

- Dice Roll Simulator

# Details

- The goal is to create a program that will simulate the roll of dice.

**Comment by Ayush7614** [comment]
@avinashkranjan plsss assign me this issue

**Comment by avinashkranjan** [comment]
Assigned to you  @Ayush7614

**Comment by Ayush7614** [comment]
@avinashkranjan sir #244 this is pull for this issue

**Comment by Ayush7614** [comment]
sir pkss review it
