### ISSUE TITLE
Rock, Paper & Scissors Game

### ISSUE THREAD

**Issue by Ayush7614** [avinashkranjan/Amazing-Python-Scripts#238]
# Aim

- Rock, Paper & Scissors Game

# Details

- The Goal is to create a command-line game where a user is given a chance to choose between rock, paper, and scissors and if the user wins the score is added, and at the end when the user finishes the game the score is shown to the user.

**Comment by Ayush7614** [comment]
plss assign me this issue @avinashkranjan sir

**Comment by avinashkranjan** [comment]
Assigned to you  @Ayush7614

**Comment by Ayush7614** [comment]
Okk No Problem sir @avinashkranjan
