### ISSUE TITLE
Guess The Number Game

### ISSUE THREAD

**Issue by Ayush7614** [avinashkranjan/Amazing-Python-Scripts#239]
# Aim

- Guess The Number Game

# Details

- In this game, the task is to create a script that generates a random number between a range if the user guesses the number right in three chance then user wins otherwise user loss.

**Comment by avinashkranjan** [comment]
Assigned to you  @Ayush7614

**Comment by sammy8825** [comment]
Can i work on this issue @avinashkranjan ?

**Comment by Ayush7614** [comment]
bro i am already working on the issue

**Comment by sammy8825** [comment]
Ok👍

**Comment by Ayush7614** [comment]
@avinashkranjan #257 this is pull for the this issue plss review it
