### ISSUE TITLE
bug in readme file of script-to-organise-files-according-to-their-extensions

### ISSUE THREAD

**Issue by Rahul555-droid** [avinashkranjan/Amazing-Python-Scripts#242]
**Describe the bug**
The readme file in the 

**To Reproduce**
1. Go to 'https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/script-to-organise-files-according-to-their-extensions'
2. Scroll down to the readme file
3. See error

**Expected behavior**
The images should show but they don't.

**Screenshots**

![Screenshot (120)](https://user-images.githubusercontent.com/60074958/104343443-f48b8c80-5521-11eb-81d6-4fe264a42c54.png)

The bug comes due to the use of double quotes in the readme file.
Will remove the double quotes and
Will change the absolute path to relative path now so that it will show in forked as well as main repo,

I didn't know that this feature existed my bad!

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by Rahul555-droid** [comment]
Hi @avinashkranjan

I Can send a PR right away or if someone else can edit it then that is good too.

**Comment by avinashkranjan** [comment]
I have fixed it don't worry.. @Rahul555-droid

**Comment by avinashkranjan** [comment]
Fixed it in 12f1eda

**Comment by Rahul555-droid** [comment]
Ok cool :)
