### ISSUE TITLE
Hangman Game

### ISSUE THREAD

**Issue by Ayush7614** [avinashkranjan/Amazing-Python-Scripts#245]
# Aim

- The task is to create a simple command-line hangman game.

# Details

- From Python Modules Create a hangman game

**Comment by Ayush7614** [comment]
@avinashkranjan plss review it

**Comment by avinashkranjan** [comment]
Sure Go ahead @Ayush7614

**Comment by Ayush7614** [comment]
#273 this is pull for this issue

**Comment by Ayush7614** [comment]
@avinashkranjan plss review it

**Comment by Ayush7614** [comment]
#278 this is pull for this issue plss review it

**Comment by Ayush7614** [comment]
@avinashkranjan plss review it

**Comment by Ayush7614** [comment]
@avinashkranjan sir plss review it
