### ISSUE TITLE
Word Detection using OpenCV python

### ISSUE THREAD

**Issue by hritik5102** [avinashkranjan/Amazing-Python-Scripts#247]
# Aim

- What is the objective of the Script
   To detect the words present in the document (page)

# Details

- What features will your script have
  - [x] contour ( bounding box ) over each word detected

**Comment by hritik5102** [comment]
Please assign this issue to me, for SWOC21 @avinashkranjan 
Thank you

**Comment by avinashkranjan** [comment]
Sure Go ahead @hritik5102
