### ISSUE TITLE
Tic Tac Toe using Min Max Algorithm

### ISSUE THREAD

**Issue by hritik5102** [avinashkranjan/Amazing-Python-Scripts#248]
# Aim

- What is the objective of the Script
   An agent (robot) will play a tic tac toe game with human 

# Details

- What the features will your script have
   - [x] Interactive UI 
   - [x] User friendly

**Comment by hritik5102** [comment]
Please assign this issue to me, for SWOC21 @avinashkranjan 
Thank you

**Comment by avinashkranjan** [comment]
Sure Go Ahead @hritik5102
