### ISSUE TITLE
Certificate Generator

### ISSUE THREAD

**Issue by sakshikhachane** [avinashkranjan/Amazing-Python-Scripts#249]
# Aim

- What is the objective of the Script
To generate certificate

# Details

- What features will your script have
The certificate will be generated automatically and will get downloaded in the directory after generation.

Please assign me this issue under SWOC.

**Comment by avinashkranjan** [comment]
Sure Go ahead @sakshikhachane

**Comment by achalesh27022003** [comment]
It has been 25 days guys. I can do this in 1 day or 2. Pls assign me this issue. @avinashkranjan sir.

**Comment by achalesh27022003** [comment]
Under SWoC

**Comment by avinashkranjan** [comment]
Sure Go Ahead @achalesh27022003

**Comment by achalesh27022003** [comment]
@avinashkranjan  sir this PR has been counted under SwoC na?

**Comment by avinashkranjan** [comment]
> @avinashkranjan sir this PR has been counted under SwoC na?

Yes
