### ISSUE TITLE
Schedule a python code to run 

### ISSUE THREAD

**Issue by vaishnavijha** [avinashkranjan/Amazing-Python-Scripts#251]
# Aim

- this script will help in scheduling the python script to run at the desired time as decided by the user. Usually this will be effective if a certain action has to be performed at a given time, for example, we have to display lunch hour on screen at 1 pm so if we schedule to run that script at 1 pm it will be automatically handled at that particular time.

# Details

- With the help of a library in python known as DateTime i will try scheduling  tasks or scripts to be run at a particular time of a day.Actually Datetime basically gives information about current date as well as time so we can make some modification to run a script at a particular time of day once we get that time.
-

**Comment by vaishnavijha** [comment]
Can I be assigned this issue if it seems a good addition to the repo.

**Comment by avinashkranjan** [comment]
Sure Go ahead @vaishnavijha
