### ISSUE TITLE
Get any website IP Address Using Python

### ISSUE THREAD

**Issue by Ayush7614** [avinashkranjan/Amazing-Python-Scripts#258]
# Aim

Get any website IP Address Using Python

# Details

Get any website IP Address Using Python Module

**Comment by avinashkranjan** [comment]
Go ahead..

**Comment by NChechulin** [comment]
This can be done in literally two lines of code:
```python
import socket
ip = socket.gethostbyname('example.com')
```

Other scripts seem a little bit more complex for me, therefore, they might be more useful,
Don't want to be toxic in any sense, but I think that if the solution can be googled within a few seconds then there's no need to include it in the repo.
