### ISSUE TITLE
Data Visualization Using Python

### ISSUE THREAD

**Issue by Ayush7614** [avinashkranjan/Amazing-Python-Scripts#259]
# Aim

Data Visualization Using Python

# Details

Data visualization in very easy in python as python uses Matlab to make a matplotlib So the script is for Data Visualization Using Python module

**Comment by avinashkranjan** [comment]
Go ahead..

**Comment by Ayush7614** [comment]
#301 this is pull for this issue @avinashkranjan sir plss review it
