### ISSUE TITLE
Add code quality Actions

### ISSUE THREAD

**Issue by NChechulin** [avinashkranjan/Amazing-Python-Scripts#263]
**Is your feature request related to a problem? Please describe.**
Code in the projects could be better,

**Describe the solution you'd like**
Add flake8 Github Action which will help new contributors to achieve better code.
Also, we could start gradually improving the quality of older projects.
The first step could be formatting with `black`.

**Comment by avinashkranjan** [comment]
Would You like to work on it @NChechulin

**Comment by vybhav72954** [comment]
@avinashkranjan If no one is up for this, consider assigning me

**Comment by avinashkranjan** [comment]
Sure @vybhav72954 Go ahead

**Comment by vybhav72954** [comment]
@avinashkranjan Just a small question, I have worked a lot on actions for code quality, I can make 4 actions

- pylnint
- black
- issort
- flake8

All 4 together might be an overkill, but we can have that as well.

As OP said, `black` is a good tool for basic styling.

According to me `pyLint` is the best bet as it is very friendly and customizable.

**Comment by avinashkranjan** [comment]
Then Go ahead with `pyLint`
