### ISSUE TITLE
Unify project naming

### ISSUE THREAD

**Issue by NChechulin** [avinashkranjan/Amazing-Python-Scripts#264]
**Is your feature request related to a problem? Please describe.**
Projects are named in different styles: `some_project`, `some-project`, `some project`, and `SomeProject`.
I believe it would be better if we unified the naming scheme.

**Describe the solution you'd like**
Manually rename all of the projects using `This style`.

**Comment by avinashkranjan** [comment]
Would You like to work on it @NChechulin ?

**Comment by NChechulin** [comment]
@avinashkranjan  Yes, sure. Should I stick to `This style` or to some other?

**Comment by avinashkranjan** [comment]
Change it to `This-Style` cause some terminals has issue changing directories when there's some between the names i.e `This Style` So, `This-Style` would be a better alternative.

**Comment by NChechulin** [comment]
Just sent a pull request (#267)
