### ISSUE TITLE
random name picker

### ISSUE THREAD

**Issue by AshirMehmood** [avinashkranjan/Amazing-Python-Scripts#2677]
### Aim

to pick random input from a list of inputs, such as names or numbers

### Details

random input picker

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by ruchspatil** [comment]
### Random name picker

**Aim**
_The Python Script should:_

- Generate random characters and numbers that will be included in the unique name.
- Prints the randomly generated unique names.


**Details**
Random Name Picker is an easy-to-use online tool to draw a random name from a list of names.  Python will be required for this project. This project allows you to randomly select a name.

**Record**

- I agree to follow this project's Code of Conduct
-  I'm a GSSoC'23 contributor
-  I want to work on this issue

**Comment by AshirMehmood** [comment]
I have already written them, but I am unable to push as when pulling it
says u able to find Lyrics Finder /scripts.py

**Comment by AshirMehmood** [comment]
I opened issue 2677 for myself and worked on it,I dont why it is not
assigned to me and someone else is making pr?
May I know the reason

**Comment by Evetfernandes** [comment]
Please assign this issue to me

**Comment by avinashkranjan** [comment]
We Already have this script @Evetfernandes , Please find some other script
