### ISSUE TITLE
Binary Calculator (GUI)

### ISSUE THREAD

**Issue by abirbhattacharya82** [avinashkranjan/Amazing-Python-Scripts#27]
# Aim

- A Calculator to perform Binary Calculations.
# Details

- A Binary calculator should be create using Tkinter and GUI Toolkit in python which does the following operations
1) Addition
2) Subtraction
3) Multiplication
4) Division

**Comment by abirbhattacharya82** [comment]
I can work on this Issue. Can you kindly assign it to me?

**Comment by avinashkranjan** [comment]
Assigned to you..You can go ahead and work on it..
