### ISSUE TITLE
Dominant Color Detection From Image 

### ISSUE THREAD

**Issue by aryangulati** [avinashkranjan/Amazing-Python-Scripts#274]
# Aim
**Analysing of Dominant Colour in Image** 

- What is the objective of the Script
Finding Dominant Colour: Finding Colour with K-means and giving appropriate colours to the pixel/data points of the image.

# Details
- Good Segmentation(Colour Extraction): Given an image in generic viewpoint, we wish to produce the best possible segmentation, by this we mean that most people would choose this segmentation if asked to make one, and it would make a good precursor for object recognition.
- Analysis of different K in K-means: Different k’s can give totally different results, and usually, there is one K which is consistent with the data points, the actual K.

**Comment by avinashkranjan** [comment]
Go ahead @aryangulati
