### ISSUE TITLE
The stale GitHub action is not working properly

### ISSUE THREAD

**Issue by vybhav72954** [avinashkranjan/Amazing-Python-Scripts#283]
**Describe the bug**
While i was testing my NewGithub action in #282 I noticed that `stale` action is not working properly.

**To Reproduce**
1. Go to `Actions` Dashboard
2. Click on `stale` action
3. See error

**Expected behavior**
There should not be any error, while the action should mark PRs as stale.

**Desktop (please complete the following information):**
 - OS: Windows [Bug is cross Platfrom]
 - Browser: Chrome

**Additional context**
Though I can't guarantee as of now, I believe it would be better to completely get rid of this action as there are better available options. I will look into it and post more if needed in the comments

**Comment by vybhav72954** [comment]
Mentors, it would be great if you can assign me. Kindly go through the _Additional Context_ and share your views as well

**Comment by avinashkranjan** [comment]
I don't see any errors, But if you have any better suggestions. Go ahead..

**Comment by vybhav72954** [comment]
@avinashkranjan If thtas the case, i will recheck the action from my side. If its working properly, I will close this issue
