### ISSUE TITLE
Adding Contributors List to the Website

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#290]
# Aim

- Since the Landing Page of the Website is Ready, Add the Contributors Sections and People who have contributed to the Repo

**Comment by NChechulin** [comment]
There's a Github bot for updating the list of contributors.
In bot's [config](https://allcontributors.org/docs/en/bot/configuration) one may specify a list of files where the bot will place HTML with contributors.

I believe we could use the bot to generate HTML and then just it on a website.
I think that we can't avoid "reading" this repo if we want the projects list to be generated automatically.

P.S It's quite late now and I'm sleepy, so my message might be unclear.
I apologize in advance.
Feel free to ask questions.

**Comment by anirudhsai20** [comment]
Hi @avinashkranjan. Can you please assign me this issue to me under SWOC?

**Comment by avinashkranjan** [comment]
Sure Go Ahead @anirudhsai20

**Comment by subhangi2731** [comment]
can you assign this to me?

**Comment by SurbhiRathi23** [comment]
Can I make the contributors list page for this website. I will use HTML,bootstrap,CSS, js. Please assign this to me.

**Comment by avinashkranjan** [comment]
@subhangi2731 Go Ahead..
@SurbhiRathi23 Issues are First Come First Serve So, It is already assigned..

**Comment by kaustubhgupta** [comment]
@SurbhiRathi23 you want to work on this issue?

**Comment by SurbhiRathi23** [comment]
@kaustubhgupta I am already working on #465 issue .

**Comment by kagritu** [comment]
I would like to work on this, as a part of GSSOC'21, so please assign that to me.

**Comment by kaustubhgupta** [comment]
@kagritu assigned to you

**Comment by kagritu** [comment]
Thank you

**Comment by kaustubhgupta** [comment]
@kagritu updates?

**Comment by kagritu** [comment]
Still working on it. I will update you soon

**Comment by kaustubhgupta** [comment]
Okay!
