### ISSUE TITLE
Snake Game in Python

### ISSUE THREAD

**Issue by ShristiJalan** [avinashkranjan/Amazing-Python-Scripts#295]
# AIM 

- Create a Snake Game using Python

# Details 

- Game Over when Snake hits the boundaries.
- Adding the Food.
- Increasing the Length of the Snake as Snake Eats the food
- Display the Score.

**Comment by CharvyJain** [comment]
@avinashkranjan I want to work on this. Can I?

**Comment by avinashkranjan** [comment]
Sure go ahead

**Comment by CharvyJain** [comment]
@avinashkranjan Please check PR #306
