### ISSUE TITLE
Email validation script using SMTP library and dnspython

### ISSUE THREAD

**Issue by Rahul555-droid** [avinashkranjan/Amazing-Python-Scripts#297]
# Aim

- A script that will validate whether an email is valid or not.

# Details

- It will use dnspython and smtp(part of standard library) libraries of python.
- It will first check the syntax of the Email id.
- if it passes the first check Then check for the MX records of the domain of the email id (like gmail.com) and see whether it is able to send mails or not.
- if it passes the second check Then it will use the smtp library to check whether the emails can indeed be sent to it or not. It won't send any message or notify the user about anything when this step executes.
SMTP commands issued are: HELO, MAIL FROM and RCPT TO.

Please assign this to me for SWOC.

thank you.

**Comment by Rahul555-droid** [comment]
Please assign this to me for SWOC.

thank you.

**Comment by avinashkranjan** [comment]
Sure Go Ahead @Rahul555-droid

**Comment by Rahul555-droid** [comment]
sorry @avinashkranjan for the delay had some stuff. Will write it in a day or so!

**Comment by saaalik** [comment]
I am interested in this project, would love to work on it. Can you assign it to me?
(gssoc participant)

**Comment by avinashkranjan** [comment]
Go Ahead @saaalik

**Comment by saaalik** [comment]
I have completed the script, documenting what I did, along with requirements and test cases
