### ISSUE TITLE
[Bug]: Lyrics Finder directory issue while cloning repo

### ISSUE THREAD

**Issue by singodiyashubham87** [avinashkranjan/Amazing-Python-Scripts#3070]
### Describe the bug

When I was trying to clone the repository to resolve the issues I've created before, I encountered an error regarding the directory name "Lyrics Finder" I want to update the name of the directory to resolve the issue.

### Expected behavior

The cloning should be done without errors

### Screenshots

![image](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/93720428/f59c3ddc-e384-4976-93b8-33232490d555)

### Device?

Desktop

### Which OS are affected?

Linux

### Enter the version of your web browser

1.96 Latest one

### Which browsers are affected?

Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @singodiyashubham87
