### ISSUE TITLE
Internshala Scraper

### ISSUE THREAD

**Issue by Ayush7614** [avinashkranjan/Amazing-Python-Scripts#310]
**Is your feature request related to a problem? Please describe.**

Internshala Scraper

**Describe the solution you'd like**

Select field, select number of pages and the script saves internships to a csv.

**Comment by Ayush7614** [comment]
Assign me this issue

**Comment by avinashkranjan** [comment]
Sure Go Ahead... @Ayush7614

**Comment by Ayush7614** [comment]
For this issue pull is #315

**Comment by Ayush7614** [comment]
Now plss review it @avinashkranjan sir
