### ISSUE TITLE
IMDB_scrapper

### ISSUE THREAD

**Issue by Ayush7614** [avinashkranjan/Amazing-Python-Scripts#311]
**Is your feature request related to a problem? Please describe.**

IMDB_scrapper

**Describe the solution you'd like**

This script takes a movie name as input and returns the information about that movie.

**Comment by avinashkranjan** [comment]
Sure Go ahead..

**Comment by Ayush7614** [comment]
#325 this is pull for this issue plss review it @avinashkranjan sir

**Comment by priyanshu20** [comment]
Hey @avinashkranjan can I take this up as a GSSOC '21 participant?

**Comment by avinashkranjan** [comment]
Sure Assigned to you @priyanshu20
