### ISSUE TITLE
To add prime cheaker

### ISSUE THREAD

**Issue by atugharajohn** [avinashkranjan/Amazing-Python-Scripts#3153]
### Aim

fdfd

### Details

To add an new script named as prime cheaker. This Python script checks if a given number is prime or not. It takes an integer as input and returns True if the number is prime, and False otherwise.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Script already present in the repo..
