### ISSUE TITLE
Video to Audio Converter GUI

### ISSUE THREAD

**Issue by Ayush7614** [avinashkranjan/Amazing-Python-Scripts#321]
# Aim

- Video to Audio Converter GUI

# Details

-  Converts any type of video file into an audio file. 
- It supports the various audio and video formats for the conversion.
- Provides a GUI [Graphical User Interface] for convenience

**Comment by Ayush7614** [comment]
This issue under swoc plss assign me

**Comment by avinashkranjan** [comment]
Sure Go Ahead.. @Ayush7614

**Comment by kshittijagrawal** [comment]
Hey there!
I'd like to contribute to the project. I want to address and fix this issue. My implementation will be in python with a clean code and documentation. Kindly provide me with this issue.
I'm also a GSSOC'21 participant.

**Comment by avinashkranjan** [comment]
Go Ahead @kshittijagrawal Assigned to you

**Comment by kshittijagrawal** [comment]
> Go Ahead @kshittijagrawal Assigned to you

hey @avinashkranjan !
I'm not able to open this issue although been assigned to it. Can you help me out here?

**Comment by avinashkranjan** [comment]
> > Go Ahead @kshittijagrawal Assigned to you
> 
> hey @avinashkranjan !
> I'm not able to open this issue although been assigned to it. Can you help me out here?

Can you explain more clearly?

**Comment by avinashkranjan** [comment]
Script will be fine..But If you want to push GUI you can do that too..That's your call.. @kshittijagrawal

**Comment by avinashkranjan** [comment]
Hey @kshittijagrawal Looks Like there was already an issue for the Same..Kindly Push GUI for your Issue...Since we already received an PR for CLI....

**Comment by amrzaki2000** [comment]
@kaustubhgupta Hello, Can I work on this for my GSSoC participation ?

**Comment by kaustubhgupta** [comment]
@amrzaki2000 okay, assigned to you!

**Comment by amrzaki2000** [comment]
@kaustubhgupta @avinashkranjan
Hello,
I'm so sorry for late pull request.
My spring semester began last Sunday and I was so busy and distracted. I'm sorry again.
Thank you

**Comment by a7medayman6** [comment]
Hello, 
I'd like to work on this issue if it still open, I'm a GSSOC'21 participant.
Also can I start with a cmd script and push the code then work on the GUI if I could ?

**Comment by kaustubhgupta** [comment]
Hi @a7medayman6,
This issue is already assigned, the particular PR was made and approved too. Unfortunately, the CLI version is also implemented a few weeks ago.

**Comment by a7medayman6** [comment]
> Hi @a7medayman6,
> This issue is already assigned, the particular PR was made and approved too. Unfortunately, the CLI version is also implemented a few weeks ago.

@kaustubhgupta  Okay thank you.
