### ISSUE TITLE
Google News Scrapper

### ISSUE THREAD

**Issue by Ayush7614** [avinashkranjan/Amazing-Python-Scripts#322]
# Aim

- Google News Scrapper

# Desciption 

- A python Automation script that helps to scrape the google news articles. The key feature of this script is that user can able to scrape the as many number of articles by giving the number of articles count. This script will generate the excel file of all the scraped articles with links with their respective titles.

**Comment by Ayush7614** [comment]
This issue is under Swoc plss assign me

**Comment by avinashkranjan** [comment]
Sure Go ahead @Ayush7614

**Comment by Ayush7614** [comment]
#333 this is pull for this issue plss review it @avinashkranjan sir
