### ISSUE TITLE
Covid19 Dectection using chest X-Ray

### ISSUE THREAD

**Issue by saiharsha-22** [avinashkranjan/Amazing-Python-Scripts#326]
@avinashkranjan I would work on this issue. I am a participant in SWOC 2021

# Aim

- The system will detect whether the person is having a covid 19 or not.

# Details

- I will train the model first with the machine learning algorithms by collected data sets. 
- After that, I will test how much accuracy is being there. 
- And I will include this whole system using Tkinter GUI. so that if a user just imports an x-Ray image,  we can check whether suffering from the covid -19 or not.

This script helps the students who are trying to learn or explore machine learning algorithms in their studies.

**Comment by avinashkranjan** [comment]
Go Ahead @saiharsha-22

**Comment by saiharsha-22** [comment]
@avinashkranjan thank you for assising the issue I will start working on it.
