### ISSUE TITLE
Message Spam detection

### ISSUE THREAD

**Issue by saiharsha-22** [avinashkranjan/Amazing-Python-Scripts#327]
@avinashkranjan I would like to work on this issue, I am a participant in SWOC 2021. 

# Aim

- Detecting whether the obtained message is spam or not spam.

# Details

- I will be using naive-Baye's machine learning algorithm. To build this model.
- I will first collect the data set, then train the model and test the model
- Then I will just import a simple text or a message and check whether the message is spam or non-spam.

This script will help the students who are exploring machine learning algorithms.

**Comment by avinashkranjan** [comment]
Sure Go ahead @saiharsha-22

**Comment by saiharsha-22** [comment]
@avinashkranjan thank you for assising the issue I will start working on it

**Comment by Nkap23** [comment]
Hello, I would love to work on this. 

My approach would be:
- Find a relevant dataset.
- Examining, analyzing, and visualizing the data.
- Data Cleaning & Feature Extraction. 
- Data Preprocessing (lemmentizing, bag of words/tdidf)
- Model training using sklearn algorithms 
- Model selection based on test results.

**Comment by avinashkranjan** [comment]
Go Ahead.. Assigned to you @Nkap23 Looking forward to your script..

**Comment by kaustubhgupta** [comment]
@Nkap23 Updates on this?

**Comment by Nkap23** [comment]
> @Nkap23 Updates on this?

Yes sir, I am working on it. 60% done. Will finish it by today or tomorrow.

**Comment by Nkap23** [comment]
Sorry for the late PR. I have finally finished it (had some urgent clg work, so this got delayed). I will be making a PR soon :)
