### ISSUE TITLE
A script for Auto Backup of files

### ISSUE THREAD

**Issue by vybhav72954** [avinashkranjan/Amazing-Python-Scripts#329]
# Aim

- A python script that can automatically backup files. Using `BackuPy` the solution can be achieved, but I have a further suggestion, as explained in detail.

# Details

- Python modules provide a means of backing up files according to the size (which files are backed up are dependent on size), this is a must-have feature, *BUT* what we actually lack is multithreading, SO a automatic backup system, sped up using multithreading, and also file compression in order to reduce the file size is what am aiming for. MultiTasking and Compression are the key features, without those 2 features the script is pretty much standard.

**Comment by avinashkranjan** [comment]
Sure Go ahead.. @vybhav72954 ..
