### ISSUE TITLE
A pretrained model for autonomous traffic sign detection

### ISSUE THREAD

**Issue by vybhav72954** [avinashkranjan/Amazing-Python-Scripts#331]
# Aim

- With the growing popularity in DL/ML, I believe having some Deep Learning projects would be a good idea.

# Details

- I propose a pre-trained model, of traffic sign detection, simple enough so that even a beginner can understand, but flexible enough so that a hobbyist can easily optimize the hyperplanes for a more structured prediction and detection

**Comment by vybhav72954** [comment]
@avinashkranjan Can you assign this and #329  to me

**Comment by avinashkranjan** [comment]
Sounds Great..
Assigned to you.. @vybhav72954
