### ISSUE TITLE
PDF Encryption

### ISSUE THREAD

**Issue by AmeyaJain-25** [avinashkranjan/Amazing-Python-Scripts#339]
# Aim

- A Python script for encrypting a PDF by some password using PyPDF2.

# Details

- The main feature would be encrypting the PDF with a password. Another feature is that it can have an admin password and a company or organization password for people working in company's to access private documents. 

- Please assign me this issue. I would like to work on this.

**Comment by avinashkranjan** [comment]
Sure Go Ahead @AmeyaJain-25

**Comment by AmeyaJain-25** [comment]
Thanks

**Comment by AmeyaJain-25** [comment]
I have made the PR #343 
Please review it.
