### ISSUE TITLE
Voice Assistant Script

### ISSUE THREAD

**Issue by saiharsha-22** [avinashkranjan/Amazing-Python-Scripts#345]
# Aim

- Voice Assistant

# Details

- It is a beginner-friendly script in python, where they can learn about the if-else conditions in python and different libraries.
- Libraries: 
   -  speech_recognition 
   - playsound
   - gTTS
   - pyttsx3

- First, we will keep few words in if-else and the system will see the cases accordingly and respond
- Example:  Hey bot can you share my ppts, 
- or small coversations

**Comment by saiharsha-22** [comment]
@avinashkranjan I would like to work on this issue, can you assign this issue to me.

**Comment by avinashkranjan** [comment]
Sure Go Ahead @saiharsha-22

**Comment by saiharsha-22** [comment]
@avinashkranjan I will start working on it. Thanks for assigning the issue.
