### ISSUE TITLE
Generate AudioBook from PDF file using Python

### ISSUE THREAD

**Issue by achalesh27022003** [avinashkranjan/Amazing-Python-Scripts#346]
# Aim
To make a audio book of any pdf using python.
- What is the objective of the Script
 The objective of script is to teach how one can generate text to speech using Python and its libraries.
# Details
- What the features will your script have
Will use pyttsx3 , PyPDF2 and tkinter libraries' modules and methods in the script.

**Comment by achalesh27022003** [comment]
@avinashkranjan  sir pls assign me this issue. I am under SWoC participant.

**Comment by avinashkranjan** [comment]
We already have a Script the Same [HERE](https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/PDF-To-Audio). How's this one different?
