### ISSUE TITLE
Script doing away with the complexities of string matching and regex matching in urls

### ISSUE THREAD

**Issue by vaishnavijha** [avinashkranjan/Amazing-Python-Scripts#348]
# Aim

This python script will help in regex matching that can be used by compilers or string matching .

# Details

Many times we want to have a search feature in our program.When one has a list of strings and one wants to search a term or a regex against all of them ,this script will help us to extract the most relevant ones with similarities.

**Comment by vaishnavijha** [comment]
Can I be assigned this issue to work on if it seems a good addition to the repo?

**Comment by avinashkranjan** [comment]
Sure @vaishnavijha Go ahead

**Comment by vaishnavijha** [comment]
Created pull request for this issue
