### ISSUE TITLE
Reduce Repo SIze, by removing Images from the Codebase

### ISSUE THREAD

**Issue by vybhav72954** [avinashkranjan/Amazing-Python-Scripts#349]
**Is your feature request related to a problem? Please describe.**
The `README` have Images, like screenshots, test cases n stuff. Seems like a good Idea, but well the Repo Size cause of them are increasing like crazy. Which am sure no one can deny, is a problem in itself.

**Describe the solution you'd like**
Using a platform like Imgur for hosting images, and pasting the links in place of images in the codebase.

**Describe alternatives you've considered**
There are multiple image hosting platforms that can be used.

**Additional context**
We will have to additionally change the Contributing Guidelines.

**Warning**
Am aware there is a website for this REPO as well, although I don't know whether it's static or dynamic. Whatever be the case, changing links might break the website if the links are hardcoded. One might have to deal with that, if the elements are flexible enough, this won't be a problem, or if the website is dynamic and not generated using GitHub Readmes, it would never be n issue. Never less I suggest we should remove the images as a priority, as in long run, Repo size can touch like 250+ MBs, which is never a good idea.

**Comment by avinashkranjan** [comment]
I was thinking for the Same...If anyone would like to work on that it would be great..

And About the website... It's Work in Progress [Static] But I'm thinking to use static generator like [Hugo](https://gohugo.io/) The building process could be automated with GH Actions and the website could be hosted on GH Pages. I believe the only piece of effort would be writing a python/bash script that takes project names and copies README files from each project. So, I'm still looking into that... Any help would be appreciated..

**Comment by vybhav72954** [comment]
@avinashkranjan I think i can help with the Photos

I am not good with Static pages, Dynamic websites are something which I can help with, but right now I have too much on my plate.

I can sort the images though. Kindly assign me

**Comment by avinashkranjan** [comment]
Sure Go Ahead @vybhav72954

**Comment by vybhav72954** [comment]
@avinashkranjan I was a bit busy with some stuff, so sorry for the delay, i will get all my issues sorted asap now

**Comment by avinashkranjan** [comment]
No Issues @vybhav72954
