### ISSUE TITLE
Add drawing app script

### ISSUE THREAD

**Issue by yashasvimisra2798** [avinashkranjan/Amazing-Python-Scripts#35]
**Drawing App using OpenCV**
    
   **Aim**
   Create a basic Python script used for making a drawing app using OpenCV

   **Detail**
    On calling the file on the command line a window opens where you can draw anything.

**Comment by yashasvimisra2798** [comment]
Hello, I am a CSE prefinal year student, I would like to work on this issue.

**Comment by avinashkranjan** [comment]
Assigned to you..Go ahead..

**Comment by yashasvimisra2798** [comment]
thank you

**Comment by avinashkranjan** [comment]
@yashasvimisra2798 When I can expect the PR?
