### ISSUE TITLE
Auto Wi-Fi connector

### ISSUE THREAD

**Issue by AmeyaJain-25** [avinashkranjan/Amazing-Python-Scripts#350]
# Aim

- The script would be connecting to the Wi-Fi automatically.

# Details

- When the user will run the script, the user will be shown the available network out of the saved networks. User can choose the network they want to connect and then the script will automatically connect to the network provided by the user.

I would like to do this task under SWoC
Please assign this to me.

**Comment by avinashkranjan** [comment]
Hey @AmeyaJain-25 How will this be helpful, what you're suggesting can be easily done for Taskbar in windows.. But If you're purposing else...Please elaborate ..

**Comment by avinashkranjan** [comment]
I'll Close the issue If I don't hear back from you in next 24hrs.
