### ISSUE TITLE
Distance calculating app.

### ISSUE THREAD

**Issue by pritamp17** [avinashkranjan/Amazing-Python-Scripts#351]
Is your feature request related to a problem? Please describe.
An app that can show the distance between your current position(located using user's current IP) and user searched position on Map.

Additional context.
This app will have a frontend too, to show searched position on the map.

**Comment by pritamp17** [comment]
please assign this to me under swoc.

**Comment by avinashkranjan** [comment]
Sure Go ahead @pritamp17
