### ISSUE TITLE
QR Code Generator

### ISSUE THREAD

**Issue by CharvyJain** [avinashkranjan/Amazing-Python-Scripts#352]
# AIM
This Script will help us to convert Convert weight in **Kgs** to **Gram, Pounds and Ounce.**

## Details
It will be implemented using tkinter.

**Comment by CharvyJain** [comment]
Can you assign me this under SWOC ?

**Comment by avinashkranjan** [comment]
You can Easily find them in any Calculator or Google it..It won't be of any use..Do you suggest something else? Do tell

**Comment by CharvyJain** [comment]
How about QR Code Generator using python ?

**Comment by avinashkranjan** [comment]
That Sounds Goods..Change the Issue Title and I'll Assign it to you..

**Comment by avinashkranjan** [comment]
Go Ahead @CharvyJain

**Comment by CharvyJain** [comment]
Made PR. #365 365
