### ISSUE TITLE
Port Scanning

### ISSUE THREAD

**Issue by mafiaguy** [avinashkranjan/Amazing-Python-Scripts#353]
# Aim

- A simple python scripting that help you perform port scanning

# Details

- This script tells you which port in a particular IP is open or not

**Comment by avinashkranjan** [comment]
Hey, @mafiaguy We already have a script of that kind [Here](https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Network-Scanner). How's your Script different from this?

**Comment by mafiaguy** [comment]
Hey @avinashkranjan the script you have listed showcases the list of ip address in a network( as mentioned in the readme of the script) . Whereas the issue I hve create is for a port scanner. This is a script which scans a particular ip address and checks for open port.

**Comment by avinashkranjan** [comment]
Okaey Then, Go ahead @mafiaguy Assigned to you..

**Comment by mafiaguy** [comment]
Made Pr #357

**Comment by mafiaguy** [comment]
#368
