### ISSUE TITLE
Web scraping script

### ISSUE THREAD

**Issue by yashasvimisra2798** [avinashkranjan/Amazing-Python-Scripts#36]
**Aim**
 Create a python script used for web scraping

 **Details**
  To collect data from a website, it requires to web scrape it. Taking a webpage as an example write a python script to scrape it.

**Comment by yashasvimisra2798** [comment]
Hello, I would like to work on this issue, please assign this to me.

**Comment by avinashkranjan** [comment]
Assigned this to you as well..Go ahead

**Comment by yashasvimisra2798** [comment]
thanks

**Comment by yashasvimisra2798** [comment]
I'll create the PR by tomorrow.
