### ISSUE TITLE
Creation of website blocker

### ISSUE THREAD

**Issue by Sloth-Panda** [avinashkranjan/Amazing-Python-Scripts#360]
# Aim

- What is the objective of the Script
The scripts will block websites that the user wants. Basically there will be some files that will be running in the background of the system and preventing these sites to work.
# Details

- What the features will your script have
I will be implementing it in python using datetime library

**Comment by Sloth-Panda** [comment]
@avinashkranjan will like to work on this as part of swoc

**Comment by avinashkranjan** [comment]
Sure go Ahead @Sloth-Panda
