### ISSUE TITLE
A Lyrics Generator, using an API

### ISSUE THREAD

**Issue by vybhav72954** [avinashkranjan/Amazing-Python-Scripts#367]
# Aim

- While working on a music recommendation system, I encountered a basic problem, how to generate lyrics for NLP 😞 

# Details

- A script which can generate lyric, using Genius API

**Comment by avinashkranjan** [comment]
Do you want to work on this? @vybhav72954

**Comment by vybhav72954** [comment]
Yes please, but am out of station for a few days, so i would solve this by Wednesday at best.
