### ISSUE TITLE
creation of web browser

### ISSUE THREAD

**Issue by Sloth-Panda** [avinashkranjan/Amazing-Python-Scripts#371]
# Aim

- What is the objective of the Script
- The objective of the script is to build a low functionality web browser

# Details
- What the features will your script have
- By this script we will be having some basic functionality of the web browser like searching the web

**Comment by Sloth-Panda** [comment]
@avinashkranjan would like to make this as part of swoc

**Comment by avinashkranjan** [comment]
Sure @Sloth-Panda Go ahead...
