### ISSUE TITLE
Instagram video/image downloader

### ISSUE THREAD

**Issue by Sloth-Panda** [avinashkranjan/Amazing-Python-Scripts#383]
# Aim

- What is the objective of the Script

The aim of this script is to download instagram images/videos from public accounts

# Details

- What the features will your script have

It wont be requiring any access token to download those images/videos

**Comment by Sloth-Panda** [comment]
can I work on this @avinashkranjan

**Comment by avinashkranjan** [comment]
Sure Go Ahead @Sloth-Panda
