### ISSUE TITLE
Improvement in Github Automation Script

### ISSUE THREAD

**Issue by antrikshmisri** [avinashkranjan/Amazing-Python-Scripts#386]
**Is your feature request related to a problem? Please describe.**
These are some features for my script [Github Automation](https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Github-Automation):-

1. Log changed file along with its respec. diff in form of an object into a json file
2. Remove respective object of the changed file from json that has been committed
3. Auto perform git commands on all files present in json on script start up
4. Extract all utility functions to `utils.py`
5. Add colors to print statement by using escape sequences

**Describe the solution you'd like**
I have already implemented these changes , will make a PR soon.

**Describe alternatives you've considered**
I have already implemented these changes , will make a PR soon.

**Comment by avinashkranjan** [comment]
Looking forward to the PR
