### ISSUE TITLE
Distance Calculating GUI

### ISSUE THREAD

**Issue by Aayush-hub** [avinashkranjan/Amazing-Python-Scripts#391]
# Aim

- GUI app which can calculate distance between two geolocations in kilometers.

# Details

- It will have a a TK GUI which will ask user to enter starting and ending locations and will show distance between them in result.

**Comment by Aayush-hub** [comment]
@avinashkranjan Can I work on this script?

**Comment by avinashkranjan** [comment]
Hey @Aayush-hub We already have a Script for the Same [Here](https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/380), If there's some changes kindly mention else close the issue

**Comment by Aayush-hub** [comment]
@avinashkranjan I can make a GUI app for distance calculation.

**Comment by avinashkranjan** [comment]
Sure, Go Ahead Then...
