### ISSUE TITLE
Countdown_clock_and_Timer

### ISSUE THREAD

**Issue by Ayush7614** [avinashkranjan/Amazing-Python-Scripts#396]
# Aim

- Countdown_clock_and_Timer

# Details

- A simple timer that can be used to track runtime. The purpose of this is to provide a simple, and standard, way of tracking runtime.

**Comment by Ayush7614** [comment]
@avinashkranjan sir plss assign me this issue under crosswoc

**Comment by avinashkranjan** [comment]
@Ayush7614 I don't think this Project is part of Cross WoC

**Comment by Ayush7614** [comment]
Sorry sir by mistake I write crosswoc plss assign me under Swoc

**Comment by avinashkranjan** [comment]
Sure Go Ahead @Ayush7614

**Comment by Ayush7614** [comment]
#400 this is pull for this issue
