### ISSUE TITLE
Insta-Auto Login

### ISSUE THREAD

**Issue by Aayush-hub** [avinashkranjan/Amazing-Python-Scripts#398]
# Aim

- Loging in to instagram automation.

# Details

- Automation script using selenium to auto-login to instagram.

**Comment by Aayush-hub** [comment]
@avinashkranjan as the repo contains script for auto login to facebook, I can add script to auto login to instagram. Can you please assign me this?

**Comment by avinashkranjan** [comment]
Sure Go Ahead.. @Aayush-hub
