### ISSUE TITLE
Github Bomb Issues

### ISSUE THREAD

**Issue by Ayush7614** [avinashkranjan/Amazing-Python-Scripts#405]
# Aim

- Github Bomb Issues

# Details

- This python script bombs specified number of issues on a Github Repository.

**Comment by Ayush7614** [comment]
@avinashkranjan sir plss assign me this issue under swoc

**Comment by avinashkranjan** [comment]
Go ahead @Ayush7614

**Comment by Ayush7614** [comment]
#415 this is pull for this issue
