### ISSUE TITLE
Get Phone Number Information using Python

### ISSUE THREAD

**Issue by Sloth-Panda** [avinashkranjan/Amazing-Python-Scripts#406]
# Aim

- What is the objective of the Script

using this python script the phone number's country of origin and the service provider can be known

# Details

- What the features will your script have

using phonenumbers python library, this script will be able to get the country of origin and the  service provider of a phonenumber.

like - India, JIO

**Comment by Sloth-Panda** [comment]
@avinashkranjan Can I work on this issue?

**Comment by avinashkranjan** [comment]
Sure Go ahead @Sloth-Panda
