### ISSUE TITLE
Duplicate Files finder using Hashing.

### ISSUE THREAD

**Issue by vybhav72954** [avinashkranjan/Amazing-Python-Scripts#413]
# Aim

- A script that can find duplicates of a file using its hash value. Then can identify if the files are actually duplicates or not by going through the contents, and then additionally provides a means to delete the duplicate file while keeping the original intact.

# Details

- Find the hash value.
- Find duplicates of files.
- Check the content.
- Delete the Duplicates.

**Comment by avinashkranjan** [comment]
Go Ahead @vybhav72954
