### ISSUE TITLE
A TextRank document summarizer.

### ISSUE THREAD

**Issue by vybhav72954** [avinashkranjan/Amazing-Python-Scripts#414]
# Aim

- While we have a LexRank document summarized in the Repo [here]. Lex Rank can be an overkill for small documents, where TextRank Algorithms using `stopwords` is a more optimized method. 

# Details

- The script we have is a Lex Approach.
- Lex Approach is the most used algorithm for summarization.
- While the Text Rank approach is more complex to understand compared to Lex, it is way faster for a computer to implement.
- Hence for smaller documents that don't have sophisticated words, Text Rank is a way better approach.

**Comment by vybhav72954** [comment]
Kindly assign both #413 and this to me.

**Comment by avinashkranjan** [comment]
Go Ahead @vybhav72954
