### ISSUE TITLE
Redundant .gitignores and other files which should be in the root

### ISSUE THREAD

**Issue by vybhav72954** [avinashkranjan/Amazing-Python-Scripts#418]
**Is your feature request related to a problem? Please describe.**
Multiple scrips have redundant `.gitginores` which I found when I was dealing with the whole codebase in #417 
These files are not required at all.

**Describe the solution you'd like**
Delete all the redundant .gitignore but also ensure that all the ignored files are present in the parent `.gitignore`, similar is applicable to other files which serve no purpose in the directory of scripts.

**Describe alternatives you've considered**
NA

**Comment by vybhav72954** [comment]
@avinashkranjan Please assign this to me.

**Comment by avinashkranjan** [comment]
Sure Go ahead @vybhav72954
