### ISSUE TITLE
Enforce basic pep-8 guidelines on the whole codebase

### ISSUE THREAD

**Issue by vybhav72954** [avinashkranjan/Amazing-Python-Scripts#425]
As one of my last contributions to this wonderful list, I suggest enforcing basic pep-8 guidelines across the whole project.

Though this will take some time, so am going to start already. @avinashkranjan Assign this to under SWOC

**Comment by avinashkranjan** [comment]
I was going to do the Same..Glad found someone to work on it...Go ahead @vybhav72954

**Comment by vybhav72954** [comment]
@avinashkranjan As you can see this is a big task, will take me a few hours at best, my PR might come at around 10 pm or something

**Comment by avinashkranjan** [comment]
It won't be an issue.. Go ahead I'll send the updated scoresheet by midnight.
