### ISSUE TITLE
Movie Genre prediction - Chatbot

### ISSUE THREAD

**Issue by hritik5102** [avinashkranjan/Amazing-Python-Scripts#426]
# Aim

- What is the objective of the Script
 Chatbot predicting the movie genre based on the text provided

# Details

- What features will your script have
  Interactive UI

Contribution for **SWOC21**

**Comment by avinashkranjan** [comment]
Go Ahead @hritik5102

**Comment by hritik5102** [comment]
@avinashkranjan modified check now, thank you :)
