### ISSUE TITLE
cpu temperature

### ISSUE THREAD

**Issue by Sloth-Panda** [avinashkranjan/Amazing-Python-Scripts#427]
# Aim

- What is the objective of the Script

 this script can be  used for retrieving information on different running processes and system utilization (CPU, memory, disks, network, sensors) and will be implemented in python.
# Details

- What the features will your script have
will be using psutil library which is a process and system utilities library.

**Comment by avinashkranjan** [comment]
Sure Go Ahead. @Sloth-Panda
