### ISSUE TITLE
Video to Audio converter

### ISSUE THREAD

**Issue by smriti1313** [avinashkranjan/Amazing-Python-Scripts#429]
# Aim

- A simple automation script to convert any type of video to audio.

#GSSOC'21

**Comment by avinashkranjan** [comment]
Hello Smriti, Appreciate your enthusiasm, But Since the contribution period starts from 4th You would have to wait till then..I'll assign you this issue then..

**Comment by avinashkranjan** [comment]
Sure Go Ahead @smriti1313 Assigned to You Send the PR after 8th March
