### ISSUE TITLE
Dice Rolling Simulator

### ISSUE THREAD

**Issue by mehabhalodiya** [avinashkranjan/Amazing-Python-Scripts#439]
**Describe the bug**
I can implement dice rolling simulator using tkinter in a efficient way.
You can replace [this](https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Dice-Roll-Simulator) or can add additional one using tkinter in your directory.

**Screenshots**
After executing it will look like this:
![drs](https://user-images.githubusercontent.com/73488906/109534446-5c516300-7ae1-11eb-90a1-41f06165ebd0.png)

**Comment by ChetasShree** [comment]
Hi, I want to solve this issue using python...
Please assign this issue to me under GSSOC 21 ,using python language.
Looking forward to contribute here...

**Comment by avinashkranjan** [comment]
Sure Go Ahead @mehabhalodiya Assigned to You Send the PR after 8th March

**Comment by mehabhalodiya** [comment]
Okay, I will send a PR after 8th.

**Comment by pi-squared-4** [comment]
I would love to work on this, can you assign this to me. <3

**Comment by avinashkranjan** [comment]
It's already assigned @pi-squared-4

**Comment by pi-squared-4** [comment]
Did she already send the PR?

**Comment by ChetasShree** [comment]
> Did she already send the PR?

if not please assign it to me because I asked after mehabhalodiya

**Comment by kaustubhgupta** [comment]
@mehabhalodiya can you make the PR of this today? If not then it will be assigned to @ChetasShree

**Comment by mehabhalodiya** [comment]
> @mehabhalodiya can you make the PR of this today? If not then it will be assigned to @ChetasShree
Yes
