### ISSUE TITLE
Create a Github Action to Add Hacktoberfest Tag to all the Issues

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#44]
# Aim

- Creating a Github Action to Add Hacktoberfest Tag to all the Issues

# Details

- Action which is Invoked on October 1st and Removes all the tags in October 31st

**Comment by mdb571** [comment]
Is this issue up for Hacktoberfest? If so I can create a PR on October 1

**Comment by avinashkranjan** [comment]
> Is this issue up for Hacktoberfest? If so I can create a PR on October 1

@mdb571 Ya, Sure...

**Comment by mdb571** [comment]
Should I add source code for my action as folder or just add the action workflow to the repo?

**Comment by avinashkranjan** [comment]
> Should I add source code for my action as folder or just add the action workflow to the repo?

Just Add Action to the workflow
