### ISSUE TITLE
Text to Speech

### ISSUE THREAD

**Issue by mehabhalodiya** [avinashkranjan/Amazing-Python-Scripts#440]
**Describe the bug**
I can improve [this](https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Text-To-Speech) directory of "Text to Speech" in a better way using tkinter. 

**Screenshots**
It will look like this:
![tts](https://user-images.githubusercontent.com/73488906/109536673-05995880-7ae4-11eb-8546-a8f68453111a.png)

**Comment by avinashkranjan** [comment]
Sure Go Ahead @mehabhalodiya  Assigned to You Send the PR after 8th March
