### ISSUE TITLE
Youtube Video/Playlist Downloader

### ISSUE THREAD

**Issue by XZANATOL** [avinashkranjan/Amazing-Python-Scripts#441]
* A script that allows the download of videos or playlist.

I would like to work on this script under the mentorship of GSSOC21.

## Details
* Addition of arguments that can:
    - Allows the user to download the video with any quality.
    - Allows the user to download the audio source only.
    - Download full playlists.

## Features
* Code will be commented so it can be easy to read the code flow, and for any furthur contributions to it.
* A documentation will be added before going along with the pull request.
* If possible I may add an executable version of the script. (.exe file)

**Comment by avinashkranjan** [comment]
Sure Go Ahead @XZANATOL

**Comment by XZANATOL** [comment]
Hi @avinashkranjan, I've submited my pull request for this issue early this morning. When will I get your review about it?

**Comment by avinashkranjan** [comment]
> Hi @avinashkranjan, I've submited my pull request for this issue early this morning. When will I get your review about it?

Mentors will review will soon and let you know
