### ISSUE TITLE
ATM Program using Python

### ISSUE THREAD

**Issue by PritKalariya** [avinashkranjan/Amazing-Python-Scripts#442]
# Aim

- The main aim of this script is to get a clear understanding of conditionals. It also helps in logic building, while writing the code.

# Details

- Clean and easily understandable code.
- A Simple program but helps greatly in understanding conditionals.
- Helps to get a proper understanding on how to logically organize your program while dealing with multiple if/elif statements.
- It acts as a virtual ATM, asks for a pin. When the correct pin is entered it allows you to:
  1. Check your balance.
  2. Make withdrawals.
  3.  Deposit money.
  4. Return your credit card.
- It is a command line program.

**Comment by PritKalariya** [comment]
Created this issue. Will fork the repo and upload the files once assigned.

**Comment by divyanshu887** [comment]
Hello, I want to try this. could you please assign me @PritKalariya

**Comment by avinashkranjan** [comment]
Sure Go Ahead @PritKalariya

**Comment by ambivert-sam** [comment]
I would want to work on this issue, can you please assign it to me?

**Comment by PritKalariya** [comment]
Why isn't the PR being merged yet ? Is there any issue, or needed improvement ?

**Comment by avinashkranjan** [comment]
@PritKalariya It would be merged if there's no Issue..Kindly work on other issues in the Meantime..Mentors are reviewing your PRs, if any change would be needed you will be informed.

**Comment by PritKalariya** [comment]
Sure! Thank you.

**Comment by kaustubhgupta** [comment]
@PritKalariya you didn't link the PR to the issue, that's why I wasn't sure if that PR had a valid issue. Now I have linked it and any changes in the code will be communicated

**Comment by PritKalariya** [comment]
Ohh! I see. I actually don't have much experience with making PR's.
