### ISSUE TITLE
Error while substracting a smaller number from a bigger number.

### ISSUE THREAD

**Issue by divya-gh** [avinashkranjan/Amazing-Python-Scripts#444]
**Describe the bug**
An Error was thrown when the result of the substation was a -ve number.

**To Reproduce**
1. Go to 'Calculator - calcy.py'
2. Open in Visual studio. 
3. Run the script and When prompted to 'Enter Equation, type '2-3'(without quotes) and Enter
4. Result is displayed in nextline 
5. Enter
6.  Error was thrown
![equation_empty_string](https://user-images.githubusercontent.com/74730673/110000311-c2540b00-7cd8-11eb-9d25-07ccbddd8498.jpg)

**Expected behavior**
After the result, I would expect the user to enter another equation or quit. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Python 3.6 
 - IDE -Visual Studio

**Comment by avinashkranjan** [comment]
Go ahead with the fix @divya-gh Assigned to you

**Comment by divya-gh** [comment]
Thank you! will work on it!

**Comment by ambivert-sam** [comment]
I would want to work on this issue,@smaranjitghose can you please assign it to me?

**Comment by ambivert-sam** [comment]
I would want to work on this issue , can you please assign it to me?

**Comment by kaustubhgupta** [comment]
@ambivert-sam okay assigned to you!

**Comment by smaranjitghose** [comment]
@avinashkranjan  could you please lemme know if I am somehow involved with this project or this issue. I have been receiving notifications lately😅 even though I don't remember commenting on any issue or mentoring for it.

**Comment by avinashkranjan** [comment]
> @avinashkranjan could you please lemme know if I am somehow involved with this project or this issue. I have been receiving notifications lately😅 even though I don't remember commenting on any issue or mentoring for it.

I don't think so, I don't even remember tagging you anywhere..Maybe Someone did or maybe GitHub glitch xD. You can Unsubscribe from notifications

**Comment by kaustubhgupta** [comment]
@ambivert-sam updates?

**Comment by ambivert-sam** [comment]
So sorry for delay its in process @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@ambivert-sam will you make the PR today?

**Comment by ambivert-sam** [comment]
Yes sir

**Comment by ambivert-sam** [comment]
Sir I have solved the error but while committing changes their is some issue I'm not getting where the actual problem is

**Comment by ambivert-sam** [comment]
Sir the calculation error is fixed  and solved but their is some issue regarding committing changes the changes I've made isn't showing
![Screenshot (155)](https://user-images.githubusercontent.com/74984661/111683256-41a21c80-884b-11eb-8938-9fba02da7a72.png)

**Comment by kaustubhgupta** [comment]
@ambivert-sam maybe you created a separate branch for this issue. Select that branch  in head compare

**Comment by ambivert-sam** [comment]
okay I'm doing again

**Comment by AdhilUsman** [comment]
is this still open ? can i work on it ?

**Comment by kaustubhgupta** [comment]
yes, assigned to you @AdhilUsman

**Comment by AdhilUsman** [comment]
I have been working on solving the above stated issue but it seems like there is a logical error in the code. Correct me if i am wrong. 2+2 gives 4 but 4+2 gives 4 itself and 4+3 gives 6.
![error](https://user-images.githubusercontent.com/67159195/113178606-5f6c7a00-926c-11eb-9fa2-57caee8c5351.PNG)

**Comment by kaustubhgupta** [comment]
@AdhilUsman I think the code is not fixable plus we already got a smart calculator PR merged which handles more cases than this. I think if you can rebuild this whole code then only work on this else I will close this issue. Let me know your decision

**Comment by AdhilUsman** [comment]
You may close this issue
