### ISSUE TITLE
Insta Bot

### ISSUE THREAD

**Issue by muthuannamalai12** [avinashkranjan/Amazing-Python-Scripts#450]
# Aim
- What is the objective of the Script
Insta Bot
# Details

- What the features will your script have
The Script will do the below tasks
To automatically follow a group of people.
To automatically unfollow a group of people.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of GSSOC'21. Kindly assign me this issue

**Comment by avinashkranjan** [comment]
Go Ahead @muthuannamalai12

**Comment by vivek-2000** [comment]
I want to add new features-:
Send messages to the particular user
@avinashkranjan 
I would love to work on this part of GSSOC'21. Kindly assign me this issue

**Comment by kaustubhgupta** [comment]
@vivek-2000 after we merge @muthuannamalai12 code, you can raise the issue to add your features to that existing code

**Comment by kaustubhgupta** [comment]
@vivek-2000 would you like this issue as @muthuannamalai12 failed to fix the bug in PR?

**Comment by vivek-2000** [comment]
@kaustubhgupta yes

**Comment by kaustubhgupta** [comment]
@vivek-2000 okay then assigned to you!
