### ISSUE TITLE
Whatsapp Bot

### ISSUE THREAD

**Issue by muthuannamalai12** [avinashkranjan/Amazing-Python-Scripts#451]
# Aim

- What is the objective of the Script
Whatsapp Bot
# Details
- What the features will your script have
The scripts will do the Following Tasks
To automatically send a message to a group of people individually.
To schedule your message
Voice Controlled Bot

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of GSSOC'21. Kindly assign me this issue

**Comment by avinashkranjan** [comment]
Go Ahead @muthuannamalai12
