### ISSUE TITLE
 Invisibility cloak using python

### ISSUE THREAD

**Issue by satyampgt4** [avinashkranjan/Amazing-Python-Scripts#452]
# Aim

- Invisibility cloak using python

# Details

- First we store the background 
- then set the cloak colour
- find that particular colour in the frame 
- replace the cloak with stored backgroung

**Comment by satyampgt4** [comment]
I would love to work on this issue as a part of GSSOC'21. Kindly assign me this issue @avinashkranjan

**Comment by kshittijagrawal** [comment]
Hey there!
I'd like to contribute to the project. I want to address and fix this issue. My implementation will be in python with a clean code and documentation. Kindly provide me with this issue.
I'm also a GSSOC'21 participant.

**Comment by avinashkranjan** [comment]
Hey @kshittijagrawal Since Issues are First Come First Serve..This Issue is Assigned to @satyampgt4

**Comment by kshittijagrawal** [comment]
Oh it's totally fine @avinashkranjan !

**Comment by kaustubhgupta** [comment]
@satyampgt4 Updates on this?

**Comment by mehabhalodiya** [comment]
Assign me, if anyone is not working on this!
@kaustubhgupta I will implement it by today itself!

**Comment by satyampgt4** [comment]
Sorry for delay It is done I will make pr by tomorrow

**Comment by kaustubhgupta** [comment]
@satyampgt4 Please make PR before 1 pm tomorrow, after that, I will ask @kshittijagrawal and if he also refuses, then it will be assigned to @mehabhalodiya
