### ISSUE TITLE
like to update scripts.md

### ISSUE THREAD

**Issue by deephunt3r** [avinashkranjan/Amazing-Python-Scripts#455]
some of the links in the file scripts.md are not redirecting to scripts. They are not updated with the new links to scripts.
As a participant of Gssoc21, I would like to update all the script links in the scripts.md file. 

![github](https://user-images.githubusercontent.com/60481830/110282415-710f8880-8004-11eb-8406-87fc351a082a.png)

@avinashkranjan  could you please assign it to me

**Comment by avinashkranjan** [comment]
Go Ahead @deephunt3r Assigned to you
