### ISSUE TITLE
Face Detection with OpenCV's built-in recognizer

### ISSUE THREAD

**Issue by aakriti1318** [avinashkranjan/Amazing-Python-Scripts#456]
Aim: This script recognizes the face in an image using OpenCV's built-in recognizer. 
Feature: Easy and understandable code 

I would like to work on this. Kindly assign me.

**Comment by avinashkranjan** [comment]
We already have a Script for the Same [Here](https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Face-Detection) How is your different..Please elaborate

**Comment by aakriti1318** [comment]
My script would be face detection with a different method that is with OpenCV's built-in recognizer.

**Comment by avinashkranjan** [comment]
What would be the purpose of the script? To detect face this script already does that..

**Comment by aakriti1318** [comment]
Okay. I have proposed this idea so that we can detect the faces using multiple method that is OpenCV's built-in recognizer or KNN.

**Comment by avinashkranjan** [comment]
Go Ahead Then...Assigned to you @aakriti1318

**Comment by aakriti1318** [comment]
Thank you, surely will work on it.

**Comment by anubhav201241** [comment]
Hi, Sir 

**Problem in the code:** 

The code is not fully optimized and have less feature in it. 

**What I want to add in it** 
So I want to add more feature and optimized python code in it
Feature I will be working upon is: 
1) Detects the Mid part in face.
2) Detects the eyes and face both Putting them in rectangle frame.
3) Which Detects the Eye and Face both part and also Detects the mid part of the face. 

**So please assign this updating  part to me so I can update this code and add some feature and value in it.**  
Thank You :))
