### ISSUE TITLE
Script to reset the IP configuration in case of an issue

### ISSUE THREAD

**Issue by geekymeeky** [avinashkranjan/Amazing-Python-Scripts#457]
# Aim

- To troubleshoot network errors in Windows when one is not able to browse, even though the computer can ping other Ip addresses

# Details

- This script will reset the TCP/IP configuration to default.
- This script will also recover the computer from any socket errors which arise due to some malicious script on the computer.

**Comment by geekymeeky** [comment]
As a participant of Gssoc21, I would like to work on this issue.

**Comment by avinashkranjan** [comment]
Assigned to you @geekymeeky
