### ISSUE TITLE
Python Music Player App

### ISSUE THREAD

**Issue by robin025** [avinashkranjan/Amazing-Python-Scripts#458]
Hey I am a GSSoC 21 participant and would like to contribute to this repo

# Aim

- Python GUI based music player using Pygame

# Details

- A Python GUI Based Music Player Which Uses Mutagen, Pygame, and Tkinter Themes where a user can add music to play-list

I would like to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @robin025

**Comment by pranjalparmar** [comment]
### **Aim**
Hey I am Pranjal, A GSSOC 2021 participant. I would like to work on this repo and build a GUI-based music player app.

### **Libraries**
Pickle
Tkinter
Pygame

### **Features**
Load a folder as a playlist in the app
Controls such as play, pause, next, previous 
Volume control


I would like to work on this issue and contribute to this repo.

**Comment by robin025** [comment]
> ### **Aim**
> Hey I am Pranjal, A GSSOC 2021 participant. I would like to work on this repo and build a GUI-based music player app.
> 
> ### **Libraries**
> Pickle
> Tkinter
> Pygame
> 
> ### **Features**
> Load a folder as a playlist in the app
> Controls such as play, pause, next, previous 
> Volume control
> 
> 
> I would like to work on this issue and contribute to this repo.

@pranjalparmar  I have already Been assigned this app and started working on this too

**Comment by avinashkranjan** [comment]
Hey @pranjalparmar Issues are First Come First Serve..So It's already assigned to robin. Look for other open Issues

**Comment by kaustubhgupta** [comment]
@robin025 Updates on this?

**Comment by robin025** [comment]
> @robin025 Updates on this?
will make PR by 12 AM, Sorry for the inconvenience
