### ISSUE TITLE
Quiz Application GUI

### ISSUE THREAD

**Issue by soumyavemuri** [avinashkranjan/Amazing-Python-Scripts#460]
Hello, I am a GSSoC '21 participant, I would like to contribute to this repository.

## Aim ##
Quiz Application GUI with Tkinter

## Description ##
The user will be allowed to choose between multiple categories, as well as difficulty levels. The score is calculated and displayed at the end.

**Comment by SavneetKaur01** [comment]
I would love to work on this issue. I am a GSSOC'21 participant and I would provide you with the best possible code in Python Language. I will use Tkinter Library for the same. Looking forward to contribute here.

**Comment by avinashkranjan** [comment]
Go Ahead @soumyavemuri Assigned to you..

@srisatya1197 @SavneetKaur01 Issues are First Come First Serve..Look for other open Issues or Create your own issues if you want to add any scripts

**Comment by kaustubhgupta** [comment]
@soumyavemuri Updates on this?

**Comment by soumyavemuri** [comment]
Working on this right now. Will make a PR by tomorrow for sure.
