### ISSUE TITLE
Modifying the Hangman-Game script 

### ISSUE THREAD

**Issue by madihamallick** [avinashkranjan/Amazing-Python-Scripts#462]
I would like to change the interface of Hangman game which will make it look better. Here is a preview attached.
![2](https://user-images.githubusercontent.com/70858557/110493713-e3718d00-8118-11eb-962d-c33e316bd6cf.PNG)

As a participant of Gssoc21, I would like to work on this.

**Comment by avinashkranjan** [comment]
Go Ahead @madihamallick Assigned to you
