### ISSUE TITLE
Merging two PDF's

### ISSUE THREAD

**Issue by AmeyaJain-25** [avinashkranjan/Amazing-Python-Scripts#464]
# Aim

- I would like to add another script to Merge PDF's.

# Details

- I would let user help to merge two PDF's by running just one script. I will be using PyPDF2 for this.

Please assign me this under GSSoC 21'

**Comment by avinashkranjan** [comment]
Hey @AmeyaJain-25 We already have the script for the same [here](https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/PDF-Tools). If you want to add anything more to that kindly elaborate your details

**Comment by AmeyaJain-25** [comment]
No, it was the same.
Sorry.
I'll try with a new one
