### ISSUE TITLE
Modification in Amazing-Python-Scripts-gh-pages Website

### ISSUE THREAD

**Issue by SurbhiRathi23** [avinashkranjan/Amazing-Python-Scripts#465]
@avinashkranjan There are some issues in Amazing-Python-Scripts Website

-  navbar is not clearly visible its color could be changed
-  search bar have no use in home page, we should only keep search bar in "scripts page"
-  also contributors list doesn't show correct names

I want to work on these issues, you can assign this part to me as a part of gssoc21.

**Comment by avinashkranjan** [comment]
Assigned to you Go ahead @SurbhiRathi23

**Comment by kaustubhgupta** [comment]
@SurbhiRathi23 updates on this?

**Comment by SurbhiRathi23** [comment]
@kaustubhgupta yes I am doing it. I will complete in 2-3 days.

**Comment by SurbhiRathi23** [comment]
@avinashkranjan @kaustubhgupta  I have changed the navbar of script page and home page.
Also, I have updated the names of the contributors list on home page, but there are 78 contributors. So, should I include all the 78 contributors In home page??

![2](https://user-images.githubusercontent.com/55491101/111034397-707b5580-843b-11eb-94f4-14890d4ffea4.JPG)

![3](https://user-images.githubusercontent.com/55491101/111034646-a66d0980-843c-11eb-812d-b6491aeeacd5.JPG)

**contributors list in that same home page**

![1111](https://user-images.githubusercontent.com/55491101/111034394-69544780-843b-11eb-9fab-437e1a4dd043.JPG)

**Comment by SurbhiRathi23** [comment]
@avinashkranjan . Sir reply please about the above comment.
Should I make Pull Request?

**Comment by kaustubhgupta** [comment]
> @avinashkranjan . Sir reply please about the above comment.
> Should I make Pull Request?

I have conveyed this message to him and he will review it soon

**Comment by avinashkranjan** [comment]
Hello @SurbhiRathi23 Why is their a Login/SignUp Option? What is Purpose of that?

**Comment by SurbhiRathi23** [comment]
@avinashkranjan i thought that the scripts should be accessible to authentic user only, but i will remove them if you will say.
Any other changes you want me to do??

**Comment by kaustubhgupta** [comment]
@SurbhiRathi23 you can submit a PR for this and then after looking at it, we will suggest final changes if needed. Make sure to put your changes in the gh-pages branch

**Comment by SurbhiRathi23** [comment]
@kaustubhgupta okay, I will do it by end of day.
