### ISSUE TITLE
WhatsApp Profile Picture Downloading Script

### ISSUE THREAD

**Issue by sudipg4112001** [avinashkranjan/Amazing-Python-Scripts#468]
I would like to add a project which would help us in downloading the profile pictures of all in our contact list. I would like to do in python.
I am a GSSOC'21 participant.

**Comment by avinashkranjan** [comment]
Go Ahead @sudipg4112001

**Comment by amritakesh** [comment]
hello
i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?
