### ISSUE TITLE
Script to automate Google Classroom

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#47]
# Aim

- Script to automate Google Classroom

# Details

 Add a bot which automatically joins online meetings/classes (Google meet) on time using
- Google classroom schedule in a CSV file
- Account credentials

**Comment by sooryaprakash31** [comment]
@avinashkranjan I would like to work on this. Please assign this to me!

**Comment by avinashkranjan** [comment]
@sooryaprakash31 Sure...Go ahead..
