### ISSUE TITLE
Spam Message Detector

### ISSUE THREAD

**Issue by Dhanush2612** [avinashkranjan/Amazing-Python-Scripts#479]
Program to specify spam messages.

**Comment by kaustubhgupta** [comment]
@Dhanush2612 can you provide more information on this? Is your script different from this one: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Message-Spam

**Comment by Dhanush2612** [comment]
I have completed Pull Request #491 regarding this issue.

**Comment by kaustubhgupta** [comment]
> I have completed Pull Request #491 regarding this issue.

Did you read my message above before making this PR?

**Comment by Dhanush2612** [comment]
My script isn't different. I saw it now, I am sorry.

**Comment by kaustubhgupta** [comment]
Closing this Issue now
