### ISSUE TITLE
Attachment Downloader

### ISSUE THREAD

**Issue by Kirtan17** [avinashkranjan/Amazing-Python-Scripts#482]
# Aim

- Aim of this script is to automatically download long list of attachments from the mail in no time!

# Details

- Script aims to have a search feature. The search feature will help us find the right emails (i.e emails with specific subject)

# Example
This script will be extremely helpful when xyz person wants to download all of his bank statements.

# Tech Stack
Python

I'm participant at GSSoC'21. Can you please assign this issue to me?

**Comment by kaustubhgupta** [comment]
@Kirtan17 assigned to you

**Comment by kaustubhgupta** [comment]
@Kirtan17 updates?

**Comment by Kirtan17** [comment]
Hey Kaustubh,

I was out of town. Got back today. Can you please give me 2-3 days?

**Comment by kaustubhgupta** [comment]
> Hey Kaustubh,
> 
> I was out of town. Got back today. Can you please give me 2-3 days?

Okay, try to make the PR within 2 days
