### ISSUE TITLE
GitHub Action to Add Projects Information to the Scripts.md

### ISSUE THREAD

**Issue by kaustubhgupta** [avinashkranjan/Amazing-Python-Scripts#483]
# Aim

Currently the Scripts.md file requires manual addition of script names with titles. Create a GitHub action that does this job automatically.

# Details

I am not aware of any existing GitHub action but a simple Python script will do the job combined with actions. The implementation goes like this:

- fetch the repository details about all the folders.
- add the folder name and link to the script in the table.
- add some exceptions like README.md, contribution guide, and other non-necessary files to this list. 
- The action will be configured to run at every push in the repo.

# Learning
You will get to know about GitHub API, GitHub actions and how to use Python to automate this simple task,

**Comment by Tushar1337** [comment]
can you assign this to me? I'm a gssoc'21 participant..

**Comment by saaalik** [comment]
I would love to automate this task as my first project in this repo, I am interested in this project. Can you assign it to me @kaustubhgupta ?

**Comment by kaustubhgupta** [comment]
> I would love to automate this task as my first project in this repo, I am interested in this project. Can you assign it to me @kaustubhgupta?

Sure, try out this issue and let me know if you get stuck somewhere (P.S: I have good knowledge about GitHub actions :-) )

**Comment by kaustubhgupta** [comment]
@saaalik updates?

**Comment by saaalik** [comment]
Sorry for not updating you, I have learnt basic git actions and some aspects of CI CD yaml scripts. The problem i am facing right now is how to append a newly pushed script info into the contributions.md file, I might be able to trigger a python script to append the same but that would cause multiple instances of the same "amazing-script" if the project was updated, I don't even know if we can make a python file excute based from a yaml file, You might have a solution for the problem I am stuck in but please give me another day and I might pull it off, the adernaline rush of learning in these situations is really effective.

**Comment by kaustubhgupta** [comment]
@saaalik I understand your situation. I have created a GitHub Action in Python scripts. Here is the link to that project: https://github.com/kaustubhgupta/PortfolioFy 

Although this has a different approach, I have used python to update a file. You can refer to my article where I have explained how you can achieve this: https://towardsdatascience.com/github-action-that-automates-portfolio-generation-bc15835862dc

I am not promoting my stuff but a lot of people have found my article a good start for this. 

Let me know if you need more help on this

**Comment by kaustubhgupta** [comment]
You can take your time as this is a totally different issue and level3 too

**Comment by kaustubhgupta** [comment]
@saaalik did you found the workaround for this issue?

**Comment by kaustubhgupta** [comment]
@saaalik are you working on this or shall I assign it to someone else?

**Comment by saaalik** [comment]
Yes, give me time till 19th EOD, after that you can assign it to someone else please

**Comment by kaustubhgupta** [comment]
Okay

**Comment by kaustubhgupta** [comment]
Closed for now
