### ISSUE TITLE
Translator Script in Python

### ISSUE THREAD

**Issue by NEERAJAP2001** [avinashkranjan/Amazing-Python-Scripts#484]
# Aim
This Script helps to translate from one language to another

# Details
It uses Google Trans Library and is efficient in translating.
Requires : ```pip install googletrans==3.1.0a0```

I would Like to work on this issue,
Please assign this issue to me as part of GSSOC-21.
Thanks

**Comment by kaustubhgupta** [comment]
assigned to you @NEERAJAP2001
