### ISSUE TITLE
Script for Bitcoin Mining in Python

### ISSUE THREAD

**Issue by NEERAJAP2001** [avinashkranjan/Amazing-Python-Scripts#485]
# Aim

The objective of this script is to mine Bitcoin.

# Details

It's a script to mine bitcoin but It actually won't reward any bitcoin as the difficulty level is 20 which requires huge processors for rewarding.
So, It's a fun project to understand how hashing, etc works.
I will give complete details in a pdf file to understand everything from scratch.
I would Like to work on this issue as well as part of GSSOC-21.
Thanks

**Comment by kaustubhgupta** [comment]
Sounds interesting, assigned to you @NEERAJAP2001
