### ISSUE TITLE
Caesar Cipher

### ISSUE THREAD

**Issue by smriti1313** [avinashkranjan/Amazing-Python-Scripts#488]
# Aim

- Creating a script for caesar cipher

# Details

- Caesar's cipher, the shift cipher, is one of the simplest and most widely known encryption techniques. It is a type of substitution cipher in which each letter in the plaintext is replaced by a letter some fixed number of positions down the alphabet.

**Comment by kaustubhgupta** [comment]
@smriti1313 assigned to you

**Comment by smriti1313** [comment]
Update: I will send a PR by tomorrow. I am sorry for the delay caused.
