### ISSUE TITLE
CGPA Calculator

### ISSUE THREAD

**Issue by Dhanush2612** [avinashkranjan/Amazing-Python-Scripts#493]
Python program to calculate CGPA.

**Comment by Dhanush2612** [comment]
Please assign me this issue if its valid.

**Comment by kaustubhgupta** [comment]
@avinashkranjan Should this be included in the repo?

**Comment by Dhanush2612** [comment]
I saw distance calculator in repo, so I thought of this. 
What if I include python programs to calculate gpa and cgpa both together as one issue and name it as grades calculator?

**Comment by kaustubhgupta** [comment]
shifted to #505
