### ISSUE TITLE
Grade Points Calculator

### ISSUE THREAD

**Issue by Dhanush2612** [avinashkranjan/Amazing-Python-Scripts#494]
Python Program to calculate grade points.

**Comment by Dhanush2612** [comment]
Please assign me this issue if its valid.

**Comment by kaustubhgupta** [comment]
@avinashkranjan Should this be included in the repo?

**Comment by Dhanush2612** [comment]
I saw distance calculator in repo, so I thought of adding this.

**Comment by kaustubhgupta** [comment]
> I saw distance calculator in repo, so I thought of this.
> What if I include python programs to calculate gpa and cgpa both together as one issue and name it as grades calculator?

okay, we are assigning you issue #505
