### ISSUE TITLE
News Scrapper (India Today)

### ISSUE THREAD

**Issue by honeybhardwaj** [avinashkranjan/Amazing-Python-Scripts#495]
# Aim

- The Script will scrap the news details from times of india as per user and store it in a form of csv file.

# Details

- it will be working on modules like selenium, csv etc
- the scrapping will be based on the user.
- the scraped data will be in proper format and would be stored in csv file.

**Comment by honeybhardwaj** [comment]
i would like to contribute to this script please assign it to me
regards
Honey Bhardwaj

**Comment by kaustubhgupta** [comment]
@honeybhardwaj Assigned to you

**Comment by honeybhardwaj** [comment]
@kaustubhgupta  Thanks!

**Comment by kaustubhgupta** [comment]
@honeybhardwaj updates?

**Comment by honeybhardwaj** [comment]
@kaustubhgupta  yeah am working on it the code have some issue so i m trying to figure them out.

Regards 
Honey bhardwaj

**Comment by kaustubhgupta** [comment]
@honeybhardwaj DIdi you found the workaround? It's already 6 days since this issue was assigned to you

**Comment by paulamib123** [comment]
Hi!
I am interested to work on this issue. 

But, I am not clear with what it exactly means by the line "Script will scrap the news details from times of india as per user". 
Does it mean the user will enter some keywords and we have to search all articles in the Times Of India that are related to those keywords?  

And also what exactly would be the output format in the csv file?
If you could give one example of the input and output format it would be really helpful in understanding the problem statement.

**Comment by kaustubhgupta** [comment]
@paulamib123 let me break it down for you:
- You need to take user input for type of news: Entertainment, technology, political...
- Then scrap the top 10 results for the respective category chosen by the user and then save the following details in CSV:  
    - date of publishing
    - link to the article
    - headline of the news

**Comment by paulamib123** [comment]
Okay, Thank you!
Is it possible that I can take the data from India Today instead of TOI? 
Because it seems the TOI pages are not in sync and every category has a different page design.

**Comment by kaustubhgupta** [comment]
@paulamib123 Okay, no issues, I have updated the title of the issue.
