### ISSUE TITLE
Shortest Path Finder.

### ISSUE THREAD

**Issue by SpecTEviL** [avinashkranjan/Amazing-Python-Scripts#496]
# Aim

- A shortest pathfinder between two points. 

# Details

- The user can add a path manually.
- The user can add the start point and endpoint manually.
- The shortest path is displayed in the GUI with a color.
- The area tracked can also be seen in the GUI.

**Comment by SpecTEviL** [comment]
Hey, @avinashkranjan, Vishal Patil here and would like to work on this issue under GSSoC'21. You can review the issue and assign it to me.
Thanks!

**Comment by kaustubhgupta** [comment]
@SpecTEviL this will be a GUI application?

**Comment by SpecTEviL** [comment]
> @SpecTEviL this will be a GUI application?

Yes @kaustubhgupta.

**Comment by kaustubhgupta** [comment]
okay!

**Comment by SpecTEviL** [comment]
> okay!

Thanks, @kaustubhgupta! Will work on it and make a PR ASAP.

**Comment by SpecTEviL** [comment]
Hey, @kaustubhgupta I've finished the task and have made a PR. Please review it. In case of any discrepancies do let me know.
Thanks!
