### ISSUE TITLE
Extracting the text from a real-time captured image.(GSSOC '21)

### ISSUE THREAD

**Issue by ShubhamGupta577** [avinashkranjan/Amazing-Python-Scripts#497]
# Aim

### Extracting the text from a real-time captured image.

# Details
By using Open CV we read a real-time image and by applying various filters we try to reduce the noise after that with the use of pytesseract we extract the text written in the image
Libraries used-
* cv2
* pytesseract

**Comment by ShubhamGupta577** [comment]
I want to work on this under GSSOC '21. Please assign me this issue.

**Comment by kaustubhgupta** [comment]
We already have a script for this: https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/OCR-Image-To-Text/ocr-img-to-txt.py

**Comment by kaustubhgupta** [comment]
If you want to improve upon this then kindly mention

**Comment by ShubhamGupta577** [comment]
@kaustubhgupta , I had already checked the above scripts but in that scripts, they are using an image that is already stored in the machine. 
And I want to read a real-time image using a web cam or any other camera and extract the text from that image by removing noise from it. I want to use OpenCV for this purpose which is different from the previous scripts.

**Comment by kaustubhgupta** [comment]
Okay that ways, yes go ahead with this issue 👍🏼
