### ISSUE TITLE
Slideshare Downloader

### ISSUE THREAD

**Issue by vikashkumar2020** [avinashkranjan/Amazing-Python-Scripts#498]
# Aim

- Download slides from slideshare website in PDF format from the URL.

# Details

- It will be written in python 3 and using 
docopt
img2pdf
requests
beautifulsoup4

**Comment by vikashkumar2020** [comment]
@avinashkranjan I am participant of gssoc 21 please assign this one to me

**Comment by kaustubhgupta** [comment]
Interesting, @vikashkumar2020 assigned to you!
