### ISSUE TITLE
Colour Detection

### ISSUE THREAD

**Issue by deepshikha007** [avinashkranjan/Amazing-Python-Scripts#500]
# Aim

Colour Detection using Pandas & OpenCV

# Details

To build an application through which we can automatically get the name of the color by clicking on them.  By using 3 primary colors: red, green and blue. This, will be done with data file that contains the color name and its values. Then we will calculate the distance from each color and find the shortest one.

**Comment by kaustubhgupta** [comment]
@deepshikha007 sounds interesting, but it will be a GUI application or a CLI script?

**Comment by deepshikha007** [comment]
GUI application

**Comment by kaustubhgupta** [comment]
Assigned to you @deepshikha007
