### ISSUE TITLE
Translator with gui

### ISSUE THREAD

**Issue by Ayushjain2205** [avinashkranjan/Amazing-Python-Scripts#503]
# Aim

To build a language translator using python

# Details

This script will allow users to translate between languages of their choice. This will be achieved using the help of the googletrans python package

**Comment by Ayushjain2205** [comment]
@avinashkranjan I am participant of gssoc 21 please assign this one to me

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 you have been assigned this issue for the GUI version. @NEERAJAP2001 will be making the CLI version. Make sure you both name your folders accordingly

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 updates?
