### ISSUE TITLE
Grades Calculator

### ISSUE THREAD

**Issue by Dhanush2612** [avinashkranjan/Amazing-Python-Scripts#505]
Python programs to calculate your cgpa and grade points.

**Comment by kaustubhgupta** [comment]
@Dhanush2612 Make it a GUI application

**Comment by Dhanush2612** [comment]
Is GUI enough or is web.app required?

**Comment by kaustubhgupta** [comment]
> Is GUI enough or is web.app required?

No, GUI will work

**Comment by Dhanush2612** [comment]
Reply

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by kaustubhgupta** [comment]
@Dhanush2612 updates?

**Comment by Dhanush2612** [comment]
I am working on it
