### ISSUE TITLE
Air Pollution Prediction

### ISSUE THREAD

**Issue by Pranjal-2001** [avinashkranjan/Amazing-Python-Scripts#508]
The aim behind this project is to predict air pollution index. 
The code will be tested under Python and Tensorflow.
I am a participant of GSSOC'21. 
Can i please work on it?

**Comment by Pranjal-2001** [comment]
Yes!  Could you assign  it to me?

**Comment by kaustubhgupta** [comment]
Hi @Pranjal-2001, issue assigned to you. Make sure to make it more script specific and not an end-to-end application!

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by kaustubhgupta** [comment]
@Pranjal-2001 updates?

**Comment by Pranjal-2001** [comment]
I am working on it sir..will be done by Wednesday

**Comment by kaustubhgupta** [comment]
@Pranjal-2001 Can you make the PR by today?

**Comment by Pranjal-2001** [comment]
yes sir
