### ISSUE TITLE
Titanic Survival Model

### ISSUE THREAD

**Issue by Dhanush2612** [avinashkranjan/Amazing-Python-Scripts#509]
ML model to predict Titanic Survival by making use of decision tree.

**Comment by kaustubhgupta** [comment]
@Dhanush2612 assigned to you. Make sure to make it more script-specific and not an end-to-end application!

**Comment by Dhanush2612** [comment]
Can you please explain script specific?

**Comment by kaustubhgupta** [comment]
Maybe take the inputs as this for predicting on unknown values :
```bash
python predict.py --p1 34.2 --p2 43.2   
```
or you can create a print statement for every parameter

**Comment by Dhanush2612** [comment]
I have made new PR regarding this issue. I hope it satisfies your requirements.
