### ISSUE TITLE
Add Github Token to workflow

### ISSUE THREAD

**Issue by mdb571** [avinashkranjan/Amazing-Python-Scripts#51]
**Describe the bug**
My PR #45 has a an error in the [hacktoberfest.yml](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/.github/workflows/hacktoberfest.yml).I forgot to add the Github token as an environment variable.Thus the action build fails 

**Solution**
add the following line to the [hacktoberfest.yml](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/.github/workflows/hacktoberfest.yml)
```    steps:
      - name: hacktoberfest-action
        uses: mdb571/hacktoberfest-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} <-- add this line
          LABEL_COLOR: ${{ secrets.LABEL_COLOR }}
          LABEL_FILTER: ${{secrets.LABEL_FILTER}}
```

**Comment by avinashkranjan** [comment]
@mdb571 Kindly create a PR for the Same..

**Comment by avinashkranjan** [comment]
@mdb571 Build is still failing, kindly look into that.
