### ISSUE TITLE
Mask or not

### ISSUE THREAD

**Issue by sudipg4112001** [avinashkranjan/Amazing-Python-Scripts#510]
I would like to add a project for face mask detection using CNN. Here, I would use dataset which contains real life images of human faces.

**Comment by kaustubhgupta** [comment]
@sudipg4112001 Are you sure you want to add this big project into this repo? Because it's a standalone project

**Comment by sudipg4112001** [comment]
Yes, I am sure. I feel this project will give this repo a unique feature.

**Comment by sudipg4112001** [comment]
Assign me ASAP. So that I can start working

**Comment by kaustubhgupta** [comment]
Okay @sudipg4112001, make sure to make it more script/CLI specific and not an end-to-end application!

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by sudipg4112001** [comment]
> Hello, I am a GSSOC'21 participant and would like to contribute to this project.

This is already assigned.

**Comment by kaustubhgupta** [comment]
Hello @Hamza3226,
You can contribute to this project by looking at issues with up-for-grab tags. If you didn't find any interesting issue then you can create your own issues just make sure to check if that doesn't exist before in this repo. If it's already there then you can check if you can improve that existing code and then create an issue for that too!

You have ample of choices to contribute!

**Comment by kaustubhgupta** [comment]
@sudipg4112001 updates?

**Comment by sudipg4112001** [comment]
Tomorrow I will make the PR

**Comment by kaustubhgupta** [comment]
@sudipg4112001?

**Comment by sudipg4112001** [comment]
Yeah, working on it. Will make the PR within 24 hrs.
