### ISSUE TITLE
Facebook Bot for Automatic Media Posting

### ISSUE THREAD

**Issue by vivek-2000** [avinashkranjan/Amazing-Python-Scripts#512]
What features will my script have
Posting the media Automatically

**Comment by vivek-2000** [comment]
@avinashkranjan 
I would love to work on this issue as a part of GSSOC'21. Kindly assign me this issue

**Comment by kaustubhgupta** [comment]
@vivek-2000 assigned to you

**Comment by kaustubhgupta** [comment]
@vivek-2000 updates?

**Comment by kaustubhgupta** [comment]
@vivek-2000 Issue unassigned due to no response from your side

**Comment by osamamagdy** [comment]
Hey @kaustubhgupta 
I am a participant at GSSoC 2021. I would like to contribute to this issue. Can you assign it to me. Also, I need more details as it is not clear for me right now.

**Comment by Amit366** [comment]
@kaustubhgupta can I work on this?? 
And also please can you explain what exactly have to be done.

**Comment by Amit366** [comment]
@kaustubhgupta since I have no more pending issues can I start working???

**Comment by amrzaki2000** [comment]
@kaustubhgupta Can I work on this ?

**Comment by kaustubhgupta** [comment]
@amrzaki2000 sure!

**Comment by Amit366** [comment]
@kaustubhgupta I asked for the issue first.

**Comment by kaustubhgupta** [comment]
Apologies @Amit366 for seeing this message late! That's why I unassigned @amrzaki2000 as soon as I saw your message above

**Comment by amrzaki2000** [comment]
> Apologies @Amit366 for seeing this message late! That's why I unassigned @amrzaki2000 as soon as I saw your message above
> ![image](https://user-images.githubusercontent.com/43691873/113246920-96c44080-92d7-11eb-9567-0d8808a84c8f.png)
> 

Sorry
I did not see it too
