### ISSUE TITLE
Virtual Paint

### ISSUE THREAD

**Issue by mehabhalodiya** [avinashkranjan/Amazing-Python-Scripts#519]
# Aim

- Detecting Color and using colored marker to draw virtually

# Details

- It is an OpenCV application that can track an object’s movement, using which a user can draw on the screen by moving the object around — I call it Webcam Paint.
- I will implement it with :
Step 1: Initialize some stuff (import the necessary libraries)
Step 2: Start reading the video (frame by frame)
Step 3: Find the Contour-Of-Interest
Step 4: Start drawing and store the drawings
Step 5: Show the drawings on the screen

- It will look like this:

![virtual_paint](https://user-images.githubusercontent.com/73488906/110961969-67748080-8376-11eb-871f-64d77457efc6.gif)

**Comment by mehabhalodiya** [comment]
I would like to work on this as a GSSOC'21 participant.

**Comment by avinashkranjan** [comment]
Go Ahead @mehabhalodiya
