### ISSUE TITLE
[GSSoC '21] Bubble sort simulation with GUI

### ISSUE THREAD

**Issue by amrzaki2000** [avinashkranjan/Amazing-Python-Scripts#528]
# Aim

- Show how bubble sort algorithm works.

# Details

- The script will provide a simulation of bubble sort algorithm to show the user how it works.

**Comment by kaustubhgupta** [comment]
@amrzaki2000  updates?

**Comment by amrzaki2000** [comment]
> @amrzaki2000  updates?

I'll make a pull request by tomorrow morning .
Almost finished
