### ISSUE TITLE
Emotion Prediction by Text through LSTM

### ISSUE THREAD

**Issue by AparnaJuhi** [avinashkranjan/Amazing-Python-Scripts#531]
It will be a deep learning model, which will be used to predict the emotion of the text that the user will input. The model used will be LSTM

**Comment by AparnaJuhi** [comment]
I want to work on this issue. So, please assign it to me @avinashkranjan

**Comment by kaustubhgupta** [comment]
@avinashkranjan Isn't this issue beyond the scope of this Repo?

**Comment by avinashkranjan** [comment]
Hey @AparnaJuhi Your Issue is a whole different project in itself..Since, we deal here with only Python Scripts..Deep Learning Model Won't be needed here..But I'm Sure there are plenty of Project in GSSOC'21 for the Same.
