### ISSUE TITLE
Organise Some Files

### ISSUE THREAD

**Issue by Lakhankumawat** [avinashkranjan/Amazing-Python-Scripts#536]
**Is your feature request related to a problem? Please describe.**
**YES**
When i first discovered this Repo i found it amazing source of learning new things but at the same time i was bit confused in so many files and folders and find it difficult to reach my piece of information or basically what i want to learn . So i was thinking if not all but some of the files and folders can be organised then it will be good.

**Describe the solution you'd like**
The Project Admin is kindly requested to merge all the pygames into one folder named Pygame and in it there may be subfolders for all games which are included in repo . By this it will be ease for a newcomer and beginner like me :)

**Describe alternatives you've considered**
I haven't gone through all of the contents of Repo , If i feel like same for the other then i will let admins know .

**Additional context**
**No**

**Comment by kaustubhgupta** [comment]
@Lakhankumawat this can make several issues as if the file structure is changed, the past PRs will run into merge conflict and as most of them are beginners, it would be difficult for them to update the new changes. @avinashkranjan what do you think?

**Comment by Lakhankumawat** [comment]
Yeah i think you are right , let's postpone it further when most of the things are included in repo ( i mean if there is  not much active contribution , probably after gsooc ) . It will will be good to do then , otherwise keep it as it is.👍
