### ISSUE TITLE
Path Finding script

### ISSUE THREAD

**Issue by saaalik** [avinashkranjan/Amazing-Python-Scripts#539]
# Aim

- What is the objective of the Script
Find the shortest possible path between two predefined points using `a star pathfinding algorithm`

# Details
The script will use different data structures to find the most efficent node, and visualize both the finding process and the final output path using pygame module

- What the features will your script have
Find shortest path

**Comment by kaustubhgupta** [comment]
@saaalik how this will be a script? This is a predefined algorithm

**Comment by saaalik** [comment]
The script would only contain the implementation part and visualizing the algorithm. Is the project appropriate enough for Amazing-Python-Scripts?

**Comment by kaustubhgupta** [comment]
okay go ahead with this issue

**Comment by kaustubhgupta** [comment]
@saaalik Updates on this?

**Comment by saaalik** [comment]
Completed, will be making a PR in an hour

**Comment by kaustubhgupta** [comment]
This script was already present in the repository and was detected while reviewing the PR by @santushtisharma10. Therefore, this issue will be used
