### ISSUE TITLE
Meme uploading web app 


### ISSUE THREAD

**Issue by mohammedjameel24** [avinashkranjan/Amazing-Python-Scripts#540]
Meme upload using image url caption and name 
Build on top of python flask
HTML /css / bootstrap

**Comment by kaustubhgupta** [comment]
Hi @mohammedjameel24,
Can you provide more information on this?
We are not looking for an end to end applications but scripts that can be run from a terminal or some type of GUI all restricted to scrips only

**Comment by kaustubhgupta** [comment]
@mohammedjameel24 ?

**Comment by mohammedjameel24** [comment]
@kaustubhgupta nope irrelevant to this repo 
I was talking about a django web app

**Comment by kaustubhgupta** [comment]
@mohammedjameel24 okay, closing this issue!
