### ISSUE TITLE
Instagram Liker Bot

### ISSUE THREAD

**Issue by sayantani11** [avinashkranjan/Amazing-Python-Scripts#544]
**AIM**
Instagram Liker Bot

**WHAT IT WILL DO**
Search for a particular user and if the account is public or the images are accessible will like all the posts on behalf.

**Comment by sayantani11** [comment]
I would like to work on this, please assign this to me

**Comment by kaustubhgupta** [comment]
@sayantani11 assigned to you. Make sure to name the directory as Instagram-Liker-Bot as another participant will be adding follow/unfollow insta bot
