### ISSUE TITLE
Price Comparision and Checker

### ISSUE THREAD

**Issue by aashishah** [avinashkranjan/Amazing-Python-Scripts#545]
# Aim

- The aim of this python script would be to automatically search for an item across Amazon.com, Flipkart and other online shopping websites to find the cheapest price available.

# Details

- User can enter the item to be searched for.
- The script displays all possible matches in ascending order of prices, in the form of Site - Link - Cost
- It also displays the best/cheapest price that is available.
- Will start with Amazon and Flipkart first and then add other websites.

**Comment by aashishah** [comment]
If you approve of this script idea, I would like to work on it under GSSOC'21, thank you!

**Comment by kaustubhgupta** [comment]
@aashishah assigned to you

**Comment by Amit366** [comment]
@kaustubhgupta can I work on this issue??

**Comment by aashishah** [comment]
This issue was assigned to me, I am currently working on it but have to balance university exams parallely that's why it is taking time. Please do not remove my assignment, thank you.

**Comment by kaustubhgupta** [comment]
@aashishah don't worry, you have 2 more days to work on. No one is taking your assignment
