### ISSUE TITLE
Discord Bot

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#55]
# Aim

- Code a Discord Bot

# Details

- Discord bot with moderation and information commands which is very easy to setup

**Comment by vivax3794** [comment]
I can write a bot, for "information commands", is that info about the bot?

**Comment by avinashkranjan** [comment]
@vivax3794 we are looking a dummy bot...which can be configured as per needs.... a basic bot..

**Comment by vivax3794** [comment]
sure a simple bot, should be well simple 🙃 
so I am thinking just having a `config.py`, that should be the easiest way to have somebody setup a bot?

just with the simple contents of: 
```python
# this guide explains how to get a discord bot token, and how to invite your bot to your server: 
# https://www.writebots.com/discord-bot-token/
# then just input your token here, inside the quotes
TOKEN="your token here"
```

**Comment by vivax3794** [comment]
or maybe just have that in the main file when I think about it xD

**Comment by avinashkranjan** [comment]
@vivax3794 Ok vivax...go ahead.... we can work on things along the PR.. Assigning it to you..
