### ISSUE TITLE
Applying Bitwise Operations on two images using OpenCV

### ISSUE THREAD

**Issue by undetectablevirus** [avinashkranjan/Amazing-Python-Scripts#551]
Update: https://github.com/avinashkranjan/Amazing-Python-Scripts/issues/551#issuecomment-798978506

**Comment by kaustubhgupta** [comment]
@undetectablevirus no description?

**Comment by undetectablevirus** [comment]
With Bitwise operations on two images, I meant applying bitwise AND and bitwise OR operation that will help in the masking of images. We can represent union and intersection of portions of two images with this.

**Comment by kaustubhgupta** [comment]
@undetectablevirus okay, assigned to you

**Comment by kaustubhgupta** [comment]
@undetectablevirus updates?

**Comment by kaustubhgupta** [comment]
@undetectablevirus final updates? are you working on this issue?

**Comment by undetectablevirus** [comment]
yes, i will create pull request today. Apologies for the delay
