### ISSUE TITLE
Calendar-GUI

### ISSUE THREAD

**Issue by aishwaryachand** [avinashkranjan/Amazing-Python-Scripts#552]
AIM-
Create a GUI-based Calendar that can show the calendar with respect to the given year, given by the user.
 I am A GGSOC participant .pls assign me this issue.

**Comment by kaustubhgupta** [comment]
@aishwaryachand assigned to you

**Comment by kaustubhgupta** [comment]
@aishwaryachand updates?

**Comment by aishwaryachand** [comment]
will make a pr by today @kaustubhgupta
