### ISSUE TITLE
Currency convertor - GUI based

### ISSUE THREAD

**Issue by MayankkumarTank** [avinashkranjan/Amazing-Python-Scripts#554]
# Aim
- What is the objective of the Script
--> Objective of the Script to convert the currency from one to another.

# Details

- What features will your script have
--> In this script you have to choose the from currency and to currency (units)  then, provide the amount in from currency and you will get the output that your amount is converted to to_currency amount. 

Example :

Input (In GUI) :
from_currency : USD
to_currency: INR
Amount: 10 (in USD)

Output:
Converted Amount: 730 (In INR)

Note: This script works with all types or all countries' currency and it is not rule-based. I am receiving the current rates from useful APIs. (I am a participant at GSSOC'21)

**Comment by MayankkumarTank** [comment]
I want to work with this issue as GSSOC21 participant. Looking forward to get assigned/approval.

**Comment by kaustubhgupta** [comment]
@MayankkumarTank assigned to you

**Comment by Amit366** [comment]
@kaustubhgupta can I work on this issue??

**Comment by MayankkumarTank** [comment]
It is assigned to me and I already made a pull request for this issue.

**Comment by kaustubhgupta** [comment]
@MayankkumarTank I think @Amit366 had confusion because you didn't link the issue to the PR. @Amit366 For future reference, issues with the "assigned" label are already being claimed by someone else. You need to look for "up-for-grab" labels or create your own issues

**Comment by Amit366** [comment]
@kaustubhgupta I understand that but there r some issues which are assigned for more than 5 days. But according to the rule maximum 3 to 4 days are given.

**Comment by kaustubhgupta** [comment]
@Amit366 That's our work to coordinate with participants and get the work done in time. I usually ask after 3 days if the person has some updates or not and if the participant is not active, I assign it as "up-for-grab"

**Comment by Amit366** [comment]
Ok
