### ISSUE TITLE
A one click Automatic File Arranger Built with Python

### ISSUE THREAD

**Issue by aliya-rahmani** [avinashkranjan/Amazing-Python-Scripts#558]
There are times when your downloads folder or any other directories have different types of files that you keep feeling too lazy to arrange them well into various folders like images, videos, audios, documents, compressed, programs, and folders for subfolders in that directory.

This python script or script does such manual work for you with just one click. You don't need to know programming before using the program To run the program, you simply open it in the directory which you want to arrange and everything will be sorted out for you

I  can use the OS Module of Python to achieve this type of functionality.

@kaustubhgupta  Please assign this to me.(I am a participant at GSSOC'21)

**Comment by kaustubhgupta** [comment]
We already have this script: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Organise-Files-According-To-Their-Extensions

Another version of this is also implemented: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/File-Mover

**Comment by aliya-rahmani** [comment]
@kaustubhgupta  Okay, I will create another issue with a new project idea.
