### ISSUE TITLE
Cartooning an image with openCV

### ISSUE THREAD

**Issue by aliya-rahmani** [avinashkranjan/Amazing-Python-Scripts#559]
Computer Vision as you know (or even if you don’t) is a very powerful tool with immense possibilities. So, when I set up to prepare a comic of one of my friend’s college life, I soon realized that I needed something that would reduce my efforts of actually painting it but will retain the quality and I came up with the following solution. So, in this project we will cartoonize an image with openCV.

Please assign me this task under gssoc.

**Comment by kaustubhgupta** [comment]
@aliya-rahmani assigned to you
