### ISSUE TITLE
Raspberry pi scripts addition

### ISSUE THREAD

**Issue by dhriti987** [avinashkranjan/Amazing-Python-Scripts#560]
# Aim

- Raspberry pi Python scripts

# Details

- Scripts for Raspberry Pi for Blinking LEDs , Using different sensors etc

**Comment by dhriti987** [comment]
i Want to work on this.

**Comment by kaustubhgupta** [comment]
@dhriti987 these scripts are for real devices or for emulators?

**Comment by dhriti987** [comment]
real device

**Comment by kaustubhgupta** [comment]
@dhriti987 then how can we verify the working of the scripts because none of us has a raspberry device?

**Comment by dhriti987** [comment]
will this simulator work?
https://create.withcode.uk/python/A3

**Comment by dhriti987** [comment]
i never tried any simulator. I have raspberry pi 3 at my home

**Comment by kaustubhgupta** [comment]
@dhriti987 I don't have much knowledge on this and therefore I can't say anything. @antrikshmisri @santushtisharma10 do you have any idea of this?

**Comment by antrikshmisri** [comment]
@kaustubhgupta Same here and I don't know of any raspberry pi emulators. @santushtisharma10 What about you?
