### ISSUE TITLE
Script to scrape live cricket score from Cricbuzz

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#57]
# Aim

- Script to scrape live cricket score from Cricbuzz

# Details

- Add python script to scrape the live cricket score from Cricbuzz.com and send a toast notification in a given time interval

**Comment by bislara** [comment]
Hey i would like to work on this. Can you assign it to me?

**Comment by avinashkranjan** [comment]
Sure @bislara ... Go ahead..
