### ISSUE TITLE
Script to auto-attend Zoom Classes

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#58]
# Aim

- Create a Script to auto-attend Zoom Classes. 

# Details

- The basic features that should be present include:
> Get the Meeting ID and Meeting Password from the Console
> Open the Zoom Class keeping Camera/Audio off.

**Comment by SethWalkeroo** [comment]
Hello, I would like to do this.

**Comment by avinashkranjan** [comment]
@SethWalkeroo, Sure go ahead.. Assigned to you..
