### ISSUE TITLE
Desktop Daily Top News Notification App

### ISSUE THREAD

**Issue by vikashkumar2020** [avinashkranjan/Amazing-Python-Scripts#581]
# Aim

- a simple application which produces a notification message in the form of a pop-up message on desktop. It runs on your system and will be utilized to send you notifications after some time. notification on desktop will be top news headlines of the day which will be fetched from news website

# Details

- libraries like request, notify2, etc will be used to make this application

**Comment by kaustubhgupta** [comment]
@vikashkumar2020 What type of notifications will be script push?

**Comment by vikashkumar2020** [comment]
notification on desktop will be top news headlines of the day which will be fetched from news website

**Comment by kaustubhgupta** [comment]
@vikashkumar2020 okay then, rename the issue and description according to this "top news headlines of the day which will be fetched from news website".

**Comment by kaustubhgupta** [comment]
@vikashkumar2020 updates?

**Comment by vikashkumar2020** [comment]
I will complete it by tommorow it is in progress

**Comment by kaustubhgupta** [comment]
@vikashkumar2020 ?

**Comment by vikashkumar2020** [comment]
Actually my script runs well in ubuntu but does not in windows as it contains dbus module which is not there for windows. Please tell me should i make pull request with that script or try to find something else method.

**Comment by kaustubhgupta** [comment]
For windows desktop notifications, you can use plyer library

**Comment by kaustubhgupta** [comment]
@vikashkumar2020 you need to make the PR for this today only

**Comment by Amit366** [comment]
@kaustubhgupta can I work on this issue??

**Comment by kaustubhgupta** [comment]
@Amit366 assigned
