### ISSUE TITLE
Sticky notes GUI

### ISSUE THREAD

**Issue by vikashkumar2020** [avinashkranjan/Amazing-Python-Scripts#582]
# Aim

- A simple GUI based application in Python that helps you to create simple remember lists or sticky notes.

**Comment by kaustubhgupta** [comment]
@vikashkumar2020 assigned to you.

**Comment by kaustubhgupta** [comment]
@vikashkumar2020 updates?

**Comment by vikashkumar2020** [comment]
I will complete it by today it is in progress
