### ISSUE TITLE
Select Stocks by Volume Increases

### ISSUE THREAD

**Issue by Amit366** [avinashkranjan/Amazing-Python-Scripts#586]
# Aim

- Script to determine and choose stocks whose volume increased over a given amount of time

# Details

-The user can provide the dataset, number of days for comparison and also how many times the volume must be increased. Then after taking the inputs the script will check and give the results of the stocks.

Updates: Made it real-time, inc points

**Comment by kaustubhgupta** [comment]
@Amit366 I didn't understand the issue. Can you explain in some other way?

**Comment by Amit366** [comment]
Like there will be a dataset of stocks . The script will compare the stock values and over a few days and return the stocks whose cost have increased.

**Comment by kaustubhgupta** [comment]
@Amit366 so that will be over an old dataset and not in real-time?

**Comment by Amit366** [comment]
Not in real time

**Comment by kaustubhgupta** [comment]
@antrikshmisri @santushtisharma10 what do you think of this?

**Comment by Amit366** [comment]
@kaustubhgupta If you want then I can work on real-time too.

**Comment by antrikshmisri** [comment]
@kaustubhgupta Let's give it a try ,@Amit366 can add real-time support later on.

**Comment by kaustubhgupta** [comment]
@antrikshmisri okay! @Amit366 assigned to you

**Comment by kaustubhgupta** [comment]
@Amit366 updated description and level
