### ISSUE TITLE
Edge Detction of a image using OpenCV

### ISSUE THREAD

**Issue by ShubhamGupta577** [avinashkranjan/Amazing-Python-Scripts#589]
# Aim

In this Script, we going to detect the edges of an image using a python script.

# Details

In our script, the user has to just upload a picture and as an output, he/she will get an edge-detected picture. For this purpose, we are going to use OpenCV.
It is very useful because edges are the points in images where the color or brightness has great changes.

**Comment by ShubhamGupta577** [comment]
@kaustubhgupta I want to work on this under GSSOC'21. Please assign me this issue.

**Comment by kaustubhgupta** [comment]
@ShubhamGupta577 assigned to you
