### ISSUE TITLE
Python Image Processing🎬

### ISSUE THREAD

**Issue by Lakhankumawat** [avinashkranjan/Amazing-Python-Scripts#590]
# Aim 
- To add some projects/Examples depicting the use of Image Processing and Image Enhancing using Python

# Details
- To show how image are processed and can be used in python 
- To show how the Python Image Libraries such as Pillow works and their uses.
- To show compressing , Resizing and Enhancing images through python script

**Comment by Lakhankumawat** [comment]
I would like to work on this issue ...

**Comment by kaustubhgupta** [comment]
@Lakhankumawat assigned to you. Add only examples not any project.

**Comment by Lakhankumawat** [comment]
I got a doubt , i had earlier pull requests but due to some issues they weren't merged and the PR was closed and  if i commit to my fork after completing this issue . Does all those earlier commits will be a problem .
_Or do I_
 

a. Delete my fork and start commiting again from fresh .
b.  Create a branch of my fork and that than pull as request (Compare across fork like that ) . 

Please Guide

**Comment by kaustubhgupta** [comment]
@Lakhankumawat option B: create a branch of your fork and then a new pull request. Further, you can also delete the local branch via this command: git branch -d nameofbranch or git branch -D nameofbranch.

This will delete your local branch. To further explore on how to delete remote branch, you can refer this article: https://www.git-tower.com/learn/git/faq/delete-remote-branch/
