### ISSUE TITLE
Crossword Solver in python

### ISSUE THREAD

**Issue by aliya-rahmani** [avinashkranjan/Amazing-Python-Scripts#594]
The idea behind the Crossword Solver is you type a word with some letters missing, and the program works out all the possible words that would fit with the known letters and spaces.

@kaustubhgupta  Please assign me this task.

**Comment by kaustubhgupta** [comment]
@aliya-rahmani interesting, assigned to you!

**Comment by kaustubhgupta** [comment]
@aliya-rahmani updates?

**Comment by aliya-rahmani** [comment]
@kaustubhgupta, it's in progress, will make a PR soon.

**Comment by kaustubhgupta** [comment]
@aliya-rahmani Did you made any progress?

**Comment by aliya-rahmani** [comment]
@kaustubhgupta I have made a PR #684
