### ISSUE TITLE
Steganography

### ISSUE THREAD

**Issue by dhriti987** [avinashkranjan/Amazing-Python-Scripts#599]
# Aim

- Python Script for Steganography

# Details

- Hiding text inside an Image and retrieving The text from an Image

**Comment by dhriti987** [comment]
I would like to work on this.

**Comment by kaustubhgupta** [comment]
@dhriti987 assigned to you

**Comment by dhriti987** [comment]
Should i make command line options?

**Comment by kaustubhgupta** [comment]
@dhriti987 That's totally up to you, btw what type of options you suggest?

**Comment by dhriti987** [comment]
@kaustubhgupta 
-e  encode
-o encoded image file name 
-d decode
-t output decoded data in text file

**Comment by dhriti987** [comment]
is there any deadline for submission.... Actually my exams are going on

**Comment by kaustubhgupta** [comment]
@dhriti987 options are fine, you can go ahead with coding. You have 1 week to implement it.

**Comment by kaustubhgupta** [comment]
@dhriti987 did you made any progress in the script?

**Comment by dhriti987** [comment]
Yes...... should I have to make readme file?
i will make a PR tomorrow.

**Comment by kaustubhgupta** [comment]
Yes, a readme file is required.

**Comment by dhriti987** [comment]
@kaustubhgupta i have made a pull request... please review it
