### ISSUE TITLE
Instagram Profile Pic Downloader

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#60]
# Aim

- Script to download Instagram Profile Pic when given a username

# Details

- Develop a script in Python to download Instagram profile photos when given a username

**Comment by hardikkhurana** [comment]
Hii @avinashkranjan, I am new to hacktober fest and this is my first time working on a project. Can you assign me this project I can do this with python3.
Thanks in advance..

**Comment by avinashkranjan** [comment]
@hardikkhurana .. Sure.. Happy Coding... 😊

**Comment by hardikkhurana** [comment]
I have completed the task.
Thank you for giving me this chance I hope you like my work.

**Comment by avinashkranjan** [comment]
@hardikkhurana Kindly make the asked changes..

**Comment by Tanujcbe** [comment]
Can I work on the task?

**Comment by avinashkranjan** [comment]
@Tanujcbe .. @hardikkhurana is already working on it.. and has pushed a script ..You can work on some order scripts... Or Create an Issue and add a script for the same..

**Comment by Tanujcbe** [comment]
@avinashkranjan Can I work on amazon prize tracker?

**Comment by avinashkranjan** [comment]
@Tanujcbe We already have a script for the same... you can create a Price tracker for some other shopping site...

**Comment by Tanujcbe** [comment]
@avinashkranjan Can I create an IPL score automater?

**Comment by avinashkranjan** [comment]
@Tanujcbe Sure.... Go ahead Create a Issue of Script Addition for the Same...
