### ISSUE TITLE
Alarm clock with GUI in python

### ISSUE THREAD

**Issue by Anupreetadas** [avinashkranjan/Amazing-Python-Scripts#600]
# Aim

- The objective is to implement an alarm clock using python. Basically the aim is to build the project using the current date and time as well as to provide a user interface to set the alarm according to the requirement in 24-hour format.

# Details

- Tkinter module in python will help to create a dialog box with any information that we want to provide or get from the users.
-Datetime and time modules in python will help to work with the dates and time of the current day when the user is operating python and to manipulate it too.
-Winsound module will provide access to the basic sound playing machinery provided by Windows platforms. This is useful to generate the sound immediately when a function is called.

**Comment by kaustubhgupta** [comment]
@Anupreetadas interesting, assigned to you!

**Comment by kaustubhgupta** [comment]
@Anupreetadas issue closed
