### ISSUE TITLE
YouTube Video Downloader with GUI

### ISSUE THREAD

**Issue by mehabhalodiya** [avinashkranjan/Amazing-Python-Scripts#602]
# Aim

- **YouTube Video Downloader** is an application to download videos from YouTube. This provides users to download videos they need in their devices and watch them offline.
- The objective of this script is to download any type of video in a fast and easy way from YouTube in your device.

# Details

- In this python script, user has to copy the YouTube video URL that they want to download and simply paste that URL in the ‘paste link here’ section and click on the download button, it will start downloading the video. When video downloading finishes, it shows a message ‘downloaded’ popup on the window below the download button.
- It will look like this:

![YTVD](https://user-images.githubusercontent.com/73488906/111301619-6eeaa100-8678-11eb-9ef2-5ce1b02571cf.png)

**Comment by mehabhalodiya** [comment]
I would like to work on this under GSSOC'21.

**Comment by mehabhalodiya** [comment]
@antrikshmisri @kaustubhgupta Kindly assign this to me.

**Comment by kaustubhgupta** [comment]
@mehabhalodiya assigned to you
