### ISSUE TITLE
AI Integrated Ludo Game Made In Python Tkinter

### ISSUE THREAD

**Issue by SamarpanCoder2002** [avinashkranjan/Amazing-Python-Scripts#604]
# Aim

Play Game With Artifical Intelligence at the time of loniliness

# Details

I make AI-Integrated Ludo Game in Python Tkinter...... In this, You can play with computer as well as your friends

I am also a gssoc'21 participant....please assign me to here @avinashkranjan

**Comment by kaustubhgupta** [comment]
@SamarpanCoder2002 assigned to you

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 assigned to you

Pull request already attached..... Please review @kaustubhgupta and merge it... Thanks
