### ISSUE TITLE
Spotify Downloader

### ISSUE THREAD

**Issue by muthuannamalai12** [avinashkranjan/Amazing-Python-Scripts#607]
# Aim
- What is the objective of the Script
- To download songs from Spotify

# Details
My script does the following
- Downloads music from Spotify as an MP3 file.
- Applies basic on metadata like track name, track number, album, genre and more.

**Comment by muthuannamalai12** [comment]
Kindly assign me this issue as a part of gssoc'21 @avinashkranjan

**Comment by kaustubhgupta** [comment]
@muthuannamalai12 you already have two 2 active PRs with bugs.

**Comment by kaustubhgupta** [comment]
@muthuannamalai12 updates?

**Comment by muthuannamalai12** [comment]
Will complete within today

**Comment by Sibasish-Padhy** [comment]
hi @kaustubhgupta i am a gssoc participant 2021 and I want to contribute to this issue can u assign me this task

**Comment by Sibasish-Padhy** [comment]
thank you @kaustubhgupta can u gimme the deadline to submit the pr??

**Comment by kaustubhgupta** [comment]
@Sibasish-Padhy 7 days from the day of the assignment. I will ping you on 3rd day for updates

**Comment by Sibasish-Padhy** [comment]
sir I have searched for the implementation of the project from some sources,one of them being a simple implementation of spotdl in google collab and nothing more,although I have to do it in pycharm can doing it in collab is allowable?if not,then I ain't able to understand how to put together the script as this is my first time i have forked my repo and cloned it to my local machine.now a bit of more guidance from your side can be helpful.It is my first time here and I being a noob wanna learn something useful. thank you

**Comment by kaustubhgupta** [comment]
@Sibasish-Padhy look at this closed PR, maybe you can fix this code: https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/688

**Comment by Sibasish-Padhy** [comment]
okay sir thank you

**Comment by kaustubhgupta** [comment]
@Sibasish-Padhy updates?

**Comment by Sibasish-Padhy** [comment]
sir working on it ....but the code's working absolutely fine on my laptop(the code you assigned me for fixing) so what shall i do now? can you please help!!!

**Comment by kaustubhgupta** [comment]
@Sibasish-Padhy That code has been copied from the documentation and that's why it was marked as plag. Your task is to implement it in your own way

**Comment by Sibasish-Padhy** [comment]
okay sir will try to submit by sunday @kaustubhgupta thank you

**Comment by kaustubhgupta** [comment]
You need to submit PR within 3 days(till sunday), after that  the issue will be assigned to someone else

**Comment by Sibasish-Padhy** [comment]
@kaustubhgupta sir have created a draft pr for you to review the code and give better suggestions on improving the code....please do review it and suggest me how to improve on my fallacies
