### ISSUE TITLE
PDF2text

### ISSUE THREAD

**Issue by muthuannamalai12** [avinashkranjan/Amazing-Python-Scripts#608]
# Aim

- What is the objective of the Script
To convert PDF to Text
# Details

- What the features will your script have
My script converts PDF to Text

**Comment by muthuannamalai12** [comment]
Kindly assign me this issue as a part of gssoc'21 @avinashkranjan

**Comment by kaustubhgupta** [comment]
@muthuannamalai12 same reason as given in last issue

**Comment by kaustubhgupta** [comment]
@muthuannamalai12 updates?

**Comment by muthuannamalai12** [comment]
Will complete within today

**Comment by Amit366** [comment]
@kaustubhgupta I would like to work on this issue??

**Comment by kaustubhgupta** [comment]
@Amit366 assigned to you

**Comment by Amit366** [comment]
@kaustubhgupta I have a doubt. Like you said to display the text in different files so I tried the code which you suggested above but only one file is created.

**Comment by Amit366** [comment]
Could you please help me??

**Comment by Amit366** [comment]
![Screenshot (125)](https://user-images.githubusercontent.com/60662775/112299464-d4b0db80-8cbd-11eb-982f-0d66d72e5ccc.png)
