### ISSUE TITLE
Temporary Registrations and Sign-Up Tool

### ISSUE THREAD

**Issue by DevLokCodes** [avinashkranjan/Amazing-Python-Scripts#61]
# Aim

- Objective of the Script : To generate a Python script to help with temporary details for signups and registrations and to avoid spams if real details are given.

# Details

- Features of the Script : A python script that generate a new temporary profile that can be used for annoying logins, sign ups, registrations etc.

> Script will create a username, temporary email id, strong password

**Comment by avinashkranjan** [comment]
@DevLokCodes Do you want to work on this script?

**Comment by DevLokCodes** [comment]
yeaa i would like to work on it

**Comment by avinashkranjan** [comment]
@DevLokCodes Go ahead then...

**Comment by DevLokCodes** [comment]
thankyou for accepting my issue 👍🙌

**Comment by avinashkranjan** [comment]
@DevLokCodes It was great idea for a script..🚀
