### ISSUE TITLE
Contour/Shape Detection

### ISSUE THREAD

**Issue by mehabhalodiya** [avinashkranjan/Amazing-Python-Scripts#611]
# Aim

- How to detect shapes of objects by finding their contours.

# Details

- Contours are basically outline that bound the shape or form of an object. So we will be detecting multiple shapes and how many corners points each shape has along with its area .

**Comment by mehabhalodiya** [comment]
I would like to work on this under GSSOC'21.

**Comment by kaustubhgupta** [comment]
@mehabhalodiya Your one PR is under review and I just assigned you one issue. So this issue will be assigned to you after that PR is approved by all mentors and ready to merge. Until then if anyone else claims this issue, then I can't say no to them.
