### ISSUE TITLE
Connect 4 game

### ISSUE THREAD

**Issue by syamala27** [avinashkranjan/Amazing-Python-Scripts#614]
**I have created a `connect-4`  game using `Python`.** 

### **_Game rules:_**

1. Get ready :)
2. 4 consecutive  balls should match of same colour `horizontally`   `vertically` `diagonally ( either of both)`
3. That's it now u r ready to play the game :)
@santushtisharma10 @tamanna-verma @antrikshmisri @kaustubhgupta please assign me the project.

I am sharing a glimpse of it. 
 > ### **Image-1**

![image](https://user-images.githubusercontent.com/58478495/111271009-a2b4cf00-8656-11eb-8ebc-7f7bdf990804.png)

> ### **Image-2**

![image](https://user-images.githubusercontent.com/58478495/111271224-e60f3d80-8656-11eb-9c20-311b497d62f9.png)

**Comment by antrikshmisri** [comment]
@syamala27 Assigned to you
