### ISSUE TITLE
script to retrieve stored network passwords in computer

### ISSUE THREAD

**Issue by aaadddiii** [avinashkranjan/Amazing-Python-Scripts#617]
# Aim

- Script to retrieve stored network passwords in computer

# Details

- Network passwords are stored inside the computer , once connected . This python script retrieves all these stored passwords

**Comment by kaustubhgupta** [comment]
@aaadddiii Please confirm if your script is different from this https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Get-Wifi-Password and this https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Save-Wifi-Password
