### ISSUE TITLE
Twitter Fetcher

### ISSUE THREAD

**Issue by Ayushjain2205** [avinashkranjan/Amazing-Python-Scripts#621]
# Aim

To get tweets automatically from users feed

# Details

User can get top trending tweets by hashtag as per their choice

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 can you store the tweets retrieved in the SQL database? Because fetching them via Twitter API an easy task

**Comment by Ayushjain2205** [comment]
@kaustubhgupta  Yes I can do that, will store the tweets in a SQL database after fetching them

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 Okay assigned to you. Create two scripts: One to get tweets and storing them in the database. Another script to fetch the data from this database and display on the terminal
