### ISSUE TITLE
Life Expectancy Prediction

### ISSUE THREAD

**Issue by guptadiksha307** [avinashkranjan/Amazing-Python-Scripts#625]
# Aim

- Life Expectancy Prediction using Machine Learning

# Details

- A typical Regression Machine Learning project leverages historical data to predict insights into the future. This problem statement is aimed at predicting Life Expectancy rate of a country given various features. Life expectancy is a statistical measure of the average time a human being is expected to live, Life expectancy depends on various factors: Regional variations, Economic Circumstances, Sex Differences, Mental Illnesses, Physical Illnesses, Education, Year of their birth and other demographic factors. This problem statement provides a way to predict average life expectancy of people living in a country when various factors such as year, GDP, education, alcohol intake of people in the country, expenditure on healthcare system and some specific disease related deaths that happened in the country are given.

**Comment by guptadiksha307** [comment]
Kindly assign me this issue as a part of gssoc'21 @avinashkranjan

**Comment by kaustubhgupta** [comment]
@guptadiksha307 Assigned to you, refer to this PR files on how to structure your files and creating the prediction script https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/556
