### ISSUE TITLE
Slithering Snake Game using GUI

### ISSUE THREAD

**Issue by Swetha126** [avinashkranjan/Amazing-Python-Scripts#626]
**Describe the solution you'd like**
I would like to create a slithering snake game using GUI in python

**Additional context**
It is a user friendly game with a clear score board. I would write the code with appropriate comments. 

I'm a GSSOC'21 participant. Please assign me this issue

**Comment by kaustubhgupta** [comment]
@Swetha126 We already have a snake game in our repo: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Snake%20Game%20(GUI)
