### ISSUE TITLE
Desktop Drink Water Notification

### ISSUE THREAD

**Issue by viraldevpb** [avinashkranjan/Amazing-Python-Scripts#627]
# Aim

- To get enough water for our body.

# Details

- The desktop water notification displays the notification on the desktop every one minute or 30 seconds to the user to drink water. Because water is an essential need of our body.

**Comment by kaustubhgupta** [comment]
@viraldevpb Do you think spamming users every 30 seconds or minute will be useful? It will consume a lot of background resources. Any other workaround for this?

**Comment by viraldevpb** [comment]
Mine Python Script just uses one process in the background. So It will not
run any another processes in the background.

**Comment by kaustubhgupta** [comment]
@viraldevpb reduce the interval of notification to 30 minutes

**Comment by viraldevpb** [comment]
Is this time code is correct?
![dis](https://user-images.githubusercontent.com/66899360/111595604-4ab2cf80-87f2-11eb-9192-3bdfaf43a628.png)
