### ISSUE TITLE
Eye detection

### ISSUE THREAD

**Issue by Avishake007** [avinashkranjan/Amazing-Python-Scripts#629]
I want to add a eye detection feature.
please assign me for this issue

**Comment by kaustubhgupta** [comment]
@Avishake007 Eye detection in videos or images?

**Comment by Avishake007** [comment]
Eye detection in video

**Comment by kaustubhgupta** [comment]
Okay assigned to you, Currently, I am looking into your body detection PR. I will let you know any changes
