### ISSUE TITLE
Tetris : The Game

### ISSUE THREAD

**Issue by lachenlama** [avinashkranjan/Amazing-Python-Scripts#632]
# Aim

- To build the evergreen game, Tetris!

# Details

- Going to be built with Pygame , simple yet effective OOP shall be featured, will try to build it as colorful as possible.

**Comment by lachenlama** [comment]
Gonna finish it up as soon as my exams over k, can I get some time like 3-4 days? @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@lachenlama you got 3 days more to complete it

**Comment by kaustubhgupta** [comment]
@lachenlama Updates?

**Comment by lachenlama** [comment]
Gonna PR today working on the readme.md file atm @kaustubhgupta
