### ISSUE TITLE
Censor word detection

### ISSUE THREAD

**Issue by jeelnathani** [avinashkranjan/Amazing-Python-Scripts#636]
I am GSSOC 21 participant. And I would like to contribute here by making program that can detect censor word

**Comment by kaustubhgupta** [comment]
@jeelnathani I am not sure what your program is about?

**Comment by jeelnathani** [comment]
censor words are swear words/abusive words/curse words/bad words in any language 
example: shit, fu*k

**Comment by kaustubhgupta** [comment]
@jeelnathani Ohkay got it, you can start working on this issue
