### ISSUE TITLE
Converting image to pencil sketch using python

### ISSUE THREAD

**Issue by vaishnavirshah** [avinashkranjan/Amazing-Python-Scripts#639]
# Aim

Converting image to pencil sketch

# Details

- Capturing live images from webcam.
- Or Uploading image to the webpage.
- Implementation of script using flask

**Comment by vaishnavirshah** [comment]
I am GSSOC'21 participant and would like to contribute this script.

**Comment by kaustubhgupta** [comment]
@vaishnavirshah make it a script application where you take the path of the image as input, then convert the image into sketch form and then save that output image

**Comment by vaishnavirshah** [comment]
@kaustubhgupta Hi, I did not quite understand your suggestion, I have implemented both taking images from webcam and converting to sketch as well as taking image path and converting to sketch on the webpage.

Should I not use flask? And implement both these things as a menu driven script?

**Comment by kaustubhgupta** [comment]
@vaishnavirshah Yes, port those features to the menu-driven script as we are not looking for end-to-end applications
