### ISSUE TITLE
Face Recognition

### ISSUE THREAD

**Issue by Debashish-hub** [avinashkranjan/Amazing-Python-Scripts#642]
**Is your feature request related to a problem? Please describe.**
There is a script for face detection but that won't predict whose face is that for which face recognition will be helpful.

**Describe the solution you'd like**
Face Recognition system would show the name of the person in real time from the stored database.

It would be great if I would be assigned with this issue as a GSSOC'21 participant @avinashkranjan 

Thank you

**Comment by kaustubhgupta** [comment]
we already have a script for this: https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Face-Detection/face-detect.py
And for known faces, we already have a PR under review: https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/585
