### ISSUE TITLE
Script Idea: Spotify Song data scrapper

### ISSUE THREAD

**Issue by AM1CODES** [avinashkranjan/Amazing-Python-Scripts#644]
# Aim

- Let's user scrape Songs data from Spotify.

# Details

- This script will help anyone scrape songs data such as the artist name, song name, album name and so on.
- Can come in handy when a person wishes to build a song recommender using real songs from Spotify.

P.S -  I am a GSSOC'21 Participant.

**Comment by kaustubhgupta** [comment]
@AM1CODES We already have an assigned issue for this #607
