### ISSUE TITLE
Image Editor python script

### ISSUE THREAD

**Issue by asmita20aggarwal** [avinashkranjan/Amazing-Python-Scripts#647]
**# Aim**

I will be using python pillow library to edit images.
The program is going to be menu driven.

**# Details**

The user will be asked to enter the specified path of the image and save it at the desired location by providing the path.
The user will be able to flip the images,rotate the images, enhance their contrast or sharpness and apply different filters onto the image.(black and white , sepia, negative etc)
These filters will be made by changing the RGB values of the image.
I will be adding my own custom filters such as dracula, canary yellow and rust.

**Comment by asmita20aggarwal** [comment]
I am a GSSOC'21 participant and would like to contribute to this script. 
Please assign it to me.

**Comment by antrikshmisri** [comment]
@asmita20aggarwal Assigned to you

**Comment by kaustubhgupta** [comment]
@asmita20aggarwal Updates?

**Comment by asmita20aggarwal** [comment]
@kaustubhgupta I am almost done with the script. Need to resolve some bugs, do some pep8 checks and make a read.me file.

![Screenshot (45)](https://user-images.githubusercontent.com/55752845/111895058-f7c95a00-8a35-11eb-8957-f51b2f18fc9e.png)
![pink](https://user-images.githubusercontent.com/55752845/111895070-09aafd00-8a36-11eb-80d4-8cee5b1b46dc.png)
![Edited](https://user-images.githubusercontent.com/55752845/111895075-0f084780-8a36-11eb-831c-265c815beada.png)

**Comment by kaustubhgupta** [comment]
Okay, Good progress!

**Comment by kaustubhgupta** [comment]
@asmita20aggarwal?

**Comment by asmita20aggarwal** [comment]
@kaustubhgupta Sir my script is all done. But I was stuck on how to make the readme.md file. Is it necessary to add readme.md file along with script or I can do that later too ? Shall I make the PR ?
