### ISSUE TITLE
Morse Code Translator In Python

### ISSUE THREAD

**Issue by aishwaryachand** [avinashkranjan/Amazing-Python-Scripts#649]
# Aim

- What is the objective of the Script
Create a Morse Code Translator In Python
# Details

- What features will your script have

Translate the given morse code to English

**Comment by aishwaryachand** [comment]
I am GGSOC21' participant can I work on this issue.

**Comment by antrikshmisri** [comment]
@aishwaryachand Sure , assigned to you

**Comment by kaustubhgupta** [comment]
@aishwaryachand updates?
