### ISSUE TITLE
Unzip a File

### ISSUE THREAD

**Issue by Priya96-sketch** [avinashkranjan/Amazing-Python-Scripts#651]
# Aim

- To unzip a zipped file using Python
# Details

- Going to be built with zipfile module , simple yet effective.

**Comment by Priya96-sketch** [comment]
I am GGSOC21' participant , Can I work on this issue?

**Comment by kaustubhgupta** [comment]
@Priya96-sketch Yes, assigned to you

**Comment by Priya96-sketch** [comment]
Thank You! I will start working on it now.

**Comment by kaustubhgupta** [comment]
@Priya96-sketch Updates?

**Comment by Priya96-sketch** [comment]
Yes I have uploaded the code, and it's successfully working.
Should I upload some screenshots to make it more clear?

**Comment by kaustubhgupta** [comment]
> Yes I have uploaded the code, and it's successfully working.
> Should I upload some screenshots to make it more clear?

You need to make a PR in this repo for us to review your code

**Comment by Priya96-sketch** [comment]
Okay.

**Comment by kaustubhgupta** [comment]
@Priya96-sketch?

**Comment by kaustubhgupta** [comment]
@Priya96-sketch WIll you make the PR today?

**Comment by Amit366** [comment]
@kaustubhgupta can I work??

**Comment by kaustubhgupta** [comment]
Yes, assigned to you
