### ISSUE TITLE
Notepad GUI

### ISSUE THREAD

**Issue by Ayushjain2205** [avinashkranjan/Amazing-Python-Scripts#653]
# Aim

Create a notepad clone using python(Tkinter)

# Details

Users can make text files, edit , copy, paste and save these text files using this application

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 It's already implemented in this repo: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Simple%20Notepad
