### ISSUE TITLE
Plagiarism checker in Python

### ISSUE THREAD

**Issue by Anupreetadas** [avinashkranjan/Amazing-Python-Scripts#655]
# Aim

- The objective of the script is to detect plagiarism in textual document using python.
# Details
This is a plagiarism checker made in python.It will compare the text files and tell if the document is copied or not.

# Features
 - Handling quotations
 - Automating the collection of training data.
 -  Comparing different submissions  to each other.
 -  Adapting this to work for plagiarized text.
 -  Checking if the text document is copied from google source.

**Comment by kaustubhgupta** [comment]
Sounds interesting, @Anupreetadas assigned to you!

**Comment by ANAMIKA1410** [comment]
def check_plagiarism():
    plagiarism_results = set()
    global s_vectors
    for student_a, text_vector_a in s_vectors:
        new_vectors =s_vectors.copy()
        current_index = new_vectors.index((student_a, text_vector_a))
        del new_vectors[current_index]
        for student_b , text_vector_b in new_vectors:
            sim_score = similarity(text_vector_a, text_vector_b)[0][1]
            student_pair = sorted((student_a, student_b))
            score = (student_pair[0], student_pair[1],sim_score)
            plagiarism_results.add(score)
    return plagiarism_results
Let’s print plagiarism results
for data in check_plagiarism():
    print(data)
