### ISSUE TITLE
Modification in Face-Detection/face-detect.py 

### ISSUE THREAD

**Issue by anubhav201241** [avinashkranjan/Amazing-Python-Scripts#657]
**Problem**
The code is not fully optimized and have less feature in it.

**Solution I'd like to add**
So I want to add more feature and optimized python code using open-cv in it
Feature I will be working upon is:

1) Which Detects the Mid part in the face.
2) Detects the eyes and face part , by Putting them in rectangle frame as image.

**Additional context**
I will be highly Obliged if you assign this task to me So please assign this updating part to me so I can update this code and add some feature and value in it.
Thank You :))

**Comment by kaustubhgupta** [comment]
@anubhav201241 we already have a script for this in our repo: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Face-Detection

**Comment by anubhav201241** [comment]
Sir, I have made the changes that you suggested, Please inform me if any other changes are needed?
