### ISSUE TITLE
Wikipedia Summary Generator (GUI)

### ISSUE THREAD

**Issue by Ayushjain2205** [avinashkranjan/Amazing-Python-Scripts#671]
# Aim

To display summary of a topic entered by the user 

# Details

When a user searches for a topic, a summary is displayed in the results box

**Comment by Ayushjain2205** [comment]
@kaustubhgupta Can you please assign this issue to me under GSSOC'21

**Comment by santushtisharma10** [comment]
@Ayushjain2205 assigned to you
