### ISSUE TITLE
Generation and accessing of QR code

### ISSUE THREAD

**Issue by sayantani11** [avinashkranjan/Amazing-Python-Scripts#673]
# Aim

- Generating a QR code and reading it 

# Details

- QR code is basically quick response code. We will generate QR code for links for easy access

**Comment by archana-9430** [comment]
Hi @sayantani11 , please allow me to work on this issue. I know how to make QR code in python. 
Thanks :)

**Comment by santushtisharma10** [comment]
@archana-9430 we already have QR generator script. You may look other issues which are up-for-grabs
