### ISSUE TITLE
Detect and Recognize Car License Plate

### ISSUE THREAD

**Issue by mehabhalodiya** [avinashkranjan/Amazing-Python-Scripts#675]
# Aim

- The objective is to design an efficient automatic authorized vehicle identification system by using the vehicle number plate.

# Details

- Number plate detection searches the image taken in order to locate the specific features that contain the number plate. The system makes use of OpenCV—Open source Computer Vision—to convert data from images on a camera to useful information.

**Comment by mehabhalodiya** [comment]
I would like to work on this under GSSOC'21.

**Comment by santushtisharma10** [comment]
@mehabhalodiya assigned to you
