### ISSUE TITLE
Clicking the hyperlink in Temporary-Sign-Up-Tool

### ISSUE THREAD

**Issue by chaitanyabisht** [avinashkranjan/Amazing-Python-Scripts#679]
Script folder: [https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Temporary-Sign-Up-Tool](url)

**Describe the bug**
Clicking the 10minutemail hyperlink in the webpage does not open the correct webpage

**To Reproduce**
1. Run the script
2. Click on '10minutemail.net' hyperlink

**Expected behavior**
It should open the 10minutemail.net website.

**Comment by kaustubhgupta** [comment]
@chaitanyabisht you are a participant of GGSOC or doing this contribution casually?

**Comment by chaitanyabisht** [comment]
> @chaitanyabisht you are a participant of GGSOC or doing this contribution casually?

I am a participant of GSSOC
