### ISSUE TITLE
GUI Chat application

### ISSUE THREAD

**Issue by aliya-rahmani** [avinashkranjan/Amazing-Python-Scripts#686]
# Aim

This is a simple GUI (Graphical User Interface) chat application where multiple users can connect with each other in a client-server architecture i.e the clients will interact with the help of the server.

# Details

The Python Chatbox uses the concept of Socket Programming & Multi-threading. There are two sections for the chatbot i.e server-side program called socketserver.py & client-side program namely chat.py. It allows a chat room or chat box to connect with multiple users at the same time.

**Comment by kaustubhgupta** [comment]
@aliya-rahmani Go ahead with the issue

**Comment by Yuvraj-kadale** [comment]
I would like to give this a try @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@Yuvraj-kadale Sure!

**Comment by amrzaki2000** [comment]
Hello,
I'd like to work on this.
@santushtisharma10

**Comment by santushtisharma10** [comment]
@amrzaki2000 go ahead, assigned to you

**Comment by kaustubhgupta** [comment]
@amrzaki2000 updates on this?

**Comment by amrzaki2000** [comment]
> 
> 
> @amrzaki2000 updates on this?

I'll make PR in three days I just have some quizzes at college for now

**Comment by kaustubhgupta** [comment]
@amrzaki2000 updates?

**Comment by kaustubhgupta** [comment]
@amrzaki2000?

**Comment by amrzaki2000** [comment]
> 
> 
> @amrzaki2000?

I'm sorry I'm having quizzes and I stopped working temporarily.
Can I get two more days only ?

**Comment by kaustubhgupta** [comment]
@amrzaki2000 Okay, no issues!

**Comment by kaustubhgupta** [comment]
@amrzaki2000 Today is the last date for this. I have given this day as per your contributions in the past.

**Comment by subhangi2731** [comment]
@santushtisharma10 please assign me this I will send a pr in 2 days

**Comment by kaustubhgupta** [comment]
@subhangi2731 you didn't make the PR for the Linear search visualizer. Wil you make the PR for this?

**Comment by subhangi2731** [comment]
@kaustubhgupta I had exams in my college so couldn't send the pr. U need to tell me the deadline for till when I should send the pr and I am sorry for that

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta I had exams in my college so couldn't send the pr. U need to tell me the deadline for till when I should send the pr and I am sorry for that

As told earlier, max of 7 days. On 5th day, you need to tell the share the status of the work done.
