### ISSUE TITLE
Cartoonify an image using OpenCV

### ISSUE THREAD

**Issue by undetectablevirus** [avinashkranjan/Amazing-Python-Scripts#690]
# Aim

- We will be able to get the cartoonified version of an image with the help of OpenCV

# Details

- We will be using filters for this purpose

**Comment by kaustubhgupta** [comment]
We already merged PR for this issue 2 days ago: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Cartooning%20Image
