### ISSUE TITLE
Morse Code

### ISSUE THREAD

**Issue by ssm0801** [avinashkranjan/Amazing-Python-Scripts#697]
# Aim

To encrypt and decrypt morse code.

# Details

It will encrypt the given message in morse code as well as decrypt the morse code, It will also encrypt and decrypt audio form of morse code.

**Comment by kaustubhgupta** [comment]
@ssm0801 We already have this issue taken: https://github.com/avinashkranjan/Amazing-Python-Scripts/issues/649

**Comment by ssm0801** [comment]
We can add audio feature in previous one

**Comment by kaustubhgupta** [comment]
@ssm0801 okay then, when the previous one get merged, you can raise the issue again to improve that code.
