### ISSUE TITLE
Amazon web-scraper

### ISSUE THREAD

**Issue by sarthak1905** [avinashkranjan/Amazing-Python-Scripts#70]
# Aim

Recieve an email when the price of an Amazon product drops below your budget

# Details

This script inputs three things- the link of the Amazon product, your budget for it and how frequently you wish to monitor its price. That's it- keep the script running in background and you will receive an email alerting you when the price is within your budget! 

PS- The exact instructions to do so will be provided in the README.md

**Comment by sarthak1905** [comment]
Hey, I would like to contribute to this issue. Could I please be assigned the same?

Thanks and Regards
Sarthak Saxena

**Comment by avinashkranjan** [comment]
@sarthak1905 Assigned to you.. Happy Coding..😊
