### ISSUE TITLE
Your meeting buddy

### ISSUE THREAD

**Issue by Yuvraj-kadale** [avinashkranjan/Amazing-Python-Scripts#702]
# Aim

This script aims to join the google meetings at a **_scheduled_** time in our absence. 

# Details

- Auto joining meets in our absence.
- joining at a scheduled time.
- Complete discussion is recorded in local machine.

**Comment by Yuvraj-kadale** [comment]
I would like to work on this as a part of Gssoc 21 :)

**Comment by santushtisharma10** [comment]
@Yuvraj-kadale go ahead, assigned to you
