### ISSUE TITLE
GUI QR code genrator system with python

### ISSUE THREAD

**Issue by Goheljay** [avinashkranjan/Amazing-Python-Scripts#703]
my name is Jay Gohel.  Participate in GSSOC'21.

**Aim***
- This is GUI(Graphical User interface) based QR code generator system using python. 

**Description**
- in this app, I can make GUI using Tkinter. Genrate the qrcode usinf PyPi.  
- can you assign me this feature?

**Comment by kaustubhgupta** [comment]
QR code will be generated for what purpose?

**Comment by Goheljay** [comment]
storing employee details like employee name, id, designation, department, etc...

**Comment by Goheljay** [comment]
kindly assign me. I am gssoc participant

**Comment by kaustubhgupta** [comment]
Kindly explain your issue in detail. How will QR code generator store employee details?

**Comment by Goheljay** [comment]
- I make four fields where entering employee details like employee ID, name, Designation, Department. after you can click on the "QR Code generate" Button then generate the QR code. after converting those QR codes into IMG and store in another IMG folder.

- this project completely made using core python, Tkinter.

**Comment by kaustubhgupta** [comment]
QR code will store information about what? What will happen when someone scans the QR code

**Comment by Goheljay** [comment]
when someone does a scan QR code, then the detail of the employee who entered it will be displayed.

**Comment by kaustubhgupta** [comment]
@Goheljay Okay, assigned to you

**Comment by Goheljay** [comment]
@kaustubhgupta I have submitted my PR. Please check it out.
