### ISSUE TITLE
BRICK BREAKER GAME GUI

### ISSUE THREAD

**Issue by priyanka001tech** [avinashkranjan/Amazing-Python-Scripts#704]
**Is your feature request related to a problem? Please describe.**
brick breaker game gui based

**Additional context**
I would like to do it as a gssoc particiapnt..

**Comment by kaustubhgupta** [comment]
@priyanka001tech assigned to you

**Comment by priyanka001tech** [comment]
I closed the previous pull request .After completing the project I'll make an another new pull request so that you can review that one.

**Comment by kaustubhgupta** [comment]
@priyanka001tech updates on this?

**Comment by kaustubhgupta** [comment]
@priyanka001tech you need to make the PR today itself

**Comment by priyanka001tech** [comment]
I'm working on this..
I need 2 more days to complete it

**Comment by kaustubhgupta** [comment]
@priyanka001tech Today is the last day for this

**Comment by Yuvraj-kadale** [comment]
@kaustubhgupta I am up !! Would like try .

**Comment by santushtisharma10** [comment]
@Yuvraj-kadale assigned to you

**Comment by kaustubhgupta** [comment]
@Yuvraj-kadale updates on this?

**Comment by Yuvraj-kadale** [comment]
> @Yuvraj-kadale updates on this?

About to complete. Will make a PR by today EoD.
