### ISSUE TITLE
Image to speech folder

### ISSUE THREAD

**Issue by Subhradeep10** [avinashkranjan/Amazing-Python-Scripts#706]
# Aim

- To add a programme which will convert Image to speech

**Comment by kaustubhgupta** [comment]
@Subhradeep10 assigned to you

**Comment by Amit366** [comment]
@kaustubhgupta can I work ??

**Comment by kaustubhgupta** [comment]
@Amit366 updates?

**Comment by Amit366** [comment]
@kaustubhgupta by tomorrow I will send the PR

**Comment by kaustubhgupta** [comment]
@Amit366 Cool
