### ISSUE TITLE
Desktop Voice Assistant

### ISSUE THREAD

**Issue by sayantani11** [avinashkranjan/Amazing-Python-Scripts#709]
# Aim

To be able to perform basic functions on our desktop using our voice

# Details

- What the features will your script have
Will be able to perform basic functions like:
1. Sending email
2. Opening google
3. opening some app
or any other

**Comment by santushtisharma10** [comment]
@sayantani11 go ahead, assigned to you

**Comment by kaustubhgupta** [comment]
@sayantani11 updates on this?

**Comment by sayantani11** [comment]
@kaustubhgupta I am stuck at a point where I am unable to install PyAudio..... I will fix it today with @santushtisharma10

**Comment by kaustubhgupta** [comment]
did you found any alternative for PyAudio?

**Comment by sayantani11** [comment]
Yes....I guess I will be able to push the code within a day or two
@kaustubhgupta
