### ISSUE TITLE
Sorting Algorithms in Python

### ISSUE THREAD

**Issue by varshith-k** [avinashkranjan/Amazing-Python-Scripts#712]
# Aim

- What is the objective of the Script
  To add few basic py files that has the code to sort a list.
# Details

- What the features will your script have
  It has a function(def) that has the implementation for sorting algorithms in python.

**Comment by kaustubhgupta** [comment]
@varshith-k what extra value will it add to the repo? all the sorting algorithms are already implemented in the best way possible.

**Comment by varshith-k** [comment]
@kaustubhgupta are all sorting algorithms added to the repo?

**Comment by kaustubhgupta** [comment]
Is there a need to add sorting algorithms here?

**Comment by varshith-k** [comment]
I thought they might be useful python scripts.

**Comment by kaustubhgupta** [comment]
@antrikshmisri @santushtisharma10 @Kushal997-das thoughts?

**Comment by varshith-k** [comment]
It's fine you can close this issue.

**Comment by antrikshmisri** [comment]
@varshith-k I think you should pick up something else as there are a lot of sorting algorithms already present in the codebase
