### ISSUE TITLE
🌍GPS - Track The Route 

### ISSUE THREAD

**Issue by Lakhankumawat** [avinashkranjan/Amazing-Python-Scripts#713]
# Description 
- I have been provided with a [`CSV`](https://www.bigcommerce.com/ecommerce-answers/what-csv-file-and-what-does-it-mean-my-ecommerce-business/#:~:text=A%20CSV%20is%20a%20comma,Microsoft%20Excel%20or%20Google%20Spreadsheets.)(comma separated value) file in which the **latitudes** and **longitudes** of a specific area are written
_So_ we can track the whole route of a person by reading values of that file on Google Maps and create an Image containing route or location .
_OR_ Just point the location on the map .

# Details 
- API Used [`gmplot`](https://github.com/gmplot/gmplot/wiki)

# What to do
- Take CSV file input **or** any latitudes or longitudes-> plot the map -> give output in image format

**Comment by Lakhankumawat** [comment]
I am willing to do it 🙂

**Comment by kaustubhgupta** [comment]
@Lakhankumawat the location coordinates are fetched from an API or this a fixed CSV file which will not change?

**Comment by Lakhankumawat** [comment]
- Location coordinates are imported from a fixed CSV file that doesn't change .
 - gmplot can be used to plot these coordinates on  Google map

**Comment by kaustubhgupta** [comment]
@Lakhankumawat oh okay no issues, assigned to you

**Comment by kaustubhgupta** [comment]
@Lakhankumawat updates on this?

**Comment by Lakhankumawat** [comment]
A PR is created yesterday only .🙂
