### ISSUE TITLE
Image Viewing GUI

### ISSUE THREAD

**Issue by anuragmukherjee2001** [avinashkranjan/Amazing-Python-Scripts#719]
My name is Anurag Mukherjee, a participant of GSSoC'21.

# Aim

The aim of this project is to view some given images from the image gallery using a python script in graphical based interface.

# Details
The project description is given below:-
After running the code snippet, an interface will open with two buttons:- i) previous, ii)next. The GUI will fetch images from the image folder and will be viewed in the background of the interface. The next button will proceed to the next image and the previous button will bring back to the previous image.

The image will be shown in a specific dimension, irrespective of the size of the image.

Modules and packages will be used:-
`
from tkinter import * `
`
from PIL import ImageTk, Image
`

I will write clean and easy to understand code. Please assign this issue to me.

**Comment by kaustubhgupta** [comment]
@anuragmukherjee2001 updates on this?

**Comment by anuragmukherjee2001** [comment]
@kaustubhgupta I created a pull request on this script. Please check the PR.

**Comment by Amit366** [comment]
@kaustubhgupta can I work??
