### ISSUE TITLE
Typing speed test

### ISSUE THREAD

**Issue by sudipg4112001** [avinashkranjan/Amazing-Python-Scripts#720]
I would like to add a python script on typing speed test. 
### Details:
We have to input sentences and it would show the time taken for typing, wpm and accuracy.

**Comment by dhriti987** [comment]
i want to work on this

**Comment by dhriti987** [comment]
@kaustubhgupta is this issue closed?

**Comment by kaustubhgupta** [comment]
Nope, you can start working on this

**Comment by dhriti987** [comment]
@kaustubhgupta  ok I will start working on this tomorrow.... Deadline for this?

**Comment by kaustubhgupta** [comment]
total 7 days, I will ask for updates on 3rd day

**Comment by kaustubhgupta** [comment]
@dhriti987 updates?

**Comment by dhriti987** [comment]
it will be finished by day after tomorrow ......  by the way what you suggest I should make UI with Tkinter or pygame or anything else?

**Comment by kaustubhgupta** [comment]
Tkinter is a Good option. You can also checkout PyQt5 or if you want to explore completely different framework, then you can check kivy.

**Comment by dhriti987** [comment]
I am going with Tkinter...  for sentences should i use text file or another python file?

**Comment by kaustubhgupta** [comment]
text file

**Comment by dhriti987** [comment]
it's finished 
![Screenshot (18)](https://user-images.githubusercontent.com/70242680/113162393-e44f9780-925c-11eb-8d28-1d9cb6d7018f.png)
need any changes?

**Comment by kaustubhgupta** [comment]
@dhriti987 Make the PR and then only I can review the cord and suggest changed (if needed)

**Comment by dhriti987** [comment]
i have just included 10 sentences is it ok?

**Comment by dhriti987** [comment]
@kaustubhgupta  review it
