### ISSUE TITLE
Script to schedule a google meet.

### ISSUE THREAD

**Issue by Tarun-Kamboj** [avinashkranjan/Amazing-Python-Scripts#724]
# Details

- Python Script to schedule a google meet, send invitation to the respective emails and set an event for the meet in the calendar too. The script will take email ids and time as input and create a google meet for these email ids at the specified time. These email ids will also receive an invite in the gmail inbox and an event will also be created in the calendar of these email ids for the meeting.

**Comment by Tarun-Kamboj** [comment]
@kaustubhgupta please assign this issue to me.

**Comment by kaustubhgupta** [comment]
@Tarun-Kamboj updates?

**Comment by Tarun-Kamboj** [comment]
> @Tarun-Kamboj updates?

So the script and documentation is ready. Just need to add the folder in the repo and push the changes. Will do it today.

**Comment by Tarun-Kamboj** [comment]
Created a PR @kaustubhgupta, please review.
