### ISSUE TITLE
Mini Google Assistant

### ISSUE THREAD

**Issue by A-kriti** [avinashkranjan/Amazing-Python-Scripts#726]
# Aim

- To build a mini google assistant.

# Details

- A mini google assistant using some python libraries. Kindly assign me this issue, @avinashkranjan Sir.

**Comment by santushtisharma10** [comment]
@A-kriti go ahead, assigned to you

**Comment by kaustubhgupta** [comment]
@A-kriti updates on this?

**Comment by kaustubhgupta** [comment]
@A-kriti you need to make the PR today itself else it will be assigned to someone else

**Comment by A-kriti** [comment]
@kaustubhgupta I am still working but I'll try to make a pr today!

**Comment by kaustubhgupta** [comment]
@A-kriti today is last date for this

**Comment by Arnab11917676** [comment]
@kaustubhgupta  sir can I take over this project...I have a working prototype ready for this project and I can make a PR today only...

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta sir can I take over this project...I have a working prototype ready for this project and I can make a PR today only...

As today is her last day, let her take the time.
