### ISSUE TITLE
Battery percentage notification

### ISSUE THREAD

**Issue by pankaj892** [avinashkranjan/Amazing-Python-Scripts#727]
# Aim
This script aims to show the current battery left out

- What is the objective of the Script
- Objective of the Script is to show battery percentage after every 60 mins and notify the user about remaining battery 

# Details

- The script will use some python libraries and python code to achieve this.

I would like to work on this please assign me @avinashkranjan

**Comment by santushtisharma10** [comment]
@pankaj892 assigned to you
