### ISSUE TITLE
Hindi Text POS tagging

### ISSUE THREAD

**Issue by zaverisanya** [avinashkranjan/Amazing-Python-Scripts#729]
# Aim

To remove all the POS tags from hindi text file using python script and domain NLP.

# Details

To have a separate hindi text file without POS tags.

@avinashkranjan @kaustubhgupta   I am a GSSoC'21 participant and I think this is an interesting python script of NLP domain. Kindly allow me to work on this issue and contribute to this project!

**Comment by kaustubhgupta** [comment]
@zaverisanya assigned to you
