### ISSUE TITLE
A script that finds people who don't follow you back on instagram

### ISSUE THREAD

**Issue by sarthak1905** [avinashkranjan/Amazing-Python-Scripts#73]
# Aim

Receive a list of all accounts who you follow but who don't follow you back on instagram.

# Details

This script will input your instagram username and password. None of the details are stored(as can be seen in the code of the program as well). The script then uses the selenium module to do the rest and return the required list of account names.

PS- The exact instructions, infromation and relevant details will be mentioned in the README.md file attahced with the project.

**Comment by sarthak1905** [comment]
Hey, I would like to contribute towards this issue. Please assign me the same.

Thanks and Regards
Sarthak Saxena

**Comment by avinashkranjan** [comment]
Go ahead.. @sarthak1905
