### ISSUE TITLE
Simple Music Player GUI

### ISSUE THREAD

**Issue by Ratnesh4193** [avinashkranjan/Amazing-Python-Scripts#731]
# Aim

- Created a Simple Music Player using Tkinter and Pygame

Kindly assign me this issue, @avinashkranjan Sir
![Capture](https://user-images.githubusercontent.com/57043581/112335624-67637180-8ce2-11eb-97c6-1a88f6b9497f.JPG)
.

**Comment by kaustubhgupta** [comment]
@Ratnesh4193 We already have a Music Player GUI app: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Music-Player-App
