### ISSUE TITLE
Want to add wikipedia features to this project.

### ISSUE THREAD

**Issue by rupal121** [avinashkranjan/Amazing-Python-Scripts#732]
**Is your feature request related to a problem? Please describe.**
No it's not related to the problem, it is just the addition of the new feature.

**Describe the solution you'd like**
Wikipedia features will help the users to search about various things they want like google search.

**Describe alternatives you've considered**
I will use the Wikipedia library for this.

**Comment by kaustubhgupta** [comment]
@rupal121 We already have an approved PR for this: #683
