### ISSUE TITLE
Python Tkinter Minesweeper

### ISSUE THREAD

**Issue by Ratnesh4193** [avinashkranjan/Amazing-Python-Scripts#738]
**Is your feature request related to a problem? Please describe.**

Minesweeper game written in Python using Tkinter GUI library.

@avinashkranjan @kaustubhgupta I am a GSSoC'21 participant .Kindly assign this issue to me.

   ![mine](https://user-images.githubusercontent.com/57043581/112461814-52d8b500-8d86-11eb-9b84-5dd7020de6c3.png)

**Comment by kaustubhgupta** [comment]
@Ratnesh4193 If you are thinking of adding this script: https://github.com/ripexz/python-tkinter-minesweeper

Then kindly DO NOT.

@santushtisharma10 Early detection!  😄😄

**Comment by Ratnesh4193** [comment]
I have not made this application yet so i just took the preview image.
I will not copy and paste code.

**Comment by Ratnesh4193** [comment]
@kaustubhgupta  can i work on it

**Comment by kaustubhgupta** [comment]
@Ratnesh4193 if you can develop the code and logic of the game on your own without changing variable names and restructuring the code, then I can assign this issue

**Comment by Ratnesh4193** [comment]
okk sure .Should i create an issue for the same or send my code here when completed??@kaustubhgupta

**Comment by kaustubhgupta** [comment]
@Ratnesh4193 I am assigning this issue to you. Now you can work on the code and make the PR within 7 days from now

**Comment by kaustubhgupta** [comment]
@Ratnesh4193 updates?

**Comment by Ratnesh4193** [comment]
I am taking help from some of youtube tuturials .
Have some logical bugs , will make pr within 2 days
