### ISSUE TITLE
Color Game using Tkinter

### ISSUE THREAD

**Issue by PriyanshuChatterjee** [avinashkranjan/Amazing-Python-Scripts#739]
### Aim
To make a tricky and interesting Color game using Tkinter with a GUI. 

### Details
In this game, the player has to enter the color of the word that appears on the screen. he game uses a variety of colors such as Red, Blue, Green, Pink, Black, Yellow, Orange, White, Purple, and Brown. These colors are interchangeably displayed to trick the player’s mind. The graphical user interface (GUI) will display the name of different colors in different colors. 

@avinashkranjan I am a GSSoC'21 participant and I think this is an interesting python script of GUI domain. Kindly allow me to work on this issue and contribute to this project!

**Comment by santushtisharma10** [comment]
@PriyanshuChatterjee assigned to you
