### ISSUE TITLE
Stopwatch GUI

### ISSUE THREAD

**Issue by aishwaryachand** [avinashkranjan/Amazing-Python-Scripts#741]
# Aim
I would like to work create a  stopwatch GUI

# Details

I will create a stopwatch GUI  with tkinter , it will have a start /stop button 

Pls assign me this issue

**Comment by kaustubhgupta** [comment]
@aishwaryachand We already have a similar issue for this (Alarm Clock #600). If that assigned person fails to make the correct PR, then I will assign that issue to you

**Comment by kaustubhgupta** [comment]
Are you interested in working on this issue now? The other person failed to make the right PR

**Comment by aishwaryachand** [comment]
Yes, sure I would like to work on this issue.

**Comment by kaustubhgupta** [comment]
@aishwaryachand updates?

**Comment by aishwaryachand** [comment]
I will surely make a PR by today .
