### ISSUE TITLE
Codes On Turtle Graphics

### ISSUE THREAD

**Issue by ricsin23** [avinashkranjan/Amazing-Python-Scripts#744]
Design several figures using Turtle Graphics in Python.

I am a participant at GSSOC'21, requesting admins to assign me this issue.

**Comment by kaustubhgupta** [comment]
@ricsin23 Please define thesefigures. How many figures you are going to implement in Turtle?

**Comment by kaustubhgupta** [comment]
@ricsin23 Please define these several figures. How many figures you are going to contribute?

**Comment by ricsin23** [comment]
> @ricsin23 Please define these several figures. How many figures you are going to contribute?
Hello Sir, Basically I want to design two figures, one is a Kaleido spiral and another one is an animated robot.

**Comment by kaustubhgupta** [comment]
@ricsin23 okay, assigned to you. Make sure to create separate files for patterns

**Comment by Nikita0509** [comment]
can i work on this issue 
I'm a GSSO'21 participant @kaustubhgupta

**Comment by Nikita0509** [comment]
can i also work on this issue @kaustubhgupta  ?
I'm a GSSO'21 participant

**Comment by kaustubhgupta** [comment]
@Nikita0509 issues are assigned on first come first basis. If @ricsin23 fails to make the PR on time, then it can be assigned to you
