### ISSUE TITLE
Typo in contributions guidelines-Step 5

### ISSUE THREAD

**Issue by Yuvraj-kadale** [avinashkranjan/Amazing-Python-Scripts#748]
**Describe the bug**
There is a command mistake in the step 5 to commit a message. The closing quotes are missing in the message command.
This must be corrected as few of them are newbies to open source. And some of them Copy pastes :)

**To Reproduce**
1. Scroll down to step 5 in [contributions guidelines](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md).
2. See error

**Expected behavior**
The command could have been : git commit -m "message"

**Screenshots**
![image](https://user-images.githubusercontent.com/43489758/112639031-dae1bc00-8e65-11eb-94dd-35d0258b9ae6.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by raks924** [comment]
can i work on this?
