### ISSUE TITLE
Alarm Clock using python

### ISSUE THREAD

**Issue by soha28** [avinashkranjan/Amazing-Python-Scripts#749]
**AIM :**
To implement an alarm clock using python.

**DETAILS :**
Using  datetime and tkinter libraries the project will be created . It uses current date and time as well as provides a user interface to set the alarm according to the requirement in 24-hour format.

**Comment by soha28** [comment]
@avinashkranjan I want to work on this project under GSSOC'21. Please assign this to me.

**Comment by santushtisharma10** [comment]
@soha28 we already have an issue of alarm clock (#600)
