### ISSUE TITLE
Scrap YouTube Trending Section

### ISSUE THREAD

**Issue by kaustubhgupta** [avinashkranjan/Amazing-Python-Scripts#752]
# Details
Come up with a script that stores the title of the video, youtube channel name, number of likes, dislikes, views, no of comments, date of publishing, description of the video (if possible) in a suitable database.

Create another script to fetch that database. Refer to this script for database fetching and displaying:  [Tweet Fetcher](https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Tweet-Fetcher)

------------------------------------------
Updates: Database chosen- MongoDB

**Comment by XZANATOL** [comment]
Should the database be like a real one? (using SQL or MongoDB) or using a CSV file will do the job?

**Comment by kaustubhgupta** [comment]
> Should the database be like a real one? (using SQL or MongoDB) or using a CSV file will do the job?

Actually, I want to upscale the issue-level:
CSV: level2
SQL/Mongo: level3

let me know your preference if you're interested to contibute

**Comment by XZANATOL** [comment]
Nice, I'm going to learn MongoDB right now. :joy: and yea, I would like to contribute to this one.

**Comment by kaustubhgupta** [comment]
@XZANATOL Cool 😛, assigned to you

**Comment by kaustubhgupta** [comment]
@XZANATOL updates?

**Comment by XZANATOL** [comment]
Already finished the scraping part but figuring out a way to use MongoEngine

**Comment by XZANATOL** [comment]
Update: I'm mostly done with the script, but noticed a small error with the scrap algorithm causing the order disort of some cells. I'm trying another scrap approach right now, once I finish I'll make the PR.

**Comment by kaustubhgupta** [comment]
@XZANATOL Cool 😀
