### ISSUE TITLE
LeetCode Scrapper

### ISSUE THREAD

**Issue by kaustubhgupta** [avinashkranjan/Amazing-Python-Scripts#753]
# Details

Come up with a script that scraps `n` number of problems from `any category/difficulty` provided by the user and store all the `n` problems separately in PDFs. The PDF file should contain the problem title, statement, and test cases.

User Input: `n` and `category/difficulty` of problem
Expected Output: `n` PDF files

**Comment by mehabhalodiya** [comment]
I would like to work on this.

**Comment by kaustubhgupta** [comment]
@mehabhalodiya assigned to you

**Comment by mehabhalodiya** [comment]
Sorry, I don't feel to do this right now! You can assign it to the next person.

**Comment by AshuKV** [comment]
Can I work on this issue under GSSOC21? Kindly assign it to me.

**Comment by kaustubhgupta** [comment]
@AshuKV Assigned to you

**Comment by kaustubhgupta** [comment]
@AshuKV updates?

**Comment by kaustubhgupta** [comment]
@AshuKV will you make the new code PR?

**Comment by AshuKV** [comment]
Yes, I would be making the new code PR by today EOD.
