### ISSUE TITLE
CodeChef Scrapper

### ISSUE THREAD

**Issue by kaustubhgupta** [avinashkranjan/Amazing-Python-Scripts#754]
# Details

Come up with a script that scraps `n` number of problems from `any category/difficulty` provided by the user and stores all the `n` problems separately in PDFs. The PDF file should contain the problem title, statement, and test cases.

User Input: `n` and `category/difficulty` of the problem
Expected Output: `n` PDF files

**Comment by smriti26raina** [comment]
Can you please assign this issue to me? I'm a participant of GSSOC'21.

**Comment by kaustubhgupta** [comment]
@smriti26raina assigned to you

**Comment by kaustubhgupta** [comment]
@smriti26raina updates?

**Comment by smriti26raina** [comment]
@kaustubhgupta Almost done.

**Comment by santushtisharma10** [comment]
@smriti26raina when you will be making pr??

**Comment by smriti26raina** [comment]
@santushtisharma10 I'm really sorry for the delay. I was not well from a few days. It won't happen again.
