### ISSUE TITLE
Dev.to Scrapper

### ISSUE THREAD

**Issue by kaustubhgupta** [avinashkranjan/Amazing-Python-Scripts#755]
# Details

Come up with a script that scraps `n` number of articles from `any category` such as Python, JS, Android provided by the user and stores all the `n` articles separately in PDFs. The PDF file should contain the title, article content, and author-name

User Input: `n` and `category`
Expected Output: n PDF files

**Comment by Ayushjain2205** [comment]
@kaustubhgupta  I would like to work on this, can you please assign it to me

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 sure!

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 updates?

**Comment by Arnab11917676** [comment]
Hello @Ayushjain2205 may I take over this project

**Comment by Ayushjain2205** [comment]
@kaustubhgupta  working on it will be done by tomorrow end of day
