### ISSUE TITLE
Minecraft Game Using ursina Game engine

### ISSUE THREAD

**Issue by Priyadarshan2000** [avinashkranjan/Amazing-Python-Scripts#756]
# Aim

To make a Minecraft  Game Using ursina Game engine, Python Scripts & Blender.

# Details

In this game, Minecraft demo builds with help of ursina game engine, python  Scripts and blender. In this game the player can move around and can build four different kinds of block-like Minecraft and can also destroy them while the game is on the player can listen to music and as soon as a block is destroyed a destructive noise will be created.

@avinashkranjan I am a GSSoC'21 participant and I think this is an interesting python script for the Game domain. Kindly allow me to work on this issue and contribute to this project!

**Comment by kaustubhgupta** [comment]
@Priyadarshan2000 this is a standalone project and beyond the scope of this repo

**Comment by kaustubhgupta** [comment]
@antrikshmisri @santushtisharma10 thoughts?

**Comment by antrikshmisri** [comment]
@kaustubhgupta I agree and I think a blender build is also needed for this to run.
