### ISSUE TITLE
Notepad using Tkinter

### ISSUE THREAD

**Issue by Priyadarshan2000** [avinashkranjan/Amazing-Python-Scripts#762]
# Aim

To make a Notepad Application using Tkinter with a GUI.

# Details
 
In this Project, I will deploy a Notepad Application with the help of the Tkinter module. In this application, we can save our work in any file format. many types of font available,  and increase your font size. All types of notepad functionality in this application. we can bold, italic, underline, strikethrough in this application.

@avinashkranjan I am a GSSoC'21 participant and I think this is an interesting python script of the GUI domain. Kindly allow me to work on this issue and contribute to this project!

**Comment by kaustubhgupta** [comment]
@Priyadarshan2000 we already have an implementation here: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Simple%20Notepad
