### ISSUE TITLE
Google browser Clone

### ISSUE THREAD

**Issue by anuragmukherjee2001** [avinashkranjan/Amazing-Python-Scripts#763]
I am Anurag Mukherjee, a participant of GSSoC'21.
# Aim

The aim of the script is to make a google browser clone with the help of PyQt5 module in python.

# Details
The browser will contain all the basic functionalities that a browser should have. It has a home button which takes the browser directly to the home page, a back button, which takes to the previous URL, a forward button, and a reload button which refreshes the whole web page. Apart from these it also has a editable URL area, where we can directly write the URL of our respected website. 

## Modules and packages will be used:-
1) PyQt5
2) sys

A sample image of the browser is shown below:-

![ss_1](https://user-images.githubusercontent.com/62845847/112726700-d3ddab00-8f44-11eb-934f-76c10eeec77a.png)

**Comment by kaustubhgupta** [comment]
We already have an implementation for this: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Broswer
