### ISSUE TITLE
Simple  Python IDE using Tkinter 

### ISSUE THREAD

**Issue by Priyadarshan2000** [avinashkranjan/Amazing-Python-Scripts#764]
# Aim

To make a Simple  Python IDE using Tkinter with a GUI.

# Details
In this project, I will deploy a simple  Python IDE application with the help of the Tkinter module. This application just like a python IDE. we can save our code and run this IDE. we can open our exciting Project in this IDE.

@avinashkranjan I am a GSSoC'21 participant and I think this is an interesting python script of the GUI domain. Kindly allow me to work on this issue and contribute to this project!

**Comment by santushtisharma10** [comment]
@Priyadarshan2000 assigned to you

**Comment by Priyadarshan2000** [comment]
@santushtisharma10 you added a label:enhancement . I didn't get which particularly which enhancement you talked about

**Comment by santushtisharma10** [comment]
@Priyadarshan2000 it means it is a new feature to repository
