### ISSUE TITLE
Tic Tac Toe game with GUI using Pygame in Python

### ISSUE THREAD

**Issue by Srijan-dixit** [avinashkranjan/Amazing-Python-Scripts#768]
# Aim

- To make Tic Tac Toe using pygame
- 
# Details

- The game will be having a GUI with a single player and multiplayer feature.

@avinashkranjan I am a GSSoC'21 participant and I think this is an interesting python script. Kindly allow me to work on this issue and contribute to this project!

**Comment by kaustubhgupta** [comment]
@Srijan-dixit updates?

**Comment by Lakhankumawat** [comment]
Please assign me  @kaustubhgupta  sir , whenever you thought like it to up for grab.

**Comment by Srijan-dixit** [comment]
I have completed the script i was going to make the PR today. I am having classes from 8 am to 4 pm. I'll  make it after that.

**Comment by kaustubhgupta** [comment]
@Lakhankumawat as @Srijan-dixit pushed plagiarised code, are in interested in pushing a "original" code for this PR?

**Comment by Lakhankumawat** [comment]
Yeah Sure i'll do it.

**Comment by Lakhankumawat** [comment]
As we had conversation in #794 i had made a duplicate issue but @kaustubhgupta  sir i was using pygame and issue is about tkinter , will it be okay if i do it

**Comment by kaustubhgupta** [comment]
Do you have experience with Tkinter? Can you port your pygame code to this as most probably, if you push that code, then one or the mentor will mark it plagiarism

**Comment by Lakhankumawat** [comment]
Sir i think 
> you had said me that you can add back your TicTacToe using GUI with pygame over here after marking it as plagiarism in my first PR which was #583
![Screenshot (49)](https://user-images.githubusercontent.com/55774240/113679330-46851e00-96dd-11eb-9773-0537b3c88f35.png)

Here you did mentioned you can i mean i can add my code which was closed as plagiarism to add it back create a new PR 

- I know this all sounds bit too complex but 
- let me be clear 
Please allow me to add Tic Tac Toe with GUI using pygame if it looks good merge it and all will be good.

**Comment by Lakhankumawat** [comment]
> Do you have experience with Tkinter? Can you port your pygame code to this as most probably, if you push that code, then one or the mentor will mark it plagiarism

Also i won't be able to switch whole base from pygame to tkinter , although i know tkinter but not that much

**Comment by kaustubhgupta** [comment]
> Sir i think
> 
> > you had said me that you can add back your TicTacToe using GUI with pygame over here after marking it as plagiarism in my first PR which was #583
> > ![Screenshot (49)](https://user-images.githubusercontent.com/55774240/113679330-46851e00-96dd-11eb-9773-0537b3c88f35.png)
> 
> Here you did mentioned you can i mean i can add my code which was closed as plagiarism to add it back create a new PR
> 
> * I know this all sounds bit too complex but
> * let me be clear
>   Please allow me to add Tic Tac Toe with GUI using pygame if it looks good merge it and all will be good.

@Lakhankumawat that time we were lenient with code reviews but now we don't merge any previously available code. Also, as the code is reviewed by 4 mentors, if anyone raises any claim then I will have no choice but to reject the PR. That's why I am unassigning this issue so that you don't get any strike

**Comment by Lakhankumawat** [comment]
Umm Okay sir but kindly reopen issue #794 cause you know this issue says about solving it with pygame .
It's different i guess but the idea is same
