### ISSUE TITLE
Personal Assistant Desktop Application

### ISSUE THREAD

**Issue by Arnab11917676** [avinashkranjan/Amazing-Python-Scripts#770]
# Aim

Personal Assistant using pyttsx3 in Python

# Details

In this project, I will add as much feature as possible which makes the application as much relatable as to a real PA. 
In this application, the user can send email using only his voice, use scientific calculation search chrome, Wikipedia or youtube just by speaking to it. The application will be capable to open different desktop applications like Ms.Word, Ms.Powerpoint and also take a screenshot and add a reminder, and may also be able to switch off the computer and can also do little small talk.

@avinashkranjan I am a GSSoC'21 participant and I think this is an interesting python project kindly allow me to work on this project.

**Comment by kaustubhgupta** [comment]
@Arnab11917676 We already have some issues underway that will implement the same. One of them being https://github.com/avinashkranjan/Amazing-Python-Scripts/issues/726
