### ISSUE TITLE
Cryptocurrency Wallet

### ISSUE THREAD

**Issue by Arnab11917676** [avinashkranjan/Amazing-Python-Scripts#771]
# Aim
Cryptocurrency Wallet using Python and Cryptography Concepts

# Details

In this program, I will be building a program that can perform the whole process of mining a  block, generating private and public keys along with keeping tracks of its peers, and is capable of dynamically stabilizing the difficulty of the block according to the time requirements and can also transact the transaction and sign them digitally.

@avinashkranjan I am a GSSoC'21 participant and I think this is an interesting python project kindly allow me to work on this project.

**Comment by kaustubhgupta** [comment]
@Arnab11917676 updates?

**Comment by Arnab11917676** [comment]
Yes sir, I will be uploading all the details within 6pm

**Comment by Arnab11917676** [comment]
@kaustubhgupta sir please have a look...
