### ISSUE TITLE
Create a Country Guessing Game

### ISSUE THREAD

**Issue by Shubhrima** [avinashkranjan/Amazing-Python-Scripts#778]
# Aim

-Create a game with a blank world map, that allows players to add countries to it. With every correct guess, the player earns a point. 

# Details

- 
![image](https://user-images.githubusercontent.com/68013183/112933423-6fd20700-913d-11eb-8753-920827704d92.png)

**Comment by santushtisharma10** [comment]
@Shubhrima go ahead, assigned to you
