### ISSUE TITLE
EXPENSE TRACKER USING Tkinter GUI

### ISSUE THREAD

**Issue by noobkid2411** [avinashkranjan/Amazing-Python-Scripts#779]
Aim:
The project would aim to create an app to keep a record of daily expenses and stocks in a proper format so that the user can analyze all the expenditures efficiently ,correctly and manage the funds in a better manner.

Details:

- The app would prompt the user to enter date of the expenditure which will be stored .
-Again the app would prompt the user for a name and other expense details . 
-Once submitted, the user can see the expenses under viewexpense button for each day on the tkinter window.

**Comment by santushtisharma10** [comment]
@noobkid2411 assigned to you

**Comment by kaustubhgupta** [comment]
@noobkid2411 updates?

**Comment by noobkid2411** [comment]
Would create a pr by today.

**Comment by Amit366** [comment]
@kaustubhgupta can I work??
