### ISSUE TITLE
Create a Script to hunt for Usernames across Social Channels

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#78]
# Aim

- Creating a Script to hunt for Usernames across Social Channels

# Details

- Create a Script to hunt for Usernames across Social Channels. You can take in a Username though CLI and find whether the particular Username exists on the given Social Media Channels or not. You can take in popular Social Channels (GitHub, Reddit, Instagram and more) and see if the User exists on any of these Social Channels given the Username.

**Comment by DevLokCodes** [comment]
Hey I would like to work on this,
I had something similar in mind regarding a bot that recommends you usernames based on your taste

**Comment by avinashkranjan** [comment]
@DevLokCodes Sure Go ahead..

**Comment by avinashkranjan** [comment]
@DevLokCodes Any Updates?

**Comment by DevLokCodes** [comment]
Hey sorry for the late update,
Already created a script for Reddit, GitHub, Instagram
trying to figure out for twitter 
will send a PR as soon as I figure that out

**Comment by vybhav72954** [comment]
Ok, this is intriguing, I can make a script for this but honestly would prefer using [Sherlock](https://sherlock-project.github.io/).

If you want functionality that is not present in Sherlock, kindly tell me and I will add it.

**Comment by avinashkranjan** [comment]
> Ok, this is intriguing, I can make a script for this but honestly would prefer using [Sherlock](https://sherlock-project.github.io/).
> 
> If you want functionality that is not present in Sherlock, kindly tell me and I will add it.
@vybhav72954 So, Basically Sherlock looks up and looks up all the available website I'm looking to a script to search a specific username on a specific social network.

**Comment by vybhav72954** [comment]
As in, suppose I want to search `vybhav` but only on `reddit` and `github`?

**Comment by avinashkranjan** [comment]
Exactly.... That's what I'm looking for

**Comment by vybhav72954** [comment]
Yup, that's definitely possible, am pretty sure I can make that

**Comment by avinashkranjan** [comment]
So, I'm Assigning it to you. You can go ahead and start working on the script

**Comment by vybhav72954** [comment]
I was out os station @avinashkri will start working from today only, just give me this weekend and I will close all my issues
