### ISSUE TITLE
💬WhatsApp Chats Automation

### ISSUE THREAD

**Issue by Lakhankumawat** [avinashkranjan/Amazing-Python-Scripts#780]
# Description
1. We can automate our whatsApp through python script i.e we can send message to anyone in our contact through py program .
2. We can spam any group or private chat with person easily by using whatsApp automation .
3. It gives the idea how the chating works in whatsApp .

# Details 
1. It can be done using Selenium<details>Selenium is a powerful tool for controlling web browsers through programs and performing browser automation. It is functional for all browsers, works on all major OS and its scripts are written in various languages i.e Python</details>

**Comment by Lakhankumawat** [comment]
If it seems good .<br>
Then i am ready to grab

**Comment by santushtisharma10** [comment]
@Lakhankumawat we already have [project](https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Whatsapp-Automation) related to whatsapp automation using selenium in the repository
