### ISSUE TITLE
Creating an Alarm clock.

### ISSUE THREAD

**Issue by anuragmukherjee2001** [avinashkranjan/Amazing-Python-Scripts#781]
My name is Anurag Mukherjee, a participant of GSSoC'21.
# Aim

The aim of this script is to create an Alarm clock.

# Details

This is not a GUI script. My script will have the following features:-
Firstly, script will ask the date. Then the script will ask the time of the alarm. When the time will be matched with the time of the system, the alarm sound will be played.

## Modules will be used:-
1) playsound
2) time
3) datetime

I will write clean and easy to understand code. Please assign this issue to me.

**Comment by kaustubhgupta** [comment]
@anuragmukherjee2001 this issue is already in progress
