### ISSUE TITLE
Space War Game

### ISSUE THREAD

**Issue by anuragmukherjee2001** [avinashkranjan/Amazing-Python-Scripts#783]
My name is Anurag Mukherjee, a participant of GSSoC'21.

# Aim

A space war game made purely with python.

# Details

Rules and features of the game:

  1) There is a Spaceship, which is the main hero of the game.
  2) You can control the hero using the left and right arrow keys in your keyboard.
  3) Press space bar to shoot the enemies.
  4) Each time you shoot an enemy, your score will increase by 1.
  5) If the enemy touches you, the game will be over.

## Modules will be used in this script:-
1) pygame
2) mixer from pygame
3) random
4) math 

## Preview of this game

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/62845847/103192948-9e530280-4900-11eb-8bfe-fa120a0aad91.gif)

**Comment by kaustubhgupta** [comment]
@anuragmukherjee2001 aaasigned to you
