### ISSUE TITLE
Scrape memes from reddit 

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#79]
# Aim

- Write a Script to Scrape memes from reddit !!

# Details

- Create a Script that can download all pictures of memes from any of these subreddits r/deepfriedmemes, r/surrealmemes, r/nukedmemes, r/bigbangedmemes, r/wackytictacs, r/bonehurtingjuice using Web Scrapping and store them in your Local System.
Languages

**Comment by hemantsirsat** [comment]
I can do this!

**Comment by Kreateer** [comment]
I can do this using [praw](https://praw.readthedocs.io/en/latest/), [pandas ](https://pandas.pydata.org/)and [urllib](https://docs.python.org/3/library/urllib.html). ^^

**Comment by avinashkranjan** [comment]
@Kreateer Sure.... Go ahead
