### ISSUE TITLE
Audio Steganography

### ISSUE THREAD

**Issue by MayankkumarTank** [avinashkranjan/Amazing-Python-Scripts#790]
# Aim

- In Audio Steganography,
-  Encoder: the user is requested to upload an audio file and also a secret message that he wants to hide in that audio file.
- Decoder: the user will provide the encoded audio file which has secret code inside that file and the output of the script will extract the secret message from that and provide that secret message to the user.

# Details

- I want to implement the both encoder and decoder part (different independent scripts). For hiding the secret message in the audio file I will use audio steganography algorithms and also I want to implement a decoder part as well to extract the secret message from the provided audio file.

**Comment by kaustubhgupta** [comment]
@MayankkumarTank Updates on this?

**Comment by MayankkumarTank** [comment]
Hello sir, i already made pr around 3 days ago. Named : Added Audio Steganography. Please review it sir. In future, how can i link the pr with issue. (Because it is disabled for me).

Thank you sir

**Comment by kaustubhgupta** [comment]
> Hello sir, i already made pr around 3 days ago. Named : Added Audio Steganography. Please review it sir. In future, how can i link the pr with issue. (Because it is disabled for me).
> 
> Thank you sir

For linking the issue to PR, add this line:

Fixes: #(issue_number_without_brackets)

See the implementation in the PR now

**Comment by Amit366** [comment]
@kaustubhgupta please assign it to me

**Comment by kaustubhgupta** [comment]
@Amit366 Assigned

**Comment by Trisanu-007** [comment]
@kaustubhgupta can I take a shot at this if this is unassigned ?

**Comment by kaustubhgupta** [comment]
@Trisanu-007 sure assigned to you
