### ISSUE TITLE
⭕❌ TicTacToe GUI 

### ISSUE THREAD

**Issue by Lakhankumawat** [avinashkranjan/Amazing-Python-Scripts#794]
> The repo already contains one [Tictactoe-Using-Minmax](https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Tictactoe-Using-Minmax) but it is implemented using Command line and it is single player (player VS computer)

# Aim
- TicTacToe implemented using GUI
- Two players game
- Interactive and more playful

# Details
- Libraries to be used **numpy** , **pygames** and **sys**

**Comment by Lakhankumawat** [comment]
`I` m ready to grab it .

**Comment by kaustubhgupta** [comment]
https://github.com/avinashkranjan/Amazing-Python-Scripts/issues/768

Issue already assigned
