### ISSUE TITLE
Job scraper (Monster Jobs)

### ISSUE THREAD

**Issue by Ayushjain2205** [avinashkranjan/Amazing-Python-Scripts#803]
# Aim

Scrape job openings based on users input for job title and location

# Details

This script will scrape jobs from Monster Jobs as per user input and store them in a CSV file.

**Comment by Ayushjain2205** [comment]
@kaustubhgupta I would like to work on this, can you please assign it to me

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 Any other site other than LinkedIn? We already have 2 LinkedIn scraper for different purposes

**Comment by Ayushjain2205** [comment]
@kaustubhgupta  How about monster jobs?

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 cool, assigned to you

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 updates on this?

**Comment by Ayushjain2205** [comment]
@kaustubhgupta  working on it, will make a PR by tomorrow
