### ISSUE TITLE
Bubble shooter game using python

### ISSUE THREAD

**Issue by syamala27** [avinashkranjan/Amazing-Python-Scripts#806]
## Here is the screenshot 
![bubbleshoot](https://user-images.githubusercontent.com/58478495/113405555-a8851100-93c7-11eb-9798-1d088a240289.gif)

I would like to work on this project .Please assign this issue to me @kaustubhgupta @antrikshmisri @santushtisharma10 @tamanna-verma

**Comment by antrikshmisri** [comment]
@syamala27 Sure, assigned to you
