### ISSUE TITLE
Pacman Game

### ISSUE THREAD

**Issue by sayantani11** [avinashkranjan/Amazing-Python-Scripts#809]
# Aim

- To create a basic pacman game using python

# Details

- The script will have basic things like any other pacman game, a maze which has some aliens or monsters and obstacles. The objective of pacman is to come out of the maze successfully.

**Comment by kaustubhgupta** [comment]
@sayantani11 I have assigned it as level3, make it as creative as you can!

**Comment by sayantani11** [comment]
@kaustubhgupta will try my best

**Comment by sayantani11** [comment]
@kaustubhgupta can you give me time with this one? I also have my exams going on....I will try to do as soon as possible

**Comment by kaustubhgupta** [comment]
@sayantani11 Don't worry you have 4 days more to complete it. I assigned this issue 3 days from today

**Comment by kaustubhgupta** [comment]
@sayantani11 updates?

**Comment by sayantani11** [comment]
@kaustubhgupta I am mostly done but still working on some features I guess I will able to push the code in a day or two

**Comment by kaustubhgupta** [comment]
@sayantani11 you need to make the PR today only

**Comment by sayantani11** [comment]
@kaustubhgupta I will by today.....No issues

**Comment by Amit366** [comment]
@kaustubhgupta can I work??

**Comment by kaustubhgupta** [comment]
@Amit366 I have already assigned you audio Steganography. In total, you have 3 active issues out of which one 'Expense tracker' will be approved by other mentors and the other two are: Sentiment and Audio. Complete those two and then I will assign this issue.

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta I have completed sentiment and also sent the PR

That is wrong implementation, check the commet

**Comment by Trisanu-007** [comment]
@kaustubhgupta  can I try this?

**Comment by kaustubhgupta** [comment]
@Trisanu-007 sure, be aware that the previous two PRs were marked plagiarised. So make sure to contribute original code only

**Comment by kaustubhgupta** [comment]
@Trisanu-007 updates?

**Comment by Trisanu-007** [comment]
Can I have a few more days? Due to some unexpected crisis I was  it able to work.

**Comment by kaustubhgupta** [comment]
@Trisanu-007 Last 2 days

**Comment by Trisanu-007** [comment]
Due to some issue, I can't contribute to this right now. Please reassign this.

**Comment by noviicee** [comment]
@kaustubhgupta can I take this up if it's till open..?

**Comment by sandipswain** [comment]
@kaustubhgupta Can I take up this issue?

**Comment by kaustubhgupta** [comment]
@noviicee Assigned to you!

@sandipswain issues are assigned on first come first basis

**Comment by kaustubhgupta** [comment]
@sandipswain are you still interested to work on this issue?

**Comment by Soundug** [comment]
@kaustubhgupta I would like to take up this one!

**Comment by kaustubhgupta** [comment]
@Soundug assigned to you

**Comment by kaustubhgupta** [comment]
@Soundug you need to make the PR today before 2 pm.
