### ISSUE TITLE
Python script to Create Scripts.json (For website)

### ISSUE THREAD

**Issue by kaustubhgupta** [avinashkranjan/Amazing-Python-Scripts#811]
## Idea

Currently the Scripts.md file requires manual addition of script names with other information.

## Details

The implementation goes like this:

- fetch the repository details about all the folders.
- add the folder name and link to the script
- add some exceptions like README.md, contribution guide, and other non-necessary files to this list. 
- The script will be part of a workflow soon and will be configured to run at every push in the repo.
- The script would take the following parameters as command-line arguments, make sure to use sys module (sys.argv) for this:
  - Github token
  - list of files to be excluded for being added to the json

## Learning
You will get to know about GitHub API and how to use Python to automate this task,

## Suggested Libraries
PyGitHub

## Additional Context:
Test this script for your forked copy of this repo in the local machine before pushing code,

**Comment by Sukriti-sood** [comment]
@kaustubhgupta  I would like to work on this.

**Comment by kaustubhgupta** [comment]
@Sukriti-sood assigned to you. Make sure you read all the requirements and implementation of script carefully

**Comment by TheFenrisLycaon** [comment]
Is this open ?

**Comment by Ajay-Singh-Rana** [comment]
My solution for this takes a few minutes, is that okay..?

**Comment by Ajay-Singh-Rana** [comment]
I too would like to contribute.

**Comment by Sukriti-sood** [comment]
@Ajay-Singh-Rana  It is not the right way ,I was already assigned to is issue.

**Comment by santushtisharma10** [comment]
@Ajay-Singh-Rana only the assignee can send the PR.

**Comment by Sukriti-sood** [comment]
@kaustubhgupta I have some confusion like script.json will contains object which contain folder name ,link and contributor name ,Is anything needed and also confused what to do with exceptions? Please help

**Comment by Ajay-Singh-Rana** [comment]
Oh, sorry i didn't check the assignees...Best wishes...

**Comment by kaustubhgupta** [comment]
@Sukriti-sood As mentioned in the description, the JSON file should look like this:

```
{
    "script_name1": "script_link1",
    "script_name2": "script_link2",
    .
    .
    .
}
```
