### ISSUE TITLE
Distance conversions

### ISSUE THREAD

**Issue by tanvi355** [avinashkranjan/Amazing-Python-Scripts#814]
# Aim

- What is the objective of the Script
Use it to convert the distances from one unit to other .
Ex. cm to km or m to mm
# Details

- What the features will your script have
A simple GUI with conversion options for different units of measurement

**Comment by tanvi355** [comment]
I would like to work on this under GSSoC'21

**Comment by santushtisharma10** [comment]
@tanvi355 assigned to you, go ahead
