### ISSUE TITLE
Speed typing test

### ISSUE THREAD

**Issue by mehabhalodiya** [avinashkranjan/Amazing-Python-Scripts#815]
# Aim

- It will track your typing speed.
- It is useful as one can improve their typing speed with regular practice.

# Details

- For a graphical user interface, I am going to use the `pygame` library which is used for working with graphics, along with some built-in modules of Python like `sys`, `time` and `random` library.
- I will create some functions which would be responsible for starting the game, reset the game and few helper functions (i.e. accuracy and WPM (words per minute)). to perform calculations that are required.

**Comment by mehabhalodiya** [comment]
I would like to work on this under GSSOC'21.

**Comment by kaustubhgupta** [comment]
This already exists: https://github.com/avinashkranjan/Amazing-Python-Scripts/issues/720
