### ISSUE TITLE
Finger Counter using Hand Tracking

### ISSUE THREAD

**Issue by mehabhalodiya** [avinashkranjan/Amazing-Python-Scripts#817]
# Aim

- One will get to know that how to count the fingers using a python script.

# Details

- Initially, I will go through hand tracking and then I will use the hand landmarks to count of the fingers. 
- All of this will be happening in realtime and requires close to no installations and configurations.
- I will use OpenCV, along with some built-in modules of python like `time` and `os`.

**Comment by mehabhalodiya** [comment]
I would like to work on this under GSSOC'21.

**Comment by santushtisharma10** [comment]
@mehabhalodiya assigned to you

**Comment by kaustubhgupta** [comment]
@mehabhalodiya updates on this?

**Comment by mehabhalodiya** [comment]
Yes, I am working.
I will create a PR by today or maybe tomorrow!
