### ISSUE TITLE
Amazon Scraper

### ISSUE THREAD

**Issue by Arnab11917676** [avinashkranjan/Amazing-Python-Scripts#820]
# Aim

A script that can scrape and update stock of Amazon of a particular category

# Details
In this script, the program will be able to scrape details of a particular category of Amazon on a timely basis and update the stock list

@kaustubhgupta sir please look into this project I think this will be a nice project to be added in the open-source

**Comment by santushtisharma10** [comment]
@Arnab11917676 go ahead, assigned to you

**Comment by Arnab11917676** [comment]
Hello @santushtisharma10, Update--> I am very close to finishing this project.

**Comment by kaustubhgupta** [comment]
@Arnab11917676 updates?

**Comment by Arnab11917676** [comment]
Sir I will be uploading tomorrow... Sorry for the delay...

**Comment by Arnab11917676** [comment]
Sir please a look...
