### ISSUE TITLE
Bag of words model. 

### ISSUE THREAD

**Issue by zaverisanya** [avinashkranjan/Amazing-Python-Scripts#822]
# Aim

- What is the objective of the Script
Domain- NLP

The objective of this script is to  1) tokenize the sentences taken from user. 2) transforming text to vectors where each word and its count is a feature. 3) Create dataframe  where dataframe is an analogy to excel-spreadsheet . The data will be also stored in excel sheet.

@kaustubhgupta @santushtisharma10   I am a GSSoC'21 participant and I feel this is an interesting script. Please allow me to work on this issue.

**Comment by santushtisharma10** [comment]
@zaverisanya assigned to you
