### ISSUE TITLE
Health Log Book

### ISSUE THREAD

**Issue by anuragmukherjee2001** [avinashkranjan/Amazing-Python-Scripts#823]
I am Anurag Mukherjee, I am a participant of GSSoC'21
# Aim

Keeping daily records of a person's food and workout

# Details
The script will contain the daily records of food and workouts of a person. The user will only enter the name of the foods, it will be stored in a text file with corresponding date and time. Similarly, the user will enter the types of workout at their workout time. The workouts will be stored in a text file with date and time. The user can also retrieve the data whenever they want to see.

## Advantages of the script:-

This script will help the user to maintain his/her health, as it is keeping a daily track of their diet and workout style. At the end of the day, or at the end of the week, he/she can analyze the data and can lead a healthy and fit lifestyle.

## Modules will be used:-

1)  datetime 

I will write clean and easy to understand code. Please assign this issue to me.

**Comment by santushtisharma10** [comment]
@anuragmukherjee2001 go ahead, assigned to you
