### ISSUE TITLE
Modifying Salary prediction app

### ISSUE THREAD

**Issue by Avishake007** [avinashkranjan/Amazing-Python-Scripts#825]
**Is your feature request related to a problem? Please describe.**
I want to modify the salary prediction 

**Describe the solution you'd like**
I want to add flask to the salary prediction app so that the app can be run through a web page

please assign me for this task.
I  am a gssoc'21 participant and want to work on this issue.

**Comment by santushtisharma10** [comment]
@Avishake007 we don't have to create a flask app. Only python script, gui and cli is accepted.
