### ISSUE TITLE
Dino Game 

### ISSUE THREAD

**Issue by Yash9479** [avinashkranjan/Amazing-Python-Scripts#826]
I want to contribute as a GSSOC'21 Participant. Please assign this to me.
### Aim
-To create a Dino Game using python.

### Details
-The simple Python libraries and modules.

**Comment by santushtisharma10** [comment]
@Yash9479 assigned to you

**Comment by kaustubhgupta** [comment]
@Yash9479 updates?

**Comment by Yash9479** [comment]
Working, need more two days for finishing and testing.

**Comment by kaustubhgupta** [comment]
okay!
