### ISSUE TITLE
Time series forecasting covid 19 case Notebook

### ISSUE THREAD

**Issue by ayush-raj8** [avinashkranjan/Amazing-Python-Scripts#828]
# Aim
Predicting number of covid 19 cases for next 21 days

- What is the objective of the Script
It uses daily updated  data to forecast number of fresh, death and recovered covid 19 cases for next 21 days.

# Details
Domain- ML

- What the features will your script have
- The objective of this script is to 1)use daily updated covid 19 data from open source . 2) training the data on auto arima model to predict cases for next 3 weeks. 3) Visualizing data for comparative study of cases in different nations 

I would like to work on it if assigned.

**Comment by santushtisharma10** [comment]
@ayush-raj8 go ahead , assigned to you.

**Comment by santushtisharma10** [comment]
@ayush-raj8 make sure that it  is not a notebook but a python file. Also refer to #556 for structuring and creating your prediction script
