### ISSUE TITLE
Build a Contact Book With Python, PyQt, and SQLite

### ISSUE THREAD

**Issue by Lakhankumawat** [avinashkranjan/Amazing-Python-Scripts#829]
![Build-a-Contact-Book_Watermarked](https://user-images.githubusercontent.com/55774240/113536912-dd29e000-95f4-11eb-994e-3c16ee245790.jpg)

### Demo: A Contact Book With Python
# Project Overview
> Prerequisites
- Step 1: Creating the Contact Book’s Skeleton App With PyQt
   Structuring the Contact Book Project
   Creating the Application’s Main Window
   Coding and Running the Application
- Step 2: Building the Contact Book’s GUI With Python
- Step 3: Setting Up the Contact Book’s Database
   Connecting to the Database With PyQt and SQLite
   Creating the contacts Table
   Testing the Contact Book’s Database
- Step 4: Displaying and Updating Existing Contacts
   Creating a Model to Handle the Contact Data
   Connecting the Model to the View
   Displaying and Updating Contacts
- Step 5: Creating New Contacts
  Creating the Add Contact Dialog
  Launching the Add Contact Dialog
  Processing the Add Dialog’s Data in the Model
- Step 6: Deleting Existing Contacts
  Deleting Selected Contacts
  Clearing the Contact Database
> Conclusion

**Comment by Lakhankumawat** [comment]
> Assign me

**Comment by Lakhankumawat** [comment]
> Let me be clear and mention beforehand

I will be following some sort of tutorials or articles or blog .
There is a [repo](https://github.com/realpython/materials/tree/master/python-contact-book) which i will be following , although _my code won't be same_ .
If you are okay with that and don't add **plagiarism** labels then i m okay to do it otherwise it will be good for grab.

**Comment by santushtisharma10** [comment]
@Lakhankumawat  go ahead , assigned to you

**Comment by santushtisharma10** [comment]
While creating a pr, mention the article or source you have referred to avoid any misunderstanding

**Comment by Lakhankumawat** [comment]
Sir please make it **level 3** 
1. as there are many concepts involved in it .
2. Also it is difficult to implement 
3. It's kind of big project rather than only one .py file i.e modules we have to make and packages and database

**Comment by santushtisharma10** [comment]
@Lakhankumawat I will increase the level after reviewing your PR

**Comment by kaustubhgupta** [comment]
@Lakhankumawat updates?

**Comment by Lakhankumawat** [comment]
I've been working it seems tough though for me , exams are going on .

**Comment by Lakhankumawat** [comment]
Actually unassigned  option was mis clicked i m sorry

**Comment by kaustubhgupta** [comment]
@Lakhankumawat take 3-4 days to complete it

**Comment by Lakhankumawat** [comment]
Go for **Up - For - Grab** 

## Problems i was facing implementing it .
- Connecting Sqlite DB with User Interface.
- Rendering the display , update and deleting contacts.


I Could Have copied [Source code](https://github.com/realpython/materials/tree/master/python-contact-book) and created a PR but i am here to learn and not to earn points , hope you got it .

**Comment by kaustubhgupta** [comment]
> Go for **Up - For - Grab**
> 
> ## Problems i was facing implementing it .
> * Connecting Sqlite DB with User Interface.
> * Rendering the display , update and deleting contacts.
> 
> I Could Have copied [Source code](https://github.com/realpython/materials/tree/master/python-contact-book) and created a PR but i am here to learn and not to earn points , hope you got it .

No problem, thanks for the honesty, you can always create more issues for contribution.😀

**Comment by sameeksharl** [comment]
@kaustubhgupta  This is Sameeksha !! I wanted to work on this issue . I said earlier in discord  that the SQlite is new to me but i found that its similar to SQL database commands so i would like to take up this issue .
Details (that i will be able to build) 
-It has all CRUD operation . create, view, update and delete .
- i will be using TK (as PyQt is new to me so preferred TK)
Please instruct me if any changes needed in details section 
please assign it to me

**Comment by kaustubhgupta** [comment]
@sameeksharl you can start working on this issue

**Comment by sameeksharl** [comment]
Okay thank you!!!

**Comment by sameeksharl** [comment]
@avinashkranjan Could u pls review the pr??
