### ISSUE TITLE
IPL statistics GUI 

### ISSUE THREAD

**Issue by Ayushjain2205** [avinashkranjan/Amazing-Python-Scripts#840]
# Aim

Let user choose what statistics of IPL they want to see and based on user choice web scrape it and display in a GUI

# Details

Statistics the user can choose include - Most runs, most wickets, most 4s, most 6s and about 10 more such statistics and can be chosen for every season (2008-2020)

**Comment by Ayushjain2205** [comment]
@kaustubhgupta  can I work on this?

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 sure!

P.S: I knew someone will be creating this issue very soon as IPL is near😂😄
