### ISSUE TITLE
Random password generator GUI

### ISSUE THREAD

**Issue by tanvi355** [avinashkranjan/Amazing-Python-Scripts#842]
# Aim
To create a random password 

# Details

A simple GUI based password generator.

**Comment by tanvi355** [comment]
I would like to would like to work on it under GSSoC'21

**Comment by kaustubhgupta** [comment]
@tanvi355 assigned to you

**Comment by kaustubhgupta** [comment]
@tanvi355 updates?

**Comment by tanvi355** [comment]
> @tanvi355 updates?

Working on it....will submit a PR by tomorrow evening.
