### ISSUE TITLE
Tarot Card | Fortune Teller | CLI

### ISSUE THREAD

**Issue by Akshu-on-github** [avinashkranjan/Amazing-Python-Scripts#843]
## Aim
A script that picks a random tarot card (from a deck of 78 cards)

## Details
- CLI with buffer content (initially a command-line game)
- The random.randint() function
- A list with each element having a card and a fortune

@avinashkranjan 
I'm a GSSoC'21 participant. I hope that this would be an acceptable addition and that I can start working on it asap,
Cheers,
Akshu

**Comment by Akshu-on-github** [comment]
Screenshots for a sample of the results (when run on repl.it)
<img width="460" alt="screenshot-introduction" src="https://user-images.githubusercontent.com/61582763/113908975-cbaf2680-97f4-11eb-804b-750bf9232ec2.PNG">
<img width="460" alt="screenshot-three-tarots-drawn" src="https://user-images.githubusercontent.com/61582763/113909006-d7025200-97f4-11eb-9784-cfc91fbb138c.PNG">
<img width="460" alt="screenshot-conclusion" src="https://user-images.githubusercontent.com/61582763/113909023-db2e6f80-97f4-11eb-8b8e-07e950aba52b.PNG">

**Comment by RJ535315** [comment]
Hi I can work on this issue. Please assign it to me.

**Comment by kaustubhgupta** [comment]
@Akshu-on-github Assigned to you. @RJ535315 Issues are assigned in FCFS.
