### ISSUE TITLE
Instagram photo Downloader

### ISSUE THREAD

**Issue by hasanmdarif** [avinashkranjan/Amazing-Python-Scripts#844]
I want to write some python scripts which will help to download photos from instagram under gssoc 21.

**Comment by kaustubhgupta** [comment]
@hasanmdarif Already implemented:

![image](https://user-images.githubusercontent.com/43691873/113967453-a222e900-984e-11eb-9f92-222e74a173d6.png)

https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Instagram%20downloader

https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Instagram-Profile-Pic-Downloader
