### ISSUE TITLE
A simple Text editor using Tkinter

### ISSUE THREAD

**Issue by ankurg132** [avinashkranjan/Amazing-Python-Scripts#850]
**Describe the solution you'd like**
I would like to add a python script using tkinter containing a simple GUI text editor where you can open and save changes to a text file.
I would like to work on this issue under gssoc21.

**Comment by kaustubhgupta** [comment]
Already implemented: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Simple%20Notepad
