### ISSUE TITLE
AWS Ec2 Management Scripts for Automations and testing

### ISSUE THREAD

**Issue by shantamsultania** [avinashkranjan/Amazing-Python-Scripts#856]
# Aim

To create a Python Script for AWS Automation 

# Details

to create a Python Script with the help of which one person can create an Ec2 Instance in his AWS Account, and perform various implementations on the same.
1. operations like delete all the useless EC2 which are 2 days older 
2. create ec2 with one click and more
3. it will be able to create as many ec2 you want to create be it 100 - 200 this will help a person in testing of its product on AWS platforms
4. will be able to make the required changes in one go
5. as it will be a testing Script it will not be having any relations to his main account so will save him money as well as time

**Comment by kaustubhgupta** [comment]
@shantamsultania assigned to you. Make sure to add output screenshots hiding any personal/non-disclosable information.
