### ISSUE TITLE
Create AWS Script Template's for AWS End to end testing 

### ISSUE THREAD

**Issue by shantamsultania** [avinashkranjan/Amazing-Python-Scripts#858]
# Aim

Create AWS Script Template's for AWS End to end testing 

# Details

1. it will be able to create as many ec2 you want to create be it 100 - 200 this will help a person in testing of its product on AWS platforms 
2. will be able to make the required changes in one go 
3. as it will be a testing Script it will not be having any relations to his main account so will save him money as well as time

**Comment by kaustubhgupta** [comment]
@shantamsultania assigned to you. Make sure to add output screenshots hiding any personal/non-disclosable information.

**Comment by shantamsultania** [comment]
hey @kaustubhgupta i have send a pull request for review please look into this
