### ISSUE TITLE
Link preview

### ISSUE THREAD

**Issue by jhamadhav** [avinashkranjan/Amazing-Python-Scripts#859]
# Aim

- A script to provide the user with a preview of the link entered.

# Details

- When entered a link, the script will provide with title, description, and link of the website that the URL points to.
- The script will do so by fetching the Html file for the link and analyzing the data from there.
- The data will be saved in a `JSON` file for further reference
- Every entry will have a time limit after which it will be updated

**Comment by kaustubhgupta** [comment]
@jhamadhav assigned to you. Make sure to add a GIF to demonstrate your code.

**Comment by jhamadhav** [comment]
> 
> 
> @jhamadhav assigned to you. Make sure to add a GIF to demonstrate your code.

Sure!

**Comment by kaustubhgupta** [comment]
@jhamadhav updates?

**Comment by jhamadhav** [comment]
I'm almost done,  Just some testing for edge cases.
I will make the PR asap, probably tonight.
