### ISSUE TITLE
Udemy courses details scraper

### ISSUE THREAD

**Issue by Ayushjain2205** [avinashkranjan/Amazing-Python-Scripts#862]
# Aim

To scrape details of Udemy courses.

# Details

Important details about courses like Course title, description, instructor, price, rating and number of lectures will be scrapped and stored in a db

**Comment by Ayushjain2205** [comment]
@kaustubhgupta I would like to work on this, Can you please assign this to me?

**Comment by kaustubhgupta** [comment]
Instead of CSV, can you store it a database of your choice and then create a fetcher.py file to fetch the information stored?

**Comment by Ayushjain2205** [comment]
@kaustubhgupta sure will do that.... so 2 scripts - one to scrape data from udemy and store in database , and other one to fetch data from database and display?

**Comment by kaustubhgupta** [comment]
Yes

**Comment by Ayushjain2205** [comment]
@kaustubhgupta  Sure I can do it
