### ISSUE TITLE
sort and group images according to resolution

### ISSUE THREAD

**Issue by RJ535315** [avinashkranjan/Amazing-Python-Scripts#863]
# Aim

 To write a python script to sort the images in our pc folders according to the resolution and group them by the resolution, by creating separate folders

# Details

**Is your feature request related to a problem? Please describe.**: 

Yes, We always have the problem of finding a desired resolution containing image in a bunch of images within a folder.

**Describe the solution you'd like**: 

 In order to find a solution to this problem, this is a python script which sorts images according to resolution and group them into sub folders according to resolution 

please assign this issue to me.
Thanks in advance

**Comment by kaustubhgupta** [comment]
@RJ535315 assigned to you

**Comment by RJ535315** [comment]
@kaustubhgupta please check and review the PR that i've submitted related to this issue. thank you.
