### ISSUE TITLE
Rock Paper Scissors

### ISSUE THREAD

**Issue by nidhivanjare** [avinashkranjan/Amazing-Python-Scripts#866]
# Aim

- I want to add a rock paper scissor game in python. 

I am a GSSOC'21 participant and I would like to work on this issue.

**Comment by kaustubhgupta** [comment]
@nidhivanjare We already have two versions of this game:
- CLI: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Stone-Paper-Scissors-Game
- GUI: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/StonePaperScissor%20-%20GUI
