### ISSUE TITLE
Reorder any PDF Pages

### ISSUE THREAD

**Issue by iamakkkhil** [avinashkranjan/Amazing-Python-Scripts#868]
**Describe the solution you'd like**
By using python and PyPDF2 library it will let us reorder any PDF pages and save it into our local directory.

I am a GSSOC'21 participant kindly assign me the same 
@kaustubhgupta @avinashkranjan

**Comment by kaustubhgupta** [comment]
@iamakkkhil I would suggest you add this feature in the existing PDf-Tools script: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/PDF-Tools

Can you do that?

**Comment by iamakkkhil** [comment]
Yes @kaustubhgupta

**Comment by kaustubhgupta** [comment]
Okay, assigned to you
