### ISSUE TITLE
Twitter hastag scrapper without API

### ISSUE THREAD

**Issue by RohiniRG** [avinashkranjan/Amazing-Python-Scripts#869]
**Describe the solution you'd like**
This script allows user to enter hastag and scrape the no. of tweets specified by the user and save it in a csv file by using SNScrape library of python.
I am a GSSOC21 participant kindly assign me the same. @kaustubhgupta @avinashkranjan

**Comment by kaustubhgupta** [comment]
Hi @RohiniRG,
Can you save the tweets in a database of your choice and then create another script to display these results? Then you will have two scripts: one to fetch and store the tweets data and other one to display the stored data. Let me know your thoughts

**Comment by RohiniRG** [comment]
> Hi @RohiniRG,
> Can you save the tweets in a database of your choice and then create another script to display these results? Then you will have two scripts: one to fetch and store the tweets data and other one to display the stored data. Let me know your thoughts

Yes. I can try this.

**Comment by kaustubhgupta** [comment]
@RohiniRG okay then, assigned to you

**Comment by RohiniRG** [comment]
@kaustubhgupta the script is almost prepared, but I have used .csv as my database through which I extract tweets. Would this be considered a database or should I use sqlite only?

**Comment by kaustubhgupta** [comment]
Use SQLite
