### ISSUE TITLE
Sentiment Analysis using Python

### ISSUE THREAD

**Issue by RohiniRG** [avinashkranjan/Amazing-Python-Scripts#870]
**Describe the solution you'd like**
Using deepface lab we can examine all the emotions in a person's face through a live camera feed at any given instant.
I am a GSSOC'21 participant, Kindly assign me the same @kaustubhgupta @avinashkranjan

**Comment by kaustubhgupta** [comment]
We already have this script: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Facial-Expression-Recognition
