### ISSUE TITLE
Todo-list | File handling | CLI

### ISSUE THREAD

**Issue by Avishake007** [avinashkranjan/Amazing-Python-Scripts#871]
I want to create a Todo list feature which will work based on files-handling
please assign me for this issue under gssoc'21

**Comment by kaustubhgupta** [comment]
@Avishake007 I didn't got your idea. Can you explain in detail what you want to achieve with this?

**Comment by Avishake007** [comment]
Actually I am thinking of using the read, write and append operations of file handling to create a todolist.
The todolist will be saved on a file. If a user wants to view to todo list then read operation will be used, to add we can use the append operation and to make any change we can use the write operation

**Comment by kaustubhgupta** [comment]
Okay then, assigned to you. Make sure to name it TODO (CLI-VER)

**Comment by kaustubhgupta** [comment]
@Avishake007 updates?

**Comment by Avishake007** [comment]
@kaustubhgupta I will create a pull request by today
