### ISSUE TITLE
Expense Tracker 

### ISSUE THREAD

**Issue by nidhivanjare** [avinashkranjan/Amazing-Python-Scripts#872]
# Aim

- I would like to create an Expense Tracker python project 

I am a GSSOC'21 participant and would like to work on this issue.

**Comment by kaustubhgupta** [comment]
Hi @nidhivanjare, We already have this issue: https://github.com/avinashkranjan/Amazing-Python-Scripts/issues/779 and the assigned person has also made the PR but she hasn't updated it yet. Today is her last day for this. If she fails to do so, then I will assign that issue to you. For now, this issue will be closed.
