### ISSUE TITLE
Creating a pencil sketch using Python.

### ISSUE THREAD

**Issue by ShubhamGupta577** [avinashkranjan/Amazing-Python-Scripts#881]
# Aim

- In this script, we are going to convert any image into its pencil sketch using a python script.

# Details

-In our script, the user has to just upload a picture and as an output, he/she will get a pencil sketch of that image. For this purpose, we are going to use `OpenCV`.
As a process, we will be going to reduce the noise in the image(if any), and then by performing the various operation like image conversion, blurring and many more, we will obtain our required output image.

**Comment by kaustubhgupta** [comment]
We already have this script: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/ImageToSketch
