### ISSUE TITLE
Addition of Malaria detection from cell image

### ISSUE THREAD

**Issue by ayush-raj8** [avinashkranjan/Amazing-Python-Scripts#893]
### **Aim**
Develop a web app that predicts malaria based on input of cell image. It will be a web page with flask framework as backend which will work on deep learning model of malaria trained image.

I'll like to work , if assigned.

**Comment by kaustubhgupta** [comment]
@ayush-raj8 We don't need any end-to-end flask deployed application. If you can structure your code in the script format as done in the below implementations then let me know:

https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Salary%20Predictor

**Comment by kaustubhgupta** [comment]
> @ayush-raj8 We don't need any end-to-end flask deployed application. If you can structure your code in the script format as done in the below implementations then let me know:
> 
> https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Salary%20Predictor

@ayush-raj8 Can you do this?

**Comment by ayush-raj8** [comment]
> > @ayush-raj8 We don't need any end-to-end flask deployed application. If you can structure your code in the script format as done in the below implementations then let me know:
> > https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Salary%20Predictor
> 
> @ayush-raj8 Can you do this?

Yes , I can do this.

**Comment by kaustubhgupta** [comment]
@ayush-raj8 updates on this?

**Comment by ayush-raj8** [comment]
> @ayush-raj8 updates on this?

Yes , I'll make PR soon in the format given with few days. I'll add image datasets link instead of really uploading bcoz the dataset size is of the order of GBs.
