### ISSUE TITLE
Instagram Follow- NotFollow

### ISSUE THREAD

**Issue by nidhivanjare** [avinashkranjan/Amazing-Python-Scripts#894]
# Aim

- Create an Instagram chatbot to display people you follow and who do not follow you back.
I am a GSSOC'21 Participant and would like to work on this issue.

**Comment by kaustubhgupta** [comment]
Name your script folder as "Instagram Follow- NotFollow"

**Comment by kaustubhgupta** [comment]
@nidhivanjare updates on this?

**Comment by nidhivanjare** [comment]
Working on it.. Some small bug.

**Comment by rafa1309** [comment]
Hello , My user its rafaelarevalosoficial , help me please

**Comment by avinashkranjan** [comment]
Hey @rafa1309 What do you need help with??

**Comment by rafa1309** [comment]
Hy friend , i need followers.

**Comment by avinashkranjan** [comment]
Hey @rafa1309 this is not the place for you to asking for followers, Kindly keep that in mind. Keep this as a warning, If it happens again you'll be restricted from this repo.

**Comment by kaustubhgupta** [comment]
@nidhivanjare you got tomorrow's last day to complete this issue

**Comment by nidhivanjare** [comment]
Done
