### ISSUE TITLE
Add implementation of ORB algorithm for feature detection.

### ISSUE THREAD

**Issue by ShubhamGupta577** [avinashkranjan/Amazing-Python-Scripts#898]
# Aim

- In this script, we are going to implement **ORB(Oriented FAST and Rotated BRIEF)** algorithm of `Open CV` which is used to detect and matching the features of an image.

# Details
ORB is a fusion of **FAST keypoint detector** and **BRIEF descriptor** with some added features to improve the performance. FAST is Features from the Accelerated Segment Test used to detect features from the provided image. It also uses a pyramid to produce multiscale features. Now it doesn’t compute the orientation and descriptors for the features, so this is where BRIEF comes in the role.

**Comment by ShubhamGupta577** [comment]
@kaustubhgupta Please review this issue and assign this to me under GSSOC21.

**Comment by kaustubhgupta** [comment]
@santushtisharma10 can you verify if this can be included in the repo or not? I am not sure about this

**Comment by santushtisharma10** [comment]
@kaustubhgupta it can be included, this algorithm is used to calculate features and then tell whether the input images matches or not

**Comment by kaustubhgupta** [comment]
Okay!
