### ISSUE TITLE
Documentation: Adding Readme to the all the Scripts

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#9]
# AIM

- Adding a Readme to all the scripts.

# Details

- There's no Instructions for the Scripts to explain how to works.
- So add a Readme for the Scripts which would help to overcome this problem.
- So, Add a Readme with SS to help understand how the script works.

**Comment by shahidshakil** [comment]
@avinashkranjan  Can you please assign this to me ?

**Comment by ami-harry** [comment]
I want to contribute

**Comment by avinashkranjan** [comment]
Sure @ami-harry Go ahead..

**Comment by M-PRERNA** [comment]
Hey !! I wanted to contribute to this!

**Comment by avinashkranjan** [comment]
Go ahead @M-PRERNA co-ordinate with @ami-harry and work together on the issue Assigning it to you too

**Comment by M-PRERNA** [comment]
Okay Sure will start soon!!!

**Comment by avinashkranjan** [comment]
Any updates @M-PRERNA and @ami-harry

**Comment by AnandD007** [comment]
I would like to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @AnandD007

**Comment by avinashkranjan** [comment]
@AnandD007 Any Updates??

**Comment by AnandD007** [comment]
Working On it. Tomorrow I will submit the PR

**Comment by avinashkranjan** [comment]
Okaey, Great
