### ISSUE TITLE
NSE stock market data GUI

### ISSUE THREAD

**Issue by Ayushjain2205** [avinashkranjan/Amazing-Python-Scripts#900]
# Aim

Web scrape stock market data (top 20 gainers/losers, most active equities etc ) 

# Details
display this scraped data in a GUI format where user can chose which market data analysis they want to see from a drop down menu

**Comment by Ayushjain2205** [comment]
@kaustubhgupta I would like to work on this

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 updates on this?

**Comment by Ayushjain2205** [comment]
Will make a PR by tommorow, sorry for the delay had exams

**Comment by subhangi2731** [comment]
please assign me this
