### ISSUE TITLE
Pose Estimation Real-time

### ISSUE THREAD

**Issue by mehabhalodiya** [avinashkranjan/Amazing-Python-Scripts#901]
# Aim

- The script will detect different landmarks within a human body and all of this will be done in real time .

# Details

- I will write it in three different files.
1. Firstly, will make a python file for the basic code which is required to run.
2. Secondly, we will define bunch of functions (i.e. for positions, angles, etc.) in one class of pose detector.
3. Lastly, we will test the script using pose module written.

**Comment by mehabhalodiya** [comment]
I would like to work on this under GSSoC'21.
Please assign.

**Comment by kaustubhgupta** [comment]
@mehabhalodiya don't you think it is a standalone project?

**Comment by mehabhalodiya** [comment]
I will follow your opinion.
You can let me know whatever you think.

**Comment by kaustubhgupta** [comment]
@santushtisharma10 @antrikshmisri your call?

**Comment by antrikshmisri** [comment]
@kaustubhgupta I agree this is a standalone project. We can see the implementation first then we can decide which scopes can be removed from the project.

**Comment by mehabhalodiya** [comment]
You can assign this to someone else if anyone wants to implement this.
I will not able to do this as I will be busy in some important work.
Sorry for the inconvenience!

**Comment by kaustubhgupta** [comment]
@mehabhalodiya okay no issues
