### ISSUE TITLE
🖼️ Image Operations

### ISSUE THREAD

**Issue by Lakhankumawat** [avinashkranjan/Amazing-Python-Scripts#902]
### You can do the following set of operations on any image and can save it easily .
- Rotate
- Change Transform i.e Horizontal or Vertical
- Zoom in , Zoom Out
- Scale Size
- Make an Outline Image
- **Save the Image** 
- Retaining Original Shape 
<hr>

### This all can be done easily using simple few lines of code .
Libraries to be used :

- Pygame
- OS
- Sys
- Math

### How It May Look 
<hr>

![rotscalezoom](https://user-images.githubusercontent.com/55774240/114701272-381fad80-9d40-11eb-939c-97ee439ff4bc.png)
 
<br>

 In Simple Language i can say  **A Mini Image Editor** with tools which can be used and edited images can be saved.

**Comment by Lakhankumawat** [comment]
If you liked idea please assign me.

**Comment by kaustubhgupta** [comment]
We already have this script: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Image%20editor%20python%20script
