### ISSUE TITLE
Buttons Using Pygame🆕

### ISSUE THREAD

**Issue by Lakhankumawat** [avinashkranjan/Amazing-Python-Scripts#904]
## Aim
- How to make buttons in python 
- Why to use them
- To be able to design and animate buttons in python .
- Make buttons use in any GUI based applications . ( It will be preety handy )
- To Redirect user to any other module using buttons .

## Details 
- Libraries to be used [Pygame]

**Comment by kaustubhgupta** [comment]
@Lakhankumawat Make sure to cover variety of buttons

**Comment by kaustubhgupta** [comment]
@Lakhankumawat updates on this?

**Comment by Lakhankumawat** [comment]
I will create a PR today
