### ISSUE TITLE
Bulk Email Sender using Python

### ISSUE THREAD

**Issue by dsrao711** [avinashkranjan/Amazing-Python-Scripts#905]
# Aim

- As an email sender is already implemented, a bulk email sender can be implemented to send emails to larger number of reciepients

# Details

- The emails can be read from a csv file using pandas and accordingly emails can be sent to all the entries in the file.

**Comment by dsrao711** [comment]
Please assign this issue to me as a GSSOC participant

**Comment by kaustubhgupta** [comment]
This is already implemented: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Custom-Bulk-Email-Sender
