### ISSUE TITLE
Twitter Sentimental analysis Script

### ISSUE THREAD

**Issue by shantamsultania** [avinashkranjan/Amazing-Python-Scripts#908]
# Aim
Create a Twitter Sentimental analysis Script 

# Details

- What features will your script have
1. will get a set of tweets from Twitter itself
2. perform sentimental analysis on the same
3. result will be including a set of tweets that are based on the user choice example positive tweets or Negative Tweets.
4. this can later be used to create a product-based analysis on the same.

**Comment by kaustubhgupta** [comment]
@shantamsultania assigned to you, Use snscrape library to avoid any authentication tokens

**Comment by kaustubhgupta** [comment]
@shantamsultania updates on this?

**Comment by shantamsultania** [comment]
hey i am doing the Firebase Management script first will be done with that by today then will create a PR for this one after its mergered

**Comment by kaustubhgupta** [comment]
@shantamsultania you should create a separate branch for this issue and then start with the code after you're done with firebase. The PR merge can take time

**Comment by shantamsultania** [comment]
> @shantamsultania you should create a separate branch for this issue and then start with the code after you're done with firebase. The PR merge can take time

ok will do the same just wanted to ask can I can also include a webapp of the same ?

**Comment by kaustubhgupta** [comment]
> > @shantamsultania you should create a separate branch for this issue and then start with the code after you're done with firebase. The PR merge can take time
> 
> ok will do the same just wanted to ask can I can also include a webapp of the same ?

Umm, web app is not preferred as this is a script based repository

**Comment by shantamsultania** [comment]
> > > @shantamsultania you should create a separate branch for this issue and then start with the code after you're done with firebase. The PR merge can take time
> > 
> > 
> > ok will do the same just wanted to ask can I can also include a webapp of the same ?
> 
> Umm, web app is not preferred as this is a script based repository

ok cool man
