### ISSUE TITLE
Text sentimental Analysis script

### ISSUE THREAD

**Issue by shantamsultania** [avinashkranjan/Amazing-Python-Scripts#909]
# Aim

- create a script for text sentimental analysis 
# Details

- in this a person could enter a text / paragraph as an input and in return he/she will get a idea about the impact of the text is it a positive impact text or negative impact

**Comment by kaustubhgupta** [comment]
This issue is already in progress: https://github.com/avinashkranjan/Amazing-Python-Scripts/issues/211
