### ISSUE TITLE
Firebase Management Script

### ISSUE THREAD

**Issue by shantamsultania** [avinashkranjan/Amazing-Python-Scripts#910]
# Aim

- To create a sample Firebase script for beginners to try on and learn
- the main aim is to create a demo script/program so that all can learn about the firebase database and how to use it more effectively 

# Details

To create a script with which a person can 
- get all the data from his/her firebase database
- add data to firebase real-time database as well as storage 
- also perform various other necessary functions 
- this will also contain a script/ automation script that will send user details of the database at a specific duration of time

**Comment by kaustubhgupta** [comment]
I don't have knowledge of how firebase works. @santushtisharma10 @antrikshmisri @Kushal997-das if you have any idea about this then you can assign this or close the issue

**Comment by avinashkranjan** [comment]
Sure @shantamsultania Go Ahead..Assigned to you..
