### ISSUE TITLE
Firebase notification script for android 

### ISSUE THREAD

**Issue by shantamsultania** [avinashkranjan/Amazing-Python-Scripts#911]
# Aim

- Firebase notification script for android 
- basically, push notification script for using firebase

# Details

Firebase database is one of the most used databases for any android developers these days.
but many developers are still using the traditional way of accessing the script my idea is to create a script for notification purpose that could be later integrated with android application in simple and easy steps 

I will be making a sample android application of the same so that if anyone is finding any difficulties in setting up this type of script he/she can do it easily also

**Comment by kaustubhgupta** [comment]
@shantamsultania this is a Python-based repo and we can't accept/review any android based code. Also, as you have raised the previous issue for firebase, if any other mentor has tech stack aligned to that, that issue will be assigned to you
