### ISSUE TITLE
AWS Cloud formation script 

### ISSUE THREAD

**Issue by shantamsultania** [avinashkranjan/Amazing-Python-Scripts#912]
# Aim

- AWS Cloud Formation script 
- AWS Cloud formation is a service provided by Amazon in which one person can create a MultiTasking endorsement 

# Details

- Idea is to create an AWS Cloud Formation script in which a person has to just share his/her Template and any paraments is required and a new Cloud formation Stack will be created in a click 
read more about AWS Cloud formation (PS it's not easy to create 🌝 )
https://aws.amazon.com/cloudformation/

**Comment by kaustubhgupta** [comment]
@shantamsultania none of us have any idea about AWS. The last PR of yours was understandable as I have some prior knowledge about that but this issue, no idea.
