### ISSUE TITLE
Codeforces Scraper

### ISSUE THREAD

**Issue by iamakkkhil** [avinashkranjan/Amazing-Python-Scripts#913]
**Describe the solution you'd like**
is a useful website for beginners to practice DSA problems with varying difficulty. This python script will cover the extraction of required problem statements and their related info and storing them in a PDF file.

I am GSSOC21 participant @kaustubhgupta @avinashkranjan

**Comment by kaustubhgupta** [comment]
@iamakkkhil assigned to you. Make sure to implement your findings in the same way as https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Codechef%20Scrapper but don't copy-paste the whole code like https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/833.
