### ISSUE TITLE
Third Umpire Decision Review System DRS Gully Cricket

### ISSUE THREAD

**Issue by Ayush7614** [avinashkranjan/Amazing-Python-Scripts#914]
# Aim

- Third Umpire Decision Review System DRS Gully Cricket

# Details

- We have to make DRS system with python and python modules that you can see in IPL World Cup or cricket matches

**Comment by Ayush7614** [comment]
@avinashkranjan plss assign me this issue  under Gssoc

**Comment by santushtisharma10** [comment]
@Ayush7614 go ahead, assigned to you

**Comment by santushtisharma10** [comment]
you will be using opencv module for this program, right?

**Comment by kaustubhgupta** [comment]
@Ayush7614 updates on this?

**Comment by Ayush7614** [comment]
> @Ayush7614 updates on this?

Complete by today

**Comment by kaustubhgupta** [comment]
@Ayush7614?

**Comment by Ayush7614** [comment]
> @Ayush7614?

Done plss review it @kaustubhgupta
