### ISSUE TITLE
Flappy Bird Game

### ISSUE THREAD

**Issue by Ayush7614** [avinashkranjan/Amazing-Python-Scripts#915]
# Aim

- Flappy Bird Game

# Details

- We have to add Flappy Bird Game in python using python modules

**Comment by Ayush7614** [comment]
@avinashkranjan plss assign me this issue under gssoc

**Comment by santushtisharma10** [comment]
@Ayush7614 for future reference mention the python module name you will be using in your program, instead of writing python module

**Comment by kaustubhgupta** [comment]
@Ayush7614 updates on this?

**Comment by Ayush7614** [comment]
#942 is the pull for this issue plss review it
