### ISSUE TITLE
Data Visualization

### ISSUE THREAD

**Issue by dsrao711** [avinashkranjan/Amazing-Python-Scripts#917]
# Aim

- More types of visualizations like Financial Charts and Scientific Charts can be added

# Details

-  Scientific Charts like Contour Plots , Ternary Plots 
-  Financial Charts like Waterfall Chart , Funnel Chart

Contour Plot :
<img width="240" alt="dv" src="https://user-images.githubusercontent.com/59830064/115048103-d81f3780-9ef6-11eb-9763-8a607947fb4d.png">
Ternary Plot : 
<img width="278" alt="dv2" src="https://user-images.githubusercontent.com/59830064/115048288-06047c00-9ef7-11eb-8914-51c24e21fa0c.png">
Waterfall Chart:
<img width="323" alt="dv3" src="https://user-images.githubusercontent.com/59830064/115048404-26ccd180-9ef7-11eb-8e2a-dd2dc9d8a5ee.png">
Funnel Chart:
<img width="329" alt="dv4" src="https://user-images.githubusercontent.com/59830064/115048493-3fd58280-9ef7-11eb-830a-d186429c3d5c.png">

**Comment by dsrao711** [comment]
Please assign me this issue as a GSSOC Participant

**Comment by kaustubhgupta** [comment]
Hi @dsrao711,
Will you create these plots using Plotly? As we already have a directory for data visualizations: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Data-Visualization. It has all the basic charts and adding your charts will enhance it. Let me know the library/module to be used.

**Comment by dsrao711** [comment]
Yes. I will be doing this using Plotly and it would be an add on to the already existing Data visualization project@kaustubhgupta

**Comment by kaustubhgupta** [comment]
@dsrao711 Okay then, assigned to you. Just have a look at the implementation of the current graph. You need to structure the code in the same way. That means you will create 4 folders, one for each type, and updated the readme with each graph output and your name at the end in the author section. Let me know any other doubts.

**Comment by dsrao711** [comment]
Ya, Will do that. Thank you!
