### ISSUE TITLE
Multiplayer TicTacToe GUI using Pygame

### ISSUE THREAD

**Issue by iamakkkhil** [avinashkranjan/Amazing-Python-Scripts#920]
**Describe the solution you'd like**
The script will use Pygame in order to make a user friendly GUI Multiplayer TictacToe game.
Could you please assign this issue to me. I am a gssoc'21 participant.

**Comment by kaustubhgupta** [comment]
Hi @iamakkkhil, 
We already have this issue assigned https://github.com/avinashkranjan/Amazing-Python-Scripts/issues/768 and PR under review https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/851
