### ISSUE TITLE
Parkinson Disease Prediction Model

### ISSUE THREAD

**Issue by JanhaviSoni** [avinashkranjan/Amazing-Python-Scripts#922]
# Aim

- Parkinson Disease Prediction Model

# Details

- It will predict if the the person has the disease or not . It will be trained using xgboost classifier

**Comment by santushtisharma10** [comment]
@JanhaviSoni go ahead, assigned to you

**Comment by santushtisharma10** [comment]
@JanhaviSoni you have to structure your files in the similar manner as done in this [folder](https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Salary%20Predictor)

**Comment by kaustubhgupta** [comment]
@JanhaviSoni updates on this?

**Comment by JanhaviSoni** [comment]
@kaustubhgupta I have made the model but I had confusion about python script . Can you please give some info how should this python script be prepared, I have never made it before

**Comment by kaustubhgupta** [comment]
> @JanhaviSoni you have to structure your files in the similar manner as done in this [folder](https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Salary%20Predictor)

@JanhaviSoni as @santushtisharma10 mentioned in this comment, look at this file structure or try to run this script on your local system. Basically we need two scripts: `model.py` which will contain all the model training code and this file should save the model at the end. `prediction/main.py` this script will load the saved model and then ask the user to input the features required by the model and then you need to predict the result and then display it to the user

**Comment by kaustubhgupta** [comment]
@JanhaviSoni Today is last date for this

**Comment by kaustubhgupta** [comment]
@JanhaviSoni Can you make the PR today?

**Comment by JanhaviSoni** [comment]
@kaustubhgupta I will make the PR within few days as there was some issue . I need some time.

**Comment by kaustubhgupta** [comment]
@JanhaviSoni okay last 2 days for this, after that I will be forced to close this issue

**Comment by JanhaviSoni** [comment]
@kaustubhgupta Please don't close the issue . There is covid related situation so I will be able to make PR within few days , in May

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta Please don't close the issue . There is covid related situation so I will be able to make PR within few days , in May

Ohkay that's the case, you should have informed me earlier. Sorry for hurrying things for you😶. You can submit it at your own pace, don't take this as burden and focus more on the current situation right now. May that person recovers soon🙏
