### ISSUE TITLE
AI Trainer using OpenCV

### ISSUE THREAD

**Issue by Priyadarshan2000** [avinashkranjan/Amazing-Python-Scripts#923]
# Aim

- To make an AI Trainer using OpenCV

# Details
In this Project on building an AI Trainer using OpenCV and Python. We will use the pose estimation running on the CPU to find the correct points and using these points we will get the desired angles. Then based on these angles we find many gestures including the number of biceps curls. I will write the code in a way that you will be able to find angles between any 3 points with just a single line of code.

@avinashkranjan I am a GSSoC'21 participant and I think this is an interesting python script of the OpenCV domain. Kindly allow me to work on this issue and contribute to this project!

**Comment by kaustubhgupta** [comment]
@Priyadarshan2000 This is a standalone project and out of the scope of this repo.
