### ISSUE TITLE
Spaceship Game using Pygame

### ISSUE THREAD

**Issue by iamakkkhil** [avinashkranjan/Amazing-Python-Scripts#929]
**Describe the solution you'd like**
This script will let the user play a multiplayer spaceship game built by using Pygame library of Python

I am GSSoC 21 paricipant .
Kindly assign @avinashkranjan

**Comment by kaustubhgupta** [comment]
@iamakkkhil assigned to you

**Comment by kaustubhgupta** [comment]
@iamakkkhil updates on this?

**Comment by iamakkkhil** [comment]
> @iamakkkhil updates on this?

Almost done with the game will put the PR today itself
