### ISSUE TITLE
Script to Organize Files in Your System.

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#93]
# Aim

- This script should automatically organizes your complete system making. You can use modules such as os and shutil for this purpose.

# Details

- Movies files of certain extension to specified location
- Segregate files according to their types.

**Comment by Kreateer** [comment]
@avinashkranjan Can you assign this to me? I already have a script that functions similarly to what you specified. 😄

**Comment by avinashkranjan** [comment]
Sure go ahead.. @Kreateer

**Comment by Kreateer** [comment]
@avinashkranjan Still working on this. I have most of the script done, but I'm just stuck at getting the program to sort files by date. 😅 
I got a function that loops through files in the destination directory and stores their 'last modified' dates in a dictionary, which then needs to be sorted and return something that would sort the files by the last time they were edited, but for the life of me I can't figure that part out atm 😩
