### ISSUE TITLE
Pawned or not?

### ISSUE THREAD

**Issue by RohiniRG** [avinashkranjan/Amazing-Python-Scripts#931]
**Describe the solution you'd like**
This script will let you check whether your password has been hacked or not by using https://haveibeenpwned.com/ database

I am a GSSOC21 Participant @avinashkranjan kindly assign me the same

**Comment by kaustubhgupta** [comment]
@RohiniRG same question: WIth or without GUI and secondly, name this script as "Pawned or not?"

**Comment by RohiniRG** [comment]
> @RohiniRG same question: WIth or without GUI and secondly, name this script as "Pawned or not?"

@kaustubhgupta Yes, I can make a GUI for this.

**Comment by kaustubhgupta** [comment]
@RohiniRG okay assigned to you

**Comment by kaustubhgupta** [comment]
@RohiniRG updates on this?

**Comment by RohiniRG** [comment]
> @RohiniRG updates on this?

Working on the GUI. Will be uploaded by today.
