### ISSUE TITLE
Restaurant Management System

### ISSUE THREAD

**Issue by soha28** [avinashkranjan/Amazing-Python-Scripts#932]
# Aim

To build a restaurant management system using Tkinter library of python.

# Details

This app can be used by restaurants to calculate the bill of their customers effortlessly. 
Then, the Python program behind the software will do all the calculations and will show you the total amount, along with the service charge, state tax, etc. 
It also contains a separate calculator that the restaurant owners can use for doing some essential calculations.

**Comment by soha28** [comment]
I want to work on this project under GSSOC'21. Can u please assign this to me ? @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@soha28 can you add the database to store the information entered by the user?

**Comment by soha28** [comment]
yes

**Comment by kaustubhgupta** [comment]
okay then assigned to you

**Comment by kaustubhgupta** [comment]
@soha28 updates on this?

**Comment by soha28** [comment]
Yes I'm working on the database @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@soha28 you need to make the PR today itself

**Comment by soha28** [comment]
@kaustubhgupta my exams were going on.. Please give me 2 more days

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta my exams were going on.. Please give me 2 more days

okay then, take 2 more days

**Comment by kaustubhgupta** [comment]
@soha28 Today is last day for this. No more extension after this
