### ISSUE TITLE
Linear search visualizer

### ISSUE THREAD

**Issue by tanvi355** [avinashkranjan/Amazing-Python-Scripts#933]
# Aim

To create a GUI for linear search visualization.

**Comment by tanvi355** [comment]
Please assign this to me under GSSoC'21

**Comment by kaustubhgupta** [comment]
@tanvi355 updates on this?

**Comment by tanvi355** [comment]
> @tanvi355 updates on this?

Working on it. Please give me 2 more days and I will submit a PR.

**Comment by kaustubhgupta** [comment]
@tanvi355 sure work at your pace.

**Comment by subhangi2731** [comment]
please assign me this

**Comment by kaustubhgupta** [comment]
@subhangi2731 assigned to you

**Comment by kaustubhgupta** [comment]
@subhangi2731 updates on this?

**Comment by kaustubhgupta** [comment]
@subhangi2731 are you working on this issue?

**Comment by subhangi2731** [comment]
yes @kaustubhgupta I will make a pr by tomorrow surely

**Comment by kaustubhgupta** [comment]
@subhangi2731?

**Comment by kaustubhgupta** [comment]
@tanvi355 can you make the PR for this within 3-4 days?

**Comment by tanvi355** [comment]
> @tanvi355 can you make the PR for this within 3-4 days?

okay I will try
