### ISSUE TITLE
Cryptography

### ISSUE THREAD

**Issue by codebuzzer01** [avinashkranjan/Amazing-Python-Scripts#937]
# Aim

 The objective of this project is to encode and decode messages using a common key.

# Details

 In this project, 
-Users have to enter the message to encode or decode. 
-Users have to select the mode to choose the encoding and decoding process. 
-The same key will be used to process the encoding and decoding for the same message.

**Comment by codebuzzer01** [comment]
I would like to work for this . Please assign it to me.

**Comment by kaustubhgupta** [comment]
@codebuzzer01 assigned to you
