### ISSUE TITLE
COVID-19 outbreak notification

### ISSUE THREAD

**Issue by sayantani11** [avinashkranjan/Amazing-Python-Scripts#938]
# Aim

- With Covid-19 cases being at its peak, it is useful that we keep ourselves updated with the number of cases for our safety.

# Details

- This is an notification system that will keep notifying us about the number of cases in a state and the country after a particular interval of time set by the user.

**Comment by kaustubhgupta** [comment]
@sayantani11 assigned to you

**Comment by kaustubhgupta** [comment]
@sayantani11 updates on this?

**Comment by sayantani11** [comment]
@kaustubhgupta Was a bit busy this week, I am kind of done, will push the code within monday
