### ISSUE TITLE
FLAMES Game

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#94]
# Aim

- Implementation of the FLAMES game where two names are given as input(string) and the number of unique letters is calculated. The correct letter corresponding to the names is found. It is named after the acronym: Friends, Lovers, Affectionate, Marriage, Enemies, Sibling 
- **Optional** : If you could create a GUI for the Same.. That would be great

# Example 

- Input: Player1 = AJAY, Player2 = PRIYA
Output: Friends

**Comment by jayaganeshkumar** [comment]
@avinashkranjan  can you assign me this?

**Comment by avinashkranjan** [comment]
Sure @jayaganeshkumar .. Will you be working on GUI part too??

**Comment by jayaganeshkumar** [comment]
@avinashkranjan  yeah its done almost
