### ISSUE TITLE
Beat Board

### ISSUE THREAD

**Issue by albertzeap** [avinashkranjan/Amazing-Python-Scripts#944]
# Aim

- Allows users to create music through a sound board

# Details

- GUI showing a grid of the different sounds that can be produced 
- Users can either click the pads or press keys on their keyboard to produce the sound

**Comment by kaustubhgupta** [comment]
@albertzeap Hi, are you part of GSSOC or a casual contributor?

**Comment by albertzeap** [comment]
Im just a casual contributor. I was browsing for projects I can contribute to and came across yours.

**Comment by albertzeap** [comment]
I would love to be assigned to this task and work on it if it sounds like a good idea to you

**Comment by kaustubhgupta** [comment]
@albertzeap No problem, you can start working on this issue irrespective of the fact that whether you are associated with GSSOC or not.

**Comment by kaustubhgupta** [comment]
@albertzeap are you working on this issue?

**Comment by albertzeap** [comment]
Yes I am currently working on it. I can submit a pull request Friday the latest if that is fine with you

**Comment by kaustubhgupta** [comment]
Sure, take your time

**Comment by albertzeap** [comment]
Hello @kaustubhgupta I was wondering if there was any more work that needed to be done on my part? Or do I just wait now that I submitted my pull request?
