### ISSUE TITLE
Trending GitHub Users Fetcher (GUI)

### ISSUE THREAD

**Issue by kaustubhgupta** [avinashkranjan/Amazing-Python-Scripts#947]
# Aim

To scrap details of users who are trending.

# Details

Scrapping can be done using any library of your choice. Various filters you need to provide:
- Based on location (India, Egypt...)
- Based on language (Python, Java...)
- Based on the date (Today, Week, or Month)

The data needs to be stored as an SQLite database and then displayed in the GUI application. You can opt for any GUI library: Kivy, Tkinter, Pygame, or Dear GUI.

**Comment by Nathandloria** [comment]
Hello, would you be able to assign me ( @Nathandloria ) and my team ( @noorbuchi, @cklima616, @munzekm )? We would love to work on this issue!

**Comment by kaustubhgupta** [comment]
@Nathandloria are you part of GSSOC? Because this issue is specifically for GSSOC. Also, team assignment is not possible.

**Comment by Nathandloria** [comment]
Ah, I did not give much thought to the GSSOC tag -- my apologies. Also, I was speaking of doing individual assignments for each member, not as a GitHub team, I should have clarified further. Thanks for your response!

**Comment by Ayushjain2205** [comment]
@kaustubhgupta  I would like to work on this issue if this is still up for grab

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 assigned to you!

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 updates on this?

**Comment by Ayushjain2205** [comment]
Working on it PR by tomorrow end of day
