### ISSUE TITLE
Python-Telegram bot 

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#95]
# Aim

- A telegram bot that can send memes, jokes, riddles and much more. A python-telegram wrapper can be used.

**Comment by souravmondal13** [comment]
I would like to take it can you assign this to me.

**Comment by avinashkranjan** [comment]
Sure @sooryaprakash31 go ahead.

**Comment by avinashkranjan** [comment]
@souravmondal13 Any Updates??

**Comment by Sharanya2019** [comment]
Can I work on this issue and does it come under swoc2021?

**Comment by avinashkranjan** [comment]
Sure @Sharanya2019 Go ahead

**Comment by avinashkranjan** [comment]
Any Updates @Sharanya2019

**Comment by Sharanya2019** [comment]
I am working on it @avinashkranjan 
Any deadline?

**Comment by avinashkranjan** [comment]
No @Sharanya2019 But the Earlier the Better
