### ISSUE TITLE
Balanced SubStrings

### ISSUE THREAD

**Issue by RJ535315** [avinashkranjan/Amazing-Python-Scripts#950]
# Aim

- To identify the unique balanced substrings that can be formed using the given input string and print the substrings as output

# Details

- Balanced substrings are those in which count of occurrunces of each character within the substring formed, are equal.
- Ex: acca, abbbaa, etc
- print -1, if no balanced substrings are found / can't be formed

**Comment by RJ535315** [comment]
@avinashkranjan 
please assign me the issue, I love to contribute the code related to this problem.
FYI : I'm a gssoc participant

**Comment by kaustubhgupta** [comment]
@RJ535315 This repository is not for DSA questions but rather implementations of different libraries and unique ideas. If you can make this script interactive, GUI-based or anything presentable then let me know. Also, Neo-Algo repository is better for these kind of scripts.

**Comment by RJ535315** [comment]
Ok. Thank you. I'll check those repos.
