### ISSUE TITLE
Image Colour picker 

### ISSUE THREAD

**Issue by Ayushjain2205** [avinashkranjan/Amazing-Python-Scripts#951]
# Aim

To enable a user to pick colors by clicking on any part of a picture

# Details

This project will be done using OpenCV

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 is your idea similar to this implementation? https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Color_detection

Let me know

**Comment by Ayushjain2205** [comment]
@kaustubhgupta Yes it is somewhat similar sorry for the duplicate issue
