### ISSUE TITLE
Scraping Covid-19 resources  from twitter.

### ISSUE THREAD

**Issue by smriti26raina** [avinashkranjan/Amazing-Python-Scripts#955]
# Aim

- A Twitter scraper script that will scrape all the important covid-19 resources (plasma, beds, etc).

# Details

- A script that will find and scrape all the important COVID-19 resources  (like plasma, Remdesivir injection, etc) posted by the various users on Twitter along with their contact details. It will then, saved into a CSV file for the needy persons.

**Comment by kaustubhgupta** [comment]
@smriti26raina good initiative, assigned to you!

**Comment by kaustubhgupta** [comment]
@smriti26raina updates on this?

**Comment by smriti26raina** [comment]
@kaustubhgupta, Working on this but I need little guidance on the approach. Please check the discord.

**Comment by kaustubhgupta** [comment]
> Hi, this is regarding the issue #955 (Amazing python script).Actually, I'm struck and i need guidance on the approach. I've scraped the data (required tweets) from the twitter using twint library and stored in the csv file. But the problem is CSV looks unreadable with lots of tweets and won't do any good. So,what should i do next to make it look more readable and also,I wanted to filter out the contact details inside the tweets. Can you suggest me what should be my approach to this issue?

![image](https://user-images.githubusercontent.com/43691873/116769535-8cbe6a80-aa5a-11eb-8664-f1fce8579bbc.png)


@smriti26raina As per the issue description, you are only supposed to scrap the tweets and then save them as CSV. If you wish to make the GUI and clean these tweets then it would require you to have some NLP skills (text cleaning) which require quite a lot of effort. This would mean that the current issue level would not suffice with the efforts made. I  would suggest making the PR with the current work.

**Comment by kaustubhgupta** [comment]
@smriti26raina when you are making the PR?

**Comment by smriti26raina** [comment]
I'm sorry, the script isn't functioning properly and showing some bugs.

**Comment by kaustubhgupta** [comment]
No issues
