### ISSUE TITLE
Image Stiching

### ISSUE THREAD

**Issue by ayush-raj8** [avinashkranjan/Amazing-Python-Scripts#956]
### **Image Stiching**
This be able to stitch two images together, creating a panorama of stitched images.
Sometimes , we click more than image if the object is close and large and then desire it to be in one frame.

Left view
![left](https://user-images.githubusercontent.com/52033949/115885882-027c7200-a46e-11eb-8ac5-ddb0191ab4f2.jpg)
Right view
![right](https://user-images.githubusercontent.com/52033949/115885957-14f6ab80-a46e-11eb-8721-ab17028c3a2a.jpg)
Desired output in a frame
![output](https://user-images.githubusercontent.com/52033949/115886017-25a72180-a46e-11eb-9698-514f23f11893.jpg)

**Comment by kaustubhgupta** [comment]
@ayush-raj8 updates on this?

**Comment by ayush-raj8** [comment]
@kaustubhgupta  I'll make pr within few days.

**Comment by kaustubhgupta** [comment]
@ayush-raj8 updated PR?

**Comment by ayush-raj8** [comment]
@kaustubhgupta I'll make pr soon.

**Comment by kaustubhgupta** [comment]
@ayush-raj8?
