### ISSUE TITLE
Base-N Calculator

### ISSUE THREAD

**Issue by XZANATOL** [avinashkranjan/Amazing-Python-Scripts#957]
# Aim

- A Python calculator that can convert numbers from base-X to base-Y. Example: `` Decimal to Binary ``, `` Binary to Octal ``, `` Base 3 to Base 6 ``, ..etc.

# Details

- The script will not be limited to the known bases of Binary, Octal, Decimal, and Hexadecimal. The user will be able to enter/ convert-to the desired base number.
- The Script will be able to also deal with decimal numbers.
- Imparative approach will be used. (No external libraries to do the conversion job)

# Contribution Event

- GSSOC

**Comment by kaustubhgupta** [comment]
Hi, @XZANATOL 

Can you make it a GUI application?

**Comment by XZANATOL** [comment]
Didn't try to build a GUI application before, but I think I can overcome the challenge. :D

**Comment by kaustubhgupta** [comment]
@XZANATOL okay give it a try!

**Comment by kaustubhgupta** [comment]
@XZANATOL updates on this?

**Comment by XZANATOL** [comment]
Still working on it
