### ISSUE TITLE
Keyboard Jumper Game

### ISSUE THREAD

**Issue by codebuzzer01** [avinashkranjan/Amazing-Python-Scripts#959]
# Aim
Keyboard jump game is a speed typing game that helps in improving the typing speed of players.
The objective  is to build a keyboard jump game that helps players to increase their typing speed.
In this project, the player has to press the same keys to the letters displayed on the game screen. If the player made an error while typing then the game gets over.

# Details
I will use pygame, random, and time modules in this project.

**Comment by codebuzzer01** [comment]
@kaustubhgupta  shall I work on it?

**Comment by kaustubhgupta** [comment]
@codebuzzer01 this is same as this: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Typing-Speed-Test

**Comment by codebuzzer01** [comment]
ok cool !!
