### ISSUE TITLE
Gender-Age Detection

### ISSUE THREAD

**Issue by codebuzzer01** [avinashkranjan/Amazing-Python-Scripts#960]
# Aim

This project is  a gender and age detector that will automatically guess the gender and age of the person present in an image.

# Details

It uses OpenCV.

**Comment by codebuzzer01** [comment]
@kaustubhgupta  should I work on this?

**Comment by santushtisharma10** [comment]
@codebuzzer01 assigned to you

**Comment by santushtisharma10** [comment]
@codebuzzer01 which modules you will be using ?

**Comment by codebuzzer01** [comment]
@santushtisharma10  Yes I will be  using deep learning modules.
