### ISSUE TITLE
Flappy Bird Game 

### ISSUE THREAD

**Issue by robin025** [avinashkranjan/Amazing-Python-Scripts#961]
# Aim

- Flappy Bird Game 

# Details

- Flappy Bird game  in Python using PyGame Module

Assign me this issue under GSSoC 21

**Comment by kaustubhgupta** [comment]
@robin025 assigned to you. Make sure that the code is unique and you're not copy-pasting it from somewhere else.

**Comment by santushtisharma10** [comment]
@kaustubhgupta issue #915 is also flappy bird game

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta issue #915 is also flappy bird game

The person hasn't updated why he closed the PR 5 days ago and he was assigned this issue for 10 days. I am closing that issue to avoid any confusion
