### ISSUE TITLE
Addition of DRS Script

### ISSUE THREAD

**Issue by robin025** [avinashkranjan/Amazing-Python-Scripts#962]
# Aim

- DRS(Decision Review System) Application with GUI

# Details

- Decision Review System application using Tkinter
- This application can be used to see videos in slow mode

Assign me this issue under GSSoC 21

**Comment by kaustubhgupta** [comment]
Issue already in progress: https://github.com/avinashkranjan/Amazing-Python-Scripts/issues/914
