### ISSUE TITLE
LinkedIn Certifications Manager

### ISSUE THREAD

**Issue by geekymeeky** [avinashkranjan/Amazing-Python-Scripts#968]
# Aim

- To add your Coursera certifications to your LinkedIn profile.

# Details

- This script will be automated and add your Coursera certificate to your LinkedIn profile.

**Comment by geekymeeky** [comment]
@avinashkranjan Please assign this to me under GSSoC'21.

**Comment by kaustubhgupta** [comment]
@geekymeeky only Coursera certification and no other certificates?

**Comment by geekymeeky** [comment]
@kaustubhgupta This will be the basis for this script.  I'll add more after I finish this one.

**Comment by kaustubhgupta** [comment]
You need to clearly specify this because adding only one type of certification is not useful.

**Comment by geekymeeky** [comment]
> You need to clearly specify this because adding only one type of certification is not useful.

It will also include certifications from Udemy. These two are some of the major e-learning platforms I'm familiar with, I hope the script will be useful.

**Comment by kaustubhgupta** [comment]
@geekymeeky updates on this?

**Comment by geekymeeky** [comment]
@kaustubhgupta my bad. I didn't give any updates. I'm working on this. Fortunately, I'm able to able to add the certifications when data is provided.
Initially, my plan was to create a full-fledged automation script which would scrape as well as add the certifications based on user provided credentials. Sadly, these e-learning platforms are protected by captcha which prohibits automation scripts and bots. Kindly, let me know if there's a way to do so.
As an alternative, data(certification url) will be provided by user and the script would just add certification from that data. Would that be okay ?

**Comment by kaustubhgupta** [comment]
@geekymeeky implement the way that works best.
