### ISSUE TITLE
Certificate Generator

### ISSUE THREAD

**Issue by soumik2012** [avinashkranjan/Amazing-Python-Scripts#974]
# Aim

- Generate thousands of certificates at just one click

# Details

- We need a list of names in CSV  we want to print it simple draw name in the image here
![certificate](https://user-images.githubusercontent.com/66599363/116120177-e3374c00-a6dc-11eb-8d9f-7bb0fd2b16df.jpg)

**Comment by soumik2012** [comment]
@kaustubhgupta  please assign me this issue

**Comment by kaustubhgupta** [comment]
Can you provide the functionalities to add our own custom certificate and then generate others?

**Comment by soumik2012** [comment]
> Can you provide the functionalities to add our own custom certificate and then generate others?

@kaustubhgupta No sir I can't  custom certificate user need add own certificate.

**Comment by kaustubhgupta** [comment]
@soumik2012 hmm, okay then give it a try,

**Comment by kaustubhgupta** [comment]
@soumik2012 Sorry for the confusion, this implementation already exist: https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Automatic%20Certificate%20Generator
