### ISSUE TITLE
Sinchan Drawing Using Python

### ISSUE THREAD

**Issue by Arnab11917676** [avinashkranjan/Amazing-Python-Scripts#975]
# Aim

Drawing Sinchan Using Python Turtle

# Details

In this project, I will be using the Python Turtle Module to draw the portrait of the famous cartoon character Sinchan. @kaustubhgupta  please have a look into this issue because I think this is a unique project and its something new.

**Comment by kaustubhgupta** [comment]
@Arnab11917676 assigned to you

**Comment by Arnab11917676** [comment]
@kaustubhgupta  sir in this project there is a lot of geometry is used . I believe this is more than Level 1 project. I think after you will see the project code you will also agree with me.

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta sir in this project there is a lot of geometry is used . I believe this is more than Level 1 project. I think after you will see the project code you will also agree with me.

We can increase the level after reviewing the code, no worries about that 👍

**Comment by Arnab11917676** [comment]
Okey
