### ISSUE TITLE
GST Claculator

### ISSUE THREAD

**Issue by Amit366** [avinashkranjan/Amazing-Python-Scripts#976]
# Aim

GST calculator GUI

# Details

By entering the original price and net price the script will calculate the GST percentage.

**Comment by Amit366** [comment]
@kaustubhgupta please assign this issue to me

**Comment by kaustubhgupta** [comment]
@Amit366 Two questions:
- Will you make the GUI for this?
- Are you aware of different Slabs of taxes? Not all entities are entitled to 18% GST.

**Comment by Amit366** [comment]
@kaustubhgupta I will make a Gui where the user enters the original price and net price.
To calculate the gst I will be using the formula:

((Net price - original price)*100)/original price

**Comment by kaustubhgupta** [comment]
Assigned to you,
