### ISSUE TITLE
English Theasauras

### ISSUE THREAD

**Issue by soumik2012** [avinashkranjan/Amazing-Python-Scripts#977]
# Aim

- A simple and smart command-line dictionary that displays the definition of the words entered by the user. 

# Details

- This helps the user English word definition

**Comment by soumik2012** [comment]
@kaustubhgupta  please assign me in GSSoC'21

**Comment by kaustubhgupta** [comment]
https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Dictionary-GUI

We already have this
