### ISSUE TITLE
Turtle Race

### ISSUE THREAD

**Issue by saaalik** [avinashkranjan/Amazing-Python-Scripts#981]
# Aim

A Race of turtles running through random number of blocks based on a random choice

# Details
A script written using turtle module in python, which makes 5 turtle race and move based on a random number drawn using random module.

**Comment by kaustubhgupta** [comment]
@saaalik are you planning to submit this code? https://github.com/techwithtim/Turtle-Racing-V2

**Comment by saaalik** [comment]
yes, it had a similar structure
