### ISSUE TITLE
Pikachu Drawing Using Python

### ISSUE THREAD

**Issue by Priyadarshan2000** [avinashkranjan/Amazing-Python-Scripts#983]
# Aim

- Drawing Pikachu Using Python Turtle

# Details

In this project, I will deploy a Pikachu Drawing with the help of theTurtle module. 

@avinashkranjan I am a GSSoC'21 participant and I think this is an interesting python script of the GUI domain. Kindly allow me to work on this issue and contribute to this project!

**Comment by santushtisharma10** [comment]
@Priyadarshan2000 go ahead, assigned to you
