### ISSUE TITLE
Rain Alert Mail Sender

### ISSUE THREAD

**Issue by Shubhrima** [avinashkranjan/Amazing-Python-Scripts#993]
**Is your feature request related to a problem? Please describe.**
Rain Alert Mail Sender

**Describe the solution you'd like**
An application that checks the weather condition of the given location between 7 am and 7 pm and sends a message early in the morning to the registered mail address as to whether one should carry a sunglass or an umbrella.

**Additional context**
![image](https://user-images.githubusercontent.com/68013183/116576187-f7718800-a92c-11eb-9a9c-c96eab5cdab5.png)

**Comment by santushtisharma10** [comment]
@Shubhrima go ahead assigned to you
