### ISSUE TITLE
Remove Duplication Function

### ISSUE THREAD

**Issue by U-c0de** [avinashkranjan/Amazing-Python-Scripts#996]
# Aim

- This scripts removes duplicates from the list 

# Details

- Example of how python automating function may be

Assign this to me @santushtisharma10 @avinashkranjan @kaustubhgupta @kaustubhgupta @antrikshmisri

**Comment by kaustubhgupta** [comment]
@U-c0de can you describe what you want to achieve with this script? The issue description is not very helpful

**Comment by U-c0de** [comment]
@kaustubhgupta  if their is duplication of data in a list and user don't want duplicates so he/she can easily remove it.

**Comment by kaustubhgupta** [comment]
@U-c0de this is not an appropriate script for this repo. Consider contributing to Neo Algo (if they don't have this script already)
